### ISSUE TITLE
update information about umbracoDisableElectionForSingleServer 

### ISSUE THREAD

**Issue by dampee** [umbraco/UmbracoDocs#1011]
## What type of issue is it?
Missing documentation

## What article/section is this about? 
umbracosettings.config / umbracoDisableElectionForSingleServer 

## Describe the issue:
As discussed in PR #741 we should move this into a troubleshooting section.

**Comment by dampee** [comment]
@dawoe could you help?

**Comment by sofietoft** [comment]
Hi! 
As we haven't seen any new activity on this issue in while, I'll close it for now.

If you feel it's still relevant, you're welcome to reopen it! 😁 
Thanks.

/Sofie
