### ISSUE TITLE
Missing documentation on compositions

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/UmbracoDocs#1012]
## What type of issue is it? 
Missing documentation

## Describe the issue:
It appears we have no documentation on how to use compositions for document types, maybe it fits here: https://our.umbraco.com/documentation/Getting-Started/Data/Defining-content/

**Comment by susw12** [comment]
@jmayntzhusen I can write something up for this! Please do not hesitate to point if I make a mistake in something that I write!

**Comment by jmayntzhusen** [comment]
Hey @susw12 ,

That sounds great! Please reference this issue on your pull request when you post it by writing #1012 😉

Looking forward to seeing what you come up with, and thanks for helping out! 😃

**Comment by marcemarc** [comment]
Here would be a great place: https://our.umbraco.com/documentation/Getting-Started/Data/Defining-content/

**Comment by jmayntzhusen** [comment]
Closing as it has been merged in already, great job @susw12  😃
