### ISSUE TITLE
Missing documentation on rebuilding examine indexes

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/UmbracoDocs#1013]
## What type of issue is it?
Missing documentation

## What article/section is this about? 
https://our.umbraco.com/documentation/Reference/Searching/Examine/ 

## Describe the issue:
We seem to have no documentation on the examine dashboard in the backoffice - developer section.  Would be great to have a small overview and explanation of the what you can do in there!

**Comment by ed-parry** [comment]
I'll take a look at putting something together for this - great spot @jmayntzhusen, it's probably a key area of interaction with search for a lot of people since it was introduced.
