### ISSUE TITLE
Style guidelines for language

### ISSUE THREAD

**Issue by dampee** [umbraco/UmbracoDocs#1015]
## What type of issue is it?
Discussion

## What article/section is this about? 
Contributing

## Describe the issue:
I think we should have *some* guidelines on how to write.  It was sparked by #996 and #1014 

So let us open the discussion

1. Where to put this information
2. what to put in?

For the first question, I think we should put it aside on the contributing section as started by @jmayntzhusen  in #996.

Some guidelines I think we should consider:
* We value to "keep it short". Shorter sentences are more readable than long sentences. Especially on the web. While we don't mind long sentences on print media, we need shorter sentences on the web.
* We don't deny PR's on spelling British versus American.   If you write new documentation and you are in doubt, choose American spelling over the British. I suggest we currently deny PR's changing spelling from British to American.
* Write for non-native speakers.
  *  Simplify your language. Do not use difficult words.
  * Write like a human, not a machine. 
  * Don’t be afraid to be funny, creative, or even a bit silly.  But don't forget that word games won't work as most readers are not native English.  (if necessary use "pun intended" to explain it is a joke).
* Use gender-neutral terms
* Remember that terms are obvious to you might not be obvious to others.  Crosslink to other articles if you can.
* When using code example
  * don't forget namespaces
  * copy paste should work
  * if it involves bad practices, make sure copy-paste won't work.  Or at least comment that it's bad practice.

What do you guys think?

**Comment by jmayntzhusen** [comment]
That was on my original list of things to add to the contribution guide, but I wanted to get it out there before adding too many additional sections. I think it is a great idea though!

**Comment by OwainWilliams** [comment]
This would help a lot. Having a guide makes sure everyone is writing in a similar way.

**Comment by BatJan** [comment]
It makes perfect sense @dampee I just hope you will keep it short as in the above bullet points you listed otherwise it might be a roadblock for people starting out...Like "Oh man, that's a lot of stuff to think about. I better just drop this PR".

But I guess it would be weird to write a long complicated guideline, which is all for keeping it simple anyway 😄

**Comment by jmayntzhusen** [comment]
Will close this for now as all considerations should be made in https://github.com/umbraco/rfcs/pull/9

**Comment by dampee** [comment]
Not sure that we covered all the things above in the RFC.  (To be honest, I was thinking where I left all these notes.)
