### ISSUE TITLE
Introduce related links

### ISSUE THREAD

**Issue by dampee** [umbraco/UmbracoDocs#1072]
[Sparked by the comment](https://github.com/umbraco/UmbracoDocs/pull/1065#discussion_r223582742) of @jmayntzhusen 

It would be awesome to have related links. :-)   It could be:

1. automated
2. curated

I don't think we are ready to have automated related links (someone disagree?). The dream obviously is having personalisation and have suggested related links for the visitor of the docs. But for now, I think we should focus on manually adding related links.  This was of course possible by convention at e.g. adding a related links section on the bottom on the article.

However, with the introduction of YAML we could start with introducing meta data which would enable us to render this out in a consistend professional way (with e.g. [appropriate relatedLink microdata](https://schema.org/relatedLink)).

That leaves us with having to decide on the implemention in the YAML.  But we will need to check if https://github.com/lunet-io/markdig supports this kind of YAML.  (it seems to be limited)

e.g. 
```
---
keywords: abc zyx
relatedlinks:
 - {title: This is an awesome link, url: xxx.md}
 - {title: This is an awesome link, url: xxx.md}
---
```
But that implies that we need to know the *relative path* to the URL.  I think that is not workable.  I think it would be better to reference an ID.  But im not sure that makes it readable or maintainable.
```
---
fromVersion: 7.4.0
relatedlinks:
 - {title: This is an awesome link, docId: a-guid-from-the-other-doc}
 - {title: This is an awesome link, docId: a-guid-from-the-other-doc}
---
```
Any thoughts?

**Comment by jmayntzhusen** [comment]
Hey @dampee 

My initial comment was simply about making a standardized layout for related links similar to the tip, note and warnings - this would be a lot cooler though!

We have talked about a doc guid before, I think it is something we should look into generating as it would help a lot with several things!

**Comment by dampee** [comment]
As discussed:

1. We should use Guids
2.  external links should be possible
3. we might need some taxonomie in the future to group documents

**Comment by jmayntzhusen** [comment]
As we are working on moving the documentation to a new framework this idea will have to be reevaluated. Will close this issue for now.
