### ISSUE TITLE
Feature request - Package Development Guide

### ISSUE THREAD

**Issue by MMasey** [umbraco/UmbracoDocs#1098]
It would be really useful to have some documentation around how to create, maintain and upload packages to Our & nuGet. 

A baseline would be really useful a guide that can be extended from.

@emmaburstow @leekelleher @mattbrailsford

**Comment by leekelleher** [comment]
Here's my old (old) repo for our package repo boilerplate: https://github.com/leekelleher/umbraco-package-boilerplate

If it helps? Ignore if not.

**Comment by marcemarc** [comment]
@BatJan @emmaburstow @emmagarland @leekelleher Go Cabinistas!

There is this reference for package actions: https://our.umbraco.com/documentation/Reference/Packaging/

(it would be good to review if this is 'up to date')

Secondly there 'isn't really' anything on creating a package (I mean not necessarily a package to release) but just using that section - @prjseal wrote something for 24days: https://24days.in/umbraco-cms/2017/creating-and-publishing-a-package/

But it would be super useful to have some kind of baseline, and advice particularly with ending up a Nuget package and an Umbraco package etc, it's a bit of a dark art a the moment.

**Comment by emmaburstow** [comment]
Hey Marc,

I'll send over the work in progress doc we have going on at the mo. We're looking at Paul's now so thanks! The approach we're taking is more holistic and goes into etiquette around feedback, committing to ongoing maintenance and security considerations. Mostly with an aim to standardising the approach of providing a launchpad for total beginners. 

Em

**Comment by marcemarc** [comment]
@emmaburstow ace, yes etiquette is interesting, - there was often been discussion around identifying 'community loved' packages... or having 'package status - eg actively supported - accepts contribution etc' - but if you have an idea of a new package,  it's not easy to know where to start...

Possibly also we could add a tutorial page following on from  the 'creating a property editor one'

https://our.umbraco.com/documentation/Tutorials/creating-a-property-editor/part-4

Now release your new property editor as a package...

**Comment by jmayntzhusen** [comment]
Hey all,

The new Umbraco package team will create an issue soon with more specific info about new package developer documentation. Work has started a little bit in https://github.com/umbraco/UmbracoDocs/pull/2035..

Will close this issue for now - soon we will open another with our plans and an open discussion about what sort of documentation people want 🙂
