### ISSUE TITLE
Possible Typo In Config Name in Documentation

### ISSUE THREAD

**Issue by silvia-odwyer** [umbraco/UmbracoDocs#1103]
What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about? 
https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Configuration/

## Describe the issue:
While perusing the documentation, I have discovered a possible typo in a configuration value, but I wanted to make sure that this is indeed a typo by the author of that page, and is not already called this in the codebase (so changing the method name would lead to serious implications, since it doesn't match that in the codebase). 

The configuration value is: AllowEditableFormSubmisisons 
and there's a typo in the last word, so I'm just wondering if this matches the config value in the codebase, and if you'd like me to change the value in the documentation.

![image](https://user-images.githubusercontent.com/32362757/46968001-0f07fe80-d0aa-11e8-88ed-3c72fefe47f2.png)

**Comment by muskan09** [comment]
Can I update the corrected spelling if it's not done yet?

**Comment by jmayntzhusen** [comment]
This has been fixed as of #1116 - thanks for reporting the issue 😉

@muskan09 Sorry someone already submitted this.
