### ISSUE TITLE
Document those little overlay icons that appear on top of nodes in the Content Tree

### ISSUE THREAD

**Issue by marcemarc** [umbraco/UmbracoDocs#1106]
## What type of issue is it? (Choose one - delete the others)

Missing documentation

## What article/section is this about? 
Backoffice/Sections

## Describe the issue:

Umbraco has these tiny icons that overlay the top of content nodes, and there doesn't seem to be anywhere that explains what they are...

... perhaps there should be a Using Umbraco section of the documentation, or perhaps this fits into a greater explanation of the content tree, in the backoffice/sections/content part of the docs.

The tiny green icon indicates a node has been updated, but not published.
Greyed out node indicates unpublished state
four squares indicate content is a listview
 
anything else?

**Comment by marcemarc** [comment]
see: https://our.umbraco.com/forum/using-umbraco-and-getting-started/94191-meaning-of-various-content-tree-mini-icons

**Comment by fer22f** [comment]
Hey, I want to grab this one! I will check the source code out to see if there are more enumerations, any hints as to where I could find them?
