### ISSUE TITLE
Guidelines on creating v8 content apps

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/UmbracoDocs#1108]
## What type of issue is it?
Missing documentation

## What article/section is this about? 
Content Apps in v8 - a feature that is only relevant to v8

## Describe the issue:
People want to know how to create content apps in v8.  Currently you have to play detective in the Core implementations to figure it out.  The process is very similar to adding a new property value editor and therefore a tutorial similar to that one would make sense.  I started having a go at writing one at CodeCabin after showing some people how to do them.

Have you got any thoughts where articles for v8-only features can live, for now at least?  I know I could now submit the article with only the v8 tag, but perhaps you wouldn't want 'Create a content app (v8 only)' appearing in the Tutorials list.

**Comment by jmayntzhusen** [comment]
Hey @LottePitcher 

This sounds super great! We will discuss it today at our biweekly Documentation meeting and see if we can come up with a proper plan on how we can add new features that only exist in future versions 🙂

**Comment by LottePitcher** [comment]
Thanks @jmayntzhusen. Yes I appreciate it needs some proper thought! 

If you decide it is too early for stuff like this to join the docs then I can put online as a blog post.  But that would seem a shame as then it can't be kept up-to-date by the community as the feature evolves (as no doubt it will!)

**Comment by dampee** [comment]
Hi @LottePitcher 

I have created a new branch for you which can give you a starting point.  If you (or someone else?) got somewhere, just create a PR and we'll happily review it.

Thanks a lot for creating the issue.  It's much appreciated!

Kind regards
Damiaan

**Comment by LottePitcher** [comment]
Hey @dampee 

Great. That all makes sense, so fingers crossed I end up with a PR in the right place ;-)

**Comment by LottePitcher** [comment]
@dampee how did I do?!! 
PR #1123

**Comment by dampee** [comment]
Do we close this issue, or do you think @crgrieve will pitch in here?  

We could create a new Issue or immediately a PR against the master.  (The ContentApps branch is deleted).

**Comment by LottePitcher** [comment]
Thanks @dampee !  
  
Looks like we can't navigate to the v8 page on Our at the moment, despite the fact that I can see you've added the missing version YAML.  I have a feeling that the version links aren't appearing on pages I'm sure I've seen them on previously so thinking it's a wider issue.  In which case I think this specific issue can be closed.  As you say further improvements on the content app guidelines can be done in a PR on the master branch directly.

Thanks for your help and prompt review of this :)

**Comment by LottePitcher** [comment]
Although that said... 

It would look better if there was a space in the wording in the side menu and breadcrumb - i.e. "Content Apps" not "ContentApps".   Is that fixed by adding a hyphen in the folder name?  If so, and you would like me to do that in a PR then let me know.

I don't know how searching works in Our.  Would you expect "content apps" to return matches now that these pages are published? If there is anything else I should do to this article for that to happen (as it currently returns no results), again please do let me know!

**Comment by jmayntzhusen** [comment]
@LottePitcher , @dampee The new Content Apps section is working with the versioning now, and it looks really awesome, good job to whoever was involved at CodeCabin 😄

I will close this issue now, and if there are several things missing then maybe we should open another issue with a proper list of them so it's easier to get an overview? 🙂
