### ISSUE TITLE
Add version information or last edit date to documentation

### ISSUE THREAD

**Issue by sparkalyn** [umbraco/UmbracoDocs#115]
I'm new to Umbraco and one of the things I struggle with the most is identifying which version of Umbraco various docs apply to. 

If there will not be separate documentation for each version would it be possible to tag or label documentation pages with the versions they cover?

It could be similar to the compatibility report that already exists on the projects pages. Another option would be to add version specific sections to each page. (similar to the upgrade page http://our.umbraco.org/documentation/Installation/Upgrading/version-specific)

Even adding the date that it was last updated would be great because we could see if it's been updated since the latest  release.

**Comment by sofietoft** [comment]
Hi there,
Thank you so much for submitting this request! 😁 

As it's quite old by now, I'm gonna close down the request.
I realize we haven't yet implementing a _last updated date_, but it'd definitely be a great thing to have!
I'll make sure to have a new request for this made up, in the near future!

- Sofie
