### ISSUE TITLE
Docs on using Models Builder interfaces to render compositions

### ISSUE THREAD

**Issue by greystate** [umbraco/UmbracoDocs#1151]
## What type of issue is it?

Missing documentation

## What article/section is this about?

[Reference/Templating/Modelsbuilder](https://our.umbraco.com/documentation/Reference/Templating/Modelsbuilder/)

## Describe the issue:

The Models Builder section is missing some docs on how to render data from compositions (without having to use the generic `GetPropertyValue()` thingy).

So I've started some, but thought I'd get some feedback before I went too crazy overboard :-)

They're in [my branch over here](https://github.com/greystate/UmbracoDocs/blob/527076a6a8b46a949154071e0386e6a75ce2bc3f/Reference/Templating/Modelsbuilder/Using-Interfaces.md) for public scrutiny...

**Comment by jmayntzhusen** [comment]
Hey @greystate 

The page on your branch looks good 🙂 I don't know how much you are planning to add to this, I would suggest you either use this issue to keep track of parts and then do PR's little by little or just submit what you have and then see if others add onto it. 

We may as well benefit from what is already there 😉

**Comment by greystate** [comment]
Thanks @jmayntzhusen 👍 

I'll submit a PR and get the ball rolling from there ⚾️ 🎢

**Comment by jmayntzhusen** [comment]
I would say so, it works fine at the moment 🙂
