### ISSUE TITLE
The .md extension gets stripped from code samples 

### ISSUE THREAD

**Issue by greystate** [umbraco/UmbracoDocs#1168]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Contribute/Markdown-Conventions/index.md***

In the [Internal links section](https://our.umbraco.com/documentation/Contribute/Markdown-Conventions/#internal-links) it is specifically mentioned that one should _"include the .md extension."_ - but the two code samples are both missing said extension:

<img width="892" alt="md-missing-render" src="https://user-images.githubusercontent.com/5463/47436177-42334780-d7a6-11e8-8f51-f9b7b7ddc078.png">

Yet, in the [actual code](https://github.com/umbraco/UmbracoDocs/blame/c2a8ba56acda24a44e13617d039d985c157be0aa/Contribute/Markdown-Conventions/index.md#L39-L47) (yep - I first tried editing it right away, of course :) the extensions are actually present:

<img width="809" alt="md-missing-code" src="https://user-images.githubusercontent.com/5463/47436231-63943380-d7a6-11e8-9b69-ee6f9af5ebed.png">

So looks like they're getting stripped in the process of formatting for display on Our...

The irony, of course, is that it wouldn't be *that* big a deal, if it weren't for the fact that it's *precisely* omitting the thing we're trying to tell people to do there. 😆 🤦‍♂️

**Comment by jmayntzhusen** [comment]
Hey @greystate 

You are right, if I recall the actual code I think it doesn't matter - if you add the .md it will strip it anyways.. 

It is important to note that it should either link to the folder name if you are targeting the index.md file or link to the file name if it is not in its own folder like below:

![udklip](https://user-images.githubusercontent.com/36075913/47482345-94bc4480-d836-11e8-9d0d-c12ab58f8ecb.PNG)

So if anyone is looking to update this - you can remove the part about including the extension but please make sure to make it clear that it should either go to the folder name or the file name if not index.md 🙂

**Comment by Niladri24dutta** [comment]
@jmayntzhusen and @greystate Can I work on this as a PR for hacktoberfest? This is my first time contribution to Umbraco repo

**Comment by greystate** [comment]
@Niladri24dutta No problem — go for it 👍

**Comment by Niladri24dutta** [comment]
@greystate Thanks, so as suggested I am just rephrasing the given instruction for a better understanding except the `.md` part because it by default removed as part of markdown.

**Comment by Niladri24dutta** [comment]
@greystate @jmayntzhusen I have created my first PR. Can you please check and let me know if anything needs to be changed?
