### ISSUE TITLE
The rewrite rule under the section **How can I control who accesses my backoffice using IP filtering?** has a security flaw.

### ISSUE THREAD

**Issue by jomehmet** [umbraco/UmbracoDocs#1212]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Umbraco-Cloud/Frequently-Asked-Questions/index.md***

In [how-can-i-control-who-accesses-my-backoffice-using-ip-filtering](https://github.com/umbraco/UmbracoDocs/blob/master/Umbraco-Cloud/Frequently-Asked-Questions/index.md#how-can-i-control-who-accesses-my-backoffice-using-ip-filtering)
```
        <!-- Don't apply rules on localhost so your local environment still works -->
        <add input="{HTTP_HOST}" pattern="localhost" negate="true" />
```

The HTTP_HOST input can easily be spoofed, e.g.

curl -H "Host:localhost" http://yoursecuresite.com/umbraco
 
As the remote address can't be spoofed I would recommend:
```
        <!-- Don't apply rules on localhost so your local environment still works -->
        <add input="{REMOTE_ADDR}" pattern="127.0.0.1" negate="true" />
```

**Comment by nul800sebastiaan** [comment]
The reason we want to make a rewrite rule is so that normal visitors will get the site served over https. That way man-in-the-middle attacks are not possible. No regular website visitor would ever willingly pretend to be localhost to prevent a redirect.

This exception is ONLY there so that when you're working with your site locally, you don't get redirected to https.

Is there any attack vector that I'm missing here?

Regardless, I would be happy with the updated suggestion as well, seems fine (but someone needs to test it first).

**Comment by jomehmet** [comment]
This issue was about [how-can-i-control-who-accesses-my-backoffice-using-ip-filtering](https://github.com/umbraco/UmbracoDocs/blob/master/Umbraco-Cloud/Frequently-Asked-Questions/index.md#how-can-i-control-who-accesses-my-backoffice-using-ip-filtering), thus only let certain IP-adresses geting acces to backoffice, not redirecting to https. Https wouldn't stop you for setting whatever Header you want in your http request, eg. setting a different Host. So as the HTTP_HOST is gotten from the header of the http/https request, anyone can spoof it.

Anyhow, I can see this attack doesn't work against Azure as it returns _404 - File or directory not found._ when you are using a diffrent host in the header. I guess they are routing requests based on the Host in the header. 

I get this attack to work on Windows 10 with Umbraco running on IIS with domain binding.

**Comment by nul800sebastiaan** [comment]
Cool, it seems this is a non-issue. I'll close it for now unless we can reproduce a problem. Thanks!
