### ISSUE TITLE
New backoffice clientside events for content and grid

### ISSUE THREAD

**Issue by lars-erik** [umbraco/UmbracoDocs#1215]
Missing documentation. Issue solicited by @dampee :)

## What article/section is this about? 
Extending

## Describe the issue:
The content editor process has new events: 
- content.loaded
- content.saved
- content.saving
- content.newReady
- content.unpublishing
- content.unpublished

The content is in the event args.

The grid editor has new events:
- grid.initializing
- grid.initialized
- grid.rowAdded
- grid.itemAdded

The DOM and grid model is in the event args.

Short intro to hooking up to any events on the bottom of #2639.

Both PRs:
https://github.com/umbraco/Umbraco-CMS/pull/2639
https://github.com/umbraco/Umbraco-CMS/pull/2640

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
