### ISSUE TITLE
Duplicated markdown guidelines

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/UmbracoDocs#1238]
## What type of issue is it? (Choose one - delete the others)
Duplicated documentation

## What article/section is this about? 
https://github.com/umbraco/UmbracoDocs/blob/master/README.md
https://github.com/Umbraco/UmbracoDocs/blob/master/Contribute/Markdown-Conventions/index.md

## Describe the issue:
There are some guidelines on both these pages explaining the markdown conventions to use in the documentation.  The page in the Contribute section has the new ':::' guidelines, whereas these are missing from the guidelines in the readme.

I suggest that the 'contribute' page has the full guidelines and the readme just links to that page - then only one place to keep up to date! 

Hope to do a PR shortly having a go at this

**Comment by jmayntzhusen** [comment]
Since @marcemarc merged your PR fixing this I will close this issue now 😄
