### ISSUE TITLE
Add v8 To System Requirements Page

### ISSUE THREAD

**Issue by YodasMyDad** [umbraco/UmbracoDocs#1245]
Could we get the v8 specs added to this page please. Specifically what version of ASP.NET v8 will target? Thanks..

https://our.umbraco.com/documentation/getting-started/setup/install/system-requirements

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/Setup/Install/system-requirements.md***

**Comment by nul800sebastiaan** [comment]
We'll be targetting ASP.NET 4.7.2.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by Niladri24dutta** [comment]
@nul800sebastiaan Can i work on this? Should I only need to update the .NET framework dependency for 8X version?

**Comment by jmayntzhusen** [comment]
Hi @Niladri24dutta 

Would be great if you worked on it, make sure you familiarize yourself with how our versioned documentation works: https://our.umbraco.com/documentation/Contribute/file-naming-conventions

**Comment by jmayntzhusen** [comment]
Has now been added to the requirements page: https://our.umbraco.com/documentation/Getting-Started/Setup/Requirements/ 

Thanks for reporting this problem 😉
