### ISSUE TITLE
Contradiction - Examine configuration

### ISSUE THREAD

**Issue by jamescoxhead** [umbraco/UmbracoDocs#1247]
## What type of issue is it? (Choose one - delete the others)
Two pages with conflicting information

## What article/section is this about? 
[Azure Web App configuration](https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/azure-web-apps#pre-examine-v0180) and [Flexible Load Balancing configuration](https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/load-balancing/flexible#examine-v0183)

## Describe the issue:
Whilst trying to debug an Examine issue on one of our sites this morning I came across two pages with conflicting information regarding Examine configuration.

The [flexible load balancing](https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/load-balancing/flexible#pre-examine-v0183) page says that you should add the {machinename} token to the index path. The [Azure Web Apps](https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/azure-web-apps#pre-examine-v0180) page says that you should remove this token from the path.

**Comment by sofietoft** [comment]
Hi @jamescoxhead 

Thanks for reporting this!
Sure looks like there's a mismatch between the two articles.
It also confuses me that it says *Examine v0.1.80+ / Pre Examine v0.1.80* in the Azure Web Apps article and *Examine v0.1.83+ / Pre Examine v0.1.83* in the Load balancing article 🤔 but that could perhaps have something to do with the difference in the configuration.

I'm not at all an expert in this, so we might need some help from @Shazwazza or perhaps @Jeavon ? 😇

**Comment by Jeavon** [comment]
This information is correct. The Azure Web App docs are for single Instance configuration that will never be scaled, the Load Balancing is of course configuration for scale out.
However, the tokenised path isn't required for any configuration where you have Examine v0.1.83 or higher

**Comment by jmayntzhusen** [comment]
Hi @jamescoxhead 

Have you had a chance to review what Jeavon wrote above? If there are no issues I will close this, if you disagree please reopen 🙂
