### ISSUE TITLE
Missing syntax highlighting in the documentation

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/UmbracoDocs#1266]
Our has recently been updated to support syntax highlighting https://github.com/umbraco/OurUmbraco/pull/332 

This means we are missing it everywhere in the documentation, the way to add it is to go in the markdown files and add something like this:
````
```html

<h1>headline</h1>

```
````

The currently supported highlighted languages are csharp, html, json5, xml

To make it easier we can split this task up in the subfolders of the documentation repo:

![2018-12-11_0854](https://user-images.githubusercontent.com/36075913/49786626-c0cb5080-fd24-11e8-9113-b6b5ae3f4dab.png)

- [x] Add-ons
- [x] Cheatsheets
- [x] Contribute
- [x] Development-Guidelines
- [x] Extending
- [ ] Getting-Started
- [ ] Implementation
- [ ] Reference
- [ ] Tutorials
- [ ] Umbraco-Cloud

**Comment by dampee** [comment]
👍

**Comment by jmayntzhusen** [comment]
As pretty much everything has been updated - big thanks to @BatJan! - I will close this issue 🙂🎉
