### ISSUE TITLE
The File Upload property editor lacks documentation altogether.

### ISSUE THREAD

**Issue by jabbrowocky** [umbraco/UmbracoDocs#1269]
I literally can't use the file upload property editor because your site has 0 information about it's return type or how to pull files from it in the cshtml view.  Unfortunately guessing isn't a game I like to play when developing; some documentation on this very useful property editor would be nice.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index.md***

**Comment by jmayntzhusen** [comment]
Hi @jabbrowocky 

Thanks for reporting some missing documentation, as this documentation is open source we rely on friendly and helpful members of the Umbraco community to help fill out the gaps. 

As such if you are interested in contributing information on how this property editor works then you are very welcome to submit a pull request 🙂

I can tell you that if you set up a document type with the file type and then try to debug it via Visual Studio it only returns a string containing the file path (similar to how the .Url property of a media file)

So to return the value you could do something like this:
```<a href="@Model.Content.File" >File 1</a>```

Where your file upload property has the alias `file` 😉

**Comment by jmayntzhusen** [comment]
Hey @jabbrowocky 

As this is not the only property editor missing documentation I have created a general issue about adding documentation to them, and will be closing this one. Please follow https://github.com/umbraco/UmbracoDocs/issues/1293 for any updates 🙂
