### ISSUE TITLE
When creating strongly typed classes for umbraco headless matching IS case sensitive and it's explained wrong

### ISSUE THREAD

**Issue by v3rt1go** [umbraco/UmbracoDocs#1277]
## What type of issue is it?
Wrong documentation

## What article/section is this about? 
https://our.umbraco.com/documentation/Umbraco-Cloud/Headless/Headless-Net-Client/Query

## Describe the issue:
in the https://our.umbraco.com/documentation/Umbraco-Cloud/Headless/Headless-Net-Client/Query#filter-on-document-types-with-strongly-typed-classes section of the documentation, in the example for creating strongly typed classes the comment:
`// The alias of our Document Type is "wine" and matching isn't case sensitive`
is wrong.

Matching actually is case sensitive. It takes the name of the custom class (T), strips out any "Model" part and converts the first letter of the class name to lower case. Than expects the document type alias to match. This also implies that the document type alias will always start with a lowercase letter, which is not enforced in the UI.

**Comment by jmayntzhusen** [comment]
Will close this for now, Headless is ever-changing and keeping the documentation up to date is not feasible right now.

For now we have to await the launch and then we can review whatever documentation will be available then.
