### ISSUE TITLE
Config Transforms Doesn't Mention Latch Prefix

### ISSUE THREAD

**Issue by Nicholas-Westby** [umbraco/UmbracoDocs#1284]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Umbraco-Cloud/Set-Up/Config-Transforms/index.md***

That page doesn't mention that Umbraco Cloud adds a file called `Latch.Web.live.xdt.config` by default. Note that it contains a "Latch." prefix. This does not match the format mentioned on the page, which is `{config-file name}.{environment}.xdt.config`. If it were following that format, the filename would be `Web.live.xdt.config`.

So now I'm confused, and these questions come to mind:

* Do I need to add "Latch." to all my config transforms?
* Does this apply to only the Web.config, or can it be applied to other configuration files?
* Can I remove "Latch." from my Web.config transforms?
* If I do remove "Latch." from my web.config transforms, will there be unintended side-effects?

It would be useful if this page clarified some of these points.

**Comment by nul800sebastiaan** [comment]
Just follow the documentation, which is clear and correct.

As noted in the `Latch.Web.live.xdt.config`: 

> This is the default Umbraco Cloud Latch transform file - It is used to ensure that the live site will be running
>   via https and force redirects from http to https.
>   It does so by setting the "umbracoUseSSL" setting to true, which will tell the Umbraco Backoffice to serve URLs via https
>   and it adds a redirect rule that will force the site to run via https, except for when running localhost.
> 
>   To disable the forced https, simply remove this file from your repository. This is not advised, as all domains
>   on Umbraco Cloud will be running https, as a certificate will be issued for custom domains by the Latch feature,
>   and all [alias].s1.umbraco.io domains will already be protected.
> 
>   For more info about how this file is working check: https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Config-Transforms/
>   Documentation for the redirect rule can be found on our: https://our.umbraco.com/documentation/Umbraco-Cloud/Set-up/Manage-Domains/Rewrites-on-Cloud/#running-your-site-on-https-only

**Comment by Nicholas-Westby** [comment]
I'm not sure what you mean. The documentation page does not mention the "Latch." prefix at all. It also doesn't mention the mechanism by which this file pattern can work.

Why isn't the file simply called "Web.live.xdt.config", for example? What would happen if both "Latch.Web.live.xdt.config" and "Web.live.xdt.config" were present? The documentation implies the latter should be the case, yet the former is the present file.

Could I also create "WhateverPrefix.Web.live.xdt.config"? There is a lot this documentation does not mention.

**Comment by nul800sebastiaan** [comment]
It's a special file for our Latch product. 

Have you tried following the documentation, which specifies how we expect people to work with config transforms? It mentions you can use development-specific transforms and package-specific transforms.

**Comment by Nicholas-Westby** [comment]
@nul800sebastiaan I must have missed the section about package-specific transforms. That's my mistake. Thank you for pointing me in the right direction.
