### ISSUE TITLE
installing v8 via nuget following this guide no working...

### ISSUE THREAD

**Issue by mistyn8** [umbraco/UmbracoDocs#1296]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/Setup/Install/install-umbraco-with-nuget.md***

following the instructions, with one change..
Install-Package UmbracoCms -Pre -Source https://www.myget.org/F/umbracocore/api/v3/index.json

when building (Ctrl+f5 from vs 2017) the successfully installed nuget package..
I get 
`
Server Error in '/' Application.
Parser Error
Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 

Parser Error Message: Could not load type 'Umbraco.Web.UmbracoApplication'.

Source Error: 

Line 1:  <%@ Application Inherits="Umbraco.Web.UmbracoApplication" Language="C#" %>

Source File: /global.asax    Line: 1 

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3282.0
`

It looks like all the required umbraco dlls aren't being propagated into the bin folder (they don't appear n the solution references either), are there dependencies missing in the nuget package?

**Comment by nul800sebastiaan** [comment]
It seems to be a problem on your machine, let's continue on the forum: https://our.umbraco.com/forum/umbraco-8/95272-v8-preview-via-nuget-doesnt-seem-to-fetch-umbraco-dlls-or-reference-them-in-the-solution
