### ISSUE TITLE
Renaming Seperator -> Separator

### ISSUE THREAD

**Issue by readingdancer** [umbraco/UmbracoDocs#1303]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation ( for v8 )

## Describe the issue:

I have created a pull request ( https://github.com/umbraco/Umbraco-CMS/issues/4060 ) that fixes these typos in the v8 branch, assuming it gets merged in, these are changes to the docs to reflect the change.

**Comment by jmayntzhusen** [comment]
Has been fixed now, thanks @readingdancer
