### ISSUE TITLE
Moved pages not deleted from web

### ISSUE THREAD

**Issue by lesleyauk** [umbraco/UmbracoDocs#134]
In [commit 6828dab...](https://github.com/umbraco/Umbraco4Docs/commit/6828dab43e0931bc44a56941c27bd9d7aca74d3f) several pages were moved to new locations, but the old versions still exist on the site (and Google's index). For example: [/documentation/Reference/Mvc/partial-views](http://our.umbraco.org/documentation/Reference/Mvc/partial-views) is out of date and replaced by [/documentation/Reference/Templating/Mvc/partial-views](http://our.umbraco.org/documentation/Reference/Templating/Mvc/partial-views).

Should there be a redirect on moved pages?

**Comment by hemraker** [comment]
Fixed
