### ISSUE TITLE
V8: Remove MySQL support & update requirements

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/UmbracoDocs#1380]
For reasons mentioned in https://github.com/umbraco/Umbraco-CMS/pull/4143 we've removed support for MySQL in v8. The requirements for v8 should mention this.

Furthermore to use v8, people will need .NET 4.7.2 installed on their machine and use at least Visual Studio 2017 version 15.9 and higher. Lower versions will throw errors, so 15.9+ is important to note.

Hosting requirements will also need to include 4.7.2 installed on the server.

**Comment by BatJan** [comment]
I reckon that the page about permissions also need to be updated accordingly? https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/permissions

I'll create a separate issue for this if people agree 😃

**Comment by jmayntzhusen** [comment]
Has now been added to the requirements page: https://our.umbraco.com/documentation/Getting-Started/Setup/Requirements/
