### ISSUE TITLE
Add info on missing ContentService Events

### ISSUE THREAD

**Issue by marcemarc** [umbraco/UmbracoDocs#1405]
## What type of issue is it? (Choose one - delete the others)

Missing documentation

## What article/section is this about? 
Content Service Events Page
https://our.umbraco.com/documentation/Reference/Events/ContentService-Events

## Describe the issue:

We're missing info for the following events 

Emptied Recycle Bin - ContentService_EmptiedRecycleBin(IContentService sender, Umbraco.Core.Events.RecycleBinEventArgs e)
Emptying Recyle Bin - ContentService_EmptyingRecycleBin(IContentService sender, Umbraco.Core.Events.RecycleBinEventArgs e)

SaveBlueprint - ContentService_SavedBlueprint(IContentService sender, Umbraco.Core.Events.SaveEventArgs<Umbraco.Core.Models.IContent> e)

and

DeletedBlueprint - ContentService_DeletedBlueprint(IContentService sender, Umbraco.Core.Events.DeleteEventArgs<Umbraco.Core.Models.IContent> e)

**Comment by jmayntzhusen** [comment]
Closed by #1551
