### ISSUE TITLE
Add information about how to install Umbraco using VSCode

### ISSUE THREAD

**Issue by BatJan** [umbraco/UmbracoDocs#1409]
## What type of issue is it?
Missing documentation

## What article/section is this about? 
[Installing Umbraco manually](https://our.umbraco.com/documentation/Getting-Started/Setup/Install/install-umbraco-manually)

## Describe the issue:
I just noticed that this page does not contain any information about how to install Umbraco using VSCode - This should be added and then the webmatrix way of doing things should probably have a warning stating that Webmatrix has been sunset by Microsoft and therefore it's no longer a recommended way of installing Umbraco or perhaps it should be removed entirely?

**Comment by jmayntzhusen** [comment]
Hey @BatJan 

If you go one level up from that page to the install overview: https://our.umbraco.com/documentation/Getting-Started/Setup/Install/ 

Then you will see that we actually have both the "Manual install" one you linked, but also a guide for VS Code and for doing it with NuGet in VS. 

I think you are right though and the manual install page should be removed or remade atleast as Webmatrix is deprecated.. Will bring it up on our next Docs curators meeting 👍😁
