### ISSUE TITLE
"Current" listed multiple times

### ISSUE THREAD

**Issue by BatJan** [umbraco/UmbracoDocs#1456]
## What type of issue is it?
Parsing bug I think...

## What article/section is this about? 
[Property editors - Grid Layout](https://our.umbraco.com/documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout)

## Describe the issue:
Going through the documentation some places I've noticed that it says "current" multiple times where I would expect it to have version numbers because of YAML notation. But I think there is a bug that will render the "current" link multiple times if there are sub sections containing links maybe? I'm not sure but just noticed it in particular on the page mentioned in the link above.

I'm not sure what the issue might be but surely it should not act up like this? 😃

**Comment by BatJan** [comment]
It also happens at this page: [Dropdown list Multiple](https://our.umbraco.com/documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/DropDown-List-Multiple)

Where one of the currents links to [DropDown List Multiple Publish Keys](https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/DropDown-List-Multiple-Publish-Keys)

I'm not sure why it happens though but it's a bit confusing - Can't seem to find the logic behind it.

**Comment by jmayntzhusen** [comment]
Hmm yea you are right, will have to look into the logic on Our that generates this list again, but it seems each current link is an article with similar names in sub directories to the current page, I know the versioning logic is looking at filenames, so there could be something not working as intended there 😁

**Comment by jmayntzhusen** [comment]
This had something to do with a weird structure being used, for the grid layout file it was because it had both a folder called Grid-Layout with several other articles inside, as well as a file on level with the folder called Grid-Layout.md, since we look at the path and strip away file extensions it caused this error 🙂

Should be all good now 👍
