### ISSUE TITLE
Versions box needs z-index: 1

### ISSUE THREAD

**Issue by BatJan** [umbraco/UmbracoDocs#1461]
## What type of issue is it?

Other: Minor CSS bug

## What article/section is this about? 
[Dropdown](https://our.umbraco.com/documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Dropdown)

## Describe the issue:
The versions box needs position: relative and z-index: 1; since there otherwise is a risk that the headlines will lay on top of it. Try clicking the last "Current" link in the versions box in the above link - Currently not possible (On desktop at least) 😃 - But perhaps this should be filed as a bug on the Our Umbraco issue tracker? I'll happily move it just let me know.

**Comment by jmayntzhusen** [comment]
Hey @BatJan 

Good catch! But yes this should be moved to Our I think as that is where it would need to be fixed 🙂

**Comment by BatJan** [comment]
Thanks @jmayntzhusen - I have opened a new issue at the Our tracker here https://github.com/umbraco/OurUmbraco/issues/382
