### ISSUE TITLE
Update Property Editors for v8

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/UmbracoDocs#1528]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about? 
https://our.umbraco.com/documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/ 

## Describe the issue:
With v8 coming out later this year we should update Property editors to be have up to date examples for v8 🙂

- [x] Checkbox (Umbraco.TrueFalse)
- [x] Checkbox list (Umbraco.CheckBoxList)
- [x] Color Picker (Umbraco.ColorPicker)
- [x] Content Picker (Umbraco.ContentPicker)
- [x] Date (Umbraco.Date)
- [x] Date/Time (Umbraco.DateTime)
- [x] Decimal (Umbraco.Decimal)
- [x] Dropdown (Umbraco.DropDown.Flexible)
- [x] Email address (Umbraco.EmailAddress)
- [x] File upload (Umbraco.UploadField)
- [x] Grid layout (Umbraco.Grid)
- [x] Image Cropper (Umbraco.ImageCropper)
- [x] Label (Umbraco.NoEdit)
- [x] List view (Umbraco.ListView)
- [x] Markdown editor (Umbraco.MarkdownEditor)
- [x] Media Picker (Umbraco.MediaPicker)
- [x] Member Group Picker (Umbraco.MemberGroupPicker)
- [x] Member Picker (Umbraco.MemberPicker)
- [x] Multi Url Picker (Umbraco.MultiUrlPicker)
- [x] Multinode Treepicker (Umbraco.MultiNodeTreePicker)
- [x] Nested Content (Umbraco.NestedContent)
- [x] Numeric (Umbraco.Integer)
- [x] Radio button list (Umbraco.RadioButtonList)
- [x] Repeatable textstrings (Umbraco.MultipleTextstring)
- [x] Rich Text Editor (Umbraco.TinyMCEv3)
- [x] Slider (Umbraco.Slider)
- [x] Tags (Umbraco.Tags)
- [x] Textarea (Umbraco.TextArea)
- [x] Textbox (Umbraco.TextBox)
- [x] User picker (Umbraco.UserPicker)

**Comment by Adolfi** [comment]
PR for the label property:  https://github.com/umbraco/UmbracoDocs/pull/2113

**Comment by bgunnarsson** [comment]
PR for EmailAddress: #2762

**Comment by renaa** [comment]
PR for Decimal: https://github.com/umbraco/UmbracoDocs/pull/2800

**Comment by renaa** [comment]
PR for File upload: https://github.com/umbraco/UmbracoDocs/pull/2801k

**Comment by renaa** [comment]
PR for Markdown editor: https://github.com/umbraco/UmbracoDocs/pull/2806
