### ISSUE TITLE
Improve Dependency Injection (aka, IOC) Documentation Further

### ISSUE THREAD

**Issue by Nicholas-Westby** [umbraco/UmbracoDocs#1542]
There was a ticket a while back about improving the IOC documentation: https://github.com/umbraco/UmbracoDocs/issues/342

That helped, although I found that I needed to do some more work to get DI working in a way that didn't break the back office.

This was because I had some plugins installed (in my case, Formulate). There is a comment here that explains why this is: https://our.umbraco.com/forum/umbraco-cloud/88400-umbraco-cloud-771-dependency-injection#comment-279561

In essence, it seems that every assembly that implements `TreeController` needs to be registered with the container.

I have some code that does this here: https://our.umbraco.com/forum/umbraco-cloud/88400-umbraco-cloud-771-dependency-injection#comment-302582

I'm not super sure on why this seems to be necessary, but I hope somebody who knows more about this can vet this and hopefully amend the documentation appropriately.

Here's the documentation page: https://our.umbraco.com/documentation/reference/using-ioc

**Comment by marcemarc** [comment]
Thanks @Nicholas-Westby for raising this - I'm not sure on the necessity of registering each TreeController with the container - but can raise it at the next docs meeting to see if some input can be found here and report back - so we can improve the using-ioc page for people who stumble across this issue, and your workaround - (there is another PR open to add a lightject example to the page too - https://github.com/umbraco/UmbracoDocs/pull/1170).

**Comment by sofietoft** [comment]
Hi! 
As we haven't seen any new activity on this issue in while, I'll close it for now.

If you feel it's still relevant, you're welcome to reopen it! 😁 
Thanks.

/Sofie
