### ISSUE TITLE
broken link in tutorial

### ISSUE THREAD

**Issue by nikro412956** [umbraco/UmbracoDocs#1543]
from: https://our.umbraco.com/documentation/Tutorials/Creating-Basic-Site/Creating-Your-First-Template-and-Content-Node/

to: https://our.umbraco.com/documentation/Tutorials/Creating-Basic-Site/Creating-Your-First-Template-and-Content-Node/CSS-And-JavaScript

![image](https://user-images.githubusercontent.com/22655656/52555948-6e251800-2deb-11e9-83a1-6574ca544043.png)

**Comment by nikro412956** [comment]
probably meant to go to https://our.umbraco.com/documentation/Tutorials/Creating-Basic-Site/CSS-And-JavaScript/

**Comment by jmayntzhusen** [comment]
Hey @nikro412956 

Thanks a lot for reporting this! I have fixed it now so it works again 😉
