### ISSUE TITLE
broken link in tutorial

### ISSUE THREAD

**Issue by nikro412956** [umbraco/UmbracoDocs#1544]
from: https://our.umbraco.com/documentation/Tutorials/Creating-Basic-Site/CSS-And-JavaScript/

to: https://our.umbraco.com/documentation/Tutorials/Creating-Basic-Site/CSS-And-JavaScript/Outputting-the-Document-Type-Properties

should probably be: https://our.umbraco.com/documentation/Tutorials/Creating-Basic-Site/Outputting-the-Document-Type-Properties/

![image](https://user-images.githubusercontent.com/22655656/52556542-27d0b880-2ded-11e9-8501-530504a20eb0.png)

**Comment by jmayntzhusen** [comment]
Another great catch 😁 I have gone through all of them now, so hopefully it works for you throughout the guide.

**Comment by dampee** [comment]
Hi @nikro412956 
Thanks a lot for taking time to report this.  Would you like to help out and create a Pull Request on the docs?  It's an easy fix.  I'll be glad to help you out with doing the PR.  

If not, we will fix it asap!

**Comment by nikro412956** [comment]
Hi @dampee 
I am not sure what you mean with that. 
I think i am missing a piece of context.
All the stuff about git i understand since i am a dev myself but what would i need to help you out with?

**Comment by dampee** [comment]
Hi @nikro412956 
You can do a pull request to propose a change "in code" on the documentation repo.
If you go to this page : https://github.com/umbraco/UmbracoDocs/blob/master/Tutorials/Creating-Basic-Site/CSS-And-JavaScript/index.md

You have the "source" of this documentation page.  If you then edit the documentation by clicking on this button: 
![afbeelding](https://user-images.githubusercontent.com/1857460/52557770-b4c94100-2df0-11e9-83e1-73cdc28a28bb.png)
You can change the link and click the "propose file change" at the bottom of the website.

**Comment by dampee** [comment]
Don't forget to mention this issue in the comments (which is your commit message).  You can mention an issue by using the hash tag followed by the issue number.  In this case #1554

**Comment by nikro412956** [comment]
Hi @dampee 
ah like that.
alright i will keep it in mind for the future since the current problems are fixed.
but thanks for the info.

**Comment by nikro412956** [comment]
and the quick fixes

**Comment by dampee** [comment]
Hi didn't notice @jmayntzhusen fixed in in the mean time...

fixed in 89aa5403797cbf62743e56890112d895338f0bed

**Comment by nikro412956** [comment]
Happens to the best of us
