### ISSUE TITLE
broken and wrong link in tutorial

### ISSUE THREAD

**Issue by nikro412956** [umbraco/UmbracoDocs#1545]
from: https://our.umbraco.com/documentation/Tutorials/Creating-Basic-Site/Creating-Master-Template-Part-2/

link text: https://umbraco.tv/videos/developer/fundamentals/surface-controllers/ (no longer exists)
to: https://our.umbraco.com/documentation/Reference/Templating/Mvc/forms

link text should be: https://umbraco.tv/videos/umbraco-v7/developer/fundamentals/surface-controllers/
link should be: https://umbraco.tv/videos/umbraco-v7/developer/fundamentals/surface-controllers/

currently creating a pull request to fix this

![image](https://user-images.githubusercontent.com/22655656/52565030-f1ebfe00-2e05-11e9-8c68-b17a57df922e.png)

**Comment by jmayntzhusen** [comment]
Thanks for fixing it! 🎉
