### ISSUE TITLE
Broken link in version specific upgrading

### ISSUE THREAD

**Issue by prashu2705** [umbraco/UmbracoDocs#1548]
The link  "the list on the issue tracker" - "http://issues.umbraco.org/issues/U4?q=Due+in+version%3A+7.7.0+Backwards+compatible%3F%3A+No+" is broken

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/Setup/Upgrading/version-specific.md***

**Comment by jmayntzhusen** [comment]
Hey @prashu2705 

Good catch, it seems the link was to our old issue tracker, the new one has a bit less filtering, so the new link would be: 
https://issues.umbraco.org/issues/?q=&project=U4&tagValue=&release=7.7.0&issueType=&search=search

Would you like to help others like yourself in the future by fixing the link in a PR? 🙂 For instructions you can read here: https://our.umbraco.com/documentation/Contribute/#contribute-to-umbraco-documentation

**Comment by OlenaVyshnevska** [comment]
Hey @jmayntzhusen 

Here's the PR with the broken link fix: https://github.com/umbraco/UmbracoDocs/pull/1554
