### ISSUE TITLE
Question about licensing

### ISSUE THREAD

**Issue by nikro412956** [umbraco/UmbracoDocs#1550]
hi,

i was wondering if there is any documentation about how to create and validate licenses for self created Umbraco packages?
i did notice that there was some documentation about a licensing model but there wasn't really anything about creating licenses yourself.

regard,
Nick

**Comment by nul800sebastiaan** [comment]
There's no such documentation since we don't provide any licensing products. I would recommend to research general .NET licensing products to get some ideas of what might suit your project.

**Comment by nikro412956** [comment]
@nul800sebastiaan do you know if i can get in touch with one of the Umbraco forms devs?
