### ISSUE TITLE
Sidebar nav items are out of order

### ISSUE THREAD

**Issue by dangrussell** [umbraco/UmbracoDocs#1573]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about? 
https://our.umbraco.com/documentation/Tutorials/Creating-Basic-Site/

## Describe the issue:
Under "Tutorials" > "Creating Basic Site", the menu items appear out of order.

In the menu, they appear in this order:
* Articles Parent and Article Items
* Conclusions Where Next
* Creating Master Template Part 1
* Creating Master Template Part 2
* Creating Your First Template and Content Node
* CSS And JavaScript
* Document Types
* Getting Started
* Master Template The Navigation Menu
* Outputting the Document Type Properties

In the index page of https://our.umbraco.com/documentation/Tutorials/Creating-Basic-Site/ they are mentioned in this (assumed correct) order:
* Getting Started
* Creating Your First Document Type
* Creating Your First Template and Content Node
* CSS & JavaScript
* Outputting the Document Type Properties
* Creating a Master Template Part 1
* Creating a Master Template Part 2
* Master Template - The Navigation Menu
* Articles Parent and Article Items
* Conclusions and Where Next?

**Comment by dangrussell** [comment]
![annotation 2019-02-20 145755](https://user-images.githubusercontent.com/4387475/53120902-e3e25f80-3520-11e9-8883-afefbaca950c.jpg)

**Comment by dampee** [comment]
Hi @dangrussell 
Thanks for noticing.  We'll try to update in the upcoming days.

**Comment by dampee** [comment]
There is already a PR on OUR to fix this: https://github.com/umbraco/OurUmbraco/pull/389

**Comment by jmayntzhusen** [comment]
Thanks for letting us know, has now been fixed by https://github.com/umbraco/OurUmbraco/pull/389 🎉🙂
