### ISSUE TITLE
CacheRefresher Information for V8

### ISSUE THREAD

**Issue by rsoeteman** [umbraco/UmbracoDocs#1575]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about? 
CacheRefreshers in Umbraco V8

## Describe the issue:
Since V8 the old CacheRefresher documentation is outdated, should be nice to have this for V8

**Comment by sofietoft** [comment]
Hi @rsoeteman !

Completely agree!
I've forwarded it to our developers, and they will look into get this documented ASAP.

Meanwhile, you can follow our progress on V8 Documentation here: https://our.umbraco.com/documentation/v8documentation

/Sofie

**Comment by sofietoft** [comment]
Hi @rsoeteman ! 😄 

I wanted to let you know, that I'll be closing this issue for now.
A while back, I've made another issue to get the Cache documentation updated for Umbraco 8: #1874 which has the `community/up-for-grabs` label on it.
