### ISSUE TITLE
Link to Kudu article is broken

### ISSUE THREAD

**Issue by skttl** [umbraco/UmbracoDocs#1592]
https://our.umbraco.com/documentation/Umbraco-Cloud/Troubleshooting/Deployments/Path-too-long-exception/#solution

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Umbraco-Cloud/Troubleshooting/Deployments/Path-too-long-exception/index.md***

**Comment by jmayntzhusen** [comment]
Thanks for reporting this @skttl !

It seems it is currently using this link `../../Set-up/Power-tools/` and it should be using `../../../Set-up/Power-tools/` - one level higher. Do you feel like making a PR to correct this? 🙂

**Comment by skttl** [comment]
Sure :)
