### ISSUE TITLE
Worth while documenting all the clientside events that the eventsService emits?

### ISSUE THREAD

**Issue by PeteDuncanson** [umbraco/UmbracoDocs#1595]
Discussion

There is no documentation on the eventsService or what events it emits. As a result you don't know about it, how to use it or what events you could hook into.

## Describe the issue:

There is a lack of docs at all about the eventsService in AngularJS. Poking through the code it seems there are a lot of different events that are getting fired here there and everywhere but none of them are listed anywhere, its all done with magic strings and is error prone.

Quick search through the Core code finds plenty of references:

https://github.com/umbraco/Umbraco-CMS/search?p=6&q=eventsService.on&unscoped_q=eventsService.on

Pondered a script that could hunt for these references and then list them out. Compare if new ones get added and then allow us to list what on earth each does (separately in another medium) and when you might want to use it. Currently the only other way of doing this is poking around the code.

An issue instantly arises is how to keep it up to date? Thats why I suggest a script so we can re-run it. It could alert when new ones are found or removed too.

It might be worth trying to clean up the Core code base with some constants for the event names too but thats a separate issue I think but if done could make this documentation easier as in theory it would all be in a one place (See https://github.com/umbraco/Umbraco-CMS/issues/4804).

**Comment by marcemarc** [comment]
Hi Pete

We're not sure, it would be good if it was part of the autogenerated docs, as we're trying to avoid documenting code for the sake of it in the manual documentation... if the reference can be generated from the code - in the manual docs it's good to show examples and information about the existence of things in the context of when they might be used, but with the eventsService we're not sure how best to show it off, and are open to suggestions?

**Comment by sofietoft** [comment]
Hi guys! I'm not entirely sure this is relevant here, but @abjerner is working on setting up some Angular documentation on Our: #2045

**Comment by abjerner** [comment]
If we're talking about an auto-generated list, I believe this should be part of the existing _Umbraco Backoffice UI API documentation_. But as this is build using a third party tool, I'm not sure how much we're able to customize it.

My thoughts for the additional documentation would be to have useful examples and more detailed information, whereas the _Umbraco Backoffice UI API documentation_ would be more like a reference API. But also so the two compliment each other.

**Comment by sofietoft** [comment]
Hi guys!
Just letting you know, that I'm closing this issue for now.
I don't think it makes sense to have multiple issues around the same topic. 
So, please refer to #2045 where to most recent talks around tnis topic can be found 💪 Thanks!
