### ISSUE TITLE
Add how to render the MiniProfiler to the Debugging page

### ISSUE THREAD

**Issue by louisjacksonrees** [umbraco/UmbracoDocs#1596]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about? 
https://our.umbraco.com/Documentation/Getting-Started/Code/Debugging/#miniprofiler

## Describe the issue:
It would be helpful to add this render helper for the MiniProfiler to the Debugger docs as i can't see the profiler without adding this to my page:

`@Html.RenderProfiler()`

**Comment by marcemarc** [comment]
Hi louisjacksonrees

do you have umbDebug=true on the querystring? and compilation debug true in the web.config?

with those two settings on, the miniprofiler should display

or am I misunderstanding?

regards

Marc

**Comment by louisjacksonrees** [comment]
Yeah I have both set to true, but it doesn’t show unless I add the partial
  

  
  

  
  
>

**Comment by marcemarc** [comment]
@louisjacksonrees which version of Umbraco are you using? I'll try to reproduce.

**Comment by louisjacksonrees** [comment]
Version 7.12, thank you

**Comment by marcemarc** [comment]
Hi @louisjacksonrees 

I've spun up a fresh version of Umbraco 7.12.4, installed via Nuget with the Starterkit.

If I run the site locally with Visual Studio (F5 - 'Start Debugging') and have debug attribute set to "true" in the compilation section of the web.config, then when the site displays, if I then add ?umbdebug=true to the url of the page, I do see the MiniProfiler appear.
![Mini Profiler in Top Right](https://user-images.githubusercontent.com/260802/54878126-1c2ad580-4e20-11e9-9da8-8525b0b4c801.png)

![Compilation Debug in Web.config](https://user-images.githubusercontent.com/260802/54878132-38c70d80-4e20-11e9-878f-503f14142dbe.png)

So I'm unfortunately not able to recreate the problem :-(, it doesn't seem necessary to add @Html.RenderProfiler() to make the profiler to appear! but perhaps your context of running the site trying to see the Miniprofiler is different? eg an upgraded solution, or not using Visual Studio or something else? In which case it might be a bug with Umbraco in that particular scenario, and it could be reported via the issue tracker: https://github.com/umbraco/Umbraco-CMS/issues or maybe somebody would have advice in the forum: https://our.umbraco.com/forum/

But I'm not sure we should add it to the documentation just yet, not unless we get to the bottom of why? first.

**Comment by jmayntzhusen** [comment]
Hey @louisjacksonrees 

As we haven't heard back about this I will close this issue.

If you have any follow up comments or more insight then feel free to post them here and we will reopen the issue 🙂
