### ISSUE TITLE
Save and Publish / Save / Unpublish confirmation popup

### ISSUE THREAD

**Issue by pawseytj** [umbraco/UmbracoDocs#1598]
### Save and Publish / Save / Unpublish confirmation popup temporarily obscures editable content within CMS.

[https://ibb.co/0CBYmSQ](url)

Please consider alternative methods for alerting users.

My opinion is that popup notifications should be removed all-together.  Popups could be replaced with alternative methods e.g. after clicking Save:

- Button changes to a green tick if successful, or
- Button changes to a red cross if unsuccessful, and if you hover your mouse over the button then more details should appear e.g. "_All required items have not been completed_".

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Contribute/Pull-Requests/index.md***

**Comment by jmayntzhusen** [comment]
Hey @pawseytj 

This is more of a feature request for the CMS, this issue board is for changes to the documentation of the CMS 🙂

Please create this on https://github.com/umbraco/Umbraco-CMS/issues instead.
