### ISSUE TITLE
Can we update a page to confirm that is it still correct for v8?

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/UmbracoDocs#1601]
## What type of issue is it?
Question

## What article/section is this about? 
All of them!

## Describe the issue:
The "this article has not yet been verified against Umbraco 8..." note that displays on most pages in the docs (which is an excellent idea, by the way!)  Is there a way to flag specific pages as being still correct for v8 so this message disappears?

For example, I followed the instructions for extending language files in a v8 site, and it works just fine.  So of course it would be good to stop that note from showing. I had a look at the source file and the YAML documentation but wasn't obvious.

Page in question:
https://github.com/umbraco/UmbracoDocs/blob/master/Extending/Language-Files/Language-Files-For-Packages/index.md

**Comment by marcemarc** [comment]
@LottePitcher I think there is some YAML that we can add eg 'checkedForV8' that will hide the message, but keep versionFrom as 7.0.0, but looking at the logic, I can't work out what it is/whether that's been implemented yet:

@if (currentUmbracoVersion == 8
     && currentVersionIsRemovedForv8 == false 
     && currentVersion != null
     && currentVersion.Url.EndsWith("-v7") == false
     && currentVersion.VersionFrom.Major == 7 
     && currentVersion.VersionTo.Major == 0)
{
var currentVersionIsRemovedForv8 = currentVersion != null && currentVersion.VersionRemoved != null && currentVersion.VersionRemoved.StartsWith("8");

I'll see if anyone knows...

**Comment by LottePitcher** [comment]
Thanks, I wait to hear then. 
Perhaps a positive 'this has been verified for v8' message instead of just hiding the current one might be worth considering, for a while at least.

**Comment by marcemarc** [comment]
@LottePitcher ooh, we might have an update on this soon

**Comment by marcemarc** [comment]
@LottePitcher we now have a new YAML tag: needsV8Update which is set to true on all documents that haven't been refangled for V8 yet, if a page is perfect for V7 and V8 and no new version of the document is required to be created, then completely removing the needsV8Update: tag from the YAML will mean the warning message will disappear on the page - hopefully then eventually we'll have no 'needsV8Update' YAML tags left hanging around in the docs, and we should be able to draw up a report on the pages left to test... or at least that's the gist:

So for a page that is good for both this:
---
versionFrom: 7.0.0
needsV8Update: "true"
---

would become

---
versionFrom: 7.0.0
---

**Comment by jmayntzhusen** [comment]
This is still pending as we are waiting on https://github.com/umbraco/OurUmbraco/pull/408 to be reviewed and merged 🙂

**Comment by marcemarc** [comment]
Yes but we can remove the YAML for ones that have been checked... pending the merge, eg banners won't disappear, but they will when it's merged in

**Comment by jmayntzhusen** [comment]
This is now live, if anyone finds a page with the note that shouldn't have it, please make a PR to remove the YAML tag:
`needsV8Update: true`
Likewise if you find one that doesn't have it but doesn't work, please make a PR to add the YAML tag, or create an issue for it 😁
