### ISSUE TITLE
Correction on Umbraco Document about site setup permission setting

### ISSUE THREAD

**Issue by joecklau** [umbraco/UmbracoDocs#1603]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about? 
https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/permissions#file-and-folder-permissions

## Describe the issue:
On Umbraco site setup folders Permission setting document, it said that:
> Additionally the IUSR account and IIS_IUSRS account only require 'read only' access to the site's folders

However, strictly following the document on permission setup will face error in Visual Studio Release build, i.e. web.config compilation use debug="false" (or remove debug attribute).

The symptom during browsing will be "DependencyHandler.axd" cannot be loaded/empty, giving unrelated MIME-type mismatch error message in browser console. e.g. Chrome: "Refused to apply style ...DependencyHandler.axd?... because its MIME type (”) is not a supported". (IE have different message, but same meaning)

The solution to my situation is to assign both read&write access to IUSR + IIS_IUSRS.

Please help to update the document. I think Shazwazza's ClientDependency (making DependencyHandler.axd) has already been a core component of Umbraco. It's good to cater also the permission required in this library.

**Comment by sofietoft** [comment]
Apologies for the delay on this one @joecklau, and thanks for the report!

Would you be up for updating this documentation yourself? 😄 
We have some guidelines on how here: https://our.umbraco.com/documentation/Contribute/

**Comment by sofietoft** [comment]
Hi @joecklau !

It's been a while since I've seen any activity on this issue.
I can also see that the article in question has been updated since.

I'll close this issue for now.
It would be great if you could test the new article against your setup - and please let us know if the article needs further updating 💪 
And thanks again for reporting the issue.
