### ISSUE TITLE
IoC settings for version 8

### ISSUE THREAD

**Issue by VasilkovME** [umbraco/UmbracoDocs#1604]
Could you please update the documentation how to set up Autofac for the 8th version.  
The following code from the documentation page (https://our.umbraco.com/documentation/reference/using-ioc) doesnot work: 
           
            var builder = new ContainerBuilder();

            // register all controllers found in your assembly
            builder.RegisterControllers(typeof(MvcApplication).Assembly);
            builder.RegisterApiControllers(typeof(MvcApplication).Assembly);

            // register Umbraco MVC + web API controllers used by the admin site
            builder.RegisterControllers(typeof(UmbracoApplication).Assembly);
            builder.RegisterApiControllers(typeof(UmbracoApplication).Assembly);
            
            ...........
            var container = builder.Build();
            DependencyResolver.SetResolver(new AutofacDependencyResolver(container));
            GlobalConfiguration.Configuration.DependencyResolver = new 
            AutofacWebApiDependencyResolver(container);

While trying to log in the server returns an error: An error occurred when trying to create a controller of type 'AuthenticationController'. Make sure that the controller has a parameterless public constructor."
ExceptionType: "System.InvalidOperationException"

If I remove the last line I log in successfully but on the UI and in the browser log there is an error: 
"Message":"An error has occurred.",
 "ExceptionMessage":"An error occurred during the activation of a particular registration. 
 See the inner exception for details. Registration: Activator = ContentTreeController (ReflectionActivator), 
 Services = [Umbraco.Web.Trees.ContentTreeController], 
 Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, 
 Sharing = None, Ownership = OwnedByLifetimeScope ---> 
 None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' 
 on type 'Umbraco.Web.Trees.ContentTreeController' 
 can be invoked with the available services and parameters:\r\nCannot resolve parameter 
 'Umbraco.Web.Search.UmbracoTreeSearcher treeSearcher' of constructor 'Void .ctor(Umbraco.Web.Search.UmbracoTreeSearcher, Umbraco.Web.Actions.ActionCollection)'. 

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/using-ioc.md***

**Comment by hartviglarsen** [comment]
Hello @VasilkovME !

While this article does indeed need to be updated are you aware that you can now create _composers_, in which you can register what you need?

Example: https://gist.github.com/hartviglarsen/02090abeae67e2cb07dd06d6f34d2812
Stephan's blog post: https://www.zpqrtbnk.net/posts/composing-umbraco-v8/

**Comment by VasilkovME** [comment]
> Hello @VasilkovME !
> 
> While this article does indeed need to be updated are you aware that you can now create _composers_, in which you can register what you need?
> 
> Example: https://gist.github.com/hartviglarsen/02090abeae67e2cb07dd06d6f34d2812
> Stephan's blog post: https://www.zpqrtbnk.net/posts/composing-umbraco-v8/

Now I know, thank you! ;)
