### ISSUE TITLE
(Cloud) Migrate-Existing-SiteMigrating: old sites, should mention obsolete datatypes

### ISSUE THREAD

**Issue by madsoulswe** [umbraco/UmbracoDocs#1605]
When migrating older installation that uses obsolete datatypes, they usually conflict. Because default installations contains the new datatypes with the same name as the obsolete ones.

We usually just rename the old datatypes locally to ".... (Old)" and then deploy them.

I don't know the best solution =)

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md***

**Comment by sofietoft** [comment]
Hi @madsoulswe 

The issue you're mentioning here, is the one explained here, https://our.umbraco.com/documentation/Umbraco-Cloud/Troubleshooting/Deployments/Colliding-Datatypes/ 
Is that correct?

I've thought about linking to this troubleshooting guide, in the migration article.
What do you think about that idea? 
Or perhaps we could also just mention that renaming the obsolete ones will do the trick 🤔

**Comment by madsoulswe** [comment]
Ah yes, linking that page could work. But it doesn't really mention what you could do if you have conflict between new and obsolete datatypes. Maybe just adding it as a "tip/hint" =)

**Comment by sofietoft** [comment]
Yes, that's a very valid point!

I'll have a little tip/note thing added to the article asap 😁

**Comment by sofietoft** [comment]
Have a look at this: https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/#data-types 

I decided to mention both options 😁 

Closing this issue now.
Thanks @madsoulswe ! Have a good one!
