### ISSUE TITLE
Issue rendering True-False value in Umbraco 8

### ISSUE THREAD

**Issue by kyle-jorve** [umbraco/UmbracoDocs#1612]
I just started using Umbraco 8 and I have to say it's looking good. I love that most every data type can be rendered with a simple @Model.Value or something similar. However, it looks like the True-False documentation might not have been updated for Umbraco 8, and I'm having a real hard time with it.

To summarize, I have some nested content and each item has its own true-false value. But regardless of whether the checkbox is checked or not, the value always comes back false.

Here is my code:

`@foreach (var item in productSlides)
{
     bool hasBgImg = item.Value<bool>("isBgImg");
}`

Please help!

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/True-False.md***

**Comment by nul800sebastiaan** [comment]
This is fixed in the upcoming v8.0.1 https://github.com/umbraco/Umbraco-CMS/issues/4812
