### ISSUE TITLE
Unfriendly <title>, meta description empty

### ISSUE THREAD

**Issue by dangrussell** [umbraco/UmbracoDocs#1628]
The <title> tag is not being generated in the readable, SEO-friendly way you'd expect it to be. It even had newlines in it.  I assume the wrong data is being fed into that tag in the template.
```
	<title>
                    _ - 2-Add-a-Blog-Post-Publication-Date - Lessons - Starter-kit - Tutorials - 

            Documentation - our.umbraco.com
        </title>
```
The meta description is also present but empty. The whole <head> metadata generating code might need checking.
```
	<meta name="description" content="">
```

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Tutorials/Starter-kit/Lessons/2-Add-a-Blog-Post-Publication-Date/index.md***

**Comment by sofietoft** [comment]
Hi @dangrussell 

Very good observation!
We have actually added a few YAML tags, in order to handle the meta-title and meta-description for the articles - still working on getting them documented though 😉 

Here's a quick little example of how the tags look on https://our.umbraco.com/documentation/Tutorials/:
```
---
versionFrom: 7.0.0
product: "CMS"
meta.Title: "Tutorials for beginners and master alike"
meta.Description: "Here you can find tutorials covering things like creating a site from scratch, setting up multilingual sites and many more"
---
```

**Comment by jmayntzhusen** [comment]
Thanks for reporting this @dangrussell 

Will close for now as we are aware, the YAML tags are in place to add this.
