### ISSUE TITLE
Custom dashboard tutorial issues with v8

### ISSUE THREAD

**Issue by smishra2019** [umbraco/UmbracoDocs#1634]
CustomWelcomeDashboard does not work for 'I know what you did last Tuesday..' section.

The array is returned as empty in console and it never shows any history.
The version used for testing is Umbraco 8.0.0/8.0.1.It does not work for either of the versions. Can the documentation be updated to reflect the correct code that has been tested on Umbraco 8 versions and works.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Tutorials/Creating-a-Custom-Dashboard/index.md***

**Comment by jmayntzhusen** [comment]
Hey @smishra2019 

Thanks for submitting this issue! The tutorial you mentioned has indeed not been updated for v8 yet, but needs to be. I will flag this issue as up for grabs so hopefully someone can have a look and update it 🙂

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
