### ISSUE TITLE
Adding context to samples

### ISSUE THREAD

**Issue by dangrussell** [umbraco/UmbracoDocs#1635]
Hi! I'm admittedly new to both Umbraco and ASP.NET, but I think this page could be a little more helpful with some context.  I appreciate the code samples, but I have no idea where to begin with them. Is there an existing file I should be editing? Are there new files I should be creating?

To me, this sample code is just floating out there... I'd like some guidance on how to use it.

I came across this page after learning about [ASP.NET's Bundling & Minification](https://docs.microsoft.com/en-us/aspnet/mvc/overview/performance/bundling-and-minification#using-bundling-and-minification-with-aspnet-mvc). Knowing that it's implemented in the "App_Start", I was looking to find the Umbraco version of that.  [This page](https://our.umbraco.com/documentation/reference/events/Application-Startup) led me here.

After coming up empty on searching the Umbraco codebase for things like `ICoreComposer`, I can't find anywhere where I'd even begin.

I'm not asking for support on my specific issue, just for clearer examples that ideally reference specific files.  Again, I'm new, so if what I'm asking is unusual and not standard, I'm sorry :)

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Implementation/Composing/index.md***

**Comment by jmayntzhusen** [comment]
Hey @dangrussell 

I think you are right, some more explanation of specific use cases and when composers should be used and where to place them would be nice.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
