### ISSUE TITLE
It has not been mentioned to remove {machinename} from ExaminIndex.config when upgrading

### ISSUE THREAD

**Issue by mehrdadab** [umbraco/UmbracoDocs#1644]
## What type of issue is it? 
Missing one important step when upgrading
## What article/section is this about? 
https://our.umbraco.com/documentation/getting-started/setup/upgrading/version-specific

## Describe the issue:
I noticed that in the new versions of umbraco {machinename} has been removed from ExaminIndex.config files for example:
`<IndexSet SetName="InternalIndexSet" IndexPath="~/App_Data/TEMP/ExamineIndexes/{machinename}/Internal/"/>`
converted to:
`<IndexSet SetName="InternalIndexSet" IndexPath="~/App_Data/TEMP/ExamineIndexes/Internal/"/>`
As administrators usually don't replace config files during upgrade and just edit them if needed, they easily may miss that step during upgrade, and it causes a big issue if the website is hosted on Microsoft Azure.

**Comment by sofietoft** [comment]
Apologies for the delay on this @mehrdadab !

I can see that the article you're referring to, has been updated quite a few times since you made his issue.
Could you please let me know, if what you're reporting here still applies?

**Comment by sofietoft** [comment]
@mehrdadab , I haven't heard back from you, so I wanted to check in here 😄 

Did you see my latest message?
Does what you're reporting still apply - do we need to update the docs article?

**Comment by mehrdadab** [comment]
@sofietoft , I cannot find anything related to machine name on the mentioned page yet. However I could find it here: https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/azure-web-apps , so it may not need to be updated anymore.

**Comment by sofietoft** [comment]
Ah, yes! I missed that this was related to upgrading 🤔 

Perhaps we could instead add a link from [the version specific upgrades article](https://our.umbraco.com/documentation/getting-started/setup/upgrading/version-specific) to the articles on the [Server setup](https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/azure-web-apps)? 
What do you think of that solution?

**Comment by sofietoft** [comment]
Hi @mehrdadab ,
As it's been a while since I've seen any activity on this issue, I hope it's OK that I close it down.
Also sounded like you found the information needed 💪 

You're of course more than welcome to report back, should something continue to be missing.

Thanks again for reporting!
