### ISSUE TITLE
Custom Property Editors - Documentation

### ISSUE THREAD

**Issue by tristolliday** [umbraco/UmbracoDocs#1654]
## What type of issue is it?
Missing documentation

## What article/section is this about? 
Custom Property Editors

## Describe the issue:
Missing Documentation for creating a custom property editor in Umbraco 8.

https://our.umbraco.com/documentation/Tutorials/Creating-a-Property-Editor/

**Comment by jmayntzhusen** [comment]
Hey @tristolliday 

Thanks for submitting this issue! The tutorial you mentioned has indeed not been updated for v8 yet, but needs to be. I will flag this issue as up for grabs so hopefully someone can have a look and update it 🙂

If you are having a specific issue you are stuck on in the tutorial then you can post it here and we can try to help - as rewriting a tutorial is a pretty large task you would probably get help to move on a lot quicker that way!

**Comment by tristolliday** [comment]
@jmayntzhusen The basis of the tutorial works much the same with Umbraco 8, as it did 7. 
However, the dialog service/ media services seem to operate differently on 8. Any assistance with how to integrate with these would be greatly appreciated.

Cheers,

Tris

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
