### ISSUE TITLE
IApplicationBuilder doesn't seem existing in v8 anymore

### ISSUE THREAD

**Issue by javafun** [umbraco/UmbracoDocs#1657]
Can someone help to update to the latest?

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/using-ioc.md***

**Comment by jmayntzhusen** [comment]
Hey @javafun 

The ApplicationEventHandler is no longer the way to bind things to startup events, the new way to do it in v8 is through Composing, we have some documentation on it here: 
https://our.umbraco.com/Documentation/Reference/Events/Application-Startup
https://our.umbraco.com/documentation/Implementation/Composing/

If you are looking for some general IOC then I'm afraid we don't have any docs for it now, maybe you can tell me a bit more about your specific use case so we can try to document it for v8? 🙂

**Comment by sofietoft** [comment]
Hi! 
As we haven't seen any new activity on this issue in while, I'll close it for now.

If you feel it's still relevant, you're welcome to reopen it! 😁 
Thanks.

/Sofie

**Comment by jmayntzhusen** [comment]
This is a small part of the larger issue #1697 which is why it was closed.
