### ISSUE TITLE
Issue with Grid in Grid

### ISSUE THREAD

**Issue by GaryLProthero** [umbraco/UmbracoDocs#1662]
I have an issue with the GridDocTypeEditor. I am uploading a pdf and a vide (in zip) show the issue.

[Issue with Grid.zip](https://github.com/umbraco/UmbracoDocs/files/3055332/Issue.with.Grid.zip)

[Not working.pdf](https://github.com/umbraco/UmbracoDocs/files/3055327/Not.working.pdf)

Thanks,
Gary Prothero

**Comment by jmayntzhusen** [comment]
Hey @GaryLProthero 

Thanks for reporting this, what we take here is issues with the current documentation, so articles that needs updates or reports of faults or missing things in the documentation 🙂

As this is more of a support request with your specific use of the Grid editor you will have to either reach out to the Umbraco Support at contact@umbraco.com or write your question on the community forum on Our: https://our.umbraco.com/forum/

Will close this for now, hope you figure it out 🙂
