### ISSUE TITLE
Add better visualization of the version you're looking at

### ISSUE THREAD

**Issue by greystate** [umbraco/UmbracoDocs#1665]
## What type of issue is it?

UI/UX

## What article/section is this about? 
All that have the new versioning system

## Describe the issue:

When browsing the docs, it's actually not overly obvious, which version you're looking at, e.g. here I'm actually looking at the **7.0.0+** version, but the other one is much more attention-grabbing AND has the word _(current)_ attached to it (it means 8.0.0 is the current version of Umbraco, but I don't feel like that's not how it's being interpreted).

<img width="336" alt="selected-version-now" src="https://user-images.githubusercontent.com/5463/55789024-cc077080-5ab9-11e9-981e-142abfd8d182.png">

I realize it's partly the old problem of "which one's the selected one" when you only have two choices, but maybe we could add a designated `.selected-version` class to the selected one and have it look something like this:

<img width="336" alt="selected-version-wish" src="https://user-images.githubusercontent.com/5463/55789221-2bfe1700-5aba-11e9-9764-46bd0b285621.png">

?

**Comment by jmayntzhusen** [comment]
I think this would be a great idea. And honestly I thought of removing the `(current)` thing many times as it is not working great as it is - probably also not the best way to present which version is the current one 🙂

This will take a bit of work on Our, but will keep it in mind!
