### ISSUE TITLE
IIS config is not visible on the security hardening page

### ISSUE THREAD

**Issue by sussexrick** [umbraco/UmbracoDocs#1667]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Security/Security-hardening/index.md***

The config is mentioned in the text and is present, but you need to view the source on github to see it.

**Comment by jmayntzhusen** [comment]
Hey @sussexrick 

Not sure why the examples weren't being shown, but I have fixed it now and you can see them on [the page](https://our.umbraco.com/documentation/Reference/Security/Security-hardening/) again 🙂

Thanks for reporting this issue!
