### ISSUE TITLE
When the full Umbraco 8 documentation will be ready ?

### ISSUE THREAD

**Issue by saifobeidat** [umbraco/UmbracoDocs#1672]
Thanks for **Umbraco 8**, it looks great.

But to be honest I am facing many issues because the Umbraco 8 documentation is not ready yet! especially the major changes ( examine search, Mvc/WebApi ).

Please try to finish it, because it's the main source for us , as the community members are not active as wished.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/index.md***

**Comment by dampee** [comment]
Hi @charlesroper 

There is already a lot of v8 documentation been updated. I did notice that the "not revised for v8" is not always removed.

The examine search is indeed one of the missing pieces as mentioned here: https://github.com/umbraco/UmbracoDocs/blob/master/v8documentation.md

If you found issues with existing umbraco8 docs, please create a PR or a specific issues. Like that we are able to update the documentation accordingly.

**Comment by charlesroper** [comment]
Not sure you meant to tag me in on this thread @dampee!

**Comment by jmayntzhusen** [comment]
Hey @saifobeidat 

Thanks for reporting this, we are aware there are a lot of holes in the current v8 documentation - it is very hard for us to know where to begin though, so more specific reports of missing info is greatly appreciated!

You mention examine, we are aware it is very lacking, and it is high on our list of new docs to write for v8. Would you mind elaborating a bit more on what you feel is missing for Mvc/WebApis? 🙂 Something along the lines of

> In v7 I would set up a webapi this way .... but in v8 when doing the same it does not work. This is the page I would love a v8 version of: https://our.umbraco.com/Documentation/Reference/Routing/WebApi/

With more specific issues on what is missing we can work on those specific things, we unfortunately have had several reports along the lines of "the v8 docs are unfinished, missing a bunch of things" - and I am sure you can understand it is very hard to know what to improve based on that 😉

**Comment by jmayntzhusen** [comment]
As there is nothing here we can work on specifically I will close this issue. If you come up with some more specific examples of things you feel are missing then please create a new issue with some information 🙂
