### ISSUE TITLE
The current documentation of Examine Search

### ISSUE THREAD

**Issue by MosabAbuzaid** [umbraco/UmbracoDocs#1673]
## What type of issue is it? 
Missing documentation

## Describe the issue:
I think the current documentation for the Examine search is not applicable for **Umbraco8**.

First issue:
 when I add this line "@using Examine.SearchCriteria;" , I get the below error:
> The type or namespace name ‘SearchCriteria’ doesn’t not exist in the namespace ‘Examine’ (are you missing an assembly reference)?

Second Issue:
When I use the following code: `        @foreach (var result in Umbraco.TypedSearch(Request.QueryString["query"]))`

I get this error:

> UmbracoHelper doesn’t contain a definition and no accessible extension method ‘TypedSearch’  accepting a first argument of type ‘UmbracoHelper’

Can you please update the current documentation, because we are about to start developing  a big project using **Umbraco8**, so please inform us if the documentation is going to delay.

**Comment by jmayntzhusen** [comment]
Hey @MosabAbuzaid 

It is on our list to update this documentation, but as you have seen it is not done yet. 

Examine.SearchCriteria is no longer a valid namespace, dependent on your use case you would probably need to add either `Examine` or `Umbraco.Examine`.

Looks like the Umbraco Helper doesn't extend a search method anymore either, you should be able to do something like this:
```csharp
if(ExamineManager.Instance.TryGetIndex("ExternalIndex", out var index))
{
    var searcher = index.GetSearcher();
    var results = searcher.CreateQuery().Field("nodeName", searchTerm).Execute();

    if (results.Any())
    {
        <ul>
            @foreach (var result in results)
            {
                var node = Umbraco.Content(result.Id);
                <li>
                    <a href="@node.Url">@node.Name</a>
                    <br/>Relevance - (@result.Score)
                </li>
            }
        </ul>
    }
    else
    {
        <p>No results found for query @searchTerm</p>
    }
}

return;
```

If you have some specific use cases with searching in v8 you would need documentation on then please let me know so we know where to focus our efforts 🙂

**Comment by Zweben** [comment]
> Hey @MosabAbuzaid
> 
> It is on our list to update this documentation, but as you have seen it is not done yet.
> 
> Examine.SearchCriteria is no longer a valid namespace, dependent on your use case you would probably need to add either `Examine` or `Umbraco.Examine`.
> 
> Looks like the Umbraco Helper doesn't extend a search method anymore either, you should be able to do something like this:
> 
> ```cs
> if(ExamineManager.Instance.TryGetIndex("ExternalIndex", out var index))
> {
>     var searcher = index.GetSearcher();
>     var results = searcher.CreateQuery().Field("nodeName", searchTerm).Execute();
> 
>     if (results.Any())
>     {
>         <ul>
>             @foreach (var result in results)
>             {
>                 var node = Umbraco.Content(result.Id);
>                 <li>
>                     <a href="@node.Url">@node.Name</a>
>                     <br/>Relevance - (@result.Score)
>                 </li>
>             }
>         </ul>
>     }
>     else
>     {
>         <p>No results found for query @searchTerm</p>
>     }
> }
> 
> return;
> ```
> 
> If you have some specific use cases with searching in v8 you would need documentation on then please let me know so we know where to focus our efforts 🙂

How would I perform a search by passing in raw Lucene query syntax as a string? I'm not a big fan of the Examine-specific query syntax, but it's no longer clear how I can perform a raw Lucene search.

**Comment by jmayntzhusen** [comment]
@Zweben 

If you have the basics of my example above and then do something like this it should work (haven't had time to test):
```
var results = searcher.CreateQuery().NativeQuery("nodeName:Home").Execute();
```

It seems you can add the Lucene query in the NativeQuery as a string, the source is here: https://github.com/Shazwazza/Examine/blob/v1.0.0/src/Examine/Search/IQuery.cs#L21

Will try to write up a few simple scenarios for using Examine in v8 and add to the docs ASAP so we have a bit before one of the Core devs have time to do a more comprehensive article.

Please continue to let me know which examples you would like covered in our searching docs 👍

**Comment by Zweben** [comment]
> @Zweben
> 
> If you have the basics of my example above and then do something like this it should work:
> 
> ```
> var results = searcher.CreateQuery().NativeQuery("+__IndexType:content +nodeName:People").Execute();
> ```
> It seems you can add the Lucene query in the NativeQuery as a string, the source is here: https://github.com/Shazwazza/Examine/blob/v1.0.0/src/Examine/Search/IQuery.cs#L21
> 
> Will try to write up a few simple scenarios for using Examine in v8 and add to the docs ASAP so we have a bit before one of the Core devs have time to do a more comprehensive article.
> 
> Please continue to let me know which examples you would like covered in our searching docs 👍

Thanks. Until the documentation gets updated, I think it would help to direct people to [Shannon Deminick's web demo](https://github.com/Shazwazza/Examine/tree/864168c7f019908242dd56197e075edea5ee77cf/src/Examine.Web.Demo). I'm referencing that now, and it's a big help.

Another thing that would be useful is a brief overview of how classes and methods have changed namespaces in v8, as that threw me off at first.

**Comment by saifobeidat** [comment]
> 
> ```cs
> if(ExamineManager.Instance.TryGetIndex("ExternalIndex", out var index))
> {
>     var searcher = index.GetSearcher();
>     var results = searcher.CreateQuery().Field("nodeName", searchTerm).Execute();
> 
>     if (results.Any())
>     {
>         <ul>
>             @foreach (var result in results)
>             {
>                 var node = Umbraco.Content(result.Id);
>                 <li>
>                     <a href="@node.Url">@node.Name</a>
>                     <br/>Relevance - (@result.Score)
>                 </li>
>             }
>         </ul>
>     }
>     else
>     {
>         <p>No results found for query @searchTerm</p>
>     }
> }
> 
> return;
> ```
> 




Hi jmayntzhusen

Can you please show the way that we can list all nodes under specific Parent ID or even listing all nodes with specific document type name?

**Comment by jmayntzhusen** [comment]
@saifobeidat 

If you go in the backoffice to settings under examine management you can see that each nodes has some fields:
![Capture](https://user-images.githubusercontent.com/36075913/56881159-db962b80-6a5f-11e9-8e43-5f5a539d5559.PNG)

You can then amend the query in the example you linked to this:
```
var results = searcher.CreateQuery("content").ParentId(1105).Execute();
```
That would find list all children of ID 1105, if you instead want all with a specific doctype name then you'd do this:
```
var results = searcher.CreateQuery("content").Field("__NodeTypeAlias", "home").Execute();
```
This would find all nodes with doc type alias `home`

**Comment by jmayntzhusen** [comment]
Happy to hear that 🙂

We now have some basic documentation on searching in v8 here: https://our.umbraco.com/documentation/Reference/Searching/Examine/quick-start/

Some other things that we are working on adding is:
- The equivalent of GatheringNodeData in v8
- Creating a custom index
- Boosting search results

I will close this issue for now and create another one with a more clear purpose. Thanks for all the feedback so far! 😉
