### ISSUE TITLE
Azure Media Storage in v8 for Umbraco Cloud

### ISSUE THREAD

**Issue by thehaytonproject** [umbraco/UmbracoDocs#1681]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about? 
https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Media/

## Describe the issue:
Instructions for Azure Media Storage in v8 for Umbraco Cloud are missing / not verified.

I followed these steps for v8 and it causes Umbraco Boot to fail.

**Comment by Jeavon** [comment]
These docs are not updated to v8. However if you install the v2 version of the blob provider instead of v1 then Umbraco will boot and the provider will work

**Comment by sofietoft** [comment]
Closed with #1688
