### ISSUE TITLE
Where's the actual set up guide?

### ISSUE THREAD

**Issue by uli-weltersbach** [umbraco/UmbracoDocs#1689]
The first paragraph of the "Set Up" documentation is:

> Now that you've created a project there are a few things you may want to do to make working with your project easier. 

So - where do I find the steps required to create a project?
It's like the *actual*, step-by-step set up guide is missing from the set up documentation.

To be more specific, what I'm looking for is something like:

1. Open `<insert Umbraco Cloud portal URL>`.
2. If you don't have an Umbraco Cloud account yet, create an account. See `<insert link to account creation guide>`.
3. Click the "Create new project" button `<insert helpful screenshot>`.
4. ...
5. Profit.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Umbraco-Cloud/Set-Up/index.md***

**Comment by sofietoft** [comment]
Hi @uli-weltersbach 

That's a very interesting observation!
We have something similar to a step-by-step on how to setup a Cloud project in the Getting Started section: https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/ 

The "Set up" section is more for setting up local instances, managing the various settings and other stuff for getting your site ready for launch.

Would be a good idea to have something on the "Set up" page directing people back to the "Getting started" section 🤔 Or what do you think?

/Sofie

**Comment by uli-weltersbach** [comment]
Hi @sofietoft 

I think the ["Umbraco Cloud cover page"](https://our.umbraco.com/documentation/Umbraco-Cloud/) fooled me into thinking that "Set up a Project" was about setting up a project.
Maybe it's enough to simply reword the relevant paragraphs on *that* page.

---

... sounds like the place to go for a sales pitch:

> Getting Started
> If you're new to Umbraco Cloud then start here. All about what Umbraco Cloud is and how you can use it to get your work done more efficiently - and have more fun.


---

... sounds like the place to go for actual setup instructions:

> Set up a Project
> How to set up a project for development. Using just Umbraco Cloud, by cloning the down locally, and when working with a team.

---

![image](https://user-images.githubusercontent.com/1416006/57216987-abb3ce80-6ff1-11e9-9cd6-edf34151cd44.png)
