### ISSUE TITLE
IOC/DI docs not compatible with V8

### ISSUE THREAD

**Issue by dawoe** [umbraco/UmbracoDocs#1697]
## What type of issue is it?
Wrong documentation

## What article/section is this about? 
https://our.umbraco.com/documentation/Reference/using-ioc

## Describe the issue:
This describes on how to setup DI for version v7. It doesn't indicate that thiis page is not updated yet for V8 like I have seen on other sections of the documentation

I have found documentation on how to register you own classes for DI. But it was not the place I was expecting it
https://our.umbraco.com/documentation/Getting-Started/Code/Umbraco-Services/#access-in-a-custom-class-via-dependency-injection

Dave

**Comment by sofietoft** [comment]
As far as I can see, this documentation has now been verified and updating for Umbraco 8 💪 

With that, I'll close this one for now.
Thanks again for reporting it, @dawoe 😁
