### ISSUE TITLE
Documentation for working with Tags

### ISSUE THREAD

**Issue by Lechus** [umbraco/UmbracoDocs#170]
1. There is:
   if (Model.HasValue("articleTags")){
   Gives me error:
   CS1928: 'Umbraco.Web.Models.RenderModel' does not contain a definition for 'HasValue' and the best extension method overload 'Umbraco.Web.PublishedContentExtensions.HasValue(Umbraco.Core.Models.IPublishedContent, string)' has some invalid arguments
2. @foreach (var tagItem in Model.articleTags.Split(','))
   gives me:
   Parser Error Message: Unexpected "foreach" keyword after "@" character.  Once inside code, you do not need to prefix constructs like "foreach" with "@".

**Comment by Shazwazza** [comment]
The docs required need to deal with how we work with Tags with the UmbracoHelper

**Comment by dampee** [comment]
@Jeavon what do you think of this commit: 24d49bbeee84b1932cc033d42404a80649b96dab

**Comment by sofietoft** [comment]
Closing this issue, as it looks like Tags has been documented.
