### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by andrevrodrigues** [umbraco/UmbracoDocs#1706]
Hi, when it will be updated to version 8? Thanks

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Routing/WebApi/index.md***

**Comment by nul800sebastiaan** [comment]
Some of this is still relevant for v8. If you need help now, make sure to post a question on the forum at https://our.umbraco.com so our friendly community can look at your problem and give you some hints.

**Comment by jmayntzhusen** [comment]
Since the page already has a needs verification tag on it we will close this for now.
