### ISSUE TITLE
Syntax error in Nested Content documentation example code

### ISSUE THREAD

**Issue by neurox** [umbraco/UmbracoDocs#1718]
In the section "Rendering Nested Content" the second code example, there is an extra ")" in the code: <p>@Html.Raw(Html.ReplaceLineBreaksForHtml(description)))</p>, should be: <p>@Html.Raw(Html.ReplaceLineBreaksForHtml(description))</p>. ***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index.md***

**Comment by jmayntzhusen** [comment]
Will close this as you have already fixed it in a PR - thanks again!
