### ISSUE TITLE
Video not working

### ISSUE THREAD

**Issue by rich-hamilton** [umbraco/UmbracoDocs#1724]
Video unavailable
This video is restricted. Try signing in with a Google Apps account.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/New-in-V8.md***

**Comment by sofietoft** [comment]
Hi @rich-hamilton 

Thanks for reporting this.
I have no trouble watching the video though - I've even tried in incognito mode using Chrome 🤔
Are you able to watch the video directly on Youtube by any chance? https://www.youtube.com/watch?v=g5qwzmxiWJU

/Sofie

**Comment by jmayntzhusen** [comment]
As we have had no response we will close this issue. Please let us know if this continues to be a problem 🙂
