### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by DavidKMc** [umbraco/UmbracoDocs#1736]
Broken link is in on page https://our.umbraco.com/documentation/Umbraco-Cloud/Troubleshooting/Deployments/Structure-Error/#getting-your-environment-in-sync

Link is 'What are UDA files?
![image](https://user-images.githubusercontent.com/51828250/59517093-b435d980-8eba-11e9-8a1b-7c265f8dcfe8.png)

**Comment by nul800sebastiaan** [comment]
Which of the links is broken please? :)

**Comment by jmayntzhusen** [comment]
Hey @DavidKMc 

Thanks for reporting this broken link, I have updated it so it now works in https://github.com/umbraco/UmbracoDocs/commit/2ce5da00e90c3eecd6b54b3e252b151b869fa414 🙂
