### ISSUE TITLE
Preventing Examine from returning deleted nodes?

### ISSUE THREAD

**Issue by saifobeidat** [umbraco/UmbracoDocs#1737]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about? 
(https://our.umbraco.com/Documentation/Reference/Searching/Examine/)

## Describe the issue:

Hello,

I am using Examine to return some nodes in certain document type alias.

Refering to this document: https://our.umbraco.com/documentation/Reference/Searching/Examine/Quick-Start/

` results = searcher.CreateQuery().Field("__IndexType", "content").And().Field("__NodeTypeAlias", "client").Execute();
`

All is perfect if there are no deleted nodes, but if there, I get some issues like counting the results and other things because of those deleted nodes.

The question is, how to avoid deleted nodes from returning ?

**Comment by marcemarc** [comment]
Hi Saifobeidat

If you are using the ExternalIndex then this should not contain any unpublished or deleted nodes!

This is an issue that has been reported on the Issue Tracker for Umbraco V8:

[https://github.com/umbraco/Umbraco-CMS/issues/5218](https://github.com/umbraco/Umbraco-CMS/issues/5218)

So we probably wouldn't add documentation here, as hopefully this will be fixed pretty soon!

If you are looking for a quick fix and workaround in the meantime, then explaining the problem in the  Umbraco Forum might find that somebody also experienced this in the community and thought of a good temporary solution: [https://our.umbraco.com/forum/](https://our.umbraco.com/forum/)

In V7 the 'recycle bin' always had a 'Path' of '-1,-20' and any deleted content would therefore have a Path property starting '-1,-20'...
...and I think the same convention exists in V8, so perhaps you could modify your Examine query to exclude any content items that have a Path beginning '-1,-20' or similar temporary workaround?

regards

Marc

**Comment by nul800sebastiaan** [comment]
As @marcemarc mentions this is a bug the we need to fix soon! No need to update the docs for this one as it's a bug. Thanks for reporting!
