### ISSUE TITLE
Example view of content app  should use umb-box directives

### ISSUE THREAD

**Issue by dawoe** [umbraco/UmbracoDocs#1741]
I see the view is using the markup generated by the umb-box directives.

Would it not be better to use these directives in examples. 

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Extending/Content-Apps/index.md***

**Comment by jmayntzhusen** [comment]
Hey @dawoe 

I made the example and am not that familiar with both AngularJS and the Umbraco backoffice directives, which is why it was made this way 😁

If there are changes that can improve the example and make it closer to a best practise then you are very welcome to provide a PR! 👍

**Comment by dawoe** [comment]
As you requested. PR provided

**Comment by jmayntzhusen** [comment]
Thanks for the PR 👌
