### ISSUE TITLE
Backup process unclear

### ISSUE THREAD

**Issue by kjsguld** [umbraco/UmbracoDocs#1764]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Umbraco-Cloud/Databases/index.md***

Following the process description of how to acquire a backup file, no further description is given of how to use a such file to restore from a such file.

**Comment by jmayntzhusen** [comment]
We are already documenting far beyond our scope in this article. I understand some people may have trouble with this kind of thing, but it is not at all Umbraco related, and they should really know how to handle database backup files if they want to use them for anything. 

We also don't document how to open a browser, etc - it is not really up to us to document how to use external tools, so will close this issue 🙂

**Comment by kjsguld** [comment]
I fully agree that this is outside the scope of the first title "databases" which is very broad. Shouldn't all regarding the backups then rather be a section/article of its own? 
To be rather straight forward I think telling how a user can obtain a backup is rather pointless if we don't tell how you'd actually use it.
