### ISSUE TITLE
Document new [ValidateUmbracoFormRouteString] attribute for SurfaceControllers

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/UmbracoDocs#1781]
## What type of issue is it?
Missing documentation

## Describe the issue:
A new C# attribute has been added to the upcoming 8.1.1 & 7.15.1 releases `[ValidateUmbracoFormRouteString]` to help with securing Umbraco SurfaceControllers.

Chat with @Shazwazza or @nul800sebastiaan about details/specifics

**Comment by jmayntzhusen** [comment]
For future reference:
CMS PR: https://github.com/umbraco/Umbraco-CMS/pull/5895

Locations that may need a mention: 
https://our.umbraco.com/Documentation/Reference/Routing/surface-controllers
https://our.umbraco.com/Documentation/Implementation/Controllers/

**Comment by jmayntzhusen** [comment]
We will need some more info from @Shazwazza on what this does and in which cases it should be used.

**Comment by ronaldbarendse** [comment]
Whenever `@Html.BeginUmbracoForm<MyController>(...)` is used to generate a form that posts to a `SurfaceController`, the form action points to the current content URL, so a hidden field `ufprt` is added that contains the controller, action and optional area of the `SurfaceController`). Without this field, Umbraco wouldn't know it should execute the controller action, especially when multiple forms with different controllers are added into a page.

As this field is encrypted with the applications machine key, you can only execute the controller action when it is rendered by the application. This prevents manually posting to the automatically routed URL that surface controllers also have... So it's basically an anti-forgery token 😉 I hope this makes sense and clarifies it a bit!

**Comment by sofietoft** [comment]
Thanks for the insights @ronaldbarendse ! 😄 

Would you be up for taking a shot at writing the missing docs here?

**Comment by ronaldbarendse** [comment]
@sofietoft I'll try to set some time apart for this 👍

**Comment by sofietoft** [comment]
That would be awesome @ronaldbarendse ! 😄 🎉
