### ISSUE TITLE
Version control is broken

### ISSUE THREAD

**Issue by Sinnedennis** [umbraco/UmbracoDocs#1793]
The version control for this page (V7, V8) is displaying links to its child pages instead of version specific instances of this page. 

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Templating/Mvc/forms.md***

**Comment by nul800sebastiaan** [comment]
Thanks, something weird is definitely going on here, should be looked into! https://our.umbraco.com/documentation/Reference/Templating/Mvc/forms

**Comment by sofietoft** [comment]
Thanks for reporting! 😄 

We've discovered the issue, and it should be working now 💪
