### ISSUE TITLE
Cannot see Developers section in V8

### ISSUE THREAD

**Issue by KamranIE** [umbraco/UmbracoDocs#1796]
Looks like 'Developers' section no longer exists which is referenced in XSLT macro creation topic. Right now I cannot see any option to create an XSLT macro in V8.

**Comment by nul800sebastiaan** [comment]
There's also no longer XSLT macro's in v8 :-)

Which documentation are you looking at? I think you're looking at documentation for v7 which is no longer valid for v8. Do you have a link to what you were looking at? We might need to mark it as v8 only.

I couldn't find anything for v8 referring to XSLT macro's but I might have missed something, let us know! 

For now I'll close this issue. Make sure to get some [help on the forums](https://our.umbraco.com) to find an alternative for what you're trying to do in v8.
