### ISSUE TITLE
I don't think the c# serilog logging level configuration example works as expected as it stands

### ISSUE THREAD

**Issue by tom-ingeniuus** [umbraco/UmbracoDocs#1797]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/Code/Debugging/Logging/index.md***

When I tried this, and set the logging level to Warning I was still getting Debug information (my development preference set in serilog.config) showing in the logs.

I think this is because the lines
.ReadFromConfigFile()
.ReadFromUserConfigFile();
override the statements
 .OutputDefaultTextFile(LogEventLevel.Error)
.OutputDefaultJsonFile(LogEventLevel.Information)
because of what's already in the default config files.

Removing the logging level from the config files automatically sets the logging level to Verbose.

The only way I could get this to work as expected while retaining the other default config settings was as follows:

            var logLevelSetting = ConfigurationManager.AppSettings["IGS.MinimumLoggingLevel"];
            const bool ignoreCase = true;
            if (!Enum.TryParse(logLevelSetting, ignoreCase, out LogEventLevel level))
            {
                level = LogEventLevel.Information;
            }

            var levelSwitch = new LoggingLevelSwitch {MinimumLevel = level};

            var loggerConfig = new LoggerConfiguration()
                .MinimalConfiguration()
                .ReadFromConfigFile()
                .ReadFromUserConfigFile()
                .MinimumLevel.ControlledBy(levelSwitch);

The appsetting can then be altered for different environments via a standard web.config transform

**Comment by nul800sebastiaan** [comment]
Thanks @tom-ingeniuus - looks like this documentation cold do with a bit more testing and reviewing. 👍

**Comment by jmayntzhusen** [comment]
Will make this up for grabs - needs to test the current docs, if it is not working as is we can try out Toms fix above and then update the docs accordingly.

**Comment by TwoMoreThings** [comment]
The original issue was resolved with this commit to the docs
https://github.com/umbraco/UmbracoDocs/commit/39d58fbf0f25577fadaffc5e5f770db709341dea#diff-0a97340bb2848817b55ea4b2b4429367
maybe this should be closed?

**Comment by marcemarc** [comment]
done!
