### ISSUE TITLE
Need a clever way to migrate to language variants

### ISSUE THREAD

**Issue by kasperdyrvig** [umbraco/UmbracoDocs#1803]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about? 
https://our.umbraco.com/Documentation/Tutorials/Creating-Basic-Site/Adding-Language-Variants in combination with https://our.umbraco.com/Documentation/Tutorials/Multilanguage-Setup/index-v7

## Describe the issue:
I have a V7 multi language site (created according to the guide above). I would like to migrate to V8 _and_ use language variants. Is the only way to do this a week of copy/paste, or is there a more clever way?

**Comment by nul800sebastiaan** [comment]
We unfortunately don't have a way to convert this data. Fun fact: a multilingual setup like that still works, but it's clearly not the "new" way we want to do things. 

Migrating from v7 to v8 tries to keep your data intact like it was in v7 and from there on out you're responsible for restructuring it the way you want it to be.

Sorry I don't have better news for you :-)
