### ISSUE TITLE
link not working

### ISSUE THREAD

**Issue by AndyVokurka** [umbraco/UmbracoDocs#1804]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Tags/index.md***

link at the bottom of the page is dead.

**Comment by nul800sebastiaan** [comment]
Thanks! This now links to the intended page https://our.umbraco.com/documentation/Reference/Querying/UmbracoHelper/#working-with-tags
