### ISSUE TITLE
applications.config no longer present in v8 - document needs updating.

### ISSUE THREAD

**Issue by John-Blair** [umbraco/UmbracoDocs#1810]
applications.config no longer present in v8 - document needs updating.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Extending/Section-Trees/sections.md***

**Comment by nul800sebastiaan** [comment]
Yep, that should probably have a "versionTo" field (I can't remember the exact notation). This file doesn't exist on v8 and never will. :)

**Comment by crgrieve** [comment]
I have set his using versionRemoved rather than versionTo... hope this works?

https://github.com/umbraco/UmbracoDocs/pull/1812

**Comment by crgrieve** [comment]
@nul800sebastiaan I submitted a PR for the applications.config adding versionRemoved. Hopefully this is right way?

If so, could also do the dashboard.config? Is it completely removed in v8 too?

**Comment by John-Blair** [comment]
I'd add 
404handlers.config
baserestextensions.config
embeddedmedia.config
examineindex.config
examinesettings.config
feedproxy.config
filesystemproviders.config
log4net.config
scripting.config
trees.config

Thanks

**Comment by jmayntzhusen** [comment]
While none of these exist in v8 the question is how to present it in the docs.. 

I'd say ideally we would have an 8+ version of these articles simply saying the config file is not there in v8 and then linking to an article describing how to do it instead..

Of course this would require that we had articles describing the v8 equivalent of doing stuff in the config files which is currently not the case 😬

Think we will discuss the best way to handle these kinds of things at our next [docs curator](https://our.umbraco.com/community/the-documentation-curators/) meeting 🙂

**Comment by crgrieve** [comment]
ok, thanks @jmayntzhusen :) I'll wait to see the approach before updating any others. Happy to update and contribute further based on what you decide.

**Comment by jmayntzhusen** [comment]
Hey everybody

Will close this issue for now, Marc has made a new more general issue for what to do with the missing config options in v8 here: #1817 

We have decided that the most user friendly thing to do here is to have v8 versions of all of the config articles that then explain that the config file is not there in v8, and optimally it would also link to or include some examples of how things would then be configged through code 🙂
