### ISSUE TITLE
Update 'Reference - Config' landing page to explain new approach to setting config in code

### ISSUE THREAD

**Issue by marcemarc** [umbraco/UmbracoDocs#1817]
## What type of issue is it? (Choose one - delete the others)
Discussion
Missing documentation
Wrong documentation
- All three!

## What article/section is this about? 
Config Reference: https://our.umbraco.com/documentation/Reference/Config/

## Describe the issue:

A lot of configuration (but not all) has moved from /config/files.config on disk to being set via code. In places where the configured functionality is discussed in the documentation, it makes sense to update for V8 to explain the new approach in context, however we have a 'reference' section that lists all of the config files and what they can configure... out of the context...

People who have come from V7 will likely follow the journey of 'where is dashboards.config gone' rather than assuming there is a new approach...

So I think we could make this config landing page a general hub for the changes to the approach for some of the configurations.

https://our.umbraco.com/documentation/Reference/Config/

Have an opening paragraph explaining the change of the approach to setting config in Umbraco (and explain some of the benefits).

Identify config files that have gone, linking to replacement pages that explain how to set the config in V8 (or overtime update the links as this documentation becomes available)

Identify config files that still exist, ImageProcessor etc, and link through to the details of setting those configs.

When we are retiring specific documentation pages regarding a config file eg applications.config we can create a V8 version of the page, that points people back to this page to explain the rationale of the change, and that the config file has gone, along with a link to the equivalent way of setting the config via V8 if it exists (or create an up for  grabs issue, for creating the docs for providing examples of how to set the config in code)

I think throughout pages and tutorials we link to the reference config page, along the lines of check out this page for 'full options' so it would be good overtime to have equivalent content for setting each type of config via code- it's just not necessarily 1-1 since existing pages about a particular config subect only exist because a seperate .config file existed...

... but we do need to provide a journey of discovery for people who knew the .config files existed and start the journey wanting to know how to do the same in V8

**Comment by nul800sebastiaan** [comment]
Thanks @marcemarc - can you state your intention with this issue? Are you going to work on this, are you soliciting contributions, is this just a "feeler"? :-)

**Comment by jmayntzhusen** [comment]
Guess this is related to https://github.com/umbraco/UmbracoDocs/issues/1810 where I left a note that we (documentation curators) should discuss how to handle the removed config files in v8.

**Comment by marcemarc** [comment]
Hi @nul800sebastiaan it's just an issue with the docs!

I think to me now that we have addressed composition and DI examples, the 'next' biggie change that impacts people switching to V8, is where is the config gone...?

(well it's a toss-up between that and template examples, but I think this impacts more people because a lot has been written about template changes in different places, but we don't quite address the change in config approach anywhere.. and it puzzles people as to what has happened to it... but I might be wrong).

Anyway @jmayntzhusen is correct it's partly in response to his note, which got me thinking, and then thought I'd probably forget my thoughts by the next documentation curator meeting, so thought I'd write them down somewhere... so yes open for thoughts and discussion from the world.

But essentially I thought the strategy was one place to have the blurb to document that there has been a big change to config, and I reckon the above landing page is the best place, then update individual instances to refer back to the page... + and have a V8 page for each config file as @jmayntzhusen suggests linking to the explanation, and to the way to do it in V8, which might require further up-for-grab issues, if we have a pattern for one such config file, be easy for community to grab other ones to update...

... not sure if I'm best person to write the blurb... would you have something already in HQ? but can add it to my list and have a go if everyone thinks this is a good idea/strategy?

regards

Marc

**Comment by sofietoft** [comment]
I don't think it makes sense to have 2 issues open around the same topic: Configs.

I will close this one for now.
Refer to #2127 for updates for the versioning of the config articles 💪
