### ISSUE TITLE
"Oops, something broke" pages aren't returning 5xx

### ISSUE THREAD

**Issue by liamlaverty** [umbraco/UmbracoDocs#1822]
## What type of issue is it? (Choose one - delete the others)
Other - Technical issue with docs the site
Should return 5xx when a "ooops something broke..." is returned. This would make it easier to automatically identify broken links in the docs site.

## What article/section is this about? 
An example can be found here (linked from the sidebar `Reference -> Debugging -> Images`: https://our.umbraco.com/documentation/Reference/Debugging/Images, returns a 200 status code, but should return 5xx

**Comment by nul800sebastiaan** [comment]
How does that make it easier to identify them please?

**Comment by liamlaverty** [comment]
I've got a tool that will look through a website and find broken links, incorrect links, broken pages etc. Sometimes I run it through the documentation site to catch any missing images, or broken links (if you look back through my contrib history for this repo, it's mostly just "changed a link" or "updated a typo" type commits). 

If the "oops" pages returned either a 4xx or 5xx error, these tools would show them as big red flags and they'd get caught and resolved quickly. 

I guess there's a google analytics account for the documentation site too, which would start emailing its administrator saying "rise in the number of errors on `/documentation`" if these pages were returning these http errors

**Comment by sofietoft** [comment]
Apologies for the delay here @liamlaverty ! 

As we are hoping to move the Documentation to a new platform in the new year, we will not at this time be looking into setting up these 5xx errors.
I'm afraid the way it's currently structured, makes something like this hard to implement - it would be a rather big task, as I've understood.

I hope it's OK that I close this one for now.
Thanks for pointing out a way to keep track of the broken links though 💪 Much appreciated!
