### ISSUE TITLE
When will the documentation for cache get updated for Umbraco 8?

### ISSUE THREAD

**Issue by halfer53** [umbraco/UmbracoDocs#1833]
My umbraco website use cache api extensively. It would be great if the cache documentation get updated so we can get ready to upgrade to Umbraco 8.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Cache/index.md***

**Comment by sofietoft** [comment]
Hi @halfer53 
Thanks for reporting!
And you are absolutely right. Updating the docs about caching in Umbraco 8 is definitely a priority!

**Comment by sofietoft** [comment]
Hi @halfer53 
As I understood, the Cache in Umbraco 8 has changed, but all methods for working with it should be exactly the same.

Is it something specific that isn't working for you?

**Comment by halfer53** [comment]
thanks for your reply. What are the cache apis in Umbraco 8? I couldn't find them since ApplicationContext is removed in Umbraco 8

**Comment by jmayntzhusen** [comment]
Seems some of the documentation will definitely need an update. I think what you are looking for is something like this?
https://our.umbraco.com/apidocs/v8/csharp/api/Umbraco.Core.Cache.IAppPolicyCache.html

Should be injected wherever it's needed.

**Comment by hartviglarsen** [comment]
I'll write up something for V8 caching :)

**Comment by jmayntzhusen** [comment]
We have a starter example now via https://github.com/umbraco/UmbracoDocs/pull/1867

Will close this issue for now, if you have any suggestions for other examples please create a new issue 🙂
