### ISSUE TITLE
IPropertyValueConverter changed in v8

### ISSUE THREAD

**Issue by John-Blair** [umbraco/UmbracoDocs#1837]
Please update documentation for v8 and how to do a property value converter.
FYI I generally  find the documentation really dreadful for v8.

**Comment by sofietoft** [comment]
Hi @John-Blair 

We are working on updating and verifying all of our article for Umbraco 8! 
Our Docs are open-source, so feel free to help out 😉 

Could you give me a link to the article about the Properly Value Converters that you feel needs updating?

**Comment by John-Blair** [comment]
https://our.umbraco.com/Documentation/Extending/Property-Editors/value-converters

Change to the interface methods for v8.

**Comment by sofietoft** [comment]
Great! Thanks for reporting this 💪 

I'll make sure we get around to this.
And remember: You're more than welcome to take a shot at updating the article yourself!

**Comment by sofietoft** [comment]
Apologies for the delay on this @John-Blair !
I can tell you that we have some people working on updating the Property Value Converter article for Umbraco 8: #1865 

Hopefully it'll be ready early in the next year 💪

**Comment by sofietoft** [comment]
Closing this one, as #1865 has been merged 💪
