### ISSUE TITLE
Improve explanations on Style Guide rules

### ISSUE THREAD

**Issue by NikRimington** [umbraco/UmbracoDocs#1846]
## What type of issue is it? (Choose one - delete the others)
Discussion/Improvement

## What article/section is this about? 
https://github.com/umbraco/UmbracoDocs/blob/master/Contribute/Style-Guide/index.md

## Describe the issue
While reading the style guide, I found myself wanting to understand why some of the rules are the way they are. For example, why shouldn't a heading end in punctuation? and, what about ! as currently that is deemed valid?

Explanations of the rules seems to exist for some, such as Long Sentences which states "this is to improve readability", and Terms "this is to ensure the same spelling of terms throughout the documentation"

Adding additional explanations of the rules would, in my opinion, improve understanding and potentially open them up for more enhancement.

**Comment by jmayntzhusen** [comment]
Hey @NikRimington 

I think this is a really good point! We based our initial round of style rules on recommendations and what other organizations are doing. Writethedocs which is an open source technical documentation organization has a list of style rules you can start out with here: https://github.com/testthedocs/vale-styles

They probably have their reasons to recommend these, but blindly implementing them is also not good, so we will go through the rules on our next curators meeting and add better explanations where needed 🙂

**Comment by sofietoft** [comment]
I've taken the time to add some more explanation to the style guide rules we've outlined here: https://our.umbraco.com/documentation/Contribute/Style-Guide/

With that, I'll close this issue for now.
Please feel free to reopen, if more explanation is needed.
Thanks again for reporting!
