### ISSUE TITLE
Verify articles for Umbraco 8

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#1853]
# Help wanted
Many of our articles needs to be verified against Umbraco 8, and for that we need your help!! 🙏

## What can you do to help?
We've put together a list of articles that needs to be verified and updated for Umbraco 8. 
We need you're help to do the following:
* Pick an article on the list
* Read it!
* Test out any code snippets, tutorials and step-by-step's in the latest version of Umbraco 8

Does the article still apply for Umbraco 8?
* **Yes**: Tell us in a here, and create a PR where you remove the `needsV8Update` tag at the top of the article.
* **No**: Tell us in an issue, OR create a new Umbraco 8 compatible article about the same topic!

## The List

- [x] [Backoffice Tours](https://our.umbraco.com/documentation/Extending/Backoffice-Tours/)
- [x] [File System Providers](https://our.umbraco.com/documentation/Extending/FileSystemProviders/)
- [x] [Macro Parameter Editor](https://our.umbraco.com/documentation/Extending/Macro-Parameter-Editors/)
- [x] [Value Converters](https://our.umbraco.com/documentation/Extending/Property-Editors/value-converters)
- [x] [Value Converters - Interface Example](https://our.umbraco.com/documentation/Extending/Property-Editors/value-converters-full-example-interface)
- [x] [Value Converters - Attributes Example](https://our.umbraco.com/documentation/Extending/Property-Editors/value-converters-full-example-attributes)
- [x] [Creating Forms (not Umbraco Forms)](https://our.umbraco.com/documentation/Getting-Started/Code/Creating-Forms/)
- [x] [Debugging](https://our.umbraco.com/documentation/Getting-Started/Code/Debugging/)
- [x] [Source Control](https://our.umbraco.com/documentation/Getting-Started/Code/Source-Control/)
- [x] [Templates](https://our.umbraco.com/documentation/Getting-Started/Design/Templates/)
- [x] [Templating (Reference Section)](https://our.umbraco.com/documentation/Reference/Templating/)
- [x] [Tutorial: Add Google Authentication](https://our.umbraco.com/documentation/Tutorials/Add-Google-Authentication/)
- [x] [Tutorial: Creating a Property Editor](https://our.umbraco.com/documentation/Tutorials/Creating-a-Property-Editor/)
- [x] [Tutorial: Creating an XML Sitemap](https://our.umbraco.com/documentation/Tutorials/Creating-an-XML-Site-Map/)
- [x] [Controllers in Umbraco](https://our.umbraco.com/documentation/Implementation/Controllers/)

When you have the Documentation repository cloned down, you can also search the articles for the `needsV8Update` tag to see which articles haven't yet been verified against Umbraco 8.

Thanks for helping us out!
We appreciate all your help 😄

**Comment by susw12** [comment]
I can pick up a couple of articles if needed. Please let me know which ones are a priority.

**Comment by sofietoft** [comment]
That'd be great @susw12 😄 
They aren't prioritized, so you can just pick whatever you feel up for doing 💪

**Comment by kows** [comment]
Looking into the source control one but kinda depends on @crgrieve 's PR (I've merged all on my fork to get starting).
Mostly cleanup so far, content could use a rewrite (any platform to discuss such?).

**Comment by sofietoft** [comment]
Looks like we got the "Source control" article under control - so to speak 😉 

Not sure what you mean about a "platform to discuss" @kows ?
Could you elaborate a bit on what you mean?

**Comment by kows** [comment]
I recall Gitter being introduced to discuss PR's on packages/Core.
Looking for a channel on there or Slack (or another medium) to discuss the contents of an article.
Unless I just make "my" version of it and feedback is processed during PR review.

**Comment by sofietoft** [comment]
Ah, I understand!
We don't have anything like that for Docs specifically.
You're more than welcome to write your version and make the PR. Then we'll have a chat about it!
How does that sound?

**Comment by marcemarc** [comment]
Anyone looking to update the FileSystemProviders config, there is some excellent notes here in the source code: https://github.com/umbraco/Umbraco-CMS/blob/fdcfc48e060cbaa5d82de32aa06b20b3e057516d/src/Umbraco.Core/Composing/CompositionExtensions/FileSystems.cs

**Comment by sofietoft** [comment]
It does indeed 💪 It has also been checked! 😁

**Comment by sofietoft** [comment]
It does indeed @jmayntzhusen 💪 It has also been checked! 😁

**Comment by Adolfi** [comment]
I created a PR to tick of the **Tutorial: Creating a Property Editor** in v8: https://github.com/umbraco/UmbracoDocs/pull/2212

**Comment by sofietoft** [comment]
All articles on this list has been verified and updating for Umbraco 8.
Thanks to everyone who's contributed 🎉 Your help is always much appreciated ❤️

**Comment by marcemarc** [comment]
Awesome effort!, feel like there should be some fireworks or something?
