### ISSUE TITLE
Macros in Umbraco 8 Documentation?

### ISSUE THREAD

**Issue by HTDL-Andrew** [umbraco/UmbracoDocs#1857]
Multiple Content Picker seems to only select one item in Umbraco version 8.0.2

**Comment by nul800sebastiaan** [comment]
Unfortunately the multiple media picker is not available as a macro parameter until v8.1.4 (https://github.com/umbraco/Umbraco-CMS/issues/5335) - we recommend you update to 8.1.4 to make use of that functionality.
