### ISSUE TITLE
Ambiguous Documentation

### ISSUE THREAD

**Issue by hidarikani** [umbraco/UmbracoDocs#1869]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/Setup/Server-Setup/Load-Balancing/flexible.md***

The page doesn't explain the master and scheduling server election algorithm. It doesn't say anything about the table dbo.umbracoServer which stores the "computer name" of each cluster node. I'm guessing that the master node is determined by matching the "computer name".
Furthermore there is no way to see from the backoffice which instance is the master.

**Comment by sofietoft** [comment]
Hi @hidarikani 
Thanks for your comments here!
We are looking into getting the articles about load balancing updated - mainly for Umbraco 8 though.

Not sure about the specifics here - perhaps @Jeavon has some input on this? 🤔

**Comment by mjohl** [comment]
@sofietoft Any idea on a schedule / date of when the V8 load balancing documentation will be done? I can imagine a lot of people are waiting for it.

**Comment by sofietoft** [comment]
@mjohl Can't give you an ETA on the docs, I'm afraid.

I know @Jeavon is going to start working on them. You're more than welcome to pitch in, if you'd like 😁

**Comment by jmayntzhusen** [comment]
https://github.com/umbraco/UmbracoDocs/pull/1964 will close this one.

**Comment by sofietoft** [comment]
@hidarikani - we now have Load balancing documentation for Umbraco 8: https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/

With that, I'll close this one. Thanks again for the report 😄
