### ISSUE TITLE
Help wanted: Docs about Routing

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#1873]
# Help wanted: Docs about Routing
Many of our articles needs to be verified against Umbraco 8, and for that we need your help!! 🙏

Our article series about **Routing** needs to be verified and updated for Umbraco 8. 

We need you're help to do the following:
* Pick an article on the list
* Read it!
* Test out any code snippets, tutorials and step-by-step's in the latest version of Umbraco 8

Does the article still apply for Umbraco 8?
* **Yes**: Tell us in a here, and create a PR where you remove the `needsV8Update` tag at the top of the article.
* **No**: Tell us in an issue, OR create a new Umbraco 8 compatible article about the same topic!

## The List

- [x] [Default Routing](https://our.umbraco.com/documentation/Implementation/Default-Routing/)
- [x] [Default Routing: Inbound Pipeline](https://our.umbraco.com/documentation/Implementation/Default-Routing/Inbound-Pipeline/)
- [x] [Default Routing: Controller Selection](https://our.umbraco.com/documentation/Implementation/Default-Routing/Controller-Selection/)
- [x] [Default Routing: Execute Request](https://our.umbraco.com/documentation/Implementation/Default-Routing/Execute-Request/)
- [x] [Custom Routing](https://our.umbraco.com/documentation/Implementation/Custom-Routing/)

Thanks for helping us out!
We appreciate all your help 😄

**Comment by sumitkharche** [comment]
Hi @sofietoft , 
I am happy to pick this one.

**Comment by sumitkharche** [comment]
Hi @sofietoft, I have completed the changes and raised PR for this issue. So could you please review it and let me know your feedback.

**Comment by erikjanwestendorp** [comment]
Hi @sofietoft I updated the _Default Routing: Execute Request_ page and created a PR. Can you or someone else give it a review and give some feedback if necessary?

**Comment by erikjanwestendorp** [comment]
Hi @sofietoft I updated the _Custom Routing_ page. Can you or someone else give it a review and give some feedback if necessary?

**Comment by erikjanwestendorp** [comment]
@sofietoft the Default Routing page has no `needsV8Update` tag (anymore) but I think the page should be updated. DynamicPublishedContent can be removed for v8.

**Comment by sofietoft** [comment]
Good morning @erikjanwestendorp !

That's a good point. Would be good to have that article in two versions 🤔 
I think it's just a left over from when we added the label to begin with. We kept it off most of the index pages for some reason 😅 

Would you be up for setting it up correctly? 🤞

**Comment by erikjanwestendorp** [comment]
@sofietoft Yes of course, I will pick this up!

**Comment by erikjanwestendorp** [comment]
@sofietoft I just created a PR. I created a _default routing_ page for v8. Can you or someone else give it a review :-)

**Comment by erikjanwestendorp** [comment]
@sofietoft I Updated the _Inbound-Pipeline_ page and created a PR.

**Comment by erikjanwestendorp** [comment]
@sofietoft I don't know if this is the right place because the page isn't mentioned in this issue but I updated the [Inbound request pipeline](https://our.umbraco.com/documentation/Reference/Routing/Request-Pipeline/inbound-pipeline) page and created a [PR](https://github.com/umbraco/UmbracoDocs/pull/2261).

**Comment by sofietoft** [comment]
That's great @erikjanwestendorp ! Not entirely sure why the article isn't on the list, but thanks for reporting it here anyways 😄 

I'll make sure to get someone to review the PR as soon as possible.

**Comment by sofietoft** [comment]
Looks like all this has been updated 👏 

A huge thanks to everyone who participated.
I'll close this issue now.
