### ISSUE TITLE
Help wanted: Docs about Querying

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#1875]
# Help wanted: Docs about Querying
Many of our articles needs to be verified against Umbraco 8, and for that we need your help!! 🙏

Our article series about **Querying** needs to be verified and updated against Umbraco 8. 

We need you're help to do the following:
* Pick an article on the list
* Read it!
* Test out any code snippets, tutorials and step-by-step's in the latest version of Umbraco 8

Does the article still apply for Umbraco 8?
* **Yes**: Tell us in a here, and create a PR where you remove the `needsV8Update` tag at the top of the article.
* **No**: Tell us in an issue, OR create a new Umbraco 8 compatible article about the same topic!

## The List

- [x] [Querying: UDI Identifiers](https://our.umbraco.com/documentation/Reference/Querying/Udi)
- [x] [IPublishedContent: IsHelpers](https://our.umbraco.com/documentation/Reference/Querying/IPublishedContent/IsHelpers)
- [x] [Dynamic Published Content](https://our.umbraco.com/documentation/Reference/Querying/DynamicPublishedContent/)
- [x] [Dynamic Published Content: Properties](https://our.umbraco.com/documentation/Reference/Querying/DynamicPublishedContent/Properties)
- [x] [Dynamic Published Content: Collections](https://our.umbraco.com/documentation/Reference/Querying/DynamicPublishedContent/Collections)
- [x] [Umbraco Helper](https://our.umbraco.com/Documentation/Reference/Querying/UmbracoHelper/)
- [x] [Membership Helper](https://our.umbraco.com/documentation/Reference/Querying/MemberShipHelper/)

Thanks for helping us out!
We appreciate all your help 😄

**Comment by poornimanayar** [comment]
@sofietoft Do you still need help with this? Happy to help!

**Comment by sofietoft** [comment]
@poornimanayar We could definitely still use some help getting the articles in this list verified for Umbraco 8! 😄 

Would be awesome, if you could pitch in! 💪

**Comment by poornimanayar** [comment]
Assign it to me!!! Will have a look later today :-)

**Comment by poornimanayar** [comment]
@sofietoft , I have been looking at the IsHelpers() for IPublishedContent. Some of the Is Helper is available on an `IndexedArray` which you can loop through while some others are not. How do you want me to approach it?

**Comment by poornimanayar** [comment]
@sofietoft , [UmbracoHelper](https://our.umbraco.com/Documentation/Reference/Querying/UmbracoHelper/) has samples for both v7 and v8 in the same document. Should we segregate it out, move the contents of [Pre v7.3](https://our.umbraco.com/Documentation/Reference/Querying/UmbracoHelper/index-vpre_7_3_0) into the new v7 document and make it relevant in the document that its pre v7.3? What do you think?

**Comment by sofietoft** [comment]
Great question @poornimanayar 🤔 

It does seem a bit unnecessary to have an entire article for just that one helper.
We should definitely have at least two seperate articles for this one - one for Umbrao 8 and one for Umbraco 7.
You're asking whether the "pre v7.3" should be added to the Umbraco 7 version, right? If that's the case, I think we should try it out! And then instead of added the entire snippet from the current "pre v7.3" article, would it be an idea to just add a mention of how, if you're using that version or lower, you also need to use `child.id` ? 🤔 

Ah, that was a long sentence 🙈 Hope it makes sense!

**Comment by poornimanayar** [comment]
@sofietoft , Exactly what I meant! But you know now what makes me shy away from documentation! I am so bad at explaining things in writing Lol!

**Comment by sofietoft** [comment]
Haha 😄 I feel exactly the same @poornimanayar ! It can get so complicated sometimes, when you try to explain these kinds of things 🙈 But it's a good exercise for the brain I guess 😅

**Comment by sofietoft** [comment]
Looks like all articles in the Templating/MVC section has been verified and updated for Umbraco 8 💪 

Thanks to everyone who's contributed.
I'll close this one for now.
