### ISSUE TITLE
Help wanted: Docs about WebAPI

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#1876]
# Help wanted: Docs about WebAPI
Many of our articles needs to be verified against Umbraco 8, and for that we need your help!! 🙏

Our article series about **WebAPI** needs to be verified and updated against Umbraco 8. 

We need you're help to do the following:
* Pick an article on the list
* Read it!
* Test out any code snippets, tutorials and step-by-step's in the latest version of Umbraco 8

Does the article still apply for Umbraco 8?
* **Yes**: Tell us in a here, and create a PR where you remove the `needsV8Update` tag at the top of the article.
* **No**: Tell us in an issue, OR create a new Umbraco 8 compatible article about the same topic!

## The List

- [x] [Web API](https://our.umbraco.com/documentation/Reference/Routing/WebApi/)
- [x] [Web API: Routing](https://our.umbraco.com/documentation/Reference/Routing/WebApi/routing)
- [x] [Web API: Authorization](https://our.umbraco.com/documentation/Reference/Routing/WebApi/authorization)

Thanks for helping us out!
We appreciate all your help 😄

**Comment by crgrieve** [comment]
Hi @sofietoft , I am happy to pick this one up as I am making some WebAPI controllers on v8 at the moment so will be testing anyway :)

Thanks,
Carole

**Comment by sofietoft** [comment]
That sounds amazing @crgrieve !! 😄 
Can't wait to review the result.

**Comment by sofietoft** [comment]
Thanks for the PR @crgrieve 😄 

Can see Jesper merged it, so I'll close this issue!
