### ISSUE TITLE
Help wanted: Docs about MVC Templating

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#1877]
# Help wanted: Docs about MVC Templates
Many of our articles needs to be verified against Umbraco 8, and for that we need your help!! 🙏

Our article series about **MVC Templating** needs to be verified and updated against Umbraco 8. 

We need you're help to do the following:
* Pick an article on the list
* Read it!
* Test out any code snippets, tutorials and step-by-step's in the latest version of Umbraco 8

Does the article still apply for Umbraco 8?
* **Yes**: Tell us in a here, and create a PR where you remove the `needsV8Update` tag at the top of the article.
* **No**: Tell us in an issue, OR create a new Umbraco 8 compatible article about the same topic!

## The List

- [x] [MVC Views](https://our.umbraco.com/documentation/Reference/Templating/Mvc/views)
- [x] [MVC Views: Examples](https://our.umbraco.com/documentation/Reference/Templating/Mvc/examples)
- [x] [MVC Partial views](https://our.umbraco.com/documentation/Reference/Templating/Mvc/partial-views)
- [x] [MVC Child actions](https://our.umbraco.com/documentation/Reference/Templating/Mvc/child-actions)
- [x] [MVC Querying](https://our.umbraco.com/documentation/Reference/Templating/Mvc/querying)
- [x] [MVC Forms](https://our.umbraco.com/documentation/Reference/Templating/Mvc/forms/)
- [x] [MVC Forms: Partial Views](https://our.umbraco.com/documentation/Reference/Templating/Mvc/forms/tutorial-partial-views)
- [x] [MVC Forms: Child Actions](https://our.umbraco.com/documentation/Reference/Templating/Mvc/forms/tutorial-child-action)
- [x] [MVC Forms: Custom markup](https://our.umbraco.com/documentation/Reference/Templating/Mvc/forms/tutorial-custom-markup)

Thanks for helping us out!
We appreciate all your help 😄

**Comment by greystate** [comment]
I think I've just found my **Hacktoberfest** assignment 😆 — happy to tackle this.

**Comment by greystate** [comment]
Sidenote: The first two does not show the warning about not having been verified with V8 on Our, even though they have the `needsV8Update` tag. Is that a "the docs have not been built" issue, or something else that should ideally be reported as an issue itself?

**Comment by sofietoft** [comment]
That's awesome to hear @greystate 😎 🎉

If you check the articles directly in Github, you'll see that they actually have the "needsV8update".
https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Templating/Mvc/views.md

The reason they do not have the green box at the top of the article, is because it isn't an "index.md" file, which are the only ones we add the box to.
This sucks, I know, but that's how we did it 🙈 Hopefully we won't need to box for much longer! 💪

**Comment by greystate** [comment]
5 minutes in and I can verify that it definitely needs updating :-)

I'm on it ✍️ 📝

**Comment by sofietoft** [comment]
@greystate, it's been some time since you committed to this task - you still on it? 😄 🙈

**Comment by greystate** [comment]
@sofietoft Thanks for the nudge :D 

I was under the impression that someone else was doing a set of PRs for these during #HacktoberFest ? So I kinda didn't want to budge in...

**Comment by sofietoft** [comment]
Aah, I see 🤔
I think @emmaburstow only did the one - https://github.com/umbraco/UmbracoDocs/pull/2041.

The rest is still very much up for grabs, if you're still up for it! 😁

**Comment by poornimanayar** [comment]
@sofietoft , I can work on some of these if you need assistance.

**Comment by sofietoft** [comment]
That would be awesome @poornimanayar !! 😄

**Comment by greystate** [comment]
@sofietoft @poornimanayar Very nice indeed! I've not been able to do anything all of December so please grab any of them; no worries 🥇

**Comment by poornimanayar** [comment]
@sofietoft , I believe I have gone through all the ones that were left to be done :-)

**Comment by sofietoft** [comment]
You're right @poornimanayar ! 😄 
Great job, and thanks for putting in the work to help out.

We can definitely close this one now 👏
