### ISSUE TITLE
Links to the reference documentation

### ISSUE THREAD

**Issue by abjerner** [umbraco/UmbracoDocs#1885]
A bit similar to the Umbraco Docs, I've started a project to document our packages at Skybrud.dk. As part of this, I have both a "normal" documentation and a reference documentation for the C# assemblies.

The normal documentation is based on Markdown files. And whenever the docs mention a type, a method or similar, I can add an extra attribute to the `<code>` element, and it will be turned into a link to the reference documentation on the documentation site,

For instance I would write `<code type="Skybrud.Essentials.Json.JsonUtils, Skybrud.Essentials">JsonUtils</code>` in the Markdown, and this is then turned into a nice link to the reference documentation for the class I've specified. The same also works for method and similar - eg. with `<code method="Skybrud.Essentials.Json.JsonUtils.ParseJsonObject, Skybrud.Essentials">ParseJsonObject</code>`, I can reference a specific method in the C# assembly.

![image](https://user-images.githubusercontent.com/3634580/65894180-988f0a00-e3a9-11e9-819e-9fd05b393756.png)

The benefit of using `<code>` elements is that the documentation will look fine on GitHub. While it's primarily for types declared in our own packages, it also handles referencing types in Microsoft's packages and in Newtonsoft.Json.

I believe something like this creates a better synergy between the normal Markdown based documentation and the reference documentation. So the question is now - would something like this make sense for the Umbraco documentation as well? If so, I'd be happy to create a pull request for this 😄 

And the next next question - would any work put into this be lost when DocFX 3 is rolled out?

<hr />

To further illustrate the idea, you can see an example of a Markdown file in my documentation here:
https://raw.githubusercontent.com/skybrud/SkybrudDocs/master/Documentation/Skybrud.Essentials/Json/Index.md

The same page is shown on the documentation site here:
https://packages.skybrud.dk/skybrud.essentials/docs/json/

**Comment by nul800sebastiaan** [comment]
That would be so awesome! 👍 

I hope the work is not for nothing with DocFX 3, does @jmayntzhusen know more about this?

**Comment by jmayntzhusen** [comment]
This is great, however the docfx change would do the same and invalidate the work put in 😕

In DocFx you can specify a uid for a file in yaml, and the auto generated api docs get the namespace, fx:
```
uid: Umbraco.Web.Mvc.SurfaceController
```

You can then link to it like this:
```
[Link to SurfaceController API doc](xref: Umbraco.Web.Mvc.SurfaceController)
```

So while this would be awesome, implementing it and fixing all links would be a lot of work that we would then have to do over when switching in the future unfortunately.

**Comment by jmayntzhusen** [comment]
Will close this after our talk @abjerner thanks for the offer though! 🙂
