### ISSUE TITLE
'IBooleanOperation' does not contain a definition for 'Field' and no accessible extension method 'Field' accepting a first argument of type 'IBooleanOperation' could be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by naveenraina** [umbraco/UmbracoDocs#1886]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Searching/Examine/Quick-Start/index.md***

**Comment by naveenraina** [comment]
Neither is .NodeTypeAlias. I am using Umbraco 8.1

**Comment by nul800sebastiaan** [comment]
You forgot to put the `And()` in there, so it should be `ParentId(1105).And().Field("bodyText", searchTerm)`. 😃

**Comment by naveenraina** [comment]
Thank you for your valuable insight @nul800sebastiaan
