### ISSUE TITLE
Update Documentation for Registering Custom Sections in V8

### ISSUE THREAD

**Issue by louisjacksonrees** [umbraco/UmbracoDocs#1896]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about? 
https://our.umbraco.com/Documentation/Tutorials/Creating-a-Custom-Dashboard/
https://our.umbraco.com/Documentation/Reference/Config/dashboard/

## Describe the issue
Update References to the dashboard config file to use the newer method for V8 as outlined here:
https://our.umbraco.com/Documentation/Extending/Dashboards/

**Comment by Niladri24dutta** [comment]
@louisjacksonrees Do you mean the url needs to be updated for the config file in the documentation? please confirm so that I can work on this.

**Comment by nul800sebastiaan** [comment]
Thanks @louisjacksonrees - we should definitely update the examples in the docs to use the v8 version, is this something you would be able to contribute to?

**Comment by Niladri24dutta** [comment]
@nul800sebastiaan Can I work on this if it's still open?

**Comment by jmayntzhusen** [comment]
The tutorial is in progress: https://github.com/umbraco/UmbracoDocs/pull/1642
As for the config page we need to redo that according to https://github.com/umbraco/UmbracoDocs/issues/1817

**Comment by sofietoft** [comment]
Dashboard tutorial has been updated for Umbraco 8.
The article on the `dashboards.config` file has also been versioned for Umbraco 8.

I'll close this issue for now.
