### ISSUE TITLE
Document New Localization Technique

### ISSUE THREAD

**Issue by Nicholas-Westby** [umbraco/UmbracoDocs#194]
This issue was recently completed ("Allow Localization of Plugins without having to edit core language files"): http://issues.umbraco.org/issue/U4-5777

With that, there is a new way of localizing text (i.e., the translations can be placed in the App_Plugins folder).

Would be great if those instructions were added here: https://our.umbraco.org/documentation/Extending/Language-Files/

Found that page in the en_us.xml file that ships with Umbraco. Well, actually, the en_us.xml file had this link: http://our.umbraco.org/documentation/Extending-Umbraco/Language-Files

Notice the "Extending-Umbraco" is just "Extending" in the first link. Clicking the menu on the left of the site produced the shorter link:
![link](https://cloud.githubusercontent.com/assets/5933222/8786957/169a704c-2ee6-11e5-8149-3311833cc54d.png)

Perhaps that ought to be addresses as well (e.g., by updating the link in the Umbraco core).

**Comment by Shazwazza** [comment]
we're working on overhauling some of this documentation :) Will def get this updated

**Comment by Shazwazza** [comment]
need to doc these:

http://issues.umbraco.org/issue/U4-5777

and http://issues.umbraco.org/issue/U4-5777

**Comment by Nicholas-Westby** [comment]
Just an FYI to anybody who comes across this that some of the documentation appears to have been added now: https://our.umbraco.org/documentation/Extending/Language-Files/Language-Files-For-Packages/

**Comment by sofietoft** [comment]
Hi guys,
I'm currently working my way through the issue tracker here on the Umbraco Documentation!

Seems that documentation for this has already been created: https://our.umbraco.org/documentation/Extending/Language-Files/Language-Files-For-Packages/

I'm closing this request down.
Please feel free to create another issue on this tracker, if you feel the documentation on this area is still a bit sparse.

Thanks a lot for contributing, and keep up the good work! 😁 

- Sofie
