### ISSUE TITLE
Front end build docs

### ISSUE THREAD

**Issue by crgrieve** [umbraco/UmbracoDocs#1940]
## What type of issue is it? (Choose one - delete the others)
Discussion

## What article/section is this about? 
https://our.umbraco.com/documentation/Development-Guidelines/building-angular-project

## Describe the issue

I noticed the build instructions don't match those on the CMS repo : https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/.github/CONTRIBUTING.md#building-umbraco-from-source-code

I was going to update here but wondered what was best approach,bringing these instructions to docs repo or linking to CMS repo instructions from here (hopefully this would stop them getting out of date again?).

**Comment by sofietoft** [comment]
That's a great observation, @crgrieve 🤔 

I think it would make sense to simply remove them from the docs article, and then link to the contribution guidelines on the CMS!
The whole "Development Guidelines" is very out-of-date as I remember it, from the last time I ran through it 🙈

**Comment by crgrieve** [comment]
yeah, I set the CMS build up a few days ago so when I saw the docs I noticed it was quite different now! 

I will do a PR later to link to CMS guidelines :) Just wanted to check the correct approach. Thanks for your help!

**Comment by crgrieve** [comment]
PR submitted: https://github.com/umbraco/UmbracoDocs/pull/1951
