### ISSUE TITLE
XML snippet not showing code

### ISSUE THREAD

**Issue by richarth** [umbraco/UmbracoDocs#1971]
In the URL provider mode section of https://our.umbraco.com/documentation/reference/routing/request-pipeline/outbound-pipeline#url-provider-mode there are two blocks of code.

The second block of code detailing the settings config changes is not rendering the code to use.

**Comment by jmayntzhusen** [comment]
@richarth 

Thanks for reporting this, not sure what caused this in the first place, but this commit seems to have fixed it: https://github.com/umbraco/UmbracoDocs/commit/3fa52c525c56291cd5c482e3c71d4757d1f7940c
