### ISSUE TITLE
Should ComponentComposer be marked with IUserComposer?

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/UmbracoDocs#1974]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Implementation/Composing/index.md***

The `SubscribeToContentServiceSavingComposer` in _'Example - Creating a Component to listen for ContentService.Saving events'_ is an `IUserComposer` and later replaced with a `ComponentComposer<T>`. This class only inherits from `IComposer` (see [source](https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Core/Composing/ComponentComposer.cs#L9)), so this isn't only a quicker way to add a custom component: it's conceptionally different.

To make it exactly the same, the `SubscribeToContentServiceSavingComposer` should probably also be marked with the `IUserComposer` interface:

```c#
public class SubscribeToContentServiceSavingComposer : ComponentComposer<SubscribeToContentServiceSavingComponent>, IUserComposer
{ }
```

This is will make sure it's added after all default Umbraco composers, like the first example.

Documentation for adding custom events on [application startup](https://our.umbraco.com/Documentation/Reference/Events/Application-Startup) also references this page, but doesn't provide an easy (correct!) example. So you'll have to read the whole composing part and pick the right example code to get started.

Adding the following example will let people get started right away:

```c#
public class ApplicationComposer : ComponentComposer<ApplicationComponent>, IUserComposer
{
	public override void Compose(Composition composition)
	{
		// Only override this method if you want to compose more then only adding the component (make sure to call the base method, as the component isn't added otherwise).

		base.Compose(composition);
	}
}

public class ApplicationComponent : IComponent
{
	public void Initialize()
	{
		// Add your events here!
	}

	public void Terminate()
	{ }
}
```

This might get a little less verbose if the following PR gets merged: https://github.com/umbraco/Umbraco-CMS/pull/6654.

**Comment by sofietoft** [comment]
Thanks for reporting and for the PRs @ronaldbarendse ! 💪 

I've asked some of the more experienced Umbraco peeps to help give this a look

**Comment by sofietoft** [comment]
@ronaldbarendse - the PRs you've made here on the Docs related to this, has been merged.

That means we can close this issue, right? 🤔

**Comment by ronaldbarendse** [comment]
Both points mentioned in this issue are fixed, so we can indeed close this one! 👍

The only thing that might need a little cleanup are the mixed tabs/spaces in the [Getting started](https://our.umbraco.com/documentation/reference/events/application-startup#example---getting-started) example.
