### ISSUE TITLE
broken-link(s)

### ISSUE THREAD

**Issue by butuzov** [umbraco/UmbracoDocs#1983]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
issues about case descibed in `broken-link.md`

## Describe the issue
I was testing my tool for checking the documentation for broken links, and found few. Following `broken-link.md` I am first reporting found issues. I will update this issue after next find in order to reduce my spamming.

Broken links found
* [ ] https://our.umbraco.com/documentation/Reference/Debugging/Images (referenced from menu on https://our.umbraco.com/documentation/ see Reference/Debuging), directory itself doesn't have index.md, just images referenced at https://our.umbraco.com/documentation/Reference/Debugging

**Comment by sofietoft** [comment]
Ah, good catch!
The issue here is that the folder is called "Images" with a capital I 😅 
We'll make sure it resolved.

**Comment by butuzov** [comment]
Glad, it was informative. I need to improve a bit my tool in order to continue analysis, if you don’t mind I keep crawling your documentation as an experiment.

**Comment by sofietoft** [comment]
That's completely fine! 😄 

I look forward to hear what you find 💪

**Comment by butuzov** [comment]
Most of this is false positives (sire gives error because of DDoS protection, but link exists) or `example.org` like domains. Just a few finds:

* [x] https://marketplace.visualstudio.com/items?itemName=warren-buckley.iis-express - fp, exists.
* [x] https://www.microsoft.com/en-us/download/details.aspx?id=48264  - fp, exists.
* [ ] https://github.com/umbraco/UmbracoRestApi
* [x] http://example.com/base/test/Hello/ - `example.org`.
* [x] https://templated.co/retrospect - fp, exists: 
* [x] http://localhost - `example.org`.
* [x] http://localhost/umbraco - `example.org`:
* [x] https://our.umbraco.com/documentation/Reference/Debugging/Images - you have describe it earlier.
* [x] https://www.myget.org/F/umbracocore/api/v3/index.json - fp, exists.
* [x] http://yoursite.com/sitemap - `example.org`.
* [ ] https://github.com/umbraco/Courier/blob/master/Documentation/Developer Documentation/Data Resolvers.md
* [x] https://thisisalink.com/useful/resource fp, `example.org`: 
* [x] http://yoursite.com/umbraco/ - fp, `example.org`: 
* [x] https://mysite.com - fp, `example.org`: 
* [x] https://marketplace.visualstudio.com/items?itemName=ZpqrtBnk.UmbracoModelsBuilderExtension - fp, exists.
* [x] http://www.devx.com/xml/Article/28610/1954 -  access restricted from Ukraine, fp.
* [x] https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Visual-Studio - see PR details.
* [x] https://www.microsoft.com/en-us/download/confirmation.aspx?id=14047 - fp, exists.
* [x] https://datalust.co/seq - fp, exists.
* [x] https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=/NBiHWOnBkejXKOs.0.0.4 - fp redirection issue.
* [x] http://mysite.com/feedback - fp, `example.org` 
* [x] https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/Upgrades - See PR details.
* [x] https://www_oreilly_com/library/view/framework-design-guidelines/9780321545671 - See PR details.
* [ ] https://our.umbraco.com/documentation/Add-ons/UmbracoCourier/Old-Courier-versions - issue generated by breadcrumb link at https://our.umbraco.com/documentation/Add-ons/UmbracoCourier/Old-Courier-versions/Installation/


I also have removed from the list domain issues.umbraco.org (will check why does it erroring a bit later). 

See umbraco/UmbracoDocs#2014 for changes details.
