### ISSUE TITLE
Document custom routes with virtual nodes (UmbracoVirtualNodeRouteHandler)

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoDocs#200]
We need full documentation about custom routing using virtual nodes and the UmbracoVirtualNodeRouteHandler (including inhertited types)

There's a TODO: to fill this in here: /documentation/Reference/Routing/custom-routes

**Comment by sofietoft** [comment]
Hi @Shazwazza 

I'm currently going through the issue tracker here on the Docs.
Seems that documentation about Custom Routing has been created: https://our.umbraco.org/documentation/Reference/Routing/custom-routes

Can I close this issue down? 😁 

- Sofie

**Comment by Shazwazza** [comment]
Yup! will close :)
