### ISSUE TITLE
The documentation doesn't change version on pressing dropdown

### ISSUE THREAD

**Issue by room101b** [umbraco/UmbracoDocs#2022]
After pressing V7 in the version dropdown I expect the documentation to change to version 7 but it remains on version 8.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/index.md***

**Comment by sofietoft** [comment]
You mean the dropdown next to the search bar, right?
You are right, that switching version there, doesn't change the version of the Documentation articles.
It does, however, change which articles will be shown on top, when you search for something specific! 😁 

So, choosing `v7` in the dropdown, lets you search for articles on Umbraco 7 💪 

We are talking about improving both the search and the versioning feature. But I'm afraid adding a button that changes version of all articles at once, is not as easy as it sounds at the moment 😅 
For now, we follow the conventions described here: https://our.umbraco.com/Documentation/Contribute/file-naming-conventions
