### ISSUE TITLE
Add Angular directives, services etc. to the documentation

### ISSUE THREAD

**Issue by abjerner** [umbraco/UmbracoDocs#2045]
When extending the Umbraco backoffice, we can consult the [Umbraco Backoffice UI API documentation](https://our.umbraco.com/apidocs/v8/ui/#/api) to see which Angular directives, services and so on we can use in our custom code. But the current API documentation is far from great, as doesn't show some of the options that actually are supported, and it lacks useful examples.

On way to solve this is of course to improve the existing API documentation. But instead (or in addition to), the Angular side of the backoffice could be documented as part of the main documentation - a bit similar to how the [C# service](https://our.umbraco.com/documentation/Reference/Management/Services/) are documented in the main documentation while also being part of the C# API Documentation.

I'm a bit unsure where to put something like this in the folder structure, but content wise I was thinking about something like this:

https://gist.github.com/abjerner/61a54258de9e7dd1f15ef9a1b24425e2

I know this requires some extra work, but I'd be happy to give a hand writing this part of the documentation 😉

**Comment by nul800sebastiaan** [comment]
I am not sure what you're suggesting here @abjerner - just duplicating the existing generated documentation into the docs?

**Comment by abjerner** [comment]
The basis of this issue is that the current API reference feels a bit limited. All options and parameters (eg. for the editor service) should be documented (which they are currently not). But ideally there should be better examples on how to use the different service and directives. Perhaps even screenshots of how a given directive would look.

My question was partly whether something like this is best done by updating the existing API reference - or introducing a new part of the main documentation that focuses on describing the Angular parts in greater detail.

With the C# services that I mentioned, they are part of the C# API reference, but also described in the main documentation. It's not exactly duplicate content, but more something that is complimenting each other.

I hope that makes sense 😉

**Comment by sofietoft** [comment]
Hi @abjerner ,
I've been trying to wrap my head around this, and also had a chat with my fellow Curators about it at our meeting yesterday.
As we understand, this is two-fold:

1. There should be more details on each service in the source code - therefor also the API docs. These details should include a description of the parameters (right?)
2. There should be examples on each serivce - preferably in the Documentation on Our

Would you say, we got that all right? 😅

**Comment by abjerner** [comment]
Hi @sofietoft,

For **1)**, yes. All parameters should be documented through the ngdocs.

**2)** is what I'm asking about, as I'm not sure myself.

We could either have everything in the API documentation. But having extended explanation and examples might clutter the API documentation, so it may be more ideal to have that part in the main documentation.

On the other and, when reading the API documentation, it may not be obvious that you cand ind further explanation and examples in the main documentation.

**Comment by sofietoft** [comment]
Great! Thanks for confirming 😄 

Yes, I agree with your point about it currently being a bit difficult to link FROM the API docs to the docs on Our 🤔
The other way around is easy enough though .. Hm!

When we at some point start using DocFX adding comments like these and linking between the docs will be much simpler and easier to manage!

The question then remains - should we start adding some examples on Our now, or wait till DocFX become a reality - hopefully some time next year 🤞

**Comment by abjerner** [comment]
I think anything we add now is better than what we have now - especially if there is not confirmed ETA for the next version of DocFX. And then we can always update it again when DocFX is rolled out.

But next question is then where should something like this live in the structure?

**Comment by sofietoft** [comment]
Yes, definitely better than what we have now! 😄 💪 

Hm, how about under here: https://our.umbraco.com/Documentation/Reference/API-Documentation/
![backoffice-api-docs](https://user-images.githubusercontent.com/24529086/70235590-83e14080-1763-11ea-8ffd-45a40ffb2597.png)

So, adding a new section under Reference/API-Documentation .. perhaps called "Using the Backoffice UI API" or something? 🤔

**Comment by abjerner** [comment]
Possibly yes 😄 

I can try playing a bit around with that.

**Comment by sofietoft** [comment]
That would be awesome, @abjerner ! 😄

**Comment by abjerner** [comment]
I know it's the name currently used, but I feel the **UI** part in the name is a bit wrong, as an Angular service for instance isn't directly a UI component.

So for now I've just created an **Angular** sub section under **Reference**. I'm still just playing around in my local Our installation, so I haven't committed anything yet.

![image](https://user-images.githubusercontent.com/3634580/70397001-8d420580-1a0e-11ea-8d48-d7ccb8229e0e.png)

![image](https://user-images.githubusercontent.com/3634580/70397036-e4e07100-1a0e-11ea-8a87-75204cdecd8a.png)

**Comment by sofietoft** [comment]
Sorry for the delay, @abjerner !

Looks really great so far 💪 
I think calling it "Angular" should be just fine. Will bring it up with the Curators on our meeting tomorrow, to hear if they have any input! 😁

**Comment by sofietoft** [comment]
Hi @abjerner ! 😄 

It's been a while!
What's the status on these Backoffice UI API Docs you started working on? 😁

**Comment by nul800sebastiaan** [comment]
Just to chip in here, the new version of DocFX will allow for additional annotations on the auto-generated documentation. The Docs team is planning to upgrade to that version when version distinctions are fixed (so you can make a switch between v7 and v8). I feel like this would be exactly what you're looking for?

**Comment by abjerner** [comment]
@sofietoft I started on a few pages, but haven't really looked at them for a while. I'll try to catch up, and get back to you 😉 

@nul800sebastiaan possibly. So the plan is that the AngularJS documentation will also be generated by DocFX in the future?

Nevertheless, my thought was that we need "article style" documentation as an addition to the current "reference documentation". I don't think DocFX will change this part.

Here is an example of another page I started on:

![image](https://user-images.githubusercontent.com/3634580/74782795-79374180-52a4-11ea-9a6d-ab9152c64aad.png)

**Comment by sofietoft** [comment]
Looks great @abjerner ! 😄 

I'm not 100% sure what exactly will be possible with DocFX to be honest. It might not be possible to make articles like the ones you've made here, but I'm pretty sure it will give us the option to extend on the auto-generated API docs - like adding more real-life examples, and writing text to accompany the samples 🤔

**Comment by nul800sebastiaan** [comment]
Ah sorry, I misunderstood, indeed DocFX doesn't deal with our javascript docs. 
The `editorService` page looks great! Definitely will be beneficial to have extended usage examples on a lot of our services and as Pete mentions in #1595 events. I guess this one duplicates #1595 really?

**Comment by sofietoft** [comment]
Hi @PeteDuncanson .. I'm not entirely sure I understand here, so forgive me if I'm misunderstanding.
We do still have the API docs for the backoffice here: https://our.umbraco.com/apidocs/v8/ui/#/api, and it will be amended by the manual docs on Our. 
I do believe, that that's how it's going to have to be for now! 😅

**Comment by abjerner** [comment]
I think the whole situation with corona and working from home hit my motivation to do much after work, so I haven't really looked at this for a while.

Automating as much as we can is of course ideal, but right now we don't really have a context to get the parameters from the API docs. I think we'll have to write our own ngdocs parser (or find an existing one for C#) if we wish to pull this information into the main documentation. So not a quick task for now. And DocFX may (or may not) change things.

As Pete is onto, a trade off from not automating things may lead to outdated tables and examples. But I think that is something we'll have to accept for now.

Each of these pages are essentially small articles, so they require a bit of time to write. But I'll try to find some motivation again, and hopefully commit the first few pages.

**Comment by abjerner** [comment]
I often use the `<umb-load-indicator />` directive, and also did so today, so I decided to write this page:

![image](https://user-images.githubusercontent.com/3634580/82475916-8b0bc900-9acd-11ea-9fe3-5657cf02be95.png)

The current documentation is very text based (and the occasional image), but I think it sometimes needs a few links to further information. But as there isn't a component for this purpose, and links easily disappears with the the text of the article, I've tried to dabble a bit with a list of links (may require the touch of a designer).

The list is defined using HTML, but as it is a normal `<ul>` (but with a class name we can target on Our), it will be displayed as a simple list when viewing the Markdown files on GitHub:

```html
<ul class="cta-list">
	<li>
		<a href="/apidocs/v8/ui/#/api/umbraco.directives.directive:umbLoadIndicator" target="_blank">
			<code>&lt;umbLoadIndicator /&gt;</code>
			in the API documentation (opens in new window)
		</a>
	<li>
		<a href="https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/umbloadindicator.directive.js" target="_blank">
			<code>&lt;umbLoadIndicator /&gt;</code>
			source code on GitHub (opens in new window)</a>
	</li>
</ul>
```

Is this something worth pursuing? It requires that contributors to the docs know the syntax if they wish to use such a list, but IMO it will help making the documentation more readable. I generally like the concept of making these styled components, so other components may be useful as well.

**Comment by sofietoft** [comment]
This is great @abjerner ! 👏 

I like the links, and the blue box looks great.
However, in order to keep the overall consistency of the Docs, perhaps use one of the formats we have for "comments" sections? They're all Markdown...
We currently have 3 different once; Tip, Note and Warning.
Find them and the formatting for each here: https://our.umbraco.com/documentation/Contribute/Markdown-Conventions/#adding-notes-warnings-tips

What do you think? 🤔

**Comment by jmayntzhusen** [comment]
@abjerner 

The note, warning, etc we have in https://our.umbraco.com/documentation/Contribute/Markdown-Conventions/#adding-notes-warnings-tips were all based on the fact that MarkDig converts
````
```classname
markdown here
```
````

To:
```
<div class="classname">
html conversion of markdown here
</div>
```

You can find the css for the others here: https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco.Client/src/scss/sections/_docs.scss#L119

Maybe you could simple add some styling after a recognizeable classname that could allow people to do something like 

````
```links
- [first link](url)
- [secondlink](url)
- [third link](url)
```
````

And then it ends up with a custom link box based on styling specific to the .links classname?

**Comment by abjerner** [comment]
@sofietoft @jmayntzhusen thanks for the feedback :smile:

Personally I'm not a fan of the `:::` blocks as they don't work on GitHub. And the <code>```</code> equivalent doesn't render the content as it's a code snippet - at least here om GitHub.

But I'll try to play a bit with the syntax to see what makes the most sense 😉

**Comment by jmayntzhusen** [comment]
Oh woops, meant :::links, etc. not ```..

Yea I guess it's a tradeoff. The reason we did the :::name syntax in the beginning is that it is a bit more beginner friendly than managing full html elements. 

If we have content editors, etc, contributing it is easier to let them use this functionality by pointing them to a page of "custom styling" that all follow the same structure. With HTML elements it can quickly become complicated and any little syntax error will mess it up..

**Comment by abjerner** [comment]
Even though the `:::` syntax doesn't work on GitHub, I can also see the benefit of that approach. So PR for the styling is here:

https://github.com/umbraco/OurUmbraco/pull/584

**Comment by sofietoft** [comment]
As the Angular docs section has now been started on Our, I'm gonna close this issue for now.

See the following issue instead:
- Angular Directives: https://github.com/umbraco/UmbracoDocs/issues/2653
- Angular Services: https://github.com/umbraco/UmbracoDocs/issues/2654
