### ISSUE TITLE
Add link to Umbraco Cloud Portal

### ISSUE THREAD

**Issue by nojaf** [umbraco/UmbracoDocs#2047]
Believe it or not but I'm having trouble to finding the link to the Umbraco Cloud Portal.
I was expecting it to be there on this page.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/index.md***

**Comment by sofietoft** [comment]
That's an interesting observation @nojaf 🤔 

It would actually make a lot of sense to have a link to the portal in that article!
Would you be up for adding it? 😁

**Comment by sharathInfy** [comment]
@sofietoft Is this the link https://www.s1.umbraco.io/home/login/ to the portal that needs to be given? or is this the link https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-started/The-Umbraco-Cloud-Portal/ . I would be happy to change the documentation.

**Comment by sofietoft** [comment]
@sharathInfy , I can see you already made a PR 😄 ( #2050 )

And it is correct, that what we would like here, is a link to the Umbraco Cloud Portal 💪
