### ISSUE TITLE
Error creating visual studio solution to Umbraco cloud

### ISSUE THREAD

**Issue by Mervin77** [umbraco/UmbracoDocs#2063]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/index.md***

After entering the namespace in the command prompt using UaaS.cmd, the cmd closed and no solution created

**Comment by nul800sebastiaan** [comment]
@Mervin77 There's probably an error. Could you open a command prompt and run UaaS.cmd in there so that it is still open when the error occurs and should hopefully show you something more useful?

**Comment by sofietoft** [comment]
Hi @Mervin77 !

It's been a while, and we haven't heard back from you. I hope that means you managed to things working 😄 

Please let us know if that's not the case!
