### ISSUE TITLE
Umbraco Package documentation

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/UmbracoDocs#2066]
The Umbraco Package team has talked about what sort of documentation would be nice to have for packages.

We have decided on some articles, and will use this issue to keep track of all of them. If you are interested in helping out and writing an article about packages then please respond and we can assign it to you 😉

If you feel something is missing from the list then we welcome all feedback!

# Decided upon articles:
- [x] How to create a package in the backoffice - https://github.com/umbraco/UmbracoDocs/pull/2035
- [x] How to use Package Actions - https://github.com/umbraco/UmbracoDocs/pull/2064
- [x] Differences between Nuget and Zip packages -https://github.com/umbraco/UmbracoDocs/pull/2067
- [x] How to create custom Package Actions - https://github.com/umbraco/UmbracoDocs/pull/2083
- [x] How to create a Nuget package - https://github.com/umbraco/UmbracoDocs/pull/2112
- [x] How to upload your package to Our - https://github.com/umbraco/UmbracoDocs/pull/2167
- [x] Guidelines for managing packages after release - https://github.com/umbraco/UmbracoDocs/pull/2339
- [x] What is a package? (High level understanding for beginners) - WIP: https://github.com/umbraco/UmbracoDocs/pull/2217

**Comment by sofietoft** [comment]
All items are checked 💪 

I'll close this one for now.
