### ISSUE TITLE
Update image cropper docs to v8

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/UmbracoDocs#2074]
The docs for the cropper are currently referring to `Model.Content` and showing various ways of doing things in v7 but I can't actually figure out how to do it properly in v8 🙈

**Comment by nul800sebastiaan** [comment]
Oops, forgot the link https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper

**Comment by sofietoft** [comment]
I've been working on updating it actually: https://github.com/umbraco/UmbracoDocs/pull/1909

Got stuck on how to figure out which data is returned based on this section: https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper#data-returned

**Comment by sofietoft** [comment]
Closed with #2208
