### ISSUE TITLE
Missing documentation 

### ISSUE THREAD

**Issue by John-Blair** [umbraco/UmbracoDocs#2090]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/broken-link.md***

 link from 

https://umbraco.com/blog/product-update-14th-of-november/

to 

https://our.umbraco.com/documentation/Umbraco-Headless/API-Documentation/?_ga=2.212938067.65601449.1573827575-1210310562.1557930005

**Comment by sofietoft** [comment]
Great observation @John-Blair ! Thanks for making us aware of this!

We'll need to have some rewrites set up here. I'll make sure it's done asap.

**Comment by sofietoft** [comment]
Hi @John-Blair !

Just wanted to let you know, that a redirect has now been created so the link in the blog post actually leads to the API Docs.
Sorry for the delay 😅 
Thanks again for reporting!
