### ISSUE TITLE
Meta Description

### ISSUE THREAD

**Issue by DKDouglasConsulting** [umbraco/UmbracoDocs#2092]
When adding the field for meta description to the master template nothing shows up

ORG template code:
`<meta name="description" content="">`
Result: `<meta name="description" content="">`

Template Code with Tag
`<meta name="description" content="@Model.Value("description")">`
Result:  `<meta name="description" >`

**Comment by nul800sebastiaan** [comment]
Hi there @DKDouglasConsulting, this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
