### ISSUE TITLE
Images section under templates is broken

### ISSUE THREAD

**Issue by hartvig** [umbraco/UmbracoDocs#210]
https://our.umbraco.org/documentation/Reference/Templating/images gives a 404

**Comment by hemraker** [comment]
[Related to this issue](http://issues.umbraco.org/issue/OUR-328)

**Comment by nul800sebastiaan** [comment]
Fixed!

**Comment by nul800sebastiaan** [comment]
https://github.com/umbraco/OurUmbraco/commit/75732e23b3fdd435b2b7cff02879f08f3769e502
