### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by prjseal** [umbraco/UmbracoDocs#2101]
The link at the bottom of the page for *Retrieving languages* is broken

**Comment by sofietoft** [comment]
Thanks for reporting this @prjseal 😄 

It's this article you're referring to, right?
https://our.umbraco.com/Documentation/Reference/Management/Services/LocalizationService/Retrieving-languages 
I've only been able to find one link there - [ILanguage](https://our.umbraco.com/apidocs/v7/csharp/api/Umbraco.Core.Models.ILanguage.html), is that the one you cannot access?
Could you perhaps provide a URL or exact location of this broken link? 😅

**Comment by prjseal** [comment]
Sorry @sofietoft 

The page I was on is this one https://our.umbraco.com/Documentation/Reference/Management/Services/LocalizationService/Index/

I pressed the report issue at the top of the page and it was late so i didn't notice that it just raises a new issue with no context.

**Comment by dampee** [comment]
Hi @prjseal 

How did you arrived on this page? 
This issue is the /index/ at the end of the URL.  If you remove the /Index/ the "samples" link at the bottom works.  

So the real issue is how you got the "/Index" in your first place.

**Comment by prjseal** [comment]
I think i googled it

**Comment by sofietoft** [comment]
Hm! Strange that this link was out there 🤔

I'll make sure that a rewrite is added for this! Thanks for reporting @prjseal

**Comment by sofietoft** [comment]
Rewrite setup 💪 
I'll close this one.

Thanks again for reporting, @prjseal ! 😄
