### ISSUE TITLE
Update all 'This section is waiting for content' pages 

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoDocs#211]
All of these pages need to point to an issue on this tracker and be filled in or removed and redirected

**Comment by marcemarc** [comment]
Remaining todo:

Trees.config
examineindex.config

and umm umbraco.library

**Comment by marcemarc** [comment]
@Shazwazza closing this issue, have searched through the repo and on 'our umbraco', and have targeted pages containing this placeholder text, a recent flurry of PRs means there are now no longer (or as far as I can see any pages) that contain this 'This section is waiting for content' text. So I'm closing this issue on the tracker. If we do happen to come across any more 'coming soon' items we can open specific issues to address them, but I can't find any!
