### ISSUE TITLE
Query code dosent work 

### ISSUE THREAD

**Issue by ohappaAdam** [umbraco/UmbracoDocs#2114]
Hi, I think that sample code for an query for searching in more than one field is not total accurate.

No dots before Or() statements.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Searching/Examine/examine-events.md***

**Comment by jmayntzhusen** [comment]
Hey @ohappaAdam 

You are absolutely right, would you be up for making the correction? 🙂

**Comment by ohappaAdam** [comment]
Here is the correct working code:

var textFields = new[] { "title", "description",  "content", .... };
var results = searcher.CreateQuery("content").GroupedOr(textFields, searchTerm).Execute();


Med vänliga hälsningar / Best Regards

Adam Nilsson
Webbutvecklare
+46 730 - 600 264
adam@ohappa.se<mailto:adam@ohappa.se>

ohappa
Sjötullsgatan 9
824 50 HUDIKSVALL
Sweden
+46 650 - 237 40
ohappa.se<http://ohappa.se/>
facebook.com/ohappa <https://facebook.com/ohappa>
twitter.com/ohappaofficial<https://twitter.com/ohappaofficial>
instagram.com/ohappa.se/<https://instagram.com/ohappa.se>
linkedin.com/company/ohappa<http://linkedin.ohappa.se/>

P.S. Tänk på miljön och undvik onödiga utskrifter.

Från: jmayntzhusen <notifications@github.com>
Skickat: den 27 november 2019 14:43
Till: umbraco/UmbracoDocs <UmbracoDocs@noreply.github.com>
Kopia: Adam Nilsson <Adam.Nilsson@ohappa.se>; Mention <mention@noreply.github.com>
Ämne: Re: [umbraco/UmbracoDocs] Query code dosent work (#2114)


Hey @ohappaAdam<https://github.com/ohappaAdam>

You are absolutely right, would you be up for making the correction? 🙂

**Comment by liamlaverty** [comment]
made a PR matching the emailed in code above https://github.com/umbraco/UmbracoDocs/pull/2117

**Comment by sofietoft** [comment]
PR was made with the correct code snippet 😄 

Thanks again for reporting this @ohappaAdam !
