### ISSUE TITLE
Umbraco v8 documentation missing...

### ISSUE THREAD

**Issue by mistyn8** [umbraco/UmbracoDocs#2125]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype.md***

https://github.com/umbraco/Umbraco.Forms.Issues/issues/186 has u8 equivalent with a promise to update, though using this script doesn't actually work..

https://github.com/umbraco/Umbraco.Forms.Issues/issues/251

Any help appreciated

**Comment by sofietoft** [comment]
Hi @mistyn8 ! Thanks for the report.

As I read your message here, the example in https://github.com/umbraco/Umbraco.Forms.Issues/issues/186 doesn't work for you - is that right? 

I'll make sure that our Forms developers are made aware that this part of our Forms section isn't correct for Umbraco 8 yet 💪

**Comment by mistyn8** [comment]
Yep that's correct, the update method errors as shown in umbraco/Umbraco.Forms.Issues#251

**Comment by sofietoft** [comment]
@mistyn8 - can see you've been chatting with our Forms expert on this.

How did it go? Did you manage to get it up and running? 😄

**Comment by sofietoft** [comment]
Hi @mistyn8 ! It's been a while since I've heard from you here, so I wanted to check in...

Did you manage to get the Forms workflow up and running? 😄

**Comment by sofietoft** [comment]
For reference: The guide on adding a workflowtype will be updated for Umbraco 8 in this PR: #2399 💪

**Comment by sofietoft** [comment]
The PR to update the article mentioned in this issue has been merged 💪 

That also mean that this issue can be closed for now!
Thanks again for reporting.
