### ISSUE TITLE
Load balancing - explicit front end server documentation missing

### ISSUE THREAD

**Issue by brichardson-insync** [umbraco/UmbracoDocs#2126]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
From the load balancing page - set your front-end(s) (non-admin server) to be explicit replica servers 

## Describe the issue
Recommended: set your front-end(s) (non-admin server) to be explicit replica servers which means they will never be used as the master scheduler

The link for setting front-end as explicit servers: https://our.umbraco.com/documentation/getting-started/setup/server-setup/load-balancing/TBC goes to a broke page.

**Comment by sofietoft** [comment]
Thanks for reporting this @brichardson-insync !

Sure looks like the correct links are missing there 🤔
I managed to track down the one on IServerRegistrar: https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/flexible-advanced

Regarding the replica - could this be the article you're looking for: https://our.umbraco.com/documentation/getting-started/setup/server-setup/load-balancing/file-system-replication ? 🤔

I'll run it by @Jeavon who wrote these docs, to make sure we get the correct links setup here!

**Comment by brichardson-insync** [comment]
Hi @sofietoft 

Apologies, this is my first time setting up Umbraco in a Load balanced environment. 

I believe the file replication is different from the configuration needed to stop front end servers providing the backoffice links.

**Comment by sofietoft** [comment]
@brichardson-insync - the links have now been updated, and links to the correct article! 😁
