### ISSUE TITLE
Verify and update Reference/Config for Umbraco 8

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#2127]
In Umbraco 8, a lot of the config files in /Config has been removed, and the configuration is now handled in code instead. More info here: #1817 

Below is a list of the current config files with article for Umbraco 7. We need to identify which are still present in Umbraco 8. And we need to link to replacement for each of the ones that has been removed, to pages that explains how the configuration now works in Umbraco 8.

- [x] [Config landing page](https://our.umbraco.com/documentation/Reference/Config/)
- [x] [web.config](https://our.umbraco.com/documentation/Reference/Config/webconfig/)
- [x] [404handlers](https://our.umbraco.com/documentation/Reference/Config/404handlers/)
- [x] [applications.config](https://our.umbraco.com/documentation/Reference/Config/applications/)
- [x] [Dashboards.config](https://our.umbraco.com/documentation/Reference/Config/dashboard/)
- [ ] [EmbeddedMedia.config](https://our.umbraco.com/documentation/Reference/Config/EmbeddedMedia/)
- [ ] [ExamineIndex.config](https://our.umbraco.com/documentation/Reference/Config/ExamineIndex/)
- [ ] [ExamineSettings.config](https://our.umbraco.com/documentation/Reference/Config/ExamineSettings/)
- [x] [fileSystemProviders.config](https://our.umbraco.com/documentation/Reference/Config/fileSystemProviders/)
- [ ] [BaseRestExtensions.config](https://our.umbraco.com/documentation/Reference/Config/BaseRestExtensions/)
- [x] [tinyMceConfig.config](https://our.umbraco.com/documentation/Reference/Config/tinyMceConfig/)
- [x] [trees.config](https://our.umbraco.com/documentation/Reference/Config/trees/)
- [ ] [umbracoSettings.config](https://our.umbraco.com/documentation/Reference/Config/umbracoSettings/)

Related issues: 
TinyMceConfig: https://github.com/umbraco/UmbracoDocs/issues/2095 
Applications Config: https://github.com/umbraco/UmbracoDocs/issues/1810
Dashboards: https://github.com/umbraco/UmbracoDocs/issues/1896
Examine settings: https://github.com/umbraco/UmbracoDocs/issues/1794

**Comment by poornimanayar** [comment]
@sofietoft I have created a PR for the config landing page #2163

**Comment by poornimanayar** [comment]
PR for `404handlers.config` in https://github.com/umbraco/UmbracoDocs/pull/2164

**Comment by poornimanayar** [comment]
PR for `dashboard.config` in https://github.com/umbraco/UmbracoDocs/pull/2165

**Comment by poornimanayar** [comment]
PR for `trees.config` in https://github.com/umbraco/UmbracoDocs/pull/2166

**Comment by marcemarc** [comment]
@poornimanayar There was some talk regarding these config pages that don't exist for V8 anymore that perhaps, we keep a holding page in their place for V8 that kind of says:

This configuration file no longer exists in Umbraco V8 - however you can find out how to configure this functionality via code during composition...

or similar

and then link through to the place in the documentation that explains the new way of configuring the functionality in V8 or create it, if perhaps it does not yet exist.

Whilst the config files don't exist in V8 they will be a 'starting point' for people migrating from V7, along the lines of 'eek where is the dashboard.config' file gone, and then they will look here to find out what happened...

what do you think?

**Comment by poornimanayar** [comment]
Sure can @marcemarc. I will pick them up :-)

**Comment by sofietoft** [comment]
Closing this issue, as the remaining articles on the list, are gone in Umbraco 8.

Thanks to all who's helped out 😄
