### ISSUE TITLE
Editor's Manual for Umbraco 8

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#2129]
The [Umbraco 7 Editor's Manual](https://our.umbraco.com/packages/website-utilities/umbraco-7-editors-manual/) has been converted and added to the Umbraco Docs:
https://our.umbraco.com/documentation/Tutorials/Editors-Manual/

This needs to be updated for Umbraco 8!
It's a pretty big section, so I've divided it into smaller bits:

- [ ] [Landing page](https://our.umbraco.com/documentation/Tutorials/Editors-Manual/) + [Introduction](https://our.umbraco.com/documentation/Tutorials/Editors-Manual/Introduction/)
- [x] [Getting Started with Umbraco](https://our.umbraco.com/documentation/Tutorials/Editors-Manual/Getting-Started-With-Umbraco/)
- [x] [Working with content](https://our.umbraco.com/documentation/Tutorials/Editors-Manual/Working-With-Content/)
- [ ] [Version Management](https://our.umbraco.com/documentation/Tutorials/Editors-Manual/Version-Management/)
- [ ] [Media Management](https://our.umbraco.com/documentation/Tutorials/Editors-Manual/Media-Management/)
- [ ] [Tips and Tricks](https://our.umbraco.com/documentation/Tutorials/Editors-Manual/Tips-and-Tricks/)

Think some of the sections are a bit too large? Let me know, and let's see if we can divide them into even smaller bits 😄 

We might also want to consider adding more sections, related to the new features in Umbraco 8:
* Language variants
* Infite editing
* Nested Content
* More?

**Comment by OwainWilliams** [comment]
Hey @sofietoft 
I'm happy to start on the Getting Started with Umbraco section and if anyone else wants to help with subsections in there then that would be great.  :)

**Comment by OwainWilliams** [comment]
@sofietoft  - How do I create a U8 version of the docs? Do I just need change the markdown?
to this?


---
versionFrom: 8.0.0
needsV8Update: "false"
---

**Comment by sofietoft** [comment]
Great question @sofietoft !

We have some docs on it here: https://our.umbraco.com/documentation/Contribute/#multi-version-documentation
Basically, what you'll need to do:
- Copy the current file
- Rename the current file to fx index-v7.md (replace "index" with the name of the file!) and remove the `needsV8Update` label
- The new copy should take the name of the original file, and have only this YAML tag: `versionFrom: 8.0.0`

I hope it makes sense! I know it can be a bit confusing this whole versioning system 🙈 
Take a look at these articles for reference: https://github.com/umbraco/UmbracoDocs/tree/master/Getting-Started/Setup/Requirements

**Comment by sofietoft** [comment]
Hi @OwainWilliams 

You still working on this?
I have a new guy here at Umbraco HQ, who I'm going to introduce to working with Docs.
I'm gonna use the "Editors Manual" section for this, so I wanted to check how far you've gotten?
Would be silly if we started working on the same stuff you're already working 😉

**Comment by OwainWilliams** [comment]
Hey @sofietoft  
I started over Christmas but only got as far as some screenshots. Sorry, had meant to give an update. 
Happy for the new person to take this on. I'm crazy busy at work unfortunately.

**Comment by sofietoft** [comment]
@OwainWilliams No worries at all! 😄 

We'll just start working on it from here.
Should some time clear up in your schedule, you're welcome to reach out and I'll tell you how far we've gotten (will of course try to update the list above as well 😁 )
