### ISSUE TITLE
Multiple documentation for v7.0.0

### ISSUE THREAD

**Issue by steroberts89** [umbraco/UmbracoDocs#2141]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
https://our.umbraco.com/documentation/extending/property-editors/value-converters

## Describe the issue
There are three articles for v7.0.0

**Comment by sofietoft** [comment]
Hi @steroberts89 
Thanks for reporting this 💪 

There's actually already a PR open regarding the Value Converters: https://github.com/umbraco/UmbracoDocs/pull/1865 😄 
It's currently under review with our developers here at Umbraco HQ. Hope to have it live soon!

**Comment by sofietoft** [comment]
Ah, shoot! Looks like I completely misunderstood what you reported here @steroberts89 
Sorry about that!

So, there actually isn't 3 versions for Umbraco 7 😅 I'm afraid what you're seeing, is a flaw in the way we've setup the version targeting.
![image](https://user-images.githubusercontent.com/24529086/70905239-ab59c800-2003-11ea-8838-8d013883f12f.png)

The link points to these two:
https://our.umbraco.com/Documentation/Extending/Property-Editors/value-converters-full-example-interface
and
https://our.umbraco.com/Documentation/Extending/Property-Editors/value-converters-full-example-attributes

As they both start with `value-converters` which is the name of the article you're currently on, it will show you that there are two more versions of the same - even though there isn't 🙈 

I've added a tasks to somehow get this fixed - renaming the two articles should do the trick!

**Comment by sofietoft** [comment]
This has been fixed with #2193 😄
