### ISSUE TITLE
Create dashboard.config documentation

### ISSUE THREAD

**Issue by hemraker** [umbraco/UmbracoDocs#215]
/Documentation/Reference/Config/dashboard/

**Comment by marcemarc** [comment]
see https://our.umbraco.org/documentation/Extending/Dashboards/ contains some explaination of the dashboards.config - but would make sense to have a separate document for each config file in the /reference/config section

**Comment by marcemarc** [comment]
Need to rejig this around so that the information added to Extending/Dashboards is actually in the reference/config/dashboard page, and the extending page is more of an introduction to customisation dashboards

**Comment by marcemarc** [comment]
Pull request here: https://github.com/umbraco/UmbracoDocs/pull/692

**Comment by marcemarc** [comment]
@hemraker I'm closing this issue now that the Umbraco Documenters have merged in the PR to rejig the dashboard configuration pages, but feel free to re-open this issue or create a new issue if you discover something else that should be covered...
