### ISSUE TITLE
Create ExamineIndex.config documentation

### ISSUE THREAD

**Issue by hemraker** [umbraco/UmbracoDocs#217]
/Documentation/Reference/Config/ExamineIndex/

**Comment by marcemarc** [comment]
PR: https://github.com/umbraco/UmbracoDocs/pull/730

**Comment by marcemarc** [comment]
@hemraker The PR #730 has been merged in, so closing this issue  but if you notice anything else you'd like to include that would improve this documentation feel free to open a new issue
