### ISSUE TITLE
Heartcore .NET core or .NET standard

### ISSUE THREAD

**Issue by DavidDeSloovere** [umbraco/UmbracoDocs#2183]
> "It is a library for .NET Core and is based on NetStandard 2.0. This means that it can be used on the most .Net frameworks, e.g. UWP, Xamarin.Android, Xamarin.Mac and Desktop .Net 4.6.1."

Is it a .NET core lib or a .NET standard lib? Looks like it's not a .NET Core only lib but documentation is unclear.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Umbraco-Heartcore/Client-Libraries/Dot-Net-Core/index.md***

**Comment by sitereactor** [comment]
Yes, I can see how that can be confusing. It's a .NET Standard library.

Ref. https://github.com/umbraco/Umbraco.Headless.Client.Net/blob/master/src/Umbraco.Headless.Client.Net/Umbraco.Headless.Client.Net.csproj

**Comment by DavidDeSloovere** [comment]
Will the documentation will be updated, so it won't confuse others? I understand why you would like to say ".NET Core" (but that will  go away with .NET 5 arriving this year).

**Comment by sofietoft** [comment]
@DavidDeSloovere , we will indeed update the docs! 😄 

We're already working on it in #2186

**Comment by sitereactor** [comment]
This is now merged, so closing the issue.

Thanks for reporting! We corrected both in the docs and on github for the client library.
