### ISSUE TITLE
Heartcore Content Filter response is inaccurate

### ISSUE THREAD

**Issue by NiclasLindqvist** [umbraco/UmbracoDocs#2185]
## What type of issue is it?
Wrong documentation

## What article/section is this about?
https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/Content-Delivery/content/#content-filter

## Describe the issue
Content Filter response seems to be from a Search request (hints given by `_links.self.href`)

**Comment by sitereactor** [comment]
Yes, this looks like the wrong response was copied in here. Thanks for reporting, we will get it updated.

**Comment by sitereactor** [comment]
This has been corrected, so just need @sofietoft to pull it into the OUR docs site 😄
