### ISSUE TITLE
Update needed for extending/Content-Apps/

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#2191]
## What type of issue is it?

Wrong documentation

## What article/section is this about?
https://our.umbraco.com/documentation/extending/Content-Apps/

## Describe the issue
Small issue in the code example below:  "Creating a Content App in C#" 

`if(content is IContent) `

Should be:

`if (source is IContent)`

**Comment by sofietoft** [comment]
Thanks for the report @erikjanwestendorp ! 😄 

I've checked your PR, and sent you a reply over there!
