### ISSUE TITLE
Unusable desktop layout on Windows Phone

### ISSUE THREAD

**Issue by jgettrup** [umbraco/UmbracoDocs#221]
When https://our.umbraco.org/documentation/ is viewed on a Windows Phone the desktop layout is shown instead of the responsive mobile layout. The desktop layout is unusable on a small screen because the meta viewport tag does not allow user scaling. Specifically, this issue is seen on a Nokia Lumia 710 running Windows Phone 7.8.

**Comment by hemraker** [comment]
Are you only experiencing this on the documentation pages or is it a general problem with when browsing  our.umbraco.org?

**Comment by jgettrup** [comment]
It's a general problem across our.umbraco.org, although other parts of the site cope a bit better. The home page, forum and download are fairly OK, mainly because they don't have a left hand nav, but none show the correct responsive mobile layout seen on the desktop when a browser window is shrunk down to phone size.

The main problems seem to be that the main menu is not collapsing, and the left hand nav is not "linearising" to the top of the page but is remaining on the left as a separate column.

I realise Windows Phone 7.8 is an edge case. I assume the site tested OK on Windows Phone 8.

**Comment by sofietoft** [comment]
Yo!

@hemraker, this is getting fairly old, and since it was already an edge case back in 2015, I'll close it down.

Hope it's okay! 😁 
-Sofie
