### ISSUE TITLE
How to about to contribute to Umbraco source code using GIT: example and images

### ISSUE THREAD

**Issue by biapar** [umbraco/UmbracoDocs#222]
How to about to contribute to Umbraco source code using GIT: example and images

**Comment by nul800sebastiaan** [comment]
It's on my list, a rough draft is here:
https://docs.google.com/document/d/17CMmioiFIBENoum7zcu77dzBqlN9tnxmpSJgU2tk_PI/edit?usp=sharing

**Comment by sofietoft** [comment]
Yo!
Do you have a status on this, @nul800sebastiaan ? 😁 

-Sofie

**Comment by sofietoft** [comment]
Contribution docs added: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/.github/CONTRIBUTING.md
