### ISSUE TITLE
Using Ioc, Reference - misleading

### ISSUE THREAD

**Issue by rustybox** [umbraco/UmbracoDocs#2223]
## What type of issue is it? (Choose one - delete the others)
Discussion

## What article/section is this about?
https://our.umbraco.com/documentation/reference/using-ioc/#accessing-lightinject-container

## Describe the issue
The example code cannot work, see https://github.com/umbraco/Umbraco-CMS/issues/7502

**Comment by sofietoft** [comment]
Thanks for the report @rustybox ! 💪 
I can see that one of my colleagues is already looking into this.

So, just for my understanding; the snippet in the article you're referring to - it doesn't work as intended? Is that correct?

**Comment by rustybox** [comment]
That is correct, it works with LightInject in general but it won’t work with Umbraco’s implementation of IAssemblyScanner.

**Comment by sofietoft** [comment]
Ah, I see 🤔 Thanks for explaining.

Let's see what Sebastiaan finds out, as we might get some valuable information to help us get this part of the docs updated correctly 💪

**Comment by rustybox** [comment]
It's quite upsetting that this ticket isn't resolved, and by resolved I don't mean by the pull request in the related ticket.

The docs are telling lies about what is possible and this wastes the time of everyone who reads them without spending a lot of time to discover that a workaround is required.

Surely whilst evaluating options to fix the underlying issue, the docs could be updated such that people are informed that the following will not work.

```csharp
var container = composition.Concrete as LightInject.ServiceContainer;
container.RegisterAssembly(typeof(IFoo).Assembly);
```

**Comment by sofietoft** [comment]
I completely understand your frustration! 
I just really need some input from my colleagues, in order to answer this and decide on what we're going to do here. I know that we have some people looking into this currently and we should get an answer soon.

**Comment by sofietoft** [comment]
Hi @rustybox ! We've decided to get rid of this section in the docs for now! Then we can always add it back in, should that become relevant. Sorry for taking so long to do so - sometimes it just takes a bit of extra coordinating.. 

I've already made a PR to remove it - it will be merged in a minute 😁 
Thanks again for bringing this to our attention 💪

**Comment by rustybox** [comment]
Interesting, I think maybe that's gone a bit too far, one can get access to the container to register via the LightInject API e.g.

```csharp
var container = composition.Concrete as LightInject.ServiceContainer;
container.Register<IFoo, Foo>();
```

it's just the following bit which is impossible at present and deserves attention
```csharp
// It's not currently possible to do the following without some workarounds
// see https://github.com/umbraco/Umbraco-CMS/issues/7502 for details
container.RegisterAssembly(typeof(IFoo).Assembly);
```

**Comment by sofietoft** [comment]
Ah, sure! 😅 I might have been a bit "trigger happy" there..

So, what do you say to putting this back in? 

> ### Accessing LightInject container
> Should you need to carry out more complicated registrations beyond the minimalist Umbraco DI implementation, you can access the underlying DI container via the `Concrete` property of the `composition`.
> ```csharp
> var container = composition.Concrete as LightInject.ServiceContainer;
> container.Register<IFoo, Foo>();
> ```
> [Visit the LightInject site to see what is possible](https://www.lightinject.net/)

**Comment by rustybox** [comment]
Sounds like a plan, I do think it's worth explicitly mentioned that RegisterAssembly won't work until a future release.

**Comment by sofietoft** [comment]
Got it!
I've taken a shot at it here: https://github.com/umbraco/UmbracoDocs/pull/2345
Could I get your review? 🤞

**Comment by rustybox** [comment]
Docs no longer confusing thanks :) closing!
