### ISSUE TITLE
Documentation needs adjusting for "Adding configuration to a property editor"

### ISSUE THREAD

**Issue by krugarmatt** [umbraco/UmbracoDocs#2228]
## What type of issue is it?
Wrong documentation

## What article/section is this about?
https://our.umbraco.com/documentation/Tutorials/Creating-a-Property-Editor/part-2#using-the-configuration

## Describe the issue
I'm progressing through this tutorial on a v8.5.2 Umbraco instance and noticed that there are a couple of issues with the very last section of the page titled **"Using the configuration"**.

1. A small thing but the very last paragraph reads: "Because we can also use the configuration directly in our HTML like here, where we use it to toggle the preview, using the ng-hide attribute" but the code sample below this paragraph is using **ng-show**.

2. After following every instruction on the page, I noticed that the "preview" that's shown under the markdown control when editing a document in the Umbraco admin, was still being displayed even though the \<div\> container was decorated with: **ng-show="model.config.preview"** and the "Preview" setting was disabled. After console logging **$scope.model.config.preview** in the Angular controller, the value is **"0"**. Below is a screenshot of the properties as shown in the backend of the Umbraco admin and what their current states look like during the execution of the Angular controller.

    ![property_editor_pre_values_output](https://user-images.githubusercontent.com/7726098/73277355-f14ca300-41e1-11ea-9896-6249365cdf02.png)

    So it looks like since the value of **$scope.model.config.preview** is a non-empty string, **ng-show** is resolving to a truthy value and therefore the preview panel is being shown even though the preview option is disabled.

**Comment by Adolfi** [comment]
Hi @krugarmatt.
I actually submitted a PR for this page, adjusting a bunch of small stuff to fit v8: https://github.com/umbraco/UmbracoDocs/pull/2212

I will look at these 2 issues and fix them in my ongoing PR. 
Thank you so much for submitting these!

Take care!

**Comment by krugarmatt** [comment]
No worries @Adolfi. Thanks for your help.

**Comment by Adolfi** [comment]
Maybe @sofietoft could assign this issue to me, so that others dont start working on this since this is already in-progress?

**Comment by sofietoft** [comment]
Thanks for the report @krugarmatt ! 😄 

As Dennis mentioned, he's already working on getting the Property Editor tutorial up to date for Umbraco 8 💪 

I'll assign the issue to him for now.

**Comment by Adolfi** [comment]
@krugarmatt found the issue with the preview not working. It was due to missing anglebrackets.

This does not work: 
`<div id="wmd-preview-{{model.alias}}" ng-show="model.config.preview" class="wmd-panel wmd-preview"></div>`

This works:
`<div id="wmd-preview-{{model.alias}}" ng-show="{{model.config.preview}}" class="wmd-panel wmd-preview"></div>`

**Comment by krugarmatt** [comment]
Hi @Adolfi. Thanks for looking into this. I can confirm that adding braces to the value of the **ng-show** attribute does resolve the issue.

**Comment by sofietoft** [comment]
Closing this one, as #2212 has been merged 🎉
