### ISSUE TITLE
Missing page? 

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#2245]
## What type of issue is it? 
Missing page? 

## What article/section is this about?
On the [main page](https://our.umbraco.com/Documentation/) is a link to _Umbraco 8 Documentation Statuspage_ 

## Describe the issue
The status page doesn't exist (anymore) or has been moved. I can't find a v8 status page so think it no longer exists? I think it is good to remove the link to the status page. 

![image](https://user-images.githubusercontent.com/7831614/73834130-7439b300-480b-11ea-9137-44d6d121f536.png)

**Comment by sofietoft** [comment]
Great catch @erikjanwestendorp ! 😄 👏 

I've merged the PR!
