### ISSUE TITLE
Update IPublishedContent Extension Methods

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#2289]
## What type of issue is it? 
Missing documentation/Wrong documentation

## What article/section is this about?
[IPublishedContent Extension Methods](https://our.umbraco.com/documentation/Reference/Querying/IPublishedContent/ExtensionMethods/).

## Describe the issue
The "list" is incomplete and the method no longer exists in v8. It would be nice if a v8 version of the page will be added. Besides that there are a lot more methods which could be added, see:
 
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/PublishedContentExtensions.cs

and 

https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/PublishedContentExtensions.cs

**Comment by nul800sebastiaan** [comment]
While we definitely could document all of them, they are also already listed in https://our.umbraco.com/apidocs/v8/csharp/api/Umbraco.Web.PublishedContentExtensions.html 

I'd hate to do "double bookkeeping", if anything ever changes it will get out of sync.. and the apidocs are automatically generated, so up to date.

I know there's plans for updating the automation but I'm not sure what that entails. I believe @jmayntzhusen knows more about that.

**Comment by erikjanwestendorp** [comment]
@nul800sebastiaan Ah okay, maybe it's an idea to update the [IPublishedContent ](https://our.umbraco.com/Documentation/Reference/Querying/IPublishedContent/)page so that extension methods links to the [apidocs](https://our.umbraco.com/apidocs/v8/csharp/api/Umbraco.Web.PublishedContentExtensions.html) page instead of the current page with only contains the .GetKey method with does not exist in v8?

**Comment by jmayntzhusen** [comment]
The new automation is still awaiting a new release from the programme we intend to user. I think for now removing the IPublishedContent Extension methods page from the documentation and replacing the links to it with links to the API docs makes most sense - especially as the page contains less actual info than the API docs.

Don't know if the docs team has any further thoughts on it though? @sofietoft

**Comment by sofietoft** [comment]
Thanks for reporting @erikjanwestendorp ! 💪 

I see your point about documenting all the extentions, but I also have to agree with my colleagues here. It would be "double bookkeeping" to have them documented both here and in the API docs 🤔 

I do like the idea of linking directly to the API docs instead.
So, make `Extension Methods` link to https://our.umbraco.com/apidocs/v8/csharp/api/Umbraco.Web.PublishedContentExtensions.html, like you suggest! 😁

**Comment by erikjanwestendorp** [comment]
Of course avoid "double bookkeeping" where possible :-) I created a PR
