### ISSUE TITLE
Documentation Incorrect for v8

### ISSUE THREAD

**Issue by JonathonCove** [umbraco/UmbracoDocs#2300]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Querying/UmbracoHelper/index.md***

When selecting the v8 documentation and viewing the section on `.TypedSearch()` , it suggests using `ExamineManager.Instance.CreateSearchCriteria()` , which is available in 7, but not 8.

**Comment by sofietoft** [comment]
Thanks for the report @JonathonCove ! Much appreciated.

Looks like we need to check up on that for sure.
Would you happen to know, what one would use instead in Umbraco 8? 😁

**Comment by JonathonCove** [comment]
No problem. 

I was hoping you could tell me! I know I can build a query in the folling way:
`if (ExamineManager.Instance.TryGetIndex("ExternalIndex", out var index)) {
        var searcher = index.GetSearcher();
        var query= searcher.CreateQuery();
    }`

But it does not have all the features of `ExamineManager.Instance.CreateSearchCriteria()`

**Comment by sofietoft** [comment]
Ah, I'm afraid I don't right off the top of my head 😅 

Let me just run it by the documentation team - they might be able to help us out here 🤞

**Comment by Jeavon** [comment]
These methods don't exist in v8 UmbracoHelper and should be removed from the docs. #2302

That aside, your code is the correct method to search using Examine v1 in Umbraco  v8. I would suggest you post on [our.umbraco.com](https://our.umbraco.com/) if you need any further advice.

**Comment by JonathonCove** [comment]
Thanks Jeavon
