### ISSUE TITLE
Incomplete example

### ISSUE THREAD

**Issue by JonathonCove** [umbraco/UmbracoDocs#2327]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype.md***

It is also necessary to create a theme file for the custom field within `/Views/Partials/Forms/Themes/default/FieldTypes/`

Using v8

**Comment by JonathonCove** [comment]
8.4.1

**Comment by sofietoft** [comment]
Hi @JonathonCove ! Thanks for the report 😄 

So, just to make sure I understand you correctly - you've found that an additional step needs to be added for Umbraco 8. Is that right?

You're more than welcome to add it to the article, if you'd like? 😁

**Comment by JonathonCove** [comment]
That is correct. 

I certainly can, it's a small change. Do you need me to make a pull request for it?

**Comment by sofietoft** [comment]
That would be awesome, yes! 😄 

We have some contribution guidelines here: https://our.umbraco.com/documentation/Contribute/
Also, does it make sense to make a new article for Umbraco 8 on this one? In case it does, we have some docs on how to set that up as well: https://our.umbraco.com/documentation/Contribute/#multi-version-documentation

**Comment by JonathonCove** [comment]
Thanks for the links Sofie. I've added a pull request here https://github.com/umbraco/UmbracoDocs/pull/2334 . Hope it's ok!

**Comment by sofietoft** [comment]
Hi! As #2334 has been merged, I'll close this issue as well 💪 

Thanks @JonathonCove , for putting in the work to help get the Docs upated 😄
