### ISSUE TITLE
Potential issues with the NotFoundHandlers example

### ISSUE THREAD

**Issue by JonathonCove** [umbraco/UmbracoDocs#2333]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Routing/Request-Pipeline/IContentFinder.md***

I found some issues with this example when trying it out on 8.4.1, changes are in a pull request here https://github.com/umbraco/UmbracoDocs/pull/2332

**Comment by sofietoft** [comment]
Thanks @JonathonCove !

I'll make sure we get the PR reviewed as soon as possible 💪

**Comment by sofietoft** [comment]
Looks like the PR for this one has already been reviewed and merged 💪 

I'll close this issue as well.
Thanks again for putting in the work to help get this updated @JonathonCove 🙌
