### ISSUE TITLE
broken link to tutorial-child-action#AccessingViewData

### ISSUE THREAD

**Issue by shannonmckenzie** [umbraco/UmbracoDocs#236]
https://our.umbraco.org/documentation/Reference/Mvc/forms/turorial-child-action#AccessingViewData

I found the link in this [post](https://our.umbraco.org/forum/developers/api-questions/41357-return-CurrentUmbracoPage-results-in-Error-loading-Partial-View-script#comment-151363)

**Comment by sofietoft** [comment]
Hi!
I know I'm a bit late to the party, but the correct link is: https://our.umbraco.org/documentation/Reference/Templating/Mvc/Forms/tutorial-child-action#accessing-viewdata

Thanks for reporting it! 😁 
-Sofie
