### ISSUE TITLE
Code documentation needed for isolating content app validation

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/UmbracoDocs#2361]
This issue has been updated from it's original description

# Updated issue

This issue is now an up-for-grabs task to update the code documentation for the `umb-isolate-form` directive in the core. [See this description for details.](https://github.com/umbraco/Umbraco-CMS/issues/7679#issuecomment-597388969)

# ORIGINAL issue

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.3

### Bug summary

When some content app (other than the Content content app) contains a field with a validation error it is impossible to Save/Publish the content.

See the bug in action below, where I added a content app called "Form App" which contains a single `input` field that is required:
![contentapp](https://user-images.githubusercontent.com/24297947/74665306-bb2a8f80-519f-11ea-963b-b49f6b18109d.gif)

Note: it seems in a multi-lingual situation an error is also shown to the user which I did not see when the content type is invariant:
![validation-errors](https://user-images.githubusercontent.com/24297947/74665425-fd53d100-519f-11ea-85fb-ab9ffc2f3093.png)

### Steps to reproduce

1. Add a content app with some `<input>` with an `ng-model`. For example, this can be your entire content app HTML to reproduce:
```html
<input type="text" name="name" ng-model="name" required  />
```
2. Try to save or publish the content.

### Expected result

The content will be saved/published regardless of some other content app's validation state.
I am not even trying to save the other content app's stuff, I am trying to save the actual content.

### Actual result

Save/Publish fails.

**Comment by nul800sebastiaan** [comment]
Issue moved to the Docs repo as an up for grabs! 👍

**Comment by PerplexDaniel** [comment]
Thanks for the info about `umb-isolate-form`. It seems this markup would allow me to save / publish content even with empty required fields:

```html
<ng-form umb-isolate-form>
    <input type="text" name="name" ng-model="name" required />
</ng-form>
```

However, it seems to work only with `<ng-form>` and not `<form>`. So if we want a real `<form>` in our content app this issue persists unfortunately. Also, pressing <kbd>ENTER</kbd> in the text field still seems to submit the parent form so will trigger the Save/Publish dialog.

**Comment by TomBruyneel** [comment]
I think there is still some strange behaviour with the umb-isolate-form directive. When the main form has a validation error, it will also trigger errors in the ng-form with umb-isolate-form directive. Furthermore, then fixing the validation errors in the main form and pressing save again will not work.

**Comment by sofietoft** [comment]
Thanks for the comment @TomBruyneel !

Just to I'm sure I understand correctly - the issue you ran into, turns out is related to some of your custom property editors?
Is that correct?
