### ISSUE TITLE
Incorrect razor snippet in Umbraco Forms documentation 

### ISSUE THREAD

**Issue by Aaen** [umbraco/UmbracoDocs#237]
There is some old DyamicNode, pre Umbraco 6.0.0 Razor exampe that needs to be updated.

https://our.umbraco.org/Documentation/Products/UmbracoForms/Developer/Working-With-Data/

**Comment by Aaen** [comment]
I have just created a pull-request for this one https://github.com/umbraco/UmbracoDocs/pull/238

**Comment by hemraker** [comment]
Fixed with 49c4cdc6dd6992359af8cc2688007db7211b2e30
