### ISSUE TITLE
AllPropertyData is missing on RecycleBinEventArgs

### ISSUE THREAD

**Issue by vondwater** [umbraco/UmbracoDocs#2370]
I'm trying to access AllPropertyData property on the RecycleBinEventArgs but this property is missing so I cannot access this property. Am I doing something wrong or is this a bug?

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Events/ContentService-Events.md***

**Comment by sofietoft** [comment]
Hi @vondwater ! Thanks for the report.

I'm not 100% sure I understand what you're trying to do here - would you mind sharing a bit more details?

**Comment by vondwater** [comment]
Hi @sofietoft , thanks for your reply.

I want to achieve that all media files for deleted content is also removed from the media folder. So when I empty the recycle bin I want to check the propertydata for each content and then remove the media files associated with it.
I was thinking to use AllPropertyData property for it, but this property is not visible.

Is there a better approach for this?

**Comment by sofietoft** [comment]
Ah, thanks for explaining.
I'll need to investigate a bit - will get back to you asap!

**Comment by Jeavon** [comment]
@vondwater Maybe you need to use the `ContentService.Deleted` or `ContentService.Deleting` events, these occur when the items are being removed from the recycle bin? 

AllPropertyData was removed from RecycleBinEventArgs quite some time ago, we will update the documentation accordingly

**Comment by vondwater** [comment]
I'll give that a try this evening @Jeavon Thanks for your reply

**Comment by vondwater** [comment]
@Jeavon  I tried to use the mentioned events but with no success. They are not triggered for some reason. Any other solution for my case?

**Comment by vondwater** [comment]
@Jeavon  The deleted event does the trick and returns all property for the removed content. Thanks!

**Comment by Jeavon** [comment]
@vondwater I have updated the info in the linked PR also
