### ISSUE TITLE
Will you be update to .net core?

### ISSUE THREAD

**Issue by IeuanWalker** [umbraco/UmbracoDocs#2378]
## What type of issue is it? (Choose one - delete the others)
Discussion

Just wondering if you'll be migrating this project to .net core, and if so what is the time frame?

**Comment by Jeavon** [comment]
@IeuanWalker there is indeed a project migrating to Umbraco to .NET Core and there was a status update just today https://umbraco.com/blog/status-of-migration-to-net-core/
