### ISSUE TITLE
Improve the old Back Office AngularJS docs

### ISSUE THREAD

**Issue by PeteDuncanson** [umbraco/UmbracoDocs#2382]
I've been having a play around with the docs found here https://our.umbraco.com/apidocs/v8/ui/#/api/index (via the instructions here https://github.com/umbraco/Umbraco-CMS/tree/v8/contrib/src/Umbraco.Web.UI.Docs).

A couple of things jumped out to me:

1. The template rendering this is super old, it mentions IE7
2. Its all in javascript so can't really be indexed which means its not findable by Google or developers who are stuck
3. Its totally separate from the other docs
4. Its not very well laid out or easy to navigate

For 1. I managed to find some docs on how to customise the template (via the grunt version of this tool which had more docs, tried it and it works even if undocumented on the gulp version https://www.npmjs.com/package/grunt-ngdocs#template) but that doesn't help with point 2. which lead me to think that this tool might be a dead end, no SEO. However it does parse the JS really well so I'm pondering if we can't use a bit of a hybrid approach to getting these docs into the existing documentation site (and indexed via the site search too) which would solve point 3. 

This ngdoc tool we have spits out a folder of includes in /api/partials/api which I think we can just include via razor or similar. So fore go the whole AngularJS driven index page and just do it in Razor with a few helper functions to render the navigation.

Once we crack that I think we can work on point 4 by creating more "sections" with the existing tools config which I think just spits the partials out into sub folders. I'm hoping then we can do something nicer with the navigation and grouping things together. I think this can be rather manually and quite fine grained as the files aren't changing much at the minute due to no one wanting to break anything :)

Finally I'd love to include more images in these docs to actually show you what the various components look like in the back office so you can find them by what you need/look like rather than by what they are called. Might need to store some more meta data in the files to achieve some of this but that should be fine and the PR's for that would be tiny.

**Comment by PeteDuncanson** [comment]
So I can see that the main docs site (https://our.umbraco.com/documentation/) runs off some magic Markdown and Examine powered thingy that I can't seem to find. This raises a few options:

- Can we get the ngdoc tool to split out Markdown instead of HTML (something like https://github.com/domchristie/turndown)?
- All the other docs are checked in, do we want these autogenerated docs checked in too? I think maybe we do but I'm not sure how to automatically do that. I'm thinking that might be a github action or something that could be hooked up by smarter people than me (Warren sprints to mind). So when a commit goes into one of the main branches it builds the docs and tries to commit the files into the Docs repos (it should only commit changes right) or something like that. I believe that this way they will get indexed too into Examine so full site search will work out of the box?

Alternatively we can keep them separate and link off to them as we do now but tidy them up. I think it would be worth the effort to get them in properly though if we can. Even if the docs only get committed in every release worst case.

**Comment by PeteDuncanson** [comment]
Oooooh how about adding source links to the docs so you can link directly to the file on github! That would be sweet! https://www.npmjs.com/package/grunt-ngdocs#sourcelink

I've had an idea to do something similar with the templates for ages this might be a nice way to get both maybe (https://github.com/umbraco/Umbraco-CMS/issues/5047), if we are adding it for one might as well do the other.

**Comment by sofietoft** [comment]
Hi @PeteDuncanson ! 😄 

Thanks for sharing your thoughts on this topic. You have some really great and interesting points, and I agree! It would be awesome to include documentation on the UI part on Our! 
@abjerner is already working on something that will add a lot of these docs to the manual part on Our: https://github.com/umbraco/UmbracoDocs/issues/2045 - I'm sure those will be a great improvement for now.

We should also keep this in mind: https://our.umbraco.com/Documentation/Development-Guidelines/breaking-changes#javascript - so, we shouldn't make it harder for our developers to make small improvements here and there 🙈 

Sounds like have some solid ideas on how we could pull the auto-generated docs into Our - I'm afraid I don't know enough about Our to give you a qualified answer as to what's possible. Also,  implementing docs like these, should hopefully become MUCH easier in the future, as we're looking into other platforms for the Documentation 🤞

I'll bring this topic up on one of our meeting in the Docs team as well. I'm sure they'd have some great input to this!

**Comment by TimGeyssens** [comment]
If I remember correct, the docs are powered by a webhook coming from Github https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Documentation/Controllers/DocfxController.cs  so it actually downloads the mardown file coming from GitHub into ~/App_Data/Documentation then with a contentfinder a url is mapped agains the file on filesystem https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Documentation/DocumentationContentFinder.cs not sure if all these files are still in use but it appears that some had updates on the past months https://github.com/umbraco/OurUmbraco/tree/master/OurUmbraco/Documentation to get search running it is put in a custom index https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Our/Examine/DocumentationIndexDataService.cs and the search on our just looks in different indexes....

**Comment by TimGeyssens** [comment]
So to first get the js docs to render some markdown or html in a structured manner, then you'll need to update https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Documentation/DocumentationUpdater.cs and if it's downloaded in a well strucured manner to the folder structure I guess it should just work without even having to update https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Our/Examine/DocumentationIndexDataService.cs

**Comment by PeteDuncanson** [comment]
Thanks @sofietoft, lots of good info in that reply. Appreciated :)

From what I've read there is no alternative to regenerate the back office docs currently or in the near future (DocFX for instance) so its "up for grabs" I think.

I had a quick play around this morning with the converting to Markdown idea but quickly bailed on that being a good idea as all the tooling is way out of date. It might work but I think the time is better spent coming up with a better longer term soution.

After some researching I found TSDoc () which seems to be very promising. Its Microsoft owned/backed and is a generic "one parser to rule them all!" solution that you can add to. Its build for TypeScript so if we move that way in the future (as some of us predict/hope) then it will already be able to handle that. Plus there is a DocFX setup in the works which might make this a perfect fit long term. 

There is however no AngularJS config for it as yet so looks like I might have to make one. Learning from the exisign ngdoc stuff though I was looking through this morning I think that shouldn't be too difficult to port the regex etc that it uses to get it to pick up on the AngularJS flavour of JSDoc.

I'll have a play around with that some more and see what I can come up with.

Thanks to your link to "what a breaking change is" I was very excited to see that moving directives etc around is ok which might make getting the docs in a sane/logical groupings easier :)

**Comment by sofietoft** [comment]
Sounds like you're putting a lot of effort into this - that's just wonderful @PeteDuncanson ! 😄 

I look forward to see what comes out of this 💪

**Comment by PeteDuncanson** [comment]
I believe that DocFX is the HQ's choice of documentation going forward for the whole project as a result ideally anything we use for documenting the front-end should be compatible with DocFX. TSDoc is meant to work with DocFX but I can find no mention of it so I've created an issue on the DocFX github project to see what the state of play is https://github.com/dotnet/docfx/issues/5749

**Comment by enkelmedia** [comment]
I’ve also also been missing example images, specially on directives. 

As far as I understand this should be supported? 

Is this something that would be considered for a PR? I’m willing to contribute with some images, I was thinking that I would create a blogpost or a dedicated repository somewhere but if HQ would like I could do the work in the official documentation?

Cheers!

**Comment by sofietoft** [comment]
Hi @enkelmedia - thanks for the input.

I'm not enirely sure I understand what you mean by images in this context - could you elaborate a bit on that?

Also, work on adding some Angular docs to Our has already begun.
Checkout the section here: https://our.umbraco.com/documentation/Reference/Angular/

@abjerner has also created a set of Issues where we can keep track of which docs we still need to move into Our:

* Services: https://github.com/umbraco/UmbracoDocs/issues/2654
* Directives: https://github.com/umbraco/UmbracoDocs/issues/2653

**Comment by sofietoft** [comment]
Hi all,

I'm closing this issue for now.
Please instead refer to the two issues mentioned in this comment: https://github.com/umbraco/UmbracoDocs/issues/2382#issuecomment-683611091
