### ISSUE TITLE
Last example on the page is rendering the HTML instead of displaying the code

### ISSUE THREAD

**Issue by robertjf** [umbraco/UmbracoDocs#2405]
See the attached issue for details:

![image](https://user-images.githubusercontent.com/818101/77722036-51bc5d00-7038-11ea-96f0-916b8a2d3057.png)

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Routing/surface-controllers.md***

**Comment by sofietoft** [comment]
Great catch @robertjf ! 🙈 

I've updated the code snippet now - it's declared as HTML and no longer renders the HTML!
https://our.umbraco.com/documentation/Reference/Routing/surface-controllers#protecting-surface-controller-routes 

Thanks for pointing it out 💪
