### ISSUE TITLE
Can't view documentation for V7 Rest Api

### ISSUE THREAD

**Issue by deanjpearson** [umbraco/UmbracoDocs#2409]
Can't view the documentation for the Rest API for v7 of Umbraco. Is this available or stored anywhere?

This is the page with issues: https://our.umbraco.com/documentation/implementation/Rest-Api/

**Comment by nul800sebastiaan** [comment]
Here's the change that obsoleted the old docs, you can see what was there before the change on the left side: https://github.com/umbraco/UmbracoDocs/commit/89f2b4f6c50e60fd6815455374b029f342b5fa55#diff-dbba25a6a613b3653e61d4328628dc5b

Note that this is no longer supported.
