### ISSUE TITLE
Version filter not showing

### ISSUE THREAD

**Issue by NikRimington** [umbraco/UmbracoDocs#2435]
Hi, 

I think there is a problem with version filtering in the Doc's site. Not sure how wide spread it is, but this page should have a version filter on it as there is a index-v7.md file as well.
https://our.umbraco.com/documentation/Implementation/Custom-Routing/

***This is the page(s) with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Implementation/Custom-Routing/index.md
 https://github.com/umbraco/UmbracoDocs/blob/master/Implementation/Custom-Routing/index-v7.md***

**Comment by sofietoft** [comment]
Thanks for the report @NikRimington !
Something strange is going on here, and it looks like it's something general - the versioning box is completely gone from the site it looks like 🤔
Will need to investigate some more, in order to figure out what's happening! 💪

**Comment by NikRimington** [comment]
No problem, it's not completely gone as it's working in some places such as here https://our.umbraco.com/documentation/Extending/FileSystemProviders/

**Comment by sofietoft** [comment]
Oh! That's even more interesting 🤔
I've been through several articles, and all I could find were missing the box even though they should have it!

**Comment by sofietoft** [comment]
Hi @NikRimington !

We found the issue - or Jesper did 😉 
Seemed that a PR for some YAML tags with errors in the syntax had gotten merged, and messed up the entire Docs index on Our.
All fixed up now, and the search (which was also broken) and the version boxes are working again 🎉 

Thanks again for reporting it!
