### ISSUE TITLE
This page needs to be updated for v8

### ISSUE THREAD

**Issue by VijayBhatter** [umbraco/UmbracoDocs#2448]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Config/tinyMceConfig/index.md***

**Comment by sofietoft** [comment]
Thanks for reporting @VijayBhatter !

This has actually already been reported previously: https://github.com/umbraco/UmbracoDocs/issues/2095

Would you be up for taking a shot at updating the article? 😄

**Comment by sofietoft** [comment]
Hi @VijayBhatter !

The TinyMCE article has been updated for Umbraco 8 - you can find it here: https://our.umbraco.com/documentation/reference/config/tinymceconfig/

I'll consider this one closed for now.
Do let me know if something else come up - and thanks again for reporting!
