### ISSUE TITLE
Surface Controller Actions: Add more details about use cases

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/UmbracoDocs#2449]
Hi,

I don't think there is any documentation for surface controller actions at the moment. Is it worth adding that? I am happy to pick this up myself.

Poornima

**Comment by sofietoft** [comment]
Thanks for adding this issue @poornimanayar ! 😄 

I've added the `idea` label 💪

**Comment by marcemarc** [comment]
Hi @poornimanayar 

It's super great to get a page dedicated to these options, as it often confuses people over what to return when, when using a SurfaceController for the first time.

That said, would it be possible to be clearer, when each of these would be used - for example the first two, that mention CurrentUmbracoPage and RedirectToCurrentUmbracoPage have the exactly the same example... and do not say that using CurrentUmbracoPage keeps the Modelstate in tact, and RedirectToCurrentUmbracoPage clears the Modelstate... 

I think updating these examples to have those explanations would be really useful - or perhaps combining into one example with comments in the code, explaining that there is a validation error with the form, ModelState is invalid, so returning CurrentUmbracoPage keeps the values already entered by the user...? - whereas if the form is correct RedirectToCurrentUmbracoPage will clear the modelstate... and you can use the Temp directory to display a 'Form Sumitted' message.

regards

Marc

**Comment by sofietoft** [comment]
Hi all!
Just letting you know I've added some labels to this one.
Would be could to have some more details added to the [Surface Controller Actions article](https://our.umbraco.com/documentation/reference/routing/surface-controllers-actions), as per @marcemarc s comments.

Will update the title as well, to reflect that!
Thanks!
