### ISSUE TITLE
Courier Architecture links

### ISSUE THREAD

**Issue by Aaen** [umbraco/UmbracoDocs#245]
All links under https://our.umbraco.org/documentation/Add-ons/UmbracoCourier/Architecture/Index/ is broken.

**Comment by nul800sebastiaan** [comment]
How did you get to the link above @Aaen ? If you remove `/Index/` it all works, just curious how you got here.

The fix would be to automatically redirect anyone from `/Index` and `/Index/` to `/`

**Comment by hemraker** [comment]
There was a link to `Architecture/Index.md` which when parsed became `Architecture/Index/`.
