### ISSUE TITLE
Reordering the content tree on the left hand side

### ISSUE THREAD

**Issue by OwainWilliams** [umbraco/UmbracoDocs#2455]
## What type of issue is it? (Choose one - delete the others)
Other: 

Is there a way of reordering the content tree on the left hand side of each page or is this within the CMS?

## What article/section is this about?

https://our.umbraco.com/documentation/Umbraco-Heartcore/

## Describe the issue

I think the left hand side should read in this order: 

* Getting Started
* API Documentation
* Client Libraries
* Versions and Updates

It makes sense for Getting Started to be the first in the list but I don't think this can be reordered via Github. If it can be reordered, then I would make the content on the right hand hand side match.

**Comment by jmayntzhusen** [comment]
You can do it by adding them in the right order in this switch statement - a bit low tech, but you should get the idea 😁
https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Documentation/DocumentationUpdater.cs#L225

Will leave it up to the docs team to verify the proposed ordering.

**Comment by sofietoft** [comment]
Jesper beat me to it 😉 

I think the order you propose is great - let's go with that! 😁

**Comment by OwainWilliams** [comment]
Great! Thanks both. I'll make the update.
