### ISSUE TITLE
<XmlCacheEnabled>True</XmlCacheEnabled>

### ISSUE THREAD

**Issue by sarathsju** [umbraco/UmbracoDocs#2459]
when i am trying to add  
`<XmlCacheEnabled>True</XmlCacheEnabled> `
configuration in umbracosettings.config file i am getting nullponterexception in umbraco 8+
![image](https://user-images.githubusercontent.com/43876240/79952745-8c70b400-8483-11ea-8792-590da4a82fc1.png)

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Config/umbracoSettings/index.md***

**Comment by sofietoft** [comment]
Thanks for the report @sarathsju !

I'm afraid the article about the umbracoSettings that you're referring to, hasn't yet been updating for Umbraco 8 - the setting might look different in Umbraco 8, than what's described in the article you're looking at, as that's for Umbraco 7.

I'll what I can do about getting you the information you need here, to do this correctly in Umbraco 8.

**Comment by sofietoft** [comment]
Hi @sarathsju !
Apoogies for the delay on this one.

I've now had some time to investigate this issue you're having.
In Umbraco 8 there no longer is an XML cache, which also means that the setting you're trying to use is no longer available.

If you're continuing to struggle with this, I'd suggest that you head over to the [Forums](https://our.umbraco.com/forum/) - I'm sure someone will be able to help you acheive what you're trying to do 💪

**Comment by sofietoft** [comment]
I'll close this one for, as we already have an issue reporting that the umbracoSettings.config article needs to be updated for Umbraco 8 - #2127 .
