### ISSUE TITLE
Doc: Migrating an Existing Site to Umbraco Cloud is not up-to-date

### ISSUE THREAD

**Issue by stefankip** [umbraco/UmbracoDocs#2500]
I think the Migrating an Existing Site to Umbraco Cloud docs isn't up-to-date.
For example, the `umbraco.config` file is gone, I am unable to delete the media types `File`, `Folder` and `Image` in Umbraco v8, there is no `/Config/dashboard.config` file anymore and I'm unable to locate the `installed` marker in `App_Plugins/UmbracoForms`.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md***

**Comment by sofietoft** [comment]
Thanks for reporting this @stefankip !

Sure sounds like we need to get that article updated.
I'll make sure we take a look at the things you've pointed out, and make sure that the article in general does what it needs to.

Did you manage to complete the migration despite the guide being a bit out of date? 🤞

**Comment by stefankip** [comment]
Sure thing, it's running on cloud as we speak :-)
Just had to combine this article with the following article: https://our.umbraco.com/documentation/Umbraco-Cloud/set-up/Working-With-Visual-Studio/
Because I already had a repo with a Core, Web and Models project.
So now the Web repo is located inside the source repo, like that doc explains.

**Comment by sofietoft** [comment]
Sounds great @stefankip ! 💪 Wonderful to hear that you managed to complete the task.

I've added the "needs-investigation" label to this issue, and will make sure to get around to it as soon as possible!
Thanks again for reporting 😄 Much appreciated.

**Comment by sofietoft** [comment]
Hi @stefankip !

Thanks again for reporting the out-of-date article.
I've now run through the guide and updated it where needed according to Umbraco 8 projects 💪

I'll close this issue for now.

**Comment by stefankip** [comment]
> Open the **Media** types folder
> Delete **Member**

;-)

**Comment by sofietoft** [comment]
Ah, good catch 😄 
It's been updated now 💪
