### ISSUE TITLE
Document language files for packages

### ISSUE THREAD

**Issue by hemraker** [umbraco/UmbracoDocs#253]

**Comment by hemraker** [comment]
Closed with 37a53d671511c328854e45bbe57a9dec7b6a6790

**Comment by Shazwazza** [comment]
Docs are still missing from this. The PR didn't include the ability to customize the distributed Core language files without modifying the Core files... this is a new feature in 7.3 as well. I'll re-open

**Comment by perploug** [comment]
I kept it out of this as it does not apply to packages IMO

**Comment by Shazwazza** [comment]
Ahh! :) yes fair point, i didn't read the title. @hemraker can we create another docs task for that ?
