### ISSUE TITLE
Missing documentation Creating Forms Based on Datasources

### ISSUE THREAD

**Issue by Lachlann** [umbraco/UmbracoDocs#254]
as found here:
https://our.umbraco.org/Documentation/Add-ons/UmbracoForms/Editor/Creating-Forms-Based-on-Datasources

**Comment by sofietoft** [comment]
See: https://github.com/umbraco/UmbracoDocs/issues/281

**Comment by marcemarc** [comment]
The missing page is how to autogenerate an Umbraco form from an external Data Source, there is documentation for contour here; https://our.umbraco.org/projects/umbraco-pro/contour/documentation/Editor/Creating-Forms-Based-on-Datasources/ it probably works in the same way, need to check and update screenshots...

**Comment by jmayntzhusen** [comment]
Hi there!

As this issue has been here for over a year without any PRs, we have decided to close it down. 
If you feel the problem is still there, then please open a new issue with as many details as you can so someone has a chance to work on it!

Thanks for reporting it in the first place! 🙂
