### ISSUE TITLE
Add descriptions to the latch statuses so it is clear what they mean

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/UmbracoDocs#2540]
The statusses are mentioned in a list on this page. Today I had the status NoRedirects and that sounded perfect to me.

What the status actually meant was a missing negate rule.

If you could add a description and a possible solution to every status that would help me not to bother support and solve it myself. win-win.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Umbraco-Cloud/Set-Up/Umbraco-Latch/index.md***

**Comment by RyuLindow** [comment]
@sofietoft 

I think that we can close this one, no?

**Comment by jonat123** [comment]
@RyuLindow  yes I agree 🙂

I'll close this issue as we have moved over to a new certificate issuer on Umbraco Cloud and Umbraco latch and the following article have been deprecated 🙂
