### ISSUE TITLE
how can you make sure referenced projects (Core and Models) are always build in release mode when you push changes to the cloud web repo?

### ISSUE THREAD

**Issue by PeteDuncanson** [umbraco/UmbracoDocs#2544]
Not an issue I've had but one that popped up on twitter and had a solution thats on Shannons blog rather than in the offfical docs:

https://twitter.com/dawoe21/status/1271441518029606913

**Comment by sofietoft** [comment]
Thanks for reporting this @PeteDuncanson !

We do already have one solution for [working with Visual Studio and Cloud](https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/) - would be great with more examples, like the one Shannon's made 💪 

I'll look into it as soon as possible.
