### ISSUE TITLE
Example of rewrite rule is inversed

### ISSUE THREAD

**Issue by TechInfoQc** [umbraco/UmbracoDocs#2553]
With this rule, when the pattern is matched the request will be aborded, so it should be negate="true" in the rule. So when the pattern doesn't match = abord.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Security/Security-hardening/index.md***

<rule name="Allowed IPs" stopProcessing="true">
    <match url="^(?:app_plugins|config|umbraco)(?:/|$)" />
    <conditions>
        <add input="{REMOTE_ADDR}" negate="false" pattern="213.3.10.8|88.4.43.108" />
    </conditions>
    <action type="AbortRequest" />
</rule>

**Comment by sofietoft** [comment]
Thanks for the report! 💪 

I'll make sure to run this through our security experts as soon as possible!

**Comment by sofietoft** [comment]
Apologies for the delay here!

I've had this by our security people, and you are of course correct 😄 
Would you be up for updating the article with the change?

**Comment by TechInfoQc** [comment]
I've changed both, thanks
