### ISSUE TITLE
Document dynamic macro params

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/UmbracoDocs#258]
Doctype value: `[#bodyText]`
Recursive doctype value `[$headerTitle]`
Request value `[@productId]`
Session value `[%memberId]`

**Comment by Shazwazza** [comment]
Is this missing docs ?

**Comment by nul800sebastiaan** [comment]
yes

**Comment by Shazwazza** [comment]
:+1:

**Comment by hemraker** [comment]
Should you be assigned to this @nul800sebastiaan ?

**Comment by sofietoft** [comment]
Yo, @nul800sebastiaan,
Couldn't find anything about dynamic macro params in the Docs, so I suppose this is still missing, yeah?

-Sofie

**Comment by marcemarc** [comment]
@sofietoft @nul800sebastiaan ahhh the secrets of the Dynamic Macro Parameter syntax... I've added some details here: https://github.com/umbraco/UmbracoDocs/pull/613

**Comment by marcemarc** [comment]
@nul800sebastiaan @sofietoft @Shazwazza @hemraker  The documentation curators have merged this PR into the docs, so I'm closing this issue, feel free to open it again, if you spot something awry with the information on dynamic macro parameters...
