### ISSUE TITLE
order of the environments in project-components.png

### ISSUE THREAD

**Issue by peaxe** [umbraco/UmbracoDocs#2581]
Hi.
I want to start to say that the documentation is really great. So my friendly suggestion is not pointing out an error, it is based on this one:

> You want to discuss possible improvements or ways to deal with a specific thing in the documentation

Would it be possible to change the order of environments in the image "images/project-components.png" so the environments are presented from left to right: Development, Staging, Live

(As that is how the environments are usually seen in the Backoffice.)

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Umbraco-Cloud/Getting-Started/Project-Overview/index.md***

**Comment by sofietoft** [comment]
Hi @peaxe !

Thanks for the feedback.
I completely agree that it would be cool to have the environments listed in the proper order on the image.
I'll see if I can make that happen as soon as possible 👏

**Comment by sofietoft** [comment]
The image [has now been updated](https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/Project-Overview/) 😄 

I'll go ahead and close this one.
Thanks again for reporting the issue 🎉
