### ISSUE TITLE
SMTP-settings Umbraco Forms doesn't mention the notification setting

### ISSUE THREAD

**Issue by EM-Benji** [umbraco/UmbracoDocs#2588]
## What type of issue is it? (Choose one - delete the others)

Missing documentation

## What article/section is this about?
https://our.umbraco.com/documentation/Umbraco-Cloud/set-up/SMTP-settings/

## Describe the issue
In the Umbraco Forms section, it should mention that the email address value needs changing from your@email.here to the value of the from attribute as mention in https://our.umbraco.com/documentation/reference/config/umbracosettings/#notifications (which is marked as 7.0.0 + (current) )

**Comment by sofietoft** [comment]
Thanks for reporting @EM-Benji !

It is as far as I know it should not be necessary to change the "sender email" value in the notifications section in umbracoSettings.config - as that has to do with notifications and not Umbraco Forms as such 🤔 Have you had any issues with this not being set?

The article you reference here doesn't really mention the notifications part - perhaps it would be a good idea if it did!

**Comment by EM-Benji** [comment]
Yeah i didn't think it needed it too but this morning i was trying to setup smtp so forms would email when a entry is sent and after getting "Mailbox unavailable. The server response was: Verification failed for <your@email.here>" in the logs. I found that notification page in the forum., made the change on a hope and it worked.

**Comment by sofietoft** [comment]
Aha! That's interesting. Thanks for explaining! I'll run some tests on the latest versions.

So, regarding the SMTP article here - perhaps we could add the mention of the sender email value in a `note` or something 🤔

**Comment by EM-Benji** [comment]
No problem. Yeah that was my thinking just a simple note

**Comment by sofietoft** [comment]
Hi @EM-Benji !
For some reason, I cannot reproduce this issue you've been running into 🤷‍♀️

In any case, I've added a note the article like we discussed: https://our.umbraco.com/Documentation/Umbraco-Cloud/Set-Up/SMTP-settings/#umbraco-forms 

Thanks again for reporting!
I'll consider this one closed for now - please feel free to reopen it, if you feel it hasn't been resolved.
Have a great day!
