### ISSUE TITLE
Broken images in v8 Getting Started > Code > Source Control page

### ISSUE THREAD

**Issue by tommy-elliott-awh** [umbraco/UmbracoDocs#2593]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/Code/Source-Control/index.md***

The image at the end of the "What folders and files should I exclude from my source control repository?" section ( https://our.umbraco.com/documentation/getting-started/Code/Source-Control/images/v8-files_PNG ), and the image at the start of the "App_Data Folders" section ( https://our.umbraco.com/documentation/getting-started/Code/Source-Control/images/v8-app-data_PNG ) both are broken images.

**Comment by nul800sebastiaan** [comment]
Thanks @tommy-elliott-awh - I think the `.PNG` in capitals was parsed wrong.. all good now, I've renamed the image files. Thanks again!
