### ISSUE TITLE
Umbraco Forms: Update Email Templates for v8

### ISSUE THREAD

**Issue by thenexus00** [umbraco/UmbracoDocs#2594]
Isnt - Umbraco.TypedContent for example now Umbraco.Content - These should be updated on the V8 page.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Add-ons/UmbracoForms/Developer/Email-Templates/index.md***

**Comment by nul800sebastiaan** [comment]
Looks like this page is not yet ready for v8, indeed. We'll put it on our list of ideas to update this when we get a chance, thanks!
