### ISSUE TITLE
Examine documentation concerning IScopeProvider and Create

### ISSUE THREAD

**Issue by JeremiahProworks** [umbraco/UmbracoDocs#2597]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation (as far as I can tell)

## What article/section is this about?
https://our.umbraco.com/documentation/reference/searching/examine/examine-events

## Describe the issue

The documentation for v8 indicates that this should be used:

`using(var scope = _scopeProvider.Create(autocomplete: true))`

As far as I can tell this is the correct code:

`using (var scope = _scopeProvider.CreateScope(autoComplete: true))`

autoComplete appears to have a capital C. 

Perhaps this has changed with the latest Umbraco v8.

**Comment by marcemarc** [comment]
@JeremiahProworks Thanks for raising this!, we literally just pulled in an update to this page in the docs to add the information about scope,  will double double check, but I think you are right!
