### ISSUE TITLE
Broken documentation link for MemberService-Events

### ISSUE THREAD

**Issue by stodolos** [umbraco/UmbracoDocs#2598]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
MemberService-Events

## Describe the issue
https://our.umbraco.com/documentation/reference/events/MemberService-Events
"Oooops, something broke"

**Comment by marcemarc** [comment]
Thanks @stodolos for reporting this, I'm not quite sure what is immediately breaking this page, but we'll investigate further. In the meantime, if you wanted to see the information regarding MemberService Events - you can find them here in the markdown source files: https://github.com/umbraco/UmbracoDocs/blob/master/Reference/Events/MemberService-Events/MemberService-Events.md

**Comment by jmayntzhusen** [comment]
@marcemarc Pretty sure it is because the link he is going to doesn't have a corresponding index file, he'd have to go to https://our.umbraco.com/documentation/reference/events/MemberService-Events/MemberService-Events.md (Our will strip the .md) to find the file. Should probably just rename the file to index.md then it will work 🙂

**Comment by sofietoft** [comment]
Hi all!

I've had a look at this, and it looks like all that needs to be done is, that the `MemberService-Events.md` file be renamed to `index.md` - that should make https://our.umbraco.com/documentation/reference/events/MemberService-Events link correctly to the article.

See this PR: #2622

**Comment by sofietoft** [comment]
I've just merged in a fix to this one - the link now works as expected: https://our.umbraco.com/documentation/reference/events/MemberService-Events/

I'll close this issue.
Thanks again for reporting @stodolos 😄
