### ISSUE TITLE
Examples for setting different Property Editor Data Programatically

### ISSUE THREAD

**Issue by marcemarc** [umbraco/UmbracoDocs#2603]
## What type of issue is it? (Choose one - delete the others)

Missing documentation

## What article/section is this about?
Built in Property Editors:
https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/

## Describe the issue
It seems a common recurring theme in the Umbraco Forms, particularly as people try to migrate content to V8, of how to 'set' values using the ContentService for more complex Property Editors.

For example NestedContent, stores the data as JSON, but it's quite easy to create this if you know the trick of creating a Dictionary<string, string> object and add your values to that and then convert to JSON... and that trick is explained in lots of places in the forum or on the web, but it would be good to be at the bottom of the NestedContent page in the 'Built in Property Editors Section'

Similarly setting the Multi Url Picker

Possibly even the grid!

But in general it would be a nice aim to have a section on each of the pages that describe the core property editor, explaining how to set it via the ContentService

**Comment by marcemarc** [comment]
Thanks Marc, we'll have a think about that and get back to you.

**Comment by sofietoft** [comment]
As I've created a new Issue (https://github.com/umbraco/UmbracoDocs/issues/2714) where I'm listing all the properties, I'll go ahead and close this one for now.

Hope that's OK!
