### ISSUE TITLE
Issue with Articles Tutorial

### ISSUE THREAD

**Issue by thejokerd3** [umbraco/UmbracoDocs#2639]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
https://our.umbraco.com/documentation/Tutorials/Creating-Basic-Site/Articles-Parent-and-Article-Items/#articles-item

## Describe the issue

I followed the tutorial and when i completed it i saw that it printed the Anchor tags <p> in the frontend - which i dont think its supposed to do. Look at the attached picture. 

This is the part of the Code which has issues in the Tutorial:
![image](https://user-images.githubusercontent.com/20074364/89639330-a2c54300-d8ad-11ea-8d10-5a1eb7b643a2.png)

This is the frontend view:
![image](https://user-images.githubusercontent.com/20074364/89634233-58d85f00-d8a5-11ea-8954-aaca5a669886.png)

**Comment by sofietoft** [comment]
Thanks for the report @thejokerd3 !

So, just for my understanding: The issue here is, that the `<p>` tags are showing on the frontend, right?
Which property editor are you using for the `articleContent` field - a Rich Text Editor? 🤔 Perhaps that should be changed?

**Comment by thejokerd3** [comment]
No problem @sofietoft !

I just followed the tutorial - and they use a Rich Text Editor. But when i remove the ToString and Truncate methods it will exclude the <p> tags. Maybe you should change the documentation. When I have time I will look into a way to keep the ToString and Truncate and still exclude the <p> tags.

Best Regards.

**Comment by sofietoft** [comment]
Thanks for clarifying.
I've had a closer look at this, and have come up with the following suggestion:

We can add another **field** to the Article Item Document Type.
This field would be called something like "Article Preview" and be a textbox type, and have a character limit of 100 (that way the guide also utilizes some config options on properties editors..).
Then, this field is used in the Articles Main template to preview the article. 

What do you think of that solution? 🤔

**Comment by thejokerd3** [comment]
Hey Sofie.

The one you proposed is a nice work around - but it doesnt really solve the issue 😕

I've found a way that does though! Look at the picture below.

[cid:d2adf8ae-c79a-42da-9293-36c7050844df]

Im using the Html object to truncate the value - and by using that it excludes the <p> tags.

What do you think about this solution?

Best regards:

Muslim Al Ali / Thejokerd3

P.S!

It works on Umbraco Version 8.0.0 without changing the Code from the documentation. But something has changed with latest releases and now it doesnt work - so maybe the documentation has to be changed.
________________________________
Fra: sofietoft <notifications@github.com>
Sendt: 13. august 2020 11:46
Til: umbraco/UmbracoDocs <UmbracoDocs@noreply.github.com>
Cc: thejokerd3 <muslimalali@hotmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [umbraco/UmbracoDocs] Issue with Articles Tutorial (#2639)


Thanks for clarifying.
I've had a closer look at this, and have come up with the following suggestion:

We can add another field to the Article Item Document Type.
This field would be called something like "Article Preview" and be a textbox type, and have a character limit of 100 (that way the guide also utilizes some config options on properties editors..).
Then, this field is used in the Articles Main template to preview the article.

What do you think of that solution? 🤔

**Comment by sofietoft** [comment]
Thanks for taking a look @thejokerd3 

For some reason, I cannot see the image you've attached.
Now, if I understand you correctly, the solution you've found doesn't work in the latest version of Umbraco - is that correct?
If it does work in the latest version, then we can definitely use the solution you've suggested.

**Comment by thejokerd3** [comment]
Ah sorry the misunderstanding.

I meant that the Documentation tutorial only works on 8.0.0 and not on latest releases.

This is my solution on how to fix it, with one line of code.

Best regards:

Muslim Al Ali / Thejokerd3
________________________________
Fra: sofietoft <notifications@github.com>
Sendt: 14. august 2020 09:07
Til: umbraco/UmbracoDocs <UmbracoDocs@noreply.github.com>
Cc: thejokerd3 <muslimalali@hotmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [umbraco/UmbracoDocs] Issue with Articles Tutorial (#2639)


Thanks for taking a look @thejokerd3<https://github.com/thejokerd3>

For some reason, I cannot see the image you've attached.
Now, if I understand you correctly, the solution you've found doesn't work in the latest version of Umbraco - is that correct?
If it does work in the latest version, then we can definitely use the solution you've suggested.

**Comment by sofietoft** [comment]
Thanks for explaining!

I've merged https://github.com/umbraco/UmbracoDocs/pull/2658 - which closes this issue.
Thanks again for the report and for resolving the issue 💪
