### ISSUE TITLE
C# DocFX documentation "Show Source" links refer to unknown branch

### ISSUE THREAD

**Issue by abjerner** [umbraco/UmbracoDocs#2642]
The "Show Source" buttons and links all seem to refer to the `dev` branch, which doesn't exist (or at least I don't have access to it). So when clicking on one of the links, GitHub responds with a 404.

![image](https://user-images.githubusercontent.com/3634580/89743553-817a7780-daa4-11ea-902d-c345ade332f6.png)

**Comment by sofietoft** [comment]
Thanks for the report @abjerner ! 😄 

Sure sounds like we need to update something there.
Unfortunately, the ones who would be able to help with that, are on vacation this week, so we might need to wait a bit before we can get it resolved.
I'll make sure to update you here, as soon as I know more!

**Comment by jmayntzhusen** [comment]
If nothing else is specified, DocFX will set the repo url to be the same as the one you used when generating the docs, so the problem probably lies in whichever way we build these docs, which I am not sure about anymore tbh. 

Maybe @nul800sebastiaan knows more about where they are generated.

An easy first step may be to simply override the repo and branch with the github url and main branch for each major. Can be done here:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/ApiDocs/docfx.json#L51 

Will need something like:
```json
"globalMetadata": {
      "_gitContribute": {
        "repo": "https://github.com/umbraco/Umbraco-CMS",
        "branch": "v8/contrib"
      }
    },
```

Optimally when we build a release we would replace the branch there with a tag version and then deploy a version of the docs - and also have a version selector, but a good first step would be targeting the contrib branch.

**Comment by nul800sebastiaan** [comment]
They get generated when we push the button on Azure DevOps to generate them.

This is the pipeline being used: https://dev.azure.com/umbraco/Umbraco%20Cms/_build?definitionId=271&_a=summary

The URL can't be the same as the repo URL because there is no `dev` branch at all, and there never has been. 🙂

**Comment by sofietoft** [comment]
Hi all!
Just checked this one, and it doesn't look like the links in the API docs return 404s anymore.

I'll close this issue for now.
Feel free to re-open, should this issue come up again!
