### ISSUE TITLE
Missing information about how to work with JS and CSS

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#2645]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Getting-Started/Design/Stylesheets-Javascript/index.md - On Our: https://our.umbraco.com/documentation/Getting-Started/Design/Stylesheets-Javascript/***

This article should contain more information about:

* How to add javascript and stylesheet files to a project
* How to manage and work with javascript and stylesheet files directly in the backoffice
* How to render/reference the files in templates
* ... and possibly more.

**Comment by Arunoday-bhattacharjee** [comment]
Hey I would Like the work on this. Could you assign it to me

**Comment by sofietoft** [comment]
Sure thing @Arunoday-bhattacharjee !

Thanks for signing up for the task 💪

**Comment by sofietoft** [comment]
Hi @Arunoday-bhattacharjee 
In order to open this up for others, I'm gonna remove you as assignee on this issue.
Please let me know if you are still working on this, and I will assign it back to you.

Thanks!

**Comment by Jay-umbr** [comment]
Merged and closed
