### ISSUE TITLE
Reference tracking for property editors documentation is missing

### ISSUE THREAD

**Issue by dawoe** [umbraco/UmbracoDocs#2676]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
This is for package developers. So probably go in to the package development section.

## Describe the issue
Since 8.6 Umbraco tracks usages of media and content items. 
However I stumbled across a PR where some code is added so package developers can write code to provide the references. 
https://github.com/umbraco/Umbraco-CMS/pull/7228

The documentation of this is missing. So it is not clear to me if this needs to be done for all property editors that can contain references or only in special circumstances with very complex property editors.

**Comment by sofietoft** [comment]
Thanks reporting this @dawoe !

Sure seems like something that would be good to have documented 💪 
I'll run it by some people, and see if can get this written as soon as possible.
