### ISSUE TITLE
Changing IValueSetValidator for Member Index not working

### ISSUE THREAD

**Issue by deekoulos** [umbraco/UmbracoDocs#2683]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
https://our.umbraco.com/documentation/Reference/Searching/Examine/indexing/#changing-ivaluesetvalidator

## Describe the issue
First of all `composition.RegisterUnique<IUmbracoIndexConfig, CustomIndexConfig>();` should be updated to `composition.RegisterUniqueFor<IUmbracoIndexConfig, CustomIndexConfig>();`

Secondly, the documented approach just does not work. This peace of code should do what is documented here "include all data for a member excluding the built in property values.", but it does not, the indexed fields are not extended by all data except of the built in ones:

```
public class CustomizeIndexComposer : IUserComposer
{
    public void Compose(Composition composition)
    {
        // replace the default IUmbracoIndexConfig definition
        composition.RegisterUnique<IUmbracoIndexConfig, CustomIndexConfig>();
    }
}

// inherit from the default
public class CustomIndexConfig : UmbracoIndexConfig, IUmbracoIndexConfig
{
    public CustomIndexConfig(IPublicAccessService publicAccessService) : base(publicAccessService)
    {
    }

    // explicit implementation - overrides base class.
    // GetMemberValueSetValidator is used for the MemberIndex.
    IValueSetValidator IUmbracoIndexConfig.GetMemberValueSetValidator()
    {
        // NOTE - by default Umbraco only includes a small subset of fields for the member index for
        // security reasons, however you may want to include a larger set of data in the member index.
        // This example will include all data for a member excluding the built in property values.

        // all built in member properties to exclude (i.e. Password question, etc...)
        var excludeFields = Constants.Conventions.Member.GetStandardPropertyTypeStubs().Keys;

        // include everything except the above
        return new MemberValueSetValidator(null, null, null, excludeFields);
    }
}
```
I also rebuilt the index and tried out over the BO to search for additional field values, and they are not found by the index.

It seems that I am not the only one with this issue: 
https://our.umbraco.com/forum/using-umbraco-and-getting-started/102514-search-member-index-by-custom-fields

What is the correct approach here to extend the existing member index by adding all other fields including the custom ones? Could you please update the documentation respectively?

Thanks
Dee

**Comment by marcemarc** [comment]
See also this Forum post... https://our.umbraco.com/forum/using-umbraco-and-getting-started/100363-querying-members-using-examine-and-udis for more context.

**Comment by sofietoft** [comment]
Thanks for reporting this issue @deekoulos ! Much appreciated.

Based on the [forum post](https://our.umbraco.com/forum/using-umbraco-and-getting-started/100363-querying-members-using-examine-and-udis), it looks like you managed to work this out and get the code working on your site.
Is that correct for me to assume?

If that is indeed the case, would you be up for adding to the Docs how you made it work? 😄 
I'm sure that would help a lot of people out there! 'Cause I completely agree; we **need** more real-life code samples in the docs!

**Comment by deekoulos** [comment]
Hey @sofietoft,

yep, I got it runnning but not by extending the built in member index, which is the subject of this issue. In the end, I had to  implement a custom member index and ran into some crazy issues. See 

- https://our.umbraco.com/forum/using-umbraco-and-getting-started/103357-issues-with-the-custom-examine-member-index
- https://github.com/umbraco/Umbraco-CMS/issues/8766

I already documented my approach in the forum posts.

I finally found a workaround for the index update issue: Rebuilding the custom member index, right after the creation and adding to the umbraco examine indexes. I will also update the posts from the above links soon, mentioning this workaround.

This is my whole approach:

Create a custom member index, based on the member type:
```
public class MemberIndexCreator : LuceneIndexCreator, IUmbracoIndexesCreator
    {
        private readonly IProfilingLogger _profilingLogger;
        private readonly ILocalizationService _localizationService;
        private readonly IPublicAccessService _publicAccessService;

        // Since Umbraco 8 has dependency injection out of the box, we can use it to inject
        // the different services that we need.
        public MemberIndexCreator(IProfilingLogger profilingLogger,
            ILocalizationService localizationService,
            IPublicAccessService publicAccessService
        )
        {
            _profilingLogger = profilingLogger;
            _localizationService = localizationService;
            _publicAccessService = publicAccessService;
        }

        // Noticed that we return a collection of indexes? Technically you
        // can create multiple indexes in an indexCreator :) You can have a look at
        // UmbracoIndexesCreator.cs in the CMS core and see how the CMS does that.
        public override IEnumerable<IIndex> Create()
        {
            var index = new UmbracoMemberIndex("FeedbaxMembersIndex",
                new UmbracoFieldDefinitionCollection(),
                CreateFileSystemLuceneDirectory("FeedbaxMembers"),
                new CultureInvariantWhitespaceAnalyzer(),
                //new StandardAnalyzer(Lucene.Net.Util.Version.LUCENE_30),
                _profilingLogger,
                new MemberValueSetValidator(includeItemTypes: new string[] { "Member" }, null, null, null));

            return new[] { index };
        }
    }

    public class MemberComponent : IComponent
    {
        private readonly IExamineManager _examineManager;
        private readonly MemberIndexCreator _memberIndexCreator;
        private readonly IndexRebuilder _indexRebuilder;

        public MemberComponent(IExamineManager examineManager, MemberIndexCreator memberIndexCreator, IndexRebuilder indexRebuilder)
        {
            _examineManager = examineManager;
            _memberIndexCreator = memberIndexCreator;
            _indexRebuilder = indexRebuilder;
        }

        public void Initialize()
        {
            // Because the Create method returns a collection of indexes,
            // we have to loop through them.
            foreach (var index in _memberIndexCreator.Create())
            {
                index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("minimumProjectSize", FieldDefinitionTypes.Integer));

                _examineManager.AddIndex(index);
            }

            _indexRebuilder.RebuildIndex("FeedbaxMembersIndex");
        }

        public void Terminate() { }
    }

    public class MemberComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.Components().Append<MemberComponent>();
            composition.RegisterUnique<MemberIndexCreator>();
        }
    }
```

But as said, the mentioned issue of this topic: extending the member index is still open. The following code is just not getting executed:
```
IValueSetValidator IUmbracoIndexConfig.GetMemberValueSetValidator()
    {
        // NOTE - by default Umbraco only includes a small subset of fields for the member index for
        // security reasons, however you may want to include a larger set of data in the member index.
        // This example will include all data for a member excluding the built in property values.

        // all built in member properties to exclude (i.e. Password question, etc...)
        var excludeFields = Constants.Conventions.Member.GetStandardPropertyTypeStubs().Keys;

        // include everything except the above
        return new MemberValueSetValidator(null, null, null, excludeFields);
    }
```

Creating a custom member index did so far the job for me, but now I have 2 member indexes which are getting updated by umbraco, although it should be done by the builtin member index, and saving some operations on the app server.

**Comment by sofietoft** [comment]
Ah. Thanks for explaining 💪 
Glad to hear you got it to work on your end!

So, as I see this, there are two parts:

1. It would be great to have your approach added to the Docs as a separate article with en example of how this can be done
2. We need to update the current example that's in the Docs, as it doesn't work.

Regarding the second one - which version of Umbraco are you using?

I'll run it by some of the experts here at HQ and the Docs community team, so we can get the sample code updated correctly!

**Comment by deekoulos** [comment]
Yes, that would be great, thanks!

I am using 8.6.4.

**Comment by deekoulos** [comment]
Update:

in some cases this solution causes the index is locked issue. 

Here is my update solution
```
        public void Initialize()
        {
            // Because the Create method returns a collection of indexes,
            // we have to loop through them.
            foreach (var index in _memberIndexCreator.Create())
            {
                index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("minimumProjectSize", FieldDefinitionTypes.Integer));
                index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("memberGroups", FieldDefinitionTypes.FullTextSortable));

                var luceneIndex = index as LuceneIndex;
                var dir = luceneIndex.GetLuceneDirectory();
                if (IndexWriter.IsLocked(dir))
                    IndexWriter.Unlock(dir);

                _examineManager.AddIndex(index);
            }

            _indexRebuilder.RebuildIndex("FeedbaxMembersIndex");
        }

        public void Terminate() { }
    }
```

**Comment by sofietoft** [comment]
Ah, that's great! Thanks for the additional input @deekoulos .

I've sent this issue to our developers here at Umbraco HQ.
They will look at this within the next weeks, so we can get the article amended correctly.
Thanks again for reporting!

**Comment by deekoulos** [comment]
Update: 

the documentation is not wrong. Please see this comment https://github.com/umbraco/Umbraco-CMS/issues/8766#issuecomment-686549551

thanks to @nul800sebastiaan 

Maybe it would be good to additionally mention in the documentation, that the Umbraco.Core namespace is needed to be used for this method. Since Visual Studio does not suggest to import the namespace Umbraco.Core, it suggests to use the wrong method.

**Comment by nul800sebastiaan** [comment]
I think all of these code samples should have `usings` at the top, it makes no sense (IMO) for people to have to hunt them down. Resharper did it fine for me but some people are apparently not so lucky 😅

**Comment by sofietoft** [comment]
Hi @deekoulos 
Super great to hear you managed to work this one out 😄 

I completely agree that we should add the "using" statements to the samples in this article!
Would you be up for adding them, by any chance? 😇 It **is** open source anyways 😁

**Comment by nul800sebastiaan** [comment]
Added in https://github.com/umbraco/UmbracoDocs/pull/2689

**Comment by sofietoft** [comment]
Closing this one, as the using statements has been added!

Thanks all 😄
