### ISSUE TITLE
Update all examples of subscribing to static events to include corresponding 'unsubscribing' to that event during termination

### ISSUE THREAD

**Issue by marcemarc** [umbraco/UmbracoDocs#2690]
eg this sort of example:

public class SubscribeToSavedEventComponent : IComponent
    {
        private readonly ILogger _logger;

        public SubscribeToSavedEventComponent(ILogger logger)
        {
            this._logger = logger;
        }
       
        public void Initialize()
        {
            //specify my event handler
            MemberService.Saved += MemberService_Saved;
        }

        private void MemberService_Saved(IMemberService sender, SaveEventArgs<IMember> e)
        {
            foreach (var member in e.SavedEntities)
            {
                
              //write to the logs every time a member is saved
              this._logger.Info<MyPublishEventComponent>("member {member} has been saved and event fired!", member.Name);
            }
        }
        public void Terminate()
        {
            // Nothing to terminate
        }

should be

public class SubscribeToSavedEventComponent : IComponent
    {
        private readonly ILogger _logger;

        public SubscribeToSavedEventComponent(ILogger logger)
        {
            this._logger = logger;
        }
       
        public void Initialize()
        {
            //specify my event handler
            MemberService.Saved += MemberService_Saved;
        }

        private void MemberService_Saved(IMemberService sender, SaveEventArgs<IMember> e)
        {
            foreach (var member in e.SavedEntities)
            {
                
              //write to the logs every time a member is saved
              this._logger.Info<MyPublishEventComponent>("member {member} has been saved and event fired!", member.Name);
            }
        }
        public void Terminate()
        {
             //unsubscribe to event during shutdown
            MemberService.Saved -= MemberService_Saved;
        }

See this PR for context: https://github.com/umbraco/Umbraco-CMS/pull/8815

**Comment by marcemarc** [comment]
PR here: https://github.com/umbraco/UmbracoDocs/pull/2692/files

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/UmbracoDocs/pull/2692
