### ISSUE TITLE
exportMemberGroups option is not documented

### ISSUE THREAD

**Issue by sussexrick** [umbraco/UmbracoDocs#2708]
The [Umbraco Deploy releases page](https://our.umbraco.com/packages/developer-tools/umbraco-deploy/) refers to an `exportMemberGroups` setting introduced in Deploy 3.4.0, but it's not documented where this goes. Is it an element? An attribute? Is in in `UmbracoDeploy.Settings.config` or `UmbracoDeploy.config`? What's the default value?

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Umbraco-Cloud/Deployment/Deploy-Settings/index.md***

**Comment by sofietoft** [comment]
Thanks for reporting this @sussexrick !

I'll make sure to run it by our Deploy experts, so we can get this documented 💪
