### ISSUE TITLE
Document keepAlive node in umbracoSettings.config Umbraco 8.6.0

### ISSUE THREAD

**Issue by Swimburger** [umbraco/UmbracoDocs#2710]
How would I go about documenting the keepAlive node in umbracoSettins.config. This node was introduced in Umbraco 8.6.0 with pull request [#7164](https://github.com/umbraco/Umbraco-CMS/pull/7164).
I can find the markdown files for v7 Umbraco versions, but there's none for v8.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Config/umbracoSettings/index-vpost7.8.0.md***

**Comment by sofietoft** [comment]
That is a really good question @Swimburger !

We have a plan to clean all those articles up - however,  it's quite a process as there are many things to consider.

For now though, I'd suggest doing the following:

* Create a new files called `index-vpost8.6.0`
* Add the following YAML tags: `versionFrom: 8.6.0`

That will add the article to the version-box.
Then, in that article, write about the `keepAlive` node.
Oh, and add a sub heading using the name of the setting you're documenting - that should increase the searchability!
I hope that makes sense - do let me know if you have further questions!

**Comment by Swimburger** [comment]
Pull request submitted #2711
