### ISSUE TITLE
Please update this vital page for Umbraco 8 !!!

### ISSUE THREAD

**Issue by terryclancy** [umbraco/UmbracoDocs#2715]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Querying/MemberShipHelper/index.md***

**Comment by nul800sebastiaan** [comment]
Hi there @terryclancy and thank you for your request. 
I would like to remind you that we're always open to suggestions but there's a few problems with your request:

- Adding multiple exclamation marks generally looks like your screaming at us, it's not the best way to get things done 😓 
- You didn't specify what you're missing or struggling with so there's nothing we can do for you right now

I'll close this one for now, if you still have good suggestions then we're all ears.

**Comment by terryclancy** [comment]
Sebastiaan,

I hear you, agree and apologize for that and will improve the quality of my requests in future.

Terry
