### ISSUE TITLE
Unable to cancel ContentService.Saving event

### ISSUE THREAD

**Issue by skepok** [umbraco/UmbracoDocs#2726]
Umbraco 8.6.1

Hey, I've noticed when I cancel a ContentService saving event, whilst the event appears to cancel, the content is still saved.

An example of a component to replicate could be

```csharp
public class ApplicationComponent : IComponent
    {
        public void Initialize()
        {
            ContentService.Saving += ContentService_Saving;
        }

        private void ContentService_Saving(IContentService sender, SaveEventArgs<IContent> e)
        {
            foreach (var content in e.SavedEntities)
            {
		//I've tried a combination of each of these
                content.ResetDirtyProperties();
                e.Cancel = true;
                e.CancelOperation(new EventMessage("Error", "Some message", EventMessageType.Error));
		//throw new Exception("breaking");
            }
        }

        public void Terminate()
        {
        }
    }
```

This would display the message as expected, but it still saves the content node. 

Unless im going about this the wrong way, I'm pretty sure if I updated a property of a content node in the backoffice, hit save + publish, let this code run, then refreshed the page, I should see the old value of that property on the content node, but instead I see the newly saved value.

**Comment by nul800sebastiaan** [comment]
Here's how this works: it will still show you the content you tried to save so you can make corrections. However, once you refresh your browser you should see the old values again.

There is, however a bug in this, which is what you're seeing at the moment: https://github.com/umbraco/Umbraco-CMS/issues/8417

So.. the docs are correct, your foreach should look like this:
```csharp
            foreach (var content in e.SavedEntities)
            {
                e.CancelOperation(new EventMessage("Error", "Some message", EventMessageType.Error));
            }
```

I'll close this one, hopefully bug #8417 can be fixed some time soon.

**Comment by skepok** [comment]
Thanks @nul800sebastiaan ill keep an eye on umbraco/Umbraco-CMS#8417 (might event take a look myself if I find time!)

**Comment by prashant-spinx** [comment]
i have faced same issue, any one have any solution for it ?

**Comment by sofietoft** [comment]
Hi @prashant-spinx !
Sorry to hear you're running into some issues here.
As this issue has been closed on this repo, I'd suggest that you head on over to the related issue created on our CMS Issue tracker: https://github.com/umbraco/Umbraco-CMS/issues/8417

You might also be able to get some help resolving the issue or finding a work-around, by going to our [Forums on Our](https://our.umbraco.com/forum/).
A lot of friendly people in our community always ready to help.

I hope it all works out 💪
