### ISSUE TITLE
Missing tips regading "useLegacyEncoding" in webconfig. 

### ISSUE THREAD

**Issue by natanguitz** [umbraco/UmbracoDocs#2747]
Missing documentation when having useLegacyEncoding enabled in Umbraco 7 
https://our.umbraco.com/documentation/Getting-Started/Setup/Upgrading/migrating-to-v8

It looks like my project have "useLegacyEncoding"  enabled. 
After installing the clean Umbraco 8 site i could not login. 

A solution that work for me :  Go back to 7+ site, disable "useLegacyEncoding" and restore the password. 

I could continue with Step 2: Migrating content to Umbraco 8 only after running password restore.

**Comment by sofietoft** [comment]
Thanks for reporting this issue @natanguitz ! Much appreciated.

I think it makes a lot of sense to add a note about the `useLegacyEncoding` to this article.

Do you have any thoughts on where in article. by any chance?
Perhaps somewhere in the first steps? 🤔

**Comment by natanguitz** [comment]
Yes, happy to help :)  
I think another warning before the text "Once it is upgraded and you have verified everything is working, move on to step 2. "  it may be the best so nobody miss it.

**Comment by nul800sebastiaan** [comment]
There is a warning here that tells you to copy the provider configuration over:

![image](https://user-images.githubusercontent.com/304656/95098499-098c9e80-072f-11eb-8329-cfbe5d113bfb.png)

This would include everything you had on the `UsersMembershipProvider` before (including the `useLegacyEncoding` attribute). 

So most of all, I would think that warning needs clarification.

**Comment by natanguitz** [comment]
Yes i guess it would be enough with a clarification , adding the attribute's name and little earlier in the article. 
I think is possible that my case was a unique case where it was not enough to just copy & paste.

**Comment by sofietoft** [comment]
Updating the warning to mention also the `useLegacyEncoding` value sounds like a good plan.

Would you be up for updating the article yourself @natanguitz ? 😄 
We have some docs here, on how you can make the PR: https://our.umbraco.com/documentation/Contribute/

**Comment by natanguitz** [comment]
Yes, I can give it a try :)

**Comment by natanguitz** [comment]
#2753 
I think I did it the correct way :) 
cheers!!

**Comment by sofietoft** [comment]
Brilliant @natanguitz , thanks! 😄

**Comment by nul800sebastiaan** [comment]
Only mentioning `useLegacyEncoding` won't be enough tough, there's many more attributes that need to be copied over. I would update this to read more like: 

Take your current v7 configuration for the `UsersMembershipProvider` and copy that into the v8 web.config, for example, in v7 it could look like this: 

```xml
<add name="UsersMembershipProvider" type="Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco" minRequiredNonalphanumericCharacters="0" minRequiredPasswordLength="4" useLegacyEncoding="true" enablePasswordRetrieval="false" enablePasswordReset="true" requiresQuestionAndAnswer="false" passwordFormat="Hashed" maxInvalidPasswordAttempts="20" />
```

After you've copied that over to your v8 migration project, you need to change the `type` attribute from `Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco` to `Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco.Web`.

It is important that all of the attributes (in particular `useLegacyEncoding`) are copied to your v8 migration project otherwise you might not be able to log in.

**Comment by nul800sebastiaan** [comment]
I see you've also added:

> In some cases you need to go back to your **Umbraco 7.14 site** , disable it and run a password restore after that in order to login succeed in your **Umbraco 8.1 site**

I am not sure what this means and why this is necessary? I guess if it confuses me, it will confuse other people as well! 😅

**Comment by sofietoft** [comment]
As the article has now been updated according to this issue, I'll close it down.

Thanks for all who helped out! 💪
