### ISSUE TITLE
Typo in /Reference/Scheduling?

### ISSUE THREAD

**Issue by jgettrup-ng** [umbraco/UmbracoDocs#2756]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Scheduling/index.md***

I think in the section headed "RecurringTaskBase" the phrase "IsAsync must be overridden and set to false" should actually say "IsAsync must be overridden and set to true".

**Comment by sofietoft** [comment]
Thanks for reporting this @jgettrup-ng !

I think I'll need a bit more context on this one.
Could you provide some more information on this?

**Comment by sofietoft** [comment]
Looks like this one has been resolved 💪 

I'm closing the issue.
