### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/UmbracoDocs#2770]
Hello,

I want to document a couple of changes I have made to the API, but am unsure where to document them.  The changes I want to document are in v8:
`$rootScope.$on('$changeTitle',...` in init.js

and also 
`$rootScope.$on('$setAccessibleHeader',..` which had to be placed in umbeditorheader.directive.js

If you could advise me on where to update them I can add them into the docs, thank you

**Comment by sofietoft** [comment]
Hi @RachBreeze !
Sounds great that you're up for writing some docs on those things 💪 

An Angular section of the documentation on Our has been added recently - I think we should put this information in there.
The section isn't too big just yet, but you can find it here: https://our.umbraco.com/documentation/Reference/Angular/ 

For the stuff in `init.js`, you might need to start a new article about that file.
And the same goes for the `umbEditorHeader` directive!

If not on Our, you're also more than welcome to add some comments directly in the code, as they will then be part of the autogenerated docs here: https://our.umbraco.com/apidocs/v8/ui/#/api/ 

Happy to help, if you have further questions! 😄

**Comment by sofietoft** [comment]
As the PR references here has been merged, I'll go ahead and close this issue as well.

Thanks again for helping out @RachBreeze ! Much appreciated.
