### ISSUE TITLE
RenderUmbracoFormDependencies() missing

### ISSUE THREAD

**Issue by Slipoch** [umbraco/UmbracoDocs#2794]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Add-ons/UmbracoForms/Developer/Prepping-Frontend/index.md***

what using is required to use the method RenderUmbracoFormDependencies()?

It is not present in my viewpage.

**Comment by sofietoft** [comment]
Hi @Slipoch !
That's a great question.
Which version of Umbraco Forms and Umbraco are you currently running? 🤔

**Comment by sofietoft** [comment]
Hi @Slipoch !
I can see that the correct using statement has been added to the code snippets in the ["Preparing the frontend" article for the Umbraco Forms section](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Prepping-Frontend/).
That should be exactly what you're looking for.

So what that, I'll close this issue for now.
Please do not hesitate to get back in touch, if something comes up.
And thanks for raising the question!
