### ISSUE TITLE
Missing - Creating Forms Based On Datasources documentation

### ISSUE THREAD

**Issue by jenistonj** [umbraco/UmbracoDocs#281]
Broken link at
https://our.umbraco.org/documentation/Add-ons/UmbracoForms/Editor/Creating-Forms-Based-on-Datasources

**Comment by hemraker** [comment]
Datasources has been added in this pull-request https://github.com/umbraco/UmbracoDocs/pull/181, needs to be updated and added to new docs structure though.

**Comment by sofietoft** [comment]
@hemraker,
"Creating Forms based on Datasources", was that a guide that existed at some point?
Also, the PR you linked to, has been closed due to inactivity 🙈 

-Sofie

**Comment by marcemarc** [comment]
This is a duplicate of: https://github.com/umbraco/UmbracoDocs/issues/254
