### ISSUE TITLE
Storing form data in Azure blob storage

### ISSUE THREAD

**Issue by mattou07** [umbraco/UmbracoDocs#2829]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
https://our.umbraco.com/Documentation/Extending/FileSystemProviders/Azure-Blob-Storage/index-v7

## Describe the issue
This page should include information on how to pull forms data from Azure Blob Storage instead of just media. 

If its documented somewhere else feel free to close this issue.

Happy to take this on myself.

**Comment by sofietoft** [comment]
Thanks for creating the issue here @mattou07 !

Just to be sure I understand - you think we should also have an article on how to work with forms data on Azure blob, as currently the articles we have, are primarily media files and the image processor.

Is that correct? 😄

**Comment by mattou07** [comment]
@sofietoft I was thinking of having it on the same page as an added bonus to using Azure Filesystem providers. If you use blob storage container for the Umbraco Forms data folder. Which would hold forms, templates and workflows. It allows you to use features like Azure Web App slot swaps without you having to manually copy the forms data folder to the other slot as they all use the same container.

**Comment by sofietoft** [comment]
Thanks for explaining and sharing your thoughts on this @mattou07 !

So, is the setup for adding Forms to Axure Blob fairly the same as with media?
If so, then I think it would be perfectly fine to add a section to the existing article... If it's different - then I think another article would be the way to go. Not everyone uses Umbraco Forms, so it might not make sense for all that it's mentioned in this article 🤔

**Comment by sofietoft** [comment]
[PR related to this](https://github.com/umbraco/UmbracoDocs/pull/2875) has been merged, so I'll close this issue as well.
