### ISSUE TITLE
Document how to connect to sql azure databases on UaaS

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/UmbracoDocs#284]
Specifically that you need to go into options and specify the database name: 

![image](https://cloud.githubusercontent.com/assets/304656/11502022/b2584fde-9838-11e5-8a15-37a8558dde77.png)

**Comment by sofietoft** [comment]
Done: https://our.umbraco.org/documentation/Umbraco-Cloud/Databases/
