### ISSUE TITLE
Block List Editor Thumbnail Size

### ISSUE THREAD

**Issue by marcusjm** [umbraco/UmbracoDocs#2853]
## What type of issue is it? (Choose one - delete the others)
Discussion
Missing documentation

## What article/section is this about?
[(link here)](https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/)

## Describe the issue
Could we get the recommended thumbnail aspect/size to get proper thumbnail size?

**Comment by sofietoft** [comment]
Hi @marcusjm ! Thanks for the report.

Just to be sure I understand correctly; You're asking for the dimension/size of the thumbnail to be used in the Block Editor catalogue - right? 😄

**Comment by marcusjm** [comment]
> Hi @marcusjm ! Thanks for the report.
> 
> Just to be sure I understand correctly; You're asking for the dimension/size of the thumbnail to be used in the Block Editor catalogue - right? 😄

Yes, the recommended size at least. I have tried various with little success but I thought it would be a good thing to have for others too :).

**Comment by sofietoft** [comment]
Very good. Thanks for confirming.

I'll make sure we get those dimensions addded.

**Comment by sofietoft** [comment]
So, I have some answers for you.
The thumbnails for the Block List catalogue are presented in the format of 16:10 and we recommend a resolution of 400px x 250px.

Hope this is what you need.
I'll make sure it's added to the article on the docs as well.
