### ISSUE TITLE
Broken link issue

### ISSUE THREAD

**Issue by thenexus00** [umbraco/UmbracoDocs#2891]
Where the wording of "You will need to register your ContentFinder using a Composer" Is the "Using a composer" link is broken.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Getting-Started/Code/Debugging/Logging/index.md***

**Comment by sofietoft** [comment]
Great catch @thenexus00 !

I've corrected the link 💪 
Thanks for helping us keep the docs up to date!
