### ISSUE TITLE
Apple App not found

### ISSUE THREAD

**Issue by thenexus00** [umbraco/UmbracoDocs#2892]
The apple app link when clicked loads the apple app store but no app is found.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Getting-Started/Backoffice/LogViewer/index.md***

**Comment by dampee** [comment]
Hi @thenexus00 

I just tried and you are right. I got the message that the item is not available in the (Belgian and) UK store.

![afbeelding](https://user-images.githubusercontent.com/1857460/99689940-dce6d900-2a87-11eb-9acb-d9fce88db4e1.png)

**Comment by sofietoft** [comment]
Thanks for reporting this! 💪 

I've forwarded it to Warren, who's the creator of the app.
We should get this resolved soon!

**Comment by sofietoft** [comment]
Quick update on this one:

The Log Viewer App is no longer available on the AppStore, I'm afraid.
Warren tells me that he hopes to have a new build ready soon, for Mac's.
I recommend that you keep an eye on the official Github for the app, to follow new releases: https://github.com/warrenbuckley/Compact-Log-Format-Viewer

I've removed the link from the article.
Thanks again for making us aware of this 💪
