### ISSUE TITLE
GetCropUrl

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/UmbracoDocs#2929]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/index.md***

Heya 
I don't think the image src examples are correct as there is a double quotes in side the img src for "banner", and this is a compilation error in Razor
<img src="@Url.GetCropUrl(Model.Image, "banner")" />

Also GetCropUrl now needs IImageUrlGenerator which is why I came to the doc, version 8.9 ;-)

**Comment by sofietoft** [comment]
Thanks for reporting this @RachBreeze !
Much appreciated.

Sorry to see that this article hasn't been updated yet - I'll see that it's put on our list.
If you happen to find the solution to it, you're more than welcome to take a shot at updating the article 😄

**Comment by RachBreeze** [comment]
Heya @sofietoft 
Thank you for getting back so quickly..
I have found a solution to the issue re IImageUrlGenerator, I do need to find out which version of Umbraco the amend was added in and then I'll update the docs

**Comment by RachBreeze** [comment]
Hi @sofietoft 
I've tracked down the version that IImageUrlGenerator was added in 8.7.0 how do I document that up, please?  The other code snippets are still valid (just some are deprecated), so I'm not sure if I should add something to the end of the current document or start a new one, sorry for the questions

**Comment by sofietoft** [comment]
Hi @RachBreeze !

Sounds great that you tracked down the version number 💪 Thanks for doing the research on that!

And don't worry about having to ask questions about our current versioning system - we know it's not great, and that it is indeed a bit complicated 🙈

So, we generally do not encourage having details about multiple versions in the same article, as that can cause some confusion.
Instead, you should create a **new file**, which should then be the new index file.

I'd suggest you follow this flow:
- Make a copy of the existing `index.md` file
- Rename the OLD file (the one you copied) to `index-vpre8.7.md`
- In the old file, update the version tags in the top of the article to say `versionFrom: 8.0.0` and add `versionTo: 8.6.0` 
- In the new file (which should just be called `index.md`) you update the `versionFrom` tag to say `8.7.0`.
- Now all there is left, is to update the new file with the changes you've discovered

The new file will then be the new "default" file with the newest and most up-to-date docs, and the other will be marked as valid for versions 8.0 through to 8.6.

I do hope this removes some of the confusion around the versioning system.
Give it a shot, make the PR and we'll have a look at it!
And let me know if there are any questions 😄 always happy to help!

**Comment by sofietoft** [comment]
PR (#2950 ) merged.

I'll close this issue as well.
Thanks again for report and updating the docs @RachBreeze !
