### ISSUE TITLE
CreatorId is different on copied content

### ISSUE THREAD

**Issue by nitinanand27** [umbraco/UmbracoDocs#2932]
We have noticed that a default admin user with Id 0 is alloted to copied content. Is there a solution for this?

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Copying-a-Page/index.md***

**Comment by sofietoft** [comment]
Hi @nitinanand27 ! Thanks for reaching out.
And that's a great question, why that default admin user is being added 🤔 

I'll what I can do about getting you some answers to that.

**Comment by nitinanand27** [comment]
This seems to be reported here https://issues.umbraco.org/issue/U4-8250 but not solved

**Comment by sofietoft** [comment]
Ah, you're right! 🤔 This is our old issue tracker though, so I'm not sure how relevant the issues on that tracker is anymore..

Have you checked the Issue Tracker that we're currently using? It's on Github: https://github.com/umbraco/Umbraco-CMS/issues
You might be able to get some answers there.

**Comment by nitinanand27** [comment]
hmm, nothing there yet.

**Comment by sofietoft** [comment]
Thanks for checking!
I'd recommend that you create an issue for this on the tracker.
In the meantime, I'll see what I can do about getting you some answers!

**Comment by sofietoft** [comment]
Hi @nitinanand27 
Apologies for the delay.

Did you create an issue for this on the CMS issue tracker? 🤞
I'm afraid it's not something I can help you with from a Documentation perspective, so I'll have to send you over to the CMS tracker instead.
They have a few templates to choose between when creating an issue.
You're also more than welcome to reach out to our very friendly community on the forums on Our: https://our.umbraco.com/forum/ 

I hope everything works out!
