### ISSUE TITLE
uaas-cmd download link error

### ISSUE THREAD

**Issue by HamDerAndrew** [umbraco/UmbracoDocs#2946]
##Issue - Other
Error on download link for the "uaas-cmd" tool.

## What article/section is this about?
https://our.umbraco.com/documentation/Umbraco-Cloud/set-up/Working-With-Visual-Studio/#generate-a-visual-studio-solution

## Describe the issue
When I try to download the "uaas-cmd" tool for generating a Visual Studio Solution nothing happens. It throws this error in the console:

![uaas download error](https://user-images.githubusercontent.com/2794633/102199497-fbdc5d80-3ec3-11eb-9ddc-b886b2e39180.png)

So far you can get around the issue by just clicking the link provided in the console.

**Comment by nul800sebastiaan** [comment]
Thanks @HamDerAndrew - the short link was pointing to an `http` URL instead of an `https` one. This is now fixed!
