### ISSUE TITLE
Broken link to to Umbraco TV video

### ISSUE THREAD

**Issue by Aaen** [umbraco/UmbracoDocs#296]
There is a broken link on the bottom of this page https://our.umbraco.org/documentation/Reference/Searching/Examine/overview-explanation to a Umbraco TV video. 

The broken link is http://umbraco.com/help-and-support/video-tutorials/developing-with-umbraco/examine.aspx it´s link to the old video place

**Comment by marcemarc** [comment]
Link removed, closing this issue.
