### ISSUE TITLE
Export file usually fails

### ISSUE THREAD

**Issue by tnashavnade** [umbraco/UmbracoDocs#2985]
We are trying to export an Excel file in the backend. Sometimes it works but more often than not, the GetExport request fails with a status of Canceled in the browser (various browsers have the same issue). The error message is either FileNoteFound or "Could not find file" when looking more closely at the response. We can see that the file that we wish to download is created and then removed from storage during the PostGenerateExport and GetExport requests. Sometimes it is successfully downloaded and then on future requests it stops working. Sometimes it fails right away and then starts working and finally, sometimes it does not work at all and all the requests fail. The datasets we are trying to download are very small.

Is this a known issue? Any help would be greatly appreciated.

**Comment by sofietoft** [comment]
Hi @tnashavnade!
Thanks for the detailed report here.

I do think I need a bit more information in order to narrow it down though.
Where in the backoffice are you trying to download an Excel file?
Is this by any chance related to Umbraco Forms?
Are you using any third-party packages/plugins that let you export data from Umbraco into an excel file?

**Comment by tnashavnade** [comment]
Yes we are using Umbraco Forms here. I am not aware that we are using any third-party packages/plugins.

**Comment by sofietoft** [comment]
Alright. Thanks for confirming.

Sounds like you're using the feature described here: https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Editor/Viewing-and-Exporting-Entries/#exporting-data 

As far as I understand, you're having some issues with the feature - it's only letting you export the files "sometimes", which of course shouldn't be the case.

It isn't really a case for the documentation team, so here are a few suggestions for how you can move forward:
- Get in touch with our support team ( contact@umbraco.com ), who'll be able to help you identify the underlying issue
- Reach out to the community in the [forums on Our](https://our.umbraco.com/forum/)
- Report the issue on the [Umbraco Forms issue tracker](https://github.com/umbraco/Umbraco.Forms.Issues/issues)

I hope it all works out!
