### ISSUE TITLE
Member Events code sample syntax error in V8

### ISSUE THREAD

**Issue by trevorloader** [umbraco/UmbracoDocs#3021]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Events/MemberService-Events/index.md***

The sample code no longer works in v8.

Specifically, the line

`private void MemberService_Saved(IMemberService sender, SaveEventArgs<IMember> e`

throws an error as IMember is not recognised.

**Comment by sofietoft** [comment]
Thanks for the report @trevorloader !

I'll make sure we review the sample code in this article as soon as possible.

**Comment by sofietoft** [comment]
Hi @trevorloader 
We've been testing this code sample again, and found that some "using" statements are missing!

Could you try adding the following:

* using Umbraco.Core.Events;
* using Umbraco.Core.Models;
* using Umbraco.Core.Services;

That should clear up the error you're running into.
We'll make sure that the sample code is updated as well 💪
