### ISSUE TITLE
Broken links on property value converters documentation

### ISSUE THREAD

**Issue by jamescoxhead** [umbraco/UmbracoDocs#304]
There's a couple of broken links at under the Samples on the [Property Value Converters](https://our.umbraco.org/documentation/Extending/Property-Editors/value-converters) page.

It looks like the correct pages are https://our.umbraco.org/Documentation/Extending/Property-Editors/value-converters-full-example-attributes and https://our.umbraco.org/Documentation/Extending/Property-Editors/value-converters-full-example-interface.

**Comment by Jeavon** [comment]
Thanks I have fixed those links in the source md file, so Our should be fixed with next update
