### ISSUE TITLE
Expansion required

### ISSUE THREAD

**Issue by thenexus00** [umbraco/UmbracoDocs#3049]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype.md***

The old methods from Version 7 to create fields do not work for 8. Could you possibly look to expand this documentation to include how to add fields to show up. Good examples would be to...

- Create a custom field to get value from in workflow code
- Create Mapping. Fetch form fields to use to map to something
- Fetch Member Groups & Member Types (Good for mapping a form submission to member)

**Comment by sofietoft** [comment]
Thanks for the report @thenexus00 !

I agree that it would be super great with even more samples on how to extend Umbraco Forms!
Just to make sure understand what specifics you're looking for here:

* Examples of how to create custom fields, which can then be used in a custom workflow.
  * We do have an article on how to create a custom field type, perhaps that could be a good first place to look: https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype 
* Example of how to map custom field types to "something" - could you be a bit more specific on this one, as I'm not entirely sure I understand?
* Example of how to fetch existing Member Groups and Member Types when creating custom workflows

I hope I got all that right 🤞 Do let me know!

**Comment by jonat123** [comment]
Hey @thenexus00 I  hope you are doing good :-) 

I am wondering whether you saw my colleague's questions about the specifics that you were looking for?

Best regards
Jonathan

**Comment by sofietoft** [comment]
Hi @thenexus00 !

As it's been a while since we've seen activity on this Issue, I'll be closing it down.
Also, we've added a task to our internal task board, on adding more samples to our Forms docs 💪 

Please do not hesitate to get back in touch, should something come up.
Thanks again for contributing 😄
