### ISSUE TITLE
Official Content Apps Documentation page is broken

### ISSUE THREAD

**Issue by MjDhaneshKumar** [umbraco/UmbracoDocs#3050]
The issue is with documentation of content apps, it says `Oooops, something broke` , this is because of the wrong url, when I click on the versions then it loads correctly.

I redirect to the documentation from here https://umbraco.com/blog/umbraco-8-content-apps/
Link to the documentation: https://our.umbraco.com/Documentation/Extending/Content-Apps/index-v8

PFA
![Error](https://user-images.githubusercontent.com/58820887/110082547-7e820400-7db3-11eb-9182-b6d88bb36c0b.png)

**Comment by sofietoft** [comment]
Thanks for reporting this @MjDhaneshKumar !

I'll see what I can do about fixing this broken path.

**Comment by sofietoft** [comment]
The link has now been updated 💪 

Thanks again for reporting this @MjDhaneshKumar .
I'll close the issue for now.
