### ISSUE TITLE
How-to for cross-environment unattended upgrades with or without multiple servers

### ISSUE THREAD

**Issue by kdx-perbol** [umbraco/UmbracoDocs#3062]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
Getting Started > Setup > Upgrading

## Describe the issue
The documentation on cross-environment (i.e. development > test > production) upgrades has always left much to the imagination. But with the introduction of unattended upgrades in 8.12 it seems there is a risk of running into problems if making unattended upgrades across environments, especially when some environments have multiple servers (Admin/Master and Read-Only/Front). 

Also, it's not clear what scenario the unattended upgrade documenation describes - whether it's a NuGet upgrade in a development environment ("developer upgrade"), or an upgrade of an existing production installation ("administrator upgrade").

The pre-8.12 process we employ for cross-environment upgrades is this:

1. NuGet upgrade using Visual Studio. Make sure the "installed version" app setting is updated correctly to the target version. 
2. Deploy to a different environment, including the app setting 
3. Sign into Admin on the Master server and "authorize the upgrade" which now shows the same version for "source" and "target" (e.g. "from 8.11.1 to 8.11.1" when upgrading to 8.11.1), but different version IDs.
4. Wait for the upgrade to complete.
5. Browse the Read-Only servers and make sure they don't show the "upgrade required" screen. 

We only upgrade "via deployment". We never upgrade an existing installation by clicking the "click here to upgrade" button in Admin.

The documentation should say whether unattended upgrades even work for this scenario, and if so, if this is the way to do it. At the moment I'm not sure whether I can even use unattended upgrades.

**Comment by sofietoft** [comment]
Thanks for reporting this @kdx-perbol !
A very relevant scenario, that we of course need to cover in more details in the docs.

Now, we do at the very top of the "General upgrades" article have a note about how you'll need to run through the upgrade intaller on all your environments.

It might very well be different with the unattended upgrades enabled 🤔 I even think it will make it a whole lot easier, as it should mean that you would not need to run through the installer on either environments.
Of course, depending on your set up, that's not always ideal.

I'll forward this to some of our experts on the area - I'm sure they'll be able to help us out here!

**Comment by sofietoft** [comment]
Hi again @kdx-perbol !

I've now had a chat with @rasmusjp about some steps to help you use the unattended upgrades features in a set up like yours.
Here are steps:

1. NuGet upgrade using Visual Studio. Make sure the “installed version” `appSetting` is updated correctly to the **target version**.
2. Deploy to all environments - be sure to include the `appSetting` and for the Main server only, the `Umbraco.Core.RuntimeState.UpgradeUnattended` `appSetting` needs to be set to `true`.
3. Request a page on the Main server and the upgrade runs automatically without needing to authorize the upgrade.
4. Wait for the upgrade to complete.
5. Browse the Read-Only servers and make sure they don’t show the “upgrade required” screen.

Biggest difference compared to the steps you provided, is step 2.

I hope it all makes sense, and do let me know if it all makes sense.
I'll make sure the steps are added to our docs as well 💪

**Comment by sofietoft** [comment]
Steps to use unattended upgrades in load balanced setups has been added here: https://our.umbraco.com/documentation/Getting-Started/Setup/Upgrading/general#unattended-upgrades-in-a-load-balanced-setup
(it is also linked to, from the load balancing documentation)

With that, I'll close this issue for now.
Please feel free to reopen or get back with any further questions or comments you might have.

And thanks once again for helping us keeping the docs relevant for all 🙌 Much appreciated 😄
