### ISSUE TITLE
Broken link in Label page

### ISSUE THREAD

**Issue by dsychin** [umbraco/UmbracoDocs#3072]
Link to "Content Service" under "Add values programmatically" section is broken.

Correct link should be https://our.umbraco.com/documentation/reference/management/services/contentservice/

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Label.md***

**Comment by sofietoft** [comment]
Thanks for reporting this @dsychin ! 💪 

The link has now been corrected.
