### ISSUE TITLE
Broken Link - documentation/Add-ons/UmbracoForms/Installation/license

### ISSUE THREAD

**Issue by rolorogan** [umbraco/UmbracoDocs#308]
Broken link - https://our.umbraco.org/documentation/Add-ons/UmbracoForms/Installation/license

Umbraco Forms installation docs (Configuring a license) - https://our.umbraco.org/documentation/Add-ons/UmbracoForms/Installation/

**Comment by hemraker** [comment]
Thanks for reporting :)
