### ISSUE TITLE
How to trigger "You have unsaved changes" for Custom property-editor

### ISSUE THREAD

**Issue by andemt** [umbraco/UmbracoDocs#3090]
Can you please update your documentation with examples how to structure your html/js for your custom property-editor so "You have unsaved changes" appears when changing a page in Backoffice?

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Tutorials/Creating-a-Property-Editor/index.md***

**Comment by sofietoft** [comment]
Hi @andemt !

In order to help you out here, I think I need a bit more information.
Could you tell me exactly what you're trying to do here?
Where exactly are you expecting "You have unsaved changes" to appear? 🤔

**Comment by andemt** [comment]
In Backoffice, when you change a property and click on another page, a dialog pops up with ”You have unsaved changes”.

But if you follow your examples I don’t get that dialog.

**Comment by sofietoft** [comment]
Aha! 🤔 That sounds really strange!

When you noticed this - at what step in the guide were you on?
Also - which version of Umbraco are you using to run through the guide?

**Comment by andemt** [comment]
Latest version of Umbraco 8. The problem have been there at least a year. 

Should it work out of box?

**Comment by sofietoft** [comment]
Super. Thanks for letting me know!

Yeah, as far as I know, you should get that warning whenever you're switching away from something you haven't saved yet 🤔 
I'll make sure we have it checked out!

Do you remember at which step in the guide, you realized that the warning wasn't showing up?

**Comment by andemt** [comment]
So maybe update documentation how you should do a custom editor with better examples ...

**Comment by sofietoft** [comment]
Ah, cool! Great to hear you managed to work this one out yourself 💪 

I completely agree that it sounds like the samples could do with an update around this!!
Would you be up for adding the additional lines of code to the samples in the guide?
I'll make to add a review of the tutorial to our list - but in case you have a spare minute or two, you're more than welcome to take a shot at updating the docs!

**Comment by andemt** [comment]
Correct me if I am wrong, but I think `<ng-form name="textboxFieldForm">` will automatically trigger that modal if you have `<input ng-model="$scope.model.value">`.

`angularHelper.getCurrentForm($scope).$setDirty();` will help if you update $scope.model.value from angularjs-controller.

**Comment by sofietoft** [comment]
Yeah, it definitely sounds like you're on to something there!

I'll try running it past some of our angular experts to verify.

**Comment by eshanrnh** [comment]
Hi @andemt,

I am unable to produce the reported issue. I tested the steps mentioned in the [document](https://github.com/umbraco/UmbracoDocs/edit/main/Tutorials/Creating-a-Property-Editor/index.md)  for CMS version 8.16.0 and 9.0.0 and it gives me the warning message "You have unsaved changes" when changing a page in the Backoffice.

Can you let me know if you are still facing this issue?

**Comment by eshanrnh** [comment]
Closing the ticket since there has been no response/activity.
