### ISSUE TITLE
Add info about how Heartcore APIs function on Cloud

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/UmbracoDocs#3099]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
At the very top of this page - [https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/](https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/)

## Describe the issue

I would like to add the following to the article linked above:

> Heartcore comes with two different API types that can be used to fetch content; the REST API and the GraphQL API.
> 
> There's a difference between how they function in Heartcore and this section will explain what the difference is:
> 
> The REST API:
> A GET call to cdn.umbraco.io can be used to fetch data from your Heartcore backoffice and while the data comes from Heartcore we end up fetching it from the Cloudflare CDN.
> 
> Whenever any content is updated in the backoffice it'll take up to 120seconds for that change to register in the CDN which means that you will need to wait that time before your changes will show on your frontend.
> 
> The GrahpQL API:
> A POST call to graphql.umbraco.io can be used to fetch data from your Heartcore backoffice and while the data comes from Heartcore we end up fetching it from the Cloudflare CDN.
> 
> Changes made to the content in the backoffice are instantly updated in the CDN which means that there's no waiting time if you're using the GraphQL API.
> 
> The latest state of content is cached in the CDN forever until that content is updated again in the backoffice.

Things that I'm missing:

1. If a project goes down because of some random boot failed error etc. then you can still fetch data using GraphQL but not the REST API - how does it work exactly?
2. How long is the REST API data cached for of it's not forever
3. Better explanation for the REST API caching.
- Why is it different than GraphQL.
- Why does it sometimes take 5 sec and other times 120 sec for the content to update.
- Why are they different.

nr. 3 with bullet points is more of a nice to have and not really necessary but I would appreciate it if someone more experienced could help me with the missing info :)

**Comment by nul800sebastiaan** [comment]
Good suggestions for when @sofietoft and @jonat123 return after the holidays 👍

**Comment by RyuLindow** [comment]
I wrote to Rasmus about it since that's what Sofie said would be the best approach.

I'll check with him again after Easter :)

**Comment by jonat123** [comment]
As there has been no progress on this issue for some time, i will close it down for now.
