### ISSUE TITLE
Unreachable download links from page https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Healthchecks/

### ISSUE THREAD

**Issue by Jancornillie** [umbraco/UmbracoDocs#3103]
8.7.0-apply-keys-and-indexes-forms-in-db.sql and 8.7.0-apply-keys-and-indexes.sql not downloadable from page 
https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Healthchecks/

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/broken-link.md***

**Comment by jonat123** [comment]
Hey @Jancornillie good catch, i will look into it right away and see if we can get it fixed :-)

**Comment by sofietoft** [comment]
The SQL files have now been converted to Markdown files instead.

To get the scripts, simply copy and paste the code from the snippets in the links.
I'll consider this issue closed for now - please do reach out again, if something still does not add up.

Thanks again for reporting the issue!

**Comment by Jancornillie** [comment]
Thanks!
