### ISSUE TITLE
Broken Links - API Documentation to Git-Source

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/UmbracoDocs#3133]
After finding what I'm interested in using the API documentation on our.Umbraco, there is a link to [View Source] that presumably would open a new window on the relevant Git source
![image](https://user-images.githubusercontent.com/42397042/115634622-53487980-a34d-11eb-8286-05e15718b0a4.png)

It would be nice if it worked, but clicking it just ends in a 404 for me, requiring I then go and find this on Github myself.

In this example, the link is: 
https://github.com/umbraco/Umbraco-CMS/blob/8.12/src/Umbraco.Web/Media/ImageHelper.cs/#L9

I suspect the issue in this case is the '/8.12/' and that should either /v8/8.12/ or the 'current' /v8/contrib/:
https://github.com/umbraco/Umbraco-CMS/blob/v8/8.12/src/Umbraco.Web/Media/ImageHelper.cs#L9
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Media/ImageHelper.cs#L9

**Comment by nul800sebastiaan** [comment]
Thanks for reporting @c9mbundy, this has been fixed now. See https://github.com/umbraco/Umbraco-CMS/issues/9152#issuecomment-824921048 for more info.
