### ISSUE TITLE
Document new appSettings: AllowContentDashboardAccessToAllUsers

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#3136]
A new appSetting allowing the default "Getting Started" Content Dashboard to be shown for all users in the Umbraco backoffice was added in Umbraco 8.13.

This needs to be documented.
See: https://github.com/umbraco/Umbraco-CMS/pull/9999

**Comment by jonat123** [comment]
Closing this issue as it was added in #3137
