### ISSUE TITLE
Add asp to disallowedUploadFiles

### ISSUE THREAD

**Issue by mattkemp** [umbraco/UmbracoDocs#314]
After a penetration test on Umbraco version 7.4.0 assembly: 1.0.5885.31226 they found they could upload an asp file and execute it. Seems like a pretty simple change to add it to the default list of disallowed upload files in umbracoSettings.config

**Comment by mattkemp** [comment]
sorry wrong place for this

**Comment by hemraker** [comment]
http://issues.umbraco.org/ is the place for that :smiley: but thanks for reporting!!!
