### ISSUE TITLE
Need help! Our organization uses Umbraco, SMPT emails are not going out.

### ISSUE THREAD

**Issue by lcvalve** [umbraco/UmbracoDocs#3144]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/index.md***

We use Umbraco for one our apps, Umbraco uses SendGrid for SMTP for our emails. It turns out emails stopped working.
Seems UserName, Password need changing. Password generated through https://app.sendgrid.com/settings/api_keys. 
Issue: Our contact at Umbraco is no longer working at Umbraco, need someone from Umbraco to assist us with 
credentials. Please contact me at l.valverde@travisindustries.com

**Comment by sofietoft** [comment]
Hi @lcvalve !
Sorry to hear that you're having some trouble with the SMTP setting on your website.
We have some documentation about how to configure your external SMTP service on your website. You can find it right here: https://our.umbraco.com/documentation/Reference/Config/webconfig/#smtp-settings 

If you need any further help, I'd encourage you to get in touch with our friendly support team, who I'm sure will be able to help you move forward with this.
You can reach them using contact@umbraco.com.

I hope everything works out!
