### ISSUE TITLE
Umbraco 9 Documentation

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#3145]
Help wanted
--------

The release of Umbraco 9 is almost upon us, and we need to ensure that we have documentation to support it!
There is a lot of documentation that needs to be updated against Umbraco 9, and that's where we could really use your help

A lot of people will be writing and updating documentation for Umbraco 9 over the coming months.
In order to prevent that multiple people start working on the same article or topic, we've created a sheet listing all subsections in the Umbraco Documentation - one sheet for each of the main sections *Fundamentals*, *Implementation*, *Reference*, *Extending* and *Tutorials*.

* [Fundamentals](https://docs.google.com/spreadsheets/d/1SBMsjreht5rMnHysADmYMcjHFWLcAl9LzFbsSIZNxys/edit?usp=sharing)
* [Implementation](https://docs.google.com/spreadsheets/d/1r5zfT5D5N4kbZjq6YubAZLu7eXjERJh2JsALfXujuQk/edit?usp=sharing)
* [Extending](https://docs.google.com/spreadsheets/d/1g-Zwn_D4I2EQvzDwsC6_ycjkT4ny6KIBdRY40swnuSo/edit?usp=sharing)
* [Reference](https://docs.google.com/spreadsheets/d/1YyARbCbLKhqR12cfbATxyCEZ6fYYxwBXeOw-jNUyWXc/edit?usp=sharing)
* [Tutorials](https://docs.google.com/spreadsheets/d/1ya7-ss1WeqHBfpRm3hICRHyZDLAO7UeP1kMwbTmjvb8/edit?usp=sharing)

**Do you want to help out?**

There are multiple ways to let us know that you want to pitch in and help with getting the documentation updated for Umbraco 9.

* Put a comment in one of the sheets linked to above, showing us which task you'd be interested in helping out with.
* Let us know which section you'd like to help out with, by adding a comment to this issue.
* Reach out to us via docs@umbraco.com and let us know what you'd like to help out with.

Depending on the task you're interested in, we'll help you get set up 💪

Contribution guidelines
-----------------------

You can find a bunch of resources on how to contribute to the Umbraco Documentation in our [Contribute](https://our.umbraco.com/documentation/Contribute/) section.

We've also written a tutorial on how to create a new version of an already existing article. This will come in super handy when working with updating the Umbraco 9 docs.
You can find the article here:

**[How to add a new version of an article](https://our.umbraco.com/documentation/Contribute/How-to-add-a-new-verion/)**

**Comment by jemayn** [comment]
Hey @sofietoft 

Seems the Getting started sheet is broken 🙂

**Comment by sofietoft** [comment]
> Hey @sofietoft
> 
> Seems the Getting started sheet is broken 🙂

Thanks @jemayn !
I made some changes to the original sheet - should be resolved now.

**Comment by jonat123** [comment]
Since Umbraco 9 officially has been released some time ago and most of the documentation has been updated to the latest version, I will therefore close this issue down.
