### ISSUE TITLE
Need to document how to implement OAuth providers

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoDocs#317]

**Comment by sofietoft** [comment]
@Shazwazza,
Looks like this documentation has _already_ been created: https://our.umbraco.org/Documentation/Reference/Security/#back-office-users and https://our.umbraco.org/Documentation/Reference/Security/#custom-oauth-providers

Can I close this issue? 😁

**Comment by Shazwazza** [comment]
Yup! i'll close
