### ISSUE TITLE
Umbraco End of life?

### ISSUE THREAD

**Issue by xtrasmal** [umbraco/UmbracoDocs#319]
Is Umbraco still in development or what? The documentation feels like there is no love for the product. There is massive cognitive load and not enough info. 

Really makes us wonder if Umbraco is something we can trust.  So is Umbraco still being loved or is it just a milking cow that is about to die.

**Comment by dampee** [comment]
The documentation has had an insane rework last year by @hemraker. And it keeps on growing on a steady pace.  All information can be found in either the forums where lots of community members are willing to help you.  
Umbraco HQ is a company employing real (and intelligent) people, providing paid support if you want to.  Umbraco is running websites like www.asp.net among [almost 350k installs](https://twitter.com/umbraco/status/718323372258693120).  Whether that convinces you to trust umbraco is up to you of course.  

However, I am not sure why you are posting this question on the documentation issue tracker.

**Comment by nul800sebastiaan** [comment]
Umbraco is alive and kicking! We release a new and improved version every months and see about a 1000 installs every day. Many large corporations trust Umbraco (recent examples that come to mind: the NFL, Carlsberg and Red Bull).

If you are just getting started then our self-paced learning platform, Umbraco TV might be for you. Subscribe for tutorials and "how-to" videos http://umbraco.tv/

If you have any questions, the first destination being the Our Umbraco forum. Please post your question here (https://our.umbraco.org/) so that the dedicated community can help you find a solution!

**Comment by coding3d** [comment]
Many years ago, when I first discovered Umbraco I couldn't understand much from its documentation either (I haven't checked it out lately). But Umbraco TV + experimentation was, and I guess still is, the quick & fun way to go, thanks to its intuitive interface & API.

**Comment by alindgren** [comment]
Also check out the training available: http://umbraco.com/products/training/schedule

I always wish documentation was better but it has improved quite a lot over the last year.

**Comment by xtrasmal** [comment]
@dampee Did not know that. Still there are metric tons of info that could be added.

@nul800sebastiaan Thanks. I hope that the documentation keeps improving. Right now, it feels like it's been neglected. Umbraco TV sounds nice, but it should be in the documentation first. The documentation needs 1000+ more pages or so. And more coherency. It makes Umbraco feel like a dead unloved project.

If a 14 year old just bought a computer and wanted to create C# websites using Umbraco for it's CMS ..he/she would be slamming it's head against the wall out of desperation and skip the project. Cognitive load is not very child-friendly. 

@coding3d Experimentation is great, but the documentation doesn't invite newcomers to go that route. Cause software is as great as it's documentation...right?

Anyways.. I'm stuck with you guys for a while :) ploughing away through the muddy mystical forest, cause  my employer embraces Umbraco. Good luck.

**Comment by dampee** [comment]
@xtrasmal You know you are using open source.  Don't hestiate to improve documentation, or ask for help with topic you feel that are missing.

What specific topic are missing according to you?

**Comment by coding3d** [comment]
@xtrasmal I get what you're saying. I know it's a very weird way to learn it but it worked for me. I had never learned anything this way before I came across Umbraco, neither have I had the opportunity to repeat the experience with another product, not successfully at least. But strangely enough, with Umbraco, it just works...
