### ISSUE TITLE
Link to umb-property-editor from reference is incorrect

### ISSUE THREAD

**Issue by michael-JJ** [umbraco/UmbracoDocs#3193]
The anchor behind the "umb-property-editor" text links to the wrong URL, somehow the dots were replaced with underscores.
The link is correct in the markdown file but incorrect on the Umbraco website ([umbProperty page](https://our.umbraco.com/documentation/Reference/Angular/Directives/umbProperty/)).

![image](https://user-images.githubusercontent.com/36151123/118518845-d5537480-b738-11eb-934f-266a14172f78.png)

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Angular/Directives/umbProperty/Index.md***

**Comment by busrasengul** [comment]
Hey @michael-JJ 
You're absolutely right about it! It's an interesting one 🤷‍♀️
I get the same underscored link on my machine and on different browsers as well!
Thank you for flagging this out! I'll be sure we'll investigate this!

#h5yr! 🙌

**Comment by busrasengul** [comment]
Hey @michael-JJ 
There was an extra space before the link in markdown and that was causing the issue! 
We've now fixed it 🎉

Thanks and #h5yr!!
