### ISSUE TITLE
Use Deploy dashboard as the default way of performing Umbraco Deploy commands on Cloud

### ISSUE THREAD

**Issue by hjaltedaniel-umbraco** [umbraco/UmbracoDocs#3218]
## What type of issue is it? (Choose one - delete the others)
Discussion

## What article/section is this about?
https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Power-Tools/Manual-extractions/
https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Power-Tools/generating-uda-files/
https://our.umbraco.com/documentation/Umbraco-Cloud/Troubleshooting/
(Just a few examples, there are probably more around different corners of the docs)

## Describe the issue
With Umbraco Deploy 4, the long-awaited Deploy dashboard was introduced. This gives the user an easy way of extracting schema to the database, exporting deployment artifacts, and clearing cached signatures, without having the un-friendly experience of writing somewhat arbitrary commands in a tool you might not know (Kudu).

With this issue, I propose a discussion of re-writing the docs, so that the Deploy dashboard is the default way of performing the different operations that are possible to do with Umbraco Deploy. The dashboard itself is already fairly well documented in the [deploy section of the docs ](https://our.umbraco.com/documentation/Add-ons/Umbraco-Deploy/deployment-workflow/#deploy-dashboard).

**Comment by jonat123** [comment]
@hjaltedaniel-umbraco I agree that with the new deploy dashboard it makes complete sense that it should be the default way we recommend using the different operations like ehco>deploy/Export and etc. rather than kudu on Umbraco Cloud 🙂

Just tagging @sofietoft so she can chime in as well when she is back tomorrow :)

**Comment by sofietoft** [comment]
I think it's a great idea to recommend people using the Deploy Dashboard instead of the commands through KUDU! 💪

Now, I just wanna make sure I've understood correctly...
You're volunteering to update the articles, @hjaltedaniel-umbraco ? 😉 😄

**Comment by hjaltedaniel-umbraco** [comment]
I'll look into submitting a PR when I find time for it, then we can take it from there 👍
