### ISSUE TITLE
Document how cache refreshers work (ICacheRefresher)

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoDocs#323]

**Comment by sofietoft** [comment]
@Shazwazza,
Looks like someone started on these docs, but didn't quite finish?
https://our.umbraco.org/Documentation/Reference/Cache/cache-refresher

Ah, and it's related to this: https://github.com/umbraco/UmbracoDocs/issues/208, right?

**Comment by dampee** [comment]
it is linked indeed :-)

**Comment by dampee** [comment]
@sofietoft I think we should close this issue as it is linked to the #208
