### ISSUE TITLE
Document how cache refresher events work (CacheRefresherBase<PageCacheRefresher>.CacheUpdated)

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoDocs#324]

**Comment by ZNS** [comment]
Googled CacheRefresherBase and the first thing I found was this. I'd really like to see some docs on this :)

**Comment by sofietoft** [comment]
See: https://github.com/umbraco/UmbracoDocs/issues/323 and https://github.com/umbraco/UmbracoDocs/issues/208

**Comment by jmayntzhusen** [comment]
Hi there!

As this issue has been here for over a year without any PRs, we have decided to close it down. 
If you feel the problem is still there, then please open a new issue with as many details as you can so someone has a chance to work on it!

Thanks for reporting it in the first place! 🙂
