### ISSUE TITLE
New Documentation is using obsolete code for Url

### ISSUE THREAD

**Issue by russellshome** [umbraco/UmbracoDocs#3259]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker-3/index.md***

Examples such as
&lt;img src="@entry.MediaItem.Url" style="width:200px"/&gt;

should be
&lt;img src="@entry.MediaItem.Url()" style="width:200px"/&gt;

**Comment by busrasengul** [comment]
Hey @russellshome 
Thanks for flagging this up 🙌
You are right about the examples. Would you be kind to do a PR to update them? If not we'll get back at it asap!
Thank you :)
