### ISSUE TITLE
Umbraco 8+ documentation should be updated for ChangeContentType

### ISSUE THREAD

**Issue by WesselKroos** [umbraco/UmbracoDocs#3263]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
https://our.umbraco.com/documentation/reference/management/models/content#changecontenttypeicontenttype-contenttype

## Describe the issue
We've waisted a good hour trying to figure out why a method did not exist in our project. We figured it out when we found an issue in which the decision was made to remove this method from version 8+:
https://github.com/umbraco/Umbraco-CMS/issues/5070

It seems that this documentation is as old as version 6. But it should not be shown as relevant for version 8.

**Comment by busrasengul** [comment]
Hey @WesselKroos 
Sorry to hear you've lost time on this. The article shows it's for V6 and I've checked as well, it hasn't been updated for V8. (It does have a YAML tag 'needsV8Update: "true"')
We'll make sure someone looks into updating the document. But in the meantime maybe you would like to give us a PR with V8 relevant? 🙌
