### ISSUE TITLE
Upgrade from Umbraco version 7.14.0 to 8.1.0 fails

### ISSUE THREAD

**Issue by shubhashinisaggezza** [umbraco/UmbracoDocs#3266]
Upgrade from Umbraco version 7.14.0 to 8.1.0 fails.

Please check the upgrade error 
The database failed to upgrade. ERROR: The database configuration failed with the following message: After parsing a value an unexpected character was encountered: ". Path 'toolbar[1]', line 4, position 4. 

Please find log attached
[UmbracoTraceLog.SGZ-IN01082.20210611.zip](https://github.com/umbraco/UmbracoDocs/files/6643790/UmbracoTraceLog.SGZ-IN01082.20210611.zip)

**Comment by jonat123** [comment]
Hi @shubhashinisaggezza 

Sorry to hear that you're having some trouble with upgrading your website.

We have some documentation about how to migrate from Umbraco 7 to 8 here: https://our.umbraco.com/Documentation/Fundamentals/Setup/Upgrading/migrating-to-v8#migrating-content-to-umbraco-8

If you need any further help, I'd encourage you to reach out in our forum here:

- https://our.umbraco.com/forum/

I hope everything works out!
