### ISSUE TITLE
Umbraco Forms Rendering-Scripts 404 error

### ISSUE THREAD

**Issue by OwainWilliams** [umbraco/UmbracoDocs#3305]
## What type of issue is it? (Choose one - delete the others)
There is a 404 link on the documentation for Umbraco Forms when you click on Rendering Form Scripts

## What article/section is this about?
https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/

## Describe the issue
I tried to work out why there is a 404 on this link but unfortunately couldn't fix it myself or submit a PR to fix it. 
The files seem to be within the repo but for what ever reason the link just doesn't work.

**Comment by busrasengul** [comment]
Thank you for raising this issue @OwainWilliams 
We're looking into this 👍

**Comment by busrasengul** [comment]
This is fixed now @OwainWilliams 🎉
