### ISSUE TITLE
SetDefaultRenderController is not available / required

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco/UmbracoDocs#3331]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Routing/custom-controllers-v9.md***

***This is the section with issues: https://our.umbraco.com/Documentation/Reference/Routing/custom-controllers-v9#replace-umbracos-default-rendercontroller***

I tried setting the default controller as instructed, but found out that the `SetDefaultRenderController()` extension method does not exist - at least in Umbraco `v9.0.0.rc-001` - and is not required either.  The default controller replacement works without that, just by using the `services.Configure<UmbracoRenderingDefaultsOptions>( )` method as described by this [discussion](https://github.com/umbraco/Umbraco-CMS/discussions/10608)

If that's the case, please remove the reference to the `SetDefaultRenderController` method from the 'Replace Umbraco's default RenderController' section of the page. Thanks!

**Comment by JoseMarcenaro** [comment]
Thanks @marcemarc  for fixing this!

**Comment by marcemarc** [comment]
> Thanks @marcemarc for fixing this!

would love to take some credit, but as I went to update it, found @erikjanwestendorp had already done so... #h5yr's in his direction!

**Comment by erikjanwestendorp** [comment]
Thanks @marcemarc 😄
