### ISSUE TITLE
Document v9 External Login Providers

### ISSUE THREAD

**Issue by cleversolutions** [umbraco/UmbracoDocs#3339]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
https://github.com/umbraco/UmbracoDocs/blob/main/Umbraco9Articles.md

## Describe the issue
In v8 we used a wonderful Nuget package by @Shazwazza to add external login providers. That package won't be ported to v9. I would like to write an article on how to add external login providers to v9 to help others.

**Comment by busrasengul** [comment]
Hey @cleversolutions 
It's a great idea! 
Looking forward to your article! 🎉
With editing this page(https://our.umbraco.com/Documentation/Reference/Security/external-login-providers), you can create your V9 version and we'll get it reviewed after your PR!
🙌

**Comment by cleversolutions** [comment]
Thanks @busrasengul I’ll put something together today. This is my first docs contribution so I expect I’ll have a lot to learn doing it.

**Comment by busrasengul** [comment]
That's amazing @cleversolutions 
Happy to help if you need it!

**Comment by jonat123** [comment]
Closing this issue as the PR created for it have been merged in 😀

Good work @cleversolutions 😄
