### ISSUE TITLE
Custom controllers docs needs to remove the part about "In the near future we will allow setting a custom default controller"

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoDocs#337]
This part "In the near future we will allow setting a custom default controller..." needs to be removed from https://our.umbraco.org/Documentation/Reference/Routing/custom-controllers because it's actually implemented and documented.

**Comment by marcemarc** [comment]
PR here: https://github.com/umbraco/UmbracoDocs/pull/661

**Comment by Jeavon** [comment]
#661 was merged so closing
