### ISSUE TITLE
This page needs documentation on how to actually use relations.

### ISSUE THREAD

**Issue by Slipoch** [umbraco/UmbracoDocs#3370]
We need actual documentation here. On how to use it on specific node types etc.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Management/Models/Relation.md***

**Comment by erikjanwestendorp** [comment]
@Slipoch Good point! There is already a v9 version, which is almost the same as v8 only the using statements and namespaces are different. You can find the v9 version [here](https://our.umbraco.com/documentation/Reference/Management/Models/Relation-v9). I will make a v8 version of the article and make a PR.

**Comment by jonat123** [comment]
@Slipoch thanks to Erik, the documentation have now been updated :D 

I'll close this issue down 😊
