### ISSUE TITLE
Multilanguage setup link 

### ISSUE THREAD

**Issue by LionelSlade** [umbraco/UmbracoDocs#3381]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Tutorials/index.md***
When selecting the Mutilanguge hyperlink from index.md:

Runtime Error
Description: An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated.

**Comment by busrasengul** [comment]
Thank you for flagging this issue @LionelSlade 
We will check this 👍
