### ISSUE TITLE
Loading the Property Editors page displays v7 content, when v8.0.0+ is preselected

### ISSUE THREAD

**Issue by liamlaverty** [umbraco/UmbracoDocs#3391]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Backoffice/Property-Editors/index.md, which renders this page on _our_: https://our.umbraco.com/Documentation/Fundamentals/Backoffice/Property-Editors/***

## Issue
See image below, I've landed on the page, and `8.0.0 + (current)` is preselected on the right, but the content displayed is from `7.0.0 +` instead of `8.0.0 - 9.0.0`

---

## What I saw:

![image](https://user-images.githubusercontent.com/7046713/129358739-80cfea89-7390-470d-80f8-64cf62e4d99c.png)

---

## What I expected to see
![image](https://user-images.githubusercontent.com/7046713/129358965-6597cba4-790d-4cfe-9a91-54e50b058b08.png)

--- 
### Other details
Happens in Chrome, Edge, Firefox, all in private browsing with no plugins/extensions installed.

**Comment by busrasengul** [comment]
Thank you @liamlaverty for flagging this issue. I'll make sure we check this 👍
