### ISSUE TITLE
Custom Indexer in Azure Web App show's weird behavior

### ISSUE THREAD

**Issue by MjDhaneshKumar** [umbraco/UmbracoDocs#3392]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Setup/Server-Setup/azure-web-apps.md***

_Umbraco Version_: **_8.14.2_**

_Env_: **_Azure Web App_**

_Followed recommended settings_: [Recommended settings as per Doc](https://our.umbraco.com/Documentation/Fundamentals/Setup/server-setup/azure-web-apps#recommended-configuration)

Created a custom index as per the doc here https://gist.github.com/hartviglarsen/44743b32d4eea8eda3fb6d49b60dd547 and it's working fine as expected in my local environment, but it's not working as expected in DEV(_Azure Web App_).

The custom indexer is changing against the browser session & that's weird. For example: if we login to the Umbraco from a browser session and indexed successfully and tried to login from another browser session or in incognito mode then go to examine settings and we can't see the indexed data, and we need to index separately to view in the new session. It is changing against the browser session.

_**Before indexing from the browser (session 1)**_

![1](https://user-images.githubusercontent.com/58820887/129678445-f65ebbaf-dd29-4f92-81b6-9578a1a749aa.png)

**_Indexing from the browser (session 1) and successfully indexed._**

![2](https://user-images.githubusercontent.com/58820887/129678585-387626bb-8adb-43f6-b2e8-5e861074a621.png)

**_And if we try to search from the same browser session(session 1) then the result will show correctly, but if tried to login from another session (incognito mode), then it show's the data is not indexed :(_**
_See backend_

![3](https://user-images.githubusercontent.com/58820887/129678682-b75e3210-e82b-4ce9-bcfc-047178a1b170.png)

**_Please find this video for more info_** : [VIDEO](https://jumpshare.com/v/A2nmuu9KRlw7GUHMB4kw)

**Comment by busrasengul** [comment]
Thank you @MjDhaneshKumar for flagging this issue. I'll be sure we check this 👍

**Comment by MjDhaneshKumar** [comment]
Thanks, @busrasengul  , it is fixed now, by setting up the environment correctly.
