### ISSUE TITLE
Broken links/Missing articles in Umbraco 9 documentation

### ISSUE THREAD

**Issue by hemraker** [umbraco/UmbracoDocs#3431]
## What article/section is this about?
https://our.umbraco.com/documentation/Umbraco9Articles 

## Describe the issue
The first 14 articles in the Reference section are not available. I'm not sure whether these are broken links or the docs haven't actually been updated yet. I've highlighted the ones that don't work here:

![image](https://user-images.githubusercontent.com/3663619/131631080-6bf3f15a-2089-4828-a457-e83b3b3e69db.png)

**Comment by busrasengul** [comment]
I just checked it and you're correct @hemraker 
I'll investigate this asap.🤞🏼
Thank you 🙌

**Comment by hemraker** [comment]
I think it's the link that is the problem. In Umbraco 9 there is no article for Umbraco 9 as stated on the v8 version:
![image](https://user-images.githubusercontent.com/3663619/131646903-f2036339-03ec-4d0b-ae4b-2c71ea6869a4.png)

Either linking to the v8 article (which says where to find the new v9 docs) or Updating the list to something like:
* ContentService Events ->[ContentService Notifications](https://our.umbraco.com/documentation/Reference/Notifications/ContentService-Notifications)
* ContentTypeService Events -> [ContentTypeService Notifications](https://our.umbraco.com/documentation/Reference/Notifications/ContentTypeService-Notifications)

might just do the trick :)

**Comment by busrasengul** [comment]
I'm sure we have V9 articles for all the listed topics there, apparently, we put the wrong ones :) I'll find the right ones and update the links! Thank you @hemraker

**Comment by busrasengul** [comment]
Should be all fixed now :)

**Comment by hemraker** [comment]
Nice work! H5YR 🙌
