### ISSUE TITLE
Umbraco-Deploy/FAQ Missing

### ISSUE THREAD

**Issue by Deepti-Des** [umbraco/UmbracoDocs#3439]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
https://our.umbraco.com/Documentation/Add-ons/Umbraco-Deploy/FAQ

**Comment by jonat123** [comment]
@Deepti-Des  thanks for pointing this out!

Looks like an oversight from our side when we created the docs for deploy 😅
