### ISSUE TITLE
umbra.co/uaas-cmd  link is not working

### ISSUE THREAD

**Issue by Sub-Z3r0** [umbraco/UmbracoDocs#3450]
The link provided for umbraco cloud for VS is not working.  

Tried different browser and clearing cache. 

I get redirected to 

https://umbracoreleases.blob.core.windows.net/download/UaaS.cmd

And this is the message I see

@ECHO OFF
ECHO One second...
ECHO Downloading helper executable (Waasp.exe)
powershell -ExecutionPolicy Bypass -Command "(New-Object Net.WebClient).DownloadFile('https://umbracoreleases.blob.core.windows.net/download/Waasp.exe', 'Waasp.exe')"

SET /P url="Clone URL: " 
SET /P alias="Namespace: "

REM From https://stackoverflow.com/a/33155502/5018
for %%a in ("%url%") do (
   set "urlName=%%~NXa"
)
REM Remove `.git` suffix
SET identifier=%urlName:.git=%

IF NOT EXIST %alias%.Web (
	git clone %url%
)

IF EXIST %identifier% REN %identifier% %alias%.Web

Waasp.exe "%CD%" %alias% %url%
DEL Waasp.exe /Q

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/index.md***

**Comment by busrasengul** [comment]
You're right @Sub-Z3r0 
We'll update the download url 👍

**Comment by jonat123** [comment]
@Sub-Z3r0 The issue should be fixed now.

Can you try and download it and confirm that it works? 🙂

**Comment by jonat123** [comment]
This should work now.

Closing this issue down.
