### ISSUE TITLE
Missing doc for large-media-libraries

### ISSUE THREAD

**Issue by Deepti-Des** [umbraco/UmbracoDocs#3459]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
https://our.umbraco.com/documentation/Umbraco-Cloud/Deployment/Deploy-Settings/#large-media-libraries

## Describe the issue
Link here is broken instead of pointing to https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Media/ (I guess:-)
![image](https://user-images.githubusercontent.com/84541746/133049516-a4df5ab8-af30-4575-85de-9e7710af91b2.png)

**Comment by jonat123** [comment]
@Deepti-Des thanks for spotting this!

I created this PR to fix issue #3460 🙂

**Comment by jonat123** [comment]
@Deepti-Des looks like that fixed the issue :D 

Again thanks for reporting this!
