### ISSUE TITLE
Missing "Common Pitfalls" for Umbraco v9

### ISSUE THREAD

**Issue by dalyUSN** [umbraco/UmbracoDocs#3500]
## What type of issue is it? 
Missing documentation

## What article/section is this about?
https://our.umbraco.com/documentation/Reference/Common-Pitfalls

## Describe the issue
Click on the link to "Common Pitfalls" and you will be, somewhat ironically, presented with an "Oooops, something broke" message. D'oh! :-)

**Comment by Jeavon** [comment]
There is a v9 version in the works however slightly preemptively the index file has been renamed, you can access it at https://our.umbraco.com/documentation/Reference/Common-Pitfalls/index-v7

**Comment by jonat123** [comment]
@dalyUSN We have added the documentation for V9, so you can see it now :D 

I'll close this issue 😊

**Comment by dalyUSN** [comment]
Awesome, thanks for the update! #h5yr
