### ISSUE TITLE
v9 Advanced techniques with Flexible Load Balancing code samples need updating

### ISSUE THREAD

**Issue by tomten** [umbraco/UmbracoDocs#3503]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
UmbracoDocs/Fundamentals/Setup/Server-Setup/Load-Balancing/flexible-advanced.md

## Describe the issue
I think `ServerRole.Master` is now `ServerRole.SchedulingPublisher`, and the front-end read-only role `ServerRole.Subscriber`.

**Comment by Jeavon** [comment]
@tomten could you post a specific link, I believe we already updated all relevant docs with this change?

**Comment by tomten** [comment]
https://our.umbraco.com/Documentation/Fundamentals/Setup/Server-Setup/Load-Balancing/flexible-advanced had the code `ServerRole.Master` when I created this issue, i.e. the previous commit. Could have been a cache issue on my side. I can see that it's fixed now. Thanks!
