### ISSUE TITLE
Update cache example?

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#3524]
Wouldn't it be nice to update this [article](https://our.umbraco.com/documentation/Reference/Cache/examples/tags)? I think it would be nice to modify the code samples a bit and use ICacheRefresher. It's a bit contradictory to the warning in the [main article](https://our.umbraco.com/documentation/Reference/Cache/) now.

![image](https://user-images.githubusercontent.com/7831614/135825558-c03a4f8d-57fd-48f4-86d3-be8d779b7661.png)

**Comment by sofietoft** [comment]
Hi 👋 
I'm going through our Issue tracker to clean up a bit.

What's the status on this? Was the article on working with caching updated?

**Comment by erikjanwestendorp** [comment]
@sofietoft Sorry I totally forgot this one 😅 . I'll update the article and create a PR.

**Comment by sofietoft** [comment]
No worries! 😄 
Good thing I'm back to keep you all on your toes 🤪

Sounds awesome! Thanks.
