### ISSUE TITLE
Recaptcha Error for Recaptcha v2 in Umbraco v9

### ISSUE THREAD

**Issue by stefanie27** [umbraco/UmbracoDocs#3526]
Hello,

I get following error within the Umbraco Form using Recaptcha v2:

ERROR: ReCaptcha v2 is missing the Site Key. Please update the configuration to include a value at: Umbraco:Forms:FieldTypes:Recaptcha3:PublicKey

I have added the public and private key in appsettings.json like the documentation describes:

"Forms": {
      "Recaptcha2": {
        "PublicKey": "OurPublicKey",
        "PrivateKey": "OurPrivateKey"
      }
}

But it looks like according to the error message the setting needs to be the following

"Forms": {
    "FieldTypes": {
          "Recaptcha2": {
            "PublicKey": "OurPublicKey",
            "PrivateKey": "OurPrivateKey"
          }
    }
}

Kind regards,
Stefanie.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/Recaptcha2/index.md***

**Comment by jonat123** [comment]
@stefanie27 Good catch, looks like you are correct, I'll update the documentation right away 😊

**Comment by jonat123** [comment]
#3531 created this PR to post the correct information :-)

**Comment by DennettCTUIR** [comment]
I am getting this error, but my appsettings.json file shows correctly as in the example above. Like this...
"Forms": {
"FieldTypes": {
"Recaptcha2": {
"PublicKey": "OurPublicKey",
"PrivateKey": "OurPrivateKey"
}
}
}

Umbraco version 10.4.0
Current installed version of Umbraco Forms: 10.4.0

Is there any advice for this? I've been "Googling" for two days and submitted an Umbraco Forms Support ticket, but nothing has gotten me closer to a resolution. Thanks for any help anyone can offer.

**Comment by sofietoft** [comment]
Hi @DennettCTUIR !

I'm sorry to hear that you're running into this issue.
This is not really the place for handling these kind of things, and it sounds like you've reached out the correct places.
Hopefully you'll get a reply with the information you need there.

In any case, perhaps it could be worth looking into upgrading your project or perhaps, switching to recaptcha v3 instead.

I hope you manage to work this out!
/Sofie
