### ISSUE TITLE
Removing headers when hosted on Kestrel - type issue

### ISSUE THREAD

**Issue by warrentheranga** [umbraco/UmbracoDocs#3552]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Extending/Health-Check/Guides/ExcessiveHeaders.md***

current code block is: 

`public class Program
{
    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup()
                .UseKestrel(x => x.AddServerHeader = false);
            });
}`

i think this needs to be:

`public class Program
{
    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>()
                .UseKestrel(x => x.AddServerHeader = false);
            });
}`

thank you

**Comment by erikjanwestendorp** [comment]
@busrasengul Seems to be fixed already 😄
