### ISSUE TITLE
Document `AutoValidateAntiforgeryToken` attribute on SurfaceController

### ISSUE THREAD

**Issue by bjarnef** [umbraco/UmbracoDocs#3560]
## What type of issue is it?
Missing documentation

## What article/section is this about?
https://our.umbraco.com/documentation/reference/routing/surface-controllers

## Describe the issue
In Umbraco V9 SurfaceController is by default decorated with `AutoValidateAntiforgeryToken` attribute, which expect the `__RequestVerificationToken` in the HTML and verify this in the controller. However that wasn't the case in V8 and it seems e.g. a POST ajax request by default will return 404 Bad Request.

See example here https://github.com/umbraco/Umbraco-CMS/pull/9762#issuecomment-940216851

**Comment by busrasengul** [comment]
Thanks for raising this @bjarnef 
We'll check this issue soon!

**Comment by eshanrnh** [comment]
Hey @bjarnef 👋

I am closing this issue since we already have another issue (#3242) open.
