### ISSUE TITLE
Add info about upgrading SQLCE as well?

### ISSUE THREAD

**Issue by BatJan** [umbraco/UmbracoDocs#3565]
I just did an upgrade from Umbraco 9.0.0RC2 to Umbraco 9.0.1 following the instructions in this page https://our.umbraco.com/documentation/Fundamentals/Setup/Upgrading/general and I initially failed to do it properly because I am using SQL CE in this project. So I'm wondering if it would make sense to add a tip/warning that if one is using SqlCE it's needed to run `dotnet add package Umbraco.Cms.SqlCe --version <VERSION>` as well before running `dotnet restore` making it very explicit? 😃 

I'll be happy to do a PR for it if it appears to be a good and helpful idea 👍🏻

**Comment by busrasengul** [comment]
Hey @BatJan 
Thank you for raising this issue, and yes I think it'd be great if you could create a PR in the related page with a markdown format :)
```
:::warning
Your warning here
:::
```

**Comment by BatJan** [comment]
@busrasengul Ace - I've made a PR for it here https://github.com/umbraco/UmbracoDocs/pull/3574

**Comment by jonat123** [comment]
Closing this as the PR have been merged in 😄
