### ISSUE TITLE
HtmlString vs IHtmlEncodedString

### ISSUE THREAD

**Issue by Myster** [umbraco/UmbracoDocs#3573]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Templating/Modelsbuilder/Introduction.md***

This page shows that a modelsbuilder class with a property that is IHtmlEncodedString will output without the use of Html.Raw or without the use of new HtmlString(modelsBuilderObject.PropertyName.ToHtmlString())

This is not my experience, if I don't do one of these things the HTML is escaped and I see markup on my rendered page.

I would prefer modelsbuilder to produce HtmlString properties rather than using a proprietary IHtmlEncodedString which I don't understand. (perhaps this should be a bug report, not a documentation change.)

**Comment by jonat123** [comment]
Hey, @Myster I will close this issue down as it seems to be more of a CMS issue than a docs issue as mentioned in my above comment I would recommend creating it on the CMS tracker :-) 

Have a great day!
