### ISSUE TITLE
DatabaseServerMessengerOptions needs docs to show how to configure options on startup

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoDocs#359]
During startup the `DatabaseServerMessengerOptions` can be tweaked to control how often the load balancing instructions from the database are processed and pruned.

**Comment by Jeavon** [comment]
I can write this, but do you know a use case?

As far as I can tell sample code would be like this:

	namespace BearTheLoad.Logic.ServerRegistrars
	{
		using Umbraco.Core.Sync;

		public class BearTheLoadDatabaseServerMessengerOptions : DatabaseServerMessengerOptions
		{
			public BearTheLoadDatabaseServerMessengerOptions()
			{
				DaysToRetainInstructions = 2; // 2 days
				ThrottleSeconds = 5; // 5 second
				MaxProcessingInstructionCount = 1000;
				PruneThrottleSeconds = 60; // 1 minute
			}
		}
	}

And then in ApplicationStarting:

	ServerMessengerResolver.Current.SetServerMessenger(
		new DatabaseServerMessenger(applicationContext, true, new BearTheLoadDatabaseServerMessengerOptions())
	);

**Comment by Shazwazza** [comment]
You don't need to subclass the options, just set the properties when you create the options. 

If people don't want it checking instructions so often they could adjust here, i guess it depends on how much the site is serving and how often things are being published.

**Comment by Shazwazza** [comment]
Or maybe you know you take servers offline for a few days, I'm which case you'd want to retain instructions longer. 

Lastly, maybe you want to cold boot with less pending Max instructions

Really depends on what your site is doing i guess.

**Comment by Jeavon** [comment]
Cool, I'll write it up.

Code sample something like this then:

	ServerMessengerResolver.Current.SetServerMessenger(
		new DatabaseServerMessenger(
			applicationContext, 
			true, 
			new DatabaseServerMessengerOptions() {
				DaysToRetainInstructions = 2, // 2 days
				ThrottleSeconds = 5, // 5 second
				MaxProcessingInstructionCount = 1000,
				PruneThrottleSeconds = 60 // 1 minute
			}
		)
	);

**Comment by sofietoft** [comment]
Hi @Jeavon,

I'm currently working my way through the issue tracker here on the Docs.
Any chance you can give me a status on this? 😁 
I haven't been able to locate anything about this in the docs, but I might very well be looking the wrong places.

-Sofie

**Comment by Jeavon** [comment]
@sofietoft I will create the docs for this, assigned to myself :)
