### ISSUE TITLE
Fix PackageActions Documentation

### ISSUE THREAD

**Issue by BeardInASuit** [umbraco/UmbracoDocs#3601]
I see that there are many [changes ](https://github.com/umbraco/Umbraco-CMS/pull/10567/)to PackageActions that are not yet documented. 

I would suggest to at least remove mentions to old implementation in v9 documentation and refer temporarily to the [blog article](https://umbraco.com/blog/packages-in-umbraco-9-via-nuget/).

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Extending/Packages/Package-Actions/custom-package-actions.md***

**Comment by jonat123** [comment]
@BeardInASuit thanks for creating this issue!

I can see that this article was verified on the alpha and as you correctly state, there have been many changes to how packages are being implemented since then.

I'll add it to our backlog and make sure that we look into the article and update it for the latest v9 version 🙂

**Comment by jonat123** [comment]
@BeardInASuit Quick update!

I reached out to Bjarke from the CMS team, and he says that Package actions have been removed after the move to NuGet and if you want to do something similar you will need to use Package migrations instead.

I, therefore, think it is best to just completely remove the articles regarding package actions in V9.

**Comment by jonat123** [comment]
I've  created this  PR: #3623 for removing the package actions for V9 as well as adding a note for the V8 documentation stating that it has been removed and links to package migrations instead if you want to do something similar in V9 :)

**Comment by jonat123** [comment]
@BeardInASuit I merged in my PR, I'll close this issue.
