### ISSUE TITLE
Link to explain what are Singletons and Statics

### ISSUE THREAD

**Issue by mattou07** [umbraco/UmbracoDocs#3614]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
https://our.umbraco.com/documentation/Reference/Common-Pitfalls/

## Describe the issue
There should be a hyperlink to what Singletons or Statics are.

**Comment by jonat123** [comment]
@mattou07 thanks for raising this issue 🙂

The PR #3618 have been merged in with links explaining what singletons and statics are 😄

I'll close this issue then 🙂

**Comment by mattou07** [comment]
Thanks @jonat123
