### ISSUE TITLE
Database-article should show how to query the database

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/UmbracoDocs#3617]
Hi!

The article about a custom table explains well how to create a table in V9, but it does not show how to query the table and the best practice around this.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Extending/Database/index.md***

**Comment by jonat123** [comment]
Hello, @enkelmedia thanks for creating this issue 🙂

Just to be sure that I understand, do you want the article to go into how you can query and show the custom data that you have created in the custom table?

**Comment by enkelmedia** [comment]
@jonat123 Yes, I could not find any examples on how to fetch the data, I'm talking about using the IScopeProvider to create a scope, complete scope, write data etc.
