### ISSUE TITLE
Umbraco 9 examples needed

### ISSUE THREAD

**Issue by AlexSkennerton** [umbraco/UmbracoDocs#3634]
Are there plans to update this page to include examples for Umbraco 9?

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Searching/Examine/Quick-Start/index.md***

**Comment by jonat123** [comment]
@AlexSkennerton Thanks for your PR and sorry for the long wait for a reply...

It is on our list to get the examples updated, however, it is a bigger task so it takes a bit longer to get it updated.

**Comment by zach-ligenza** [comment]
I am curious to see this documentation updated for Umbraco 9 as well! =)

**Comment by alandraper** [comment]
Anyone know how to do the custom ContentValueSetValidator? Without it, search is useless.
