### ISSUE TITLE
backup of the database from your Umbraco 8 project

### ISSUE THREAD

**Issue by monais** [umbraco/UmbracoDocs#3655]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/broken-link.md***

**Comment by busrasengul** [comment]
Hey @monais 
Thank you for flagging this issue.
The link you shared is just a general link when the page is not found. Would you be able to share the actual page where the link is broken?

**Comment by sofietoft** [comment]
Hi @monais !

It's been a while, and as we haven't heard back from you, we'll close this issue for now.
Should you continue to run into issues, please do let us know and we'll do our best to help out!

Thanks again for helping us make the Umbraco docs even better 💪
