### ISSUE TITLE
Drag and drop between block lists

### ISSUE THREAD

**Issue by claushingebjerg** [umbraco/UmbracoDocs#3684]
More a feature request than a bug.

I have several editors on projects complaining that it's not possible to drag and drop a block from one block list to another block list...

To move block you have to go through this process:

1. Copy the block
2. Click "add content" on the other block list.
3. Choose "Clipboard"
4. Choose the copied block.
5. Delete original block

It would be really nice if the editor could just drag'n drop the relevant block from one block list to the other (if type is allowed).

https://user-images.githubusercontent.com/1854789/145378271-e7df7dea-f55f-44a6-bc8c-f0a0054286e7.mov

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md**
*

**Comment by jonat123** [comment]
Hello, @claushingebjerg thanks for creating this issue 🙂

That does indeed sound like a good idea and a nice feature!

However as this is the repository for the documentation, we can not really do anything about it.

I will recommend that you create a feature request on the [Umbraco CMS repository](https://github.com/umbraco/Umbraco-CMS) instead :-)

I will therefore close this issue 🙂
