### ISSUE TITLE
Config Transforms still mentions Umbraco Latch

### ISSUE THREAD

**Issue by greystate** [umbraco/UmbracoDocs#3685]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Umbraco-Cloud/Set-Up/Config-Transforms/index.md***

This page mentions that all sites (since v7.12) contains a `Latch.Web.live.xdt.config` file (https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Config-Transforms/#umbraco-latch-transforms) with a link to more info (https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Manage-Hostnames/Umbraco-Latch/index#https-by-default), which returns a 404.

**Comment by jonat123** [comment]
@greystate thanks for bringing this to our attention! 

This file does not exist anymore on new projects as we have moved away from latch and are using Cloudflare instead..

I'll create a PR to remove the part mention latch 🙂

**Comment by greystate** [comment]
Yeah — I was thinking that there's probably another page somewhere that mentions the newer `Https.Web.Live.xdt.config` file that replaced the Latch config?

**Comment by jonat123** [comment]
Hmm actually I don't think there is another page with information about the config 🤔

I think it would make sense to remove the latch section in the article you mention and add some information about the Https.Web.Live.xdt.config instead 🙂

**Comment by jonat123** [comment]
@greystate Just want to let you know, that the stuff about latch has been removed and i have added the information about the Http config file in the following PR: #3835 :-) 

I'll close this pr down :D
