### ISSUE TITLE
Document U4-8532 No built in Active Directory authentication in Umbraco 7.3+

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/UmbracoDocs#369]
Document how this works based on http://issues.umbraco.org/issue/U4-8532

**Comment by biapar** [comment]
Better documentation on OAuth or AD authentication for members or backoffice user.

**Comment by sofietoft** [comment]
Documentation added: https://our.umbraco.org/documentation/Reference/Security/#back-office-users
