### ISSUE TITLE
Umbraco v9 Load Balancing documentation referencing umbracoSettings.config

### ISSUE THREAD

**Issue by stevetemple** [umbraco/UmbracoDocs#3690]
The v9 version of the page page says: 

Set the umbracoApplicationUrl property in the Web.Routing section of /Config/umbracoSettings.config

This is no longer correct for Umbraco v9

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Setup/Server-Setup/Load-Balancing/index.md***

**Comment by jonat123** [comment]
@stevetemple I can see that you created the pr: #3691 and that it is merged in, i will then  close this Issue :) 

Thanks for the PR and have a great day!
