### ISSUE TITLE
Smidge Defaults and Options

### ISSUE THREAD

**Issue by craigs100** [umbraco/UmbracoDocs#3702]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/V9-Config/RuntimeMinificationSettings/index.md***

It would be useful to know:-
1. What are the default settings for Smidge if you don't add the "RuntimeMinification" section?
2. What are the effects of each option?
3. In the "Automatically generated settings" section, it mentions changing a version number but doesn't say where it is to change it. Likewise for the "dataFolder" setting.

Thanks

**Comment by ronaldbarendse** [comment]
The default values for Umbraco are already specified in the example (we might want to make this more clear though) and most IDEs will also show this in the auto-complete dialog:

![Auto-complete](https://user-images.githubusercontent.com/1051287/147823720-a7e84ef8-66da-4f89-b765-140a10ee02f9.png)

What might not be obvious though, is that this section is also used to configure Smidge (`SmidgeOptions` binds to `Umbraco:CMS:RuntimeMinification`), so this section can those settings as well: https://github.com/Shazwazza/Smidge/wiki/installation.

**Comment by craigs100** [comment]
Thanks for your comments on the defaults. 

WRT the Version number, I don't think I've made myself clear enough, sorry. Where is the NUMBER?  

"You might see a setting "version" with a long number after it, this setting is generated if you use the Version type cache buster, generally you don't need to change this. However. if you're making some front end changes, and not seeing the change, then you can increase this number by one, clearing the cache and now you should see the change."

It says the number can be changed but it doesn't say where the number can be found in order to change it.

**Comment by craigs100** [comment]
I found via FB that to be able to update a version number you have to add "Version" : "1234" as a new parameter. I have tested it and proved it worked so raised a PR on the page: https://github.com/umbraco/UmbracoDocs/pull/3703
