### ISSUE TITLE
404 Umbraco Forms documentation about configure license 

### ISSUE THREAD

**Issue by Aaen** [umbraco/UmbracoDocs#371]
I think there is no documentation written on this. If there is then we need to fix the link.

https://our.umbraco.org/documentation/Add-ons/UmbracoForms/Installation/license

**Comment by warrenbuckley** [comment]
Not that I am aware of @Aaen 
Perhaps based off conversations with customers regarding this topic from support tickets etc that you may be able to put something together please. If not I will need to find time & schedule it in for next sprint or something to do a docs review etc.

**Comment by Aaen** [comment]
Fixed

**Comment by hemraker** [comment]
🎉
