### ISSUE TITLE
Code disappeared when save in code editor of Rich Text Editor (Umbraco 9)

### ISSUE THREAD

**Issue by Wedeoo** [umbraco/UmbracoDocs#3737]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Rich-Text-Editor/Configuration/index.md***

Only the first line of code is saved when using 'Edit source code' in the rich text editor, the rest would disappeared
(Umbraco 9)

**Comment by busrasengul** [comment]
Hey @Wedeoo 
Thank you for raising this issue. 
Would you mind re-creating the steps for me? It's a bit unclear what are you trying to achieve exactly?

Thank you :)

**Comment by sofietoft** [comment]
Hi 👋 

As there hasn't been any activity on this issue for a while, I'll close it down.

Please feel free to get back in touch, if something still isn't quite right!
