### ISSUE TITLE
Request handler settings for char replacement

### ISSUE THREAD

**Issue by AndreyKarandashovUKAD** [umbraco/UmbracoDocs#3754]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
[(link here)](https://github.com/umbraco/Umbraco-CMS/pull/11386) - this PR was merged for v9.

## Describe the issue
Not sure if new page is created for v9, but it would be nice to have an example in documentation with this setup

**Comment by jonat123** [comment]
Hello @AndreyKarandashovUKAD thanks for creating this issue :-) 

We do indeed have documentation for this already here: https://our.umbraco.com/Documentation/Reference/V9-Config/RequestHandlerSettings/ 

Is this what you were missing in the documentation? :-)

**Comment by AndreyKarandashovUKAD** [comment]
@jonat123 Yes, exactly. Thanks.

**Comment by jonat123** [comment]
Ahh perfect 😄

Glad to hear that 🙂

I will close this issue then.

Have a great day!
