### ISSUE TITLE
Route Hijacking - posting custom model

### ISSUE THREAD

**Issue by nicholusi2021** [umbraco/UmbracoDocs#3768]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
(https://our.umbraco.com/documentation/reference/routing/custom-controllers#returning-a-view-with-a-custom-model)

## Describe the issue

Everything works as advertised to perform route hijacking and to return a custom model to the view.   I would however appreciate it if the article (or perhaps a separate article) could expand upon this topic to show how you would (as descripted in the article) hijack the route and use a custom model, but then (new part) post that custom model back to a surface controller. 

I've spend a lot of time trying to get this to work but my surface controller always receives the hijacked model and not my custom model.  My work around for this is to pass in the hijacked model and then rebuild my custom model using IFormCollection collection

```
  public IActionResult submitresults(IPublishedContent model, IFormCollection collection)
        {
              CustomViewModel cvm = new CustomViewModel (model, new PublishedValueFallback(_serviceContext, _variationContextAccessor));

                cvm.company = collection["company"];
                cvm.firstName = collection["firstName"];
                cvm.lastName = collection["lastName"];
                ...
        }
```

but this doesn't feel right.  Some documentation on this would be greatly appreciated!

**Comment by busrasengul** [comment]
Hey @nicholusi2021 
You're right that doesn't look exactly right, although might be a way to do things.
Which version are you using?

**Comment by nicholusi2021** [comment]
Hi @busrasengul 

Thanks for getting back to me.  I'm using version 9.3

**Comment by sofietoft** [comment]
Hi @nicholusi2021 !

Apologies for the delay on this one.
A lot has happened with our docs since this issue was created - would you mind confirming if what you're trying to achieve here is indeed still missing from the docs?
This is the new link to the article: https://docs.umbraco.com/umbraco-cms/reference/routing/custom-controllers#returning-a-view-with-a-custom-model

**Comment by sofietoft** [comment]
Hi @nicholusi2021 !

It's been a while since we've seen any activity here.
I'll close this issue for now.

Please feel free to re-open or create a new one, should you continue to miss this piece of information 💪
