### ISSUE TITLE
Docs for Umbraco Uno widgets is broken

### ISSUE THREAD

**Issue by bjarnef** [umbraco/UmbracoDocs#3772]
## What type of issue is it? (Choose one - delete the others)
Discussion
Broken documentation

## What article/section is this about?
[(link here)](https://our.umbraco.com/documentation/Umbraco-Uno/Widgets)

## Describe the issue
It seems the documentation for Umbraco Uno widgets is broken

E.g. link to"Working with content" https://our.umbraco.com/documentation/Umbraco-Uno/Creating-Content/Work-with-content from here https://our.umbraco.com/documentation/Umbraco-Uno/Getting-Started/#working-with-content and link to widgets from here: https://our.umbraco.com/documentation/Umbraco-Uno/Uno-pedia/#overview-of-widgets

**Comment by jonat123** [comment]
@bjarnef Thanks for making us aware, I will take a look at it in a moment 👍
