### ISSUE TITLE
Umbraco has always unavailable  

### ISSUE THREAD

**Issue by dangvantanh** [umbraco/UmbracoDocs#381]
Hi Team,

we has been used umbraco CMS and built some website large for clients. but we have some problem with caching, examine-index and The IIS has always unavailable or out of memory. Please help me recommend configuration for website with big data. 

Also, media in Backoffice is slowly. please help me how are improvement ?.

Our server configuration information below
 
Web server IIS7
.Net framework 4.5.1
Umbraco version 7.3
RAM 16 GB

thanks,
Smile

**Comment by Shazwazza** [comment]
Hi, please post Umbraco questions on the forum where the community will be able to assist you:  https://our.umbraco.org
