### ISSUE TITLE
Azure KeyVault

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#3825]
Would it be a good idea to add an article that explains how to use an Azure Key Vault?

**Comment by jonat123** [comment]
Hey @erikjanwestendorp sorry for the late reply 😅

Hmm, I don't see why not, I think it could be a good thing to have in our documentation 🙂

Is it something that you would like to look into? 🙂

**Comment by erikjanwestendorp** [comment]
@jonat123 Of course! I'm going to work on it

**Comment by sofietoft** [comment]
Hi Erik! 👋 

Just added some labels to this issue, and also assigned it to you - hope that's okay! 😄 

Hope you're doing good! Happy to see your still one of our top contributors 👏

**Comment by erikjanwestendorp** [comment]
Hi @sofietoft welcome back (I guess 😄). It's going well, hope you are too!

Of course it's okay to assign this issue to me 👍. I'll create a PR.
