### ISSUE TITLE
Where to store the xml file with rewrite rules?

### ISSUE THREAD

**Issue by sandervandepas** [umbraco/UmbracoDocs#3827]
In which folder should you place the xml file exactly?

When I reference to the project root folder in the startup.cs file (File.OpenText("IISUrlRewrite.xml")) it works with the `dotnet run` call, but when I do a `dotnet publish` it returns an error that the file cannot be found.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Routing/IISRewriteRules/index.md***

**Comment by sandervandepas** [comment]
Hi @jonat123,

I got a message from Umbraco and it should be in the root folder definitely.
The documentation was not updated and I was missing the piece to set the file in Visual Studio as "Copy if newer" on the property "Copy to Output Directory", otherwise the file wasn't copied by a publish :-)

And no, I run this site in Azure DevOps instead of Umbraco Cloud.

**Comment by jonat123** [comment]
Great to hear that you good it working :-) 

We also talked about the issue internally and it is clear that there is missing a bit of information which has caused some confusion.

I am currently working to make the documentation more clearer 😄

Thanks for raising the issue 🙂
