### ISSUE TITLE
Links are broken under Prerequties

### ISSUE THREAD

**Issue by kjsguld** [umbraco/UmbracoDocs#3840]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Add-ons/Umbraco-Deploy/Installing-Deploy/Install-Configure/index.md***

All links seem to be to non existing article in the following paragraph: 
_"Prerequisites
Ensure you have read and followed the setup guide for [new](https://our.umbraco.com/documentation/Add-ons/Umbraco-Deploy/installing-deploy/New-site/index-v9) or [new](https://our.umbraco.com/documentation/Add-ons/Umbraco-Deploy/installing-deploy/Existing-site/index-v9) projects."_

**Comment by jonat123** [comment]
@kjsguld thanks for letting us know.

It has been fixed.
