### ISSUE TITLE
Unattended-Install instructions make no mention of InstallMissingDatabase setting

### ISSUE THREAD

**Issue by p-m-j** [umbraco/UmbracoDocs#3860]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Setup/Install/Unattended-Install.md***

When Umbraco:CMS:Global:InstallMissingDatabase is false (the default value) unattended install will fail and a boot failed exception will be thrown, this would be good to highlight on the unattended install page.

The setting is lightly covered on 
https://our.umbraco.com/Documentation/Reference/V9-Config/GlobalSettings/#install-missing-database

**Comment by sofietoft** [comment]
Hi @p-m-j !

Thanks for raising this issue.
So, just for my understanding, this is what you're saying:
The `Umbraco:CMS:Global:InstallMissingDatabase` configuration setting needs to be `true` in order to use the Unattended Install feature. 
And since the setting is `false` by default the unattended install will fail.

Is that correct?

**Comment by p-m-j** [comment]
@sofietoft yep that’s correct.

**Comment by sofietoft** [comment]
Great! Thanks for confirming.

I'll make sure this is tested and that the guide for the unattended install article is updating accordingly 💪

**Comment by p-m-j** [comment]
@sofietoft Actually on second thoughts it’s probably fine as the docs mention that you should create the database upfront, so the state would be InstallEmptyDatabase rather than missing.

however it still might be worth highlighting that the setting exists and does impact the process if the database doesn’t already exist e.g if want a new sql ce database file created.

**Comment by sofietoft** [comment]
Aha! I see 🤔 
So instead, we could add a note to the Unattended install article, that mentions (and possibly also references) the database setting - just in case someone runs into the same issue as you did?

What do you think of that solution?

**Comment by p-m-j** [comment]
Sounds good to me

**Comment by sofietoft** [comment]
Super!

Would you be up for making the PR? 😄 
We have some contribution guidelines here: https://our.umbraco.com/documentation/Contribute/

Otherwise, I'll make sure it's added to our task list 💪
