### ISSUE TITLE
Property not used in code example

### ISSUE THREAD

**Issue by blockingHD** [umbraco/UmbracoDocs#3867]
Under adding settings to a type in the extending Umbraco Forms documentation it states that "With the attribute in place, the property value is set every time the class is instantiated by Umbraco Forms. This means you can use the property in your code like this:". Which then shows code which has a prop named Document which is then not used within the Execute section of the code. 

I'd assume that the log needs to log the document setting or similar to show the setting being used.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type.md***

**Comment by sofietoft** [comment]
Hi @blockingHD 😄 

Thanks for submitting this issue!
I need your help here, as I'm not entirely sure what you mean.

Would you mind trying to explain in a different way, the issue you see with the samples in this article?

**Comment by sofietoft** [comment]
Hi @blockingHD !

As I haven't heard back from you in a while, I will close this down for now.
Please do not hesitate to get back in touch should something come up!

Thanks again for helping us keep the docs up to speed 💪
