### ISSUE TITLE
The external link regarding how you enable dotnet new templates to appear in Visual Studio not working for Visual Studio 2022

### ISSUE THREAD

**Issue by andersbp** [umbraco/UmbracoDocs#3874]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Setup/Install/visual-studio.md***
When I try to following the documentation about how I can install Umbraco 9 on IIS Webserver via Visual Studio 2022, your documentation not work. This is because that I not can enable dotnet new templates to appear in Visual Studio 2022. I look on the following external link that your documentation refer to: https://devblogs.microsoft.com/dotnet/net-cli-templates-in-visual-studio/

How can I enable dotnet new templates to appear in Visual Studio 2022, so I can install Umbraco 9, and is it possible for you to make a note about that the external link you refer to not working for Visual Studio 2022 and later?

Can I install Umbraco 9 on IIs Webserver without Visual Studio (since that the webserver is on my webhost, I not have directly access to run the .net cli command)?

Thanks in advance for your answer.

Regards,
Anders

**Comment by sofietoft** [comment]
Hi @andersbp !

Thanks for reporting this issue.
Looks like you've done a lot of digging into that - which is really great, because that means that I don't have to 😉
No, just kidding of course!
I'll make sure to look into this.

So, to answer your questions I will need some backup from our experts. Will get back to you ASAP on that as well.
Let me know if you find anything new or have any questions meanwhile!

**Comment by jonat123** [comment]
Hello @andersbp sorry to hear you are having a bit of trouble.

Sofie has asked me to look into this and I believe I know what the issue might be.

For you to use the Umbraco templates in visual studio 2022, you will need to install the Umbraco templates first.

This can be done by using the .NET CLI with the following command: _dotnet new -i Umbraco.Templates::*_

We have also documented that here: https://our.umbraco.com/documentation/Fundamentals/Setup/Install/install-umbraco-with-templates#Install-the-template

Once the template has been installed, you should be able to create a project using the Umbraco templates from Visual Studio 2022.

this is the recommended way of installing Umbraco 9 :-) 

Unfortunately, i don't know anything about whether you can install IIs Webserver without Visual Studio I'm afraid 🤔

**Comment by andersbp** [comment]
Hi again, and very thanks for your help.

 

The issue with your documentation is that you link to an old guide regarding how I can install the Umbraco .net templates in Visual Studio 2019. Since I have tried to follow this guide, and the menues that the external article write about is not accessible in Visual Studio 2022, the external link is not updated.

 

Is it possible for you to update your documentation, or write to the external company that you link to, so the article can be updated?

 

Regards,

Anders

 

Fra: jonat123 ***@***.***> 
Sendt: 28. marts 2022 12:58
Til: umbraco/UmbracoDocs ***@***.***>
Cc: andersbp ***@***.***>; Mention ***@***.***>
Emne: Re: [umbraco/UmbracoDocs] The external link regarding how you enable dotnet new templates to appear in Visual Studio not working for Visual Studio 2022 (Issue #3874)

 

Hello @andersbp <https://github.com/andersbp>  sorry to hear you are having a bit of trouble.

Sofie has asked me to look into this and I believe I know what the issue might be.

For you to use the Umbraco templates in visual studio 2022, you will need to install the Umbraco templates first.

This can be done by using the .NET CLI with the following command: dotnet new -i Umbraco.Templates::*

We have also documented that here: https://our.umbraco.com/documentation/Fundamentals/Setup/Install/install-umbraco-with-templates#Install-the-template

Once the template has been installed, you should be able to create a project using the Umbraco templates from Visual Studio 2022.

this is the recommended way of installing Umbraco 9 :-)

Unfortunately, i don't know anything about whether you can install IIs Webserver without Visual Studio I'm afraid 🤔

**Comment by jonat123** [comment]
@andersbp Ahhh I see, thanks for clarifying!

I'm guessing that the preview feature that was in earlier Visual studio versions has been officially added, so you do not need to enable the preview function if you are on Visual Studio 2022 and above. 

I will look into how we can update the documentation so to avoid confusion :-) 

Thanks for bringing this to us 😄

**Comment by jonat123** [comment]
@andersbp I've created the following PR to clarify if anyone trying to install the dotnet new templates using Visual Studio 2022:

#3881
