### ISSUE TITLE
Timeout Expired errors since updating to 9.4.1

### ISSUE THREAD

**Issue by wicketbr** [umbraco/UmbracoDocs#3878]
Since updating to 9.4.1 yesterday I am seeing constant timeout errors in the BackOffice. The message states: 

<img width="413" alt="timeout" src="https://user-images.githubusercontent.com/7229612/160470237-75cc154d-4b2c-404a-b3bd-7ea8861214f1.png">

I can click Close and it seems I can continue working, but the error keeps popping up.

Thanks,

Brad

**Comment by sofietoft** [comment]
Hi @wicketbr !
Sorry to hear that you're having this issue.

I'm afraid it is not something we can help you with here, as this is really only for documentation related queries.
I'd encourage you to get in touch with our support department using [contact@umbraco.com](mailto:contact@umbraco.com), or reach out to our community at the [Forum](https://our.umbraco.com/forum/).

I hope everything works out for you 🤞
