### ISSUE TITLE
Is this sentence correct?

### ISSUE THREAD

**Issue by BatJan** [umbraco/UmbracoDocs#3880]
Hello docs team!

In the below page I stumbled upon the following paragraph where the highlighted part appears to be a bit abrupt to me?

> You might not always want to have the configuration stored in the appsettings.json file, for instance, you might not want to have the admin password in the file if using the unattended feature. You might also want to use a specific set of configurations **when developing your solution, _fortunately_, the IConfiguration pattern.**

I'm not sure whether it makes English or not? 😅 ... I would think it should read "following" instead of "fortunately" maybe?

I'll be happy to submit a PR but would like clarification first in case more words should be added / removed etc.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/V9-Config/index.md***

**Comment by sofietoft** [comment]
Hi Jan 😄 
Good to "see" you again - hope you're doing good!

I agree that the highlighted sentence you've found sounds a bit off 🤔 
Perhaps something along these lines was what was meant: 
"You might also want to use a specific set of configurations when developing your solution. **Fortunately, we have the IConfiguration pattern which you can use.**"

Would that make more sense, you think? 😅 
And perhaps we should also loose the "fortunately" - not really the best word to use in a docs article 🙈
