### ISSUE TITLE
Broken Documentation page

### ISSUE THREAD

**Issue by alberto-dd** [umbraco/UmbracoDocs#3892]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/broken-link.md***

**Comment by eshanrnh** [comment]
Hey @alberto-dd 

Thank you for reaching out. Can you link the actual article/page where the link is broken? The link you shared is just a general error link when the page is not found.

**Comment by RichezA** [comment]
Hi,

I permit myself to reply to this issue as I have found another broken link (to not cause a duplicate). Broken link is: 
https://our.umbraco.com/documentation/reference/Notifications/ContentService-Notifications/determining-new-entity.md

And it can be found on this page: https://our.umbraco.com/documentation/reference/Notifications/ContentService-Notifications/

Cordially,

**Comment by eshanrnh** [comment]
Thanks for flagging the issue, @RichezA 💪

The link is now fixed 🙂
