### ISSUE TITLE
Multiple pages for umbraco deploy create confusion

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/UmbracoDocs#3900]
There are two places where deploy settings are documented:

https://our.umbraco.com/documentation/Umbraco-Cloud/Deployment/Deploy-Settings/
and
https://our.umbraco.com/documentation/Add-ons/Umbraco-Deploy/Deploy-Settings/

They both contain different content and they both are incomplete.

I would suggest linking the umbraco cloud / deploy page to add ons / umbraco deploy because that one contains the most up to date settings. The only one that is missing is the cache reload setting

@AndyButland this is something that's important for you to know to?

**Comment by eshanrnh** [comment]
Thanks for raising this issue, @FransdeJong 💪

@AndyButland, Is this something you can look into/help us with? 🙂

**Comment by AndyButland** [comment]
It's more one for @jonat123 I think... he created these pages when Deploy was released "on-premises", but of course it was and is an important part of Cloud as well as being an "add-on".  It needs some thought for anyone browsing the Cloud documentation to make sure they aren't linking off unnecessarily to other areas... but on the other hand of course we probably don't want to duplicate information, nor risk one getting out of date.

**Comment by jonat123** [comment]
@AndyButland @FransdeJong  I've added it as a task in our backlog to take a look at this, and will look into this as soon as possible :)

**Comment by jonat123** [comment]
@FransdeJong I've had a look at the deploy settings documentation and the docs for deploy on-prem are fully up-to-date, however, noticed that the cloud documentation was missing the following settings:
- **AllowMembersDeploymentOperations and TransferMemberGroupsAsContent,** 
- **Memory cache reload,** 
- **Deployment of culture & hostnames**

I've therefore created the following PR: #3934 which adds the missing settings to the cloud documentation, making it up-to-date.

**Comment by FransdeJong** [comment]
@jonat123 
That sounds like a good start but wouldn't it be better if one page linked to the other? Or if somehow these pages are synchronized?

With the growth of features in deploy, there will be a growth in overlapping documentation in deploy on cloud and deploy on premises. It would be a pain if someone needs to sync these up all the time?

**Comment by jonat123** [comment]
@FransdeJong 

You are right, we talked internally on the team, and what we will do, is we will remove the deploy settings page from the cloud section, and then on the landing page in the deployment section, we will add a link to the deploy settings as we have done on some other pages.

That way we wont have any duplicate content and it should be easy to find, cause less confusion and be easier to maintan 🙂

**Comment by jonat123** [comment]
Forgot to write, but created this PR and merged it in #3942 where i removed the deploy settings and linked to the addons page :-)

**Comment by jonat123** [comment]
Gonna close this issue  :)
