### ISSUE TITLE
v8: missing documentation for `contentVersionCleanupPolicyGlobalSettings`

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/UmbracoDocs#3904]
This new setting in `umbracoSettings.config` doesn't seem to be documented yet. 

The default settings are: `<contentVersionCleanupPolicyGlobalSettings enable="true" keepAllVersionsNewerThanDays="7" keepLatestVersionPerDayForDays="90" />`

The explanation of these settings is the same as the ones for v9.1.0: 

https://our.umbraco.com/documentation/Reference/V9-Config/ContentSettings/#contentversioncleanuppolicy

**Comment by eshanrnh** [comment]
Thanks for raising the issue, @nul800sebastiaan 💪

We have added a `community/up-for-grabs` label. If no-one picks it up we'll add it to our to-do list. 🙂

**Comment by eshanrnh** [comment]
Added the settings in below files: 

- https://our.umbraco.com/documentation/Reference/Config/umbracoSettings/index.md
- https://our.umbraco.com/documentation/Reference/V9-Config/umbracoSettings/index.md
