### ISSUE TITLE
Should mention umbraco.config

### ISSUE THREAD

**Issue by darthglader** [umbraco/UmbracoDocs#3905]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Config/index.md***

I was wondering where umbraco.config had gone in v8. I went to our.umbraco.com to ask there.  But i found the answer which is [https://our.umbraco.com/forum/umbraco-8/97870-where-is-umbracoconfig-in-v8](https://our.umbraco.com/forum/umbraco-8/97870-where-is-umbracoconfig-in-v8/).  

I think you should say as such here.

**Comment by darthglader** [comment]
Hi @eshanrnh 
Well as it says in the link i quoted, the umbraco.config doesn't exist anymore, which as it was a fundamental piece of how Umbraco works (it is a cache of umbraco content) I was very confused.  I now know this functionality is now given to NuCache, with the equivalent content file living in App_Data\TEMP\NuCache\NuCache.Content.db .
Thanks
Paul

**Comment by eshanrnh** [comment]
Thanks for clarifying, @darthglader 🙂

We will look at updating the documentation to include this information.
