### ISSUE TITLE
Umbraco9Articles Documentation 

### ISSUE THREAD

**Issue by Yjohn** [umbraco/UmbracoDocs#3918]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/broken-link.md***

**Comment by Yjohn** [comment]
https://our.umbraco.com/documentation/Umbraco9Articles

**Comment by busrasengul** [comment]
Thank you @Yjohn for raising this issue.
We now removed those points as default documentation is already pointing V9 articles and tutorials.
I'll remove the tip as well, so it won't cause confusion.
