### ISSUE TITLE
Url broken

### ISSUE THREAD

**Issue by SerdarDemirbas** [umbraco/UmbracoDocs#3938]
in documentation:  https://umbraco.com/products/umbraco-cms/umbraco-9/

link is broken

Umbraco 9 Documentation - written step-by-step technical instructions
https://our.umbraco.com/documentation/Umbraco9Articles?_ga=2.61540847.294780478.1650965035-1825040727.1650965035

**Comment by eshanrnh** [comment]
Thanks for flagging the issue, @SerdarDemirbas 💪

We are working on fixing the link 🙂

**Comment by eshanrnh** [comment]
@SerdarDemirbas This issue is now fixed 🙂
