### ISSUE TITLE
404 on service link

### ISSUE THREAD

**Issue by kjsguld** [umbraco/UmbracoDocs#3945]
The link [recurring hosted service](https://our.umbraco.com/Documentation/Reference/Notifications/Scheduling/) returns 404

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Notifications/Creating-And-Publishing-Notifications/index.md***

**Comment by sofietoft** [comment]
Thanks for reporting 💪 

The broken link has been updated, and it is no longer broken.
