### ISSUE TITLE
How to configure tinyMCE in v.9? 

### ISSUE THREAD

**Issue by shapeh** [umbraco/UmbracoDocs#3946]
There is no page for v.9. 

I am specifically thinking about how to prevent tinymce from removing tags like

`<i class="ti-check"></i>`

-- these are themify-icons and tag is valid. 

Docs says edit 

> /config/tinyMce.config

but this file does not exist. 

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Config/tinyMceConfig/index.md***

**Comment by eshanrnh** [comment]
Thanks, @shapeh for reaching out 🙂

We have a Page for v9: https://our.umbraco.com/documentation/Reference/V9-Config/RichTextEditorSettings/

Hope this resolves your issue 💪
