### ISSUE TITLE
Broken page

### ISSUE THREAD

**Issue by JoelSmits** [umbraco/UmbracoDocs#3950]
## What type of issue is it? (Choose one - delete the others)
Broken page

## What article/section is this about?
(https://our.umbraco.com/documentation/extending/.../reference/cache/applicationcache)

## Describe the issue
Page doesn't render content properly

**Comment by eshanrnh** [comment]
Hey @JoelSmits, 

Thank you for reaching out. Can you link the actual article/page from where you navigated to the broken link? 

The link you shared is just a general error link when the page is not found.

**Comment by eshanrnh** [comment]
Hey, @JoelSmits 👋

It's been a while now and since we haven't heard back from you we are closing this issue.
If continue to run into issues, please do let us know and we'll do our best to help out 💪
