### ISSUE TITLE
ILoggingProfiler

### ISSUE THREAD

**Issue by mistyn8** [umbraco/UmbracoDocs#3954]
Should this also include information on `ILoggingProfiler`
```csharp
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Umbraco.Cms.Web.Common.Controllers;
using Umbraco.Cms.Core.Logging;

namespace Umbraco.Cms.Web.UI.NetCore
{
    public class MyApiController : UmbracoApiController
    {
        private readonly IProfilingLogger _profilingLogger;

        public MyApiController(IProfilingLogger profilingLogger)
        {
              _profilingLogger = profilingLogger;
        }

        /// /umbraco/api/MyApi/SayHello?name=John
        [HttpGet]
        public string SayHello(string name)
        {
             using (_profilingLogger.TraceDuration<MyApiController>($"Saying Hello {name}")
             return $"Hello {name}";
        }
    }
}
```
PS not sure if it supports serilog structured logging..  as samples in the code base base use string intepolation messages..
```cs
using (_profilingLogger.TraceDuration<NuCacheContentService>($"Rebuilding NuCache database with {serializer} serializer"))
                {
                    Rebuild();
                    _keyValueService.SetValue(NuCacheSerializerKey, serializer.ToString());
                }
```
https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentService.cs#L52

perhaps like ?
```cs
using (_profilingLogger.TraceDuration<NuCacheContentService>("Rebuilding NuCache database with {serializer} serializer", new object [serializer]))
```
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Code/Debugging/Logging/index.md***

**Comment by eshanrnh** [comment]
That's a good suggestion, @mistyn8 💪 We can definitely update the article with `ILoggingProfiler` information.

Would you be up for making the PR? 😄 Let me know. We have some contribution guidelines here: https://our.umbraco.com/documentation/Contribute/

Otherwise, I'll make sure it's added to our task list 💪

**Comment by sofietoft** [comment]
Hi @mistyn8 !

I've had a look at this with one of our developers and the docs community team, and we think it would be a great idea to add a note about using the IProfilingLogger 💪 

It could be something along these lines: "if you are Logging and using the MiniProfiler, then for convenience you could inject IProfilingLogger that has a reference to both ILogger and IProfiler"

Including a code snippet, would also be great.
What do you think of that solution? 😁
