### ISSUE TITLE
Markdown code is not html escaped

### ISSUE THREAD

**Issue by Nikkelmann** [umbraco/UmbracoDocs#3968]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Setup/Server-Setup/iis/index.md***

The code example at the bottom is not escaped and thus the `<AspNetCoreHostingModel>` tag is interpreted as html instead of a string literal:
![image](https://user-images.githubusercontent.com/3674690/168585408-afeed031-8e9a-4b9e-bd22-ff68e92a207a.png)

On github the markdown preview is correct, so I guess the issue is with the markdown renderer on Our:
![image](https://user-images.githubusercontent.com/3674690/168585829-c0b2817c-2045-4fa5-8f8b-36f1f71aafc1.png)

**Comment by eshanrnh** [comment]
@Nikkelmann, Thanks for flagging this issue 💪 The issue is now resolved 🙂
