### ISSUE TITLE
Minor typo: "Rollback to a Previous Versions"

### ISSUE THREAD

**Issue by tormnator** [umbraco/UmbracoDocs#3975]
Should say: "Rollback to a Previous Version".

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Tutorials/Editors-Manual/Version-Management/index.md***

**Comment by eshanrnh** [comment]
Thanks for reporting the typo, @tormnator 💪

The issue is now fixed. 🙂
