### ISSUE TITLE
Remove reference to Umbraco Uno

### ISSUE THREAD

**Issue by tormnator** [umbraco/UmbracoDocs#3976]
Since Uno has been discontinued, the "...or take a look at our "no code/low code" option, Umbraco Uno." can be removed.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Getting-Started/Developing-websites-with-Umbraco/index.md***

**Comment by eshanrnh** [comment]
Thanks for flagging this issue, @tormnator 💪

Uno reference is now removed from the article. 🙂
