### ISSUE TITLE
External login providers - Microsoft example

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#3994]
Is it an idea to extend the article about [external login providers](https://our.umbraco.com/documentation/reference/security/external-login-providers/) with code examples of a Microsoft implementation?

**Comment by erikjanwestendorp** [comment]
@eshanrnh Yes of course I want to give it a try. 😄. 

Would it be a good idea to move the article to a folder so that it appears in the menu?

**Comment by eshanrnh** [comment]
That's amazing, @erikjanwestendorp 💪

You can definitely move the article to a folder. It would be good to have it listed in the menu. 😀
