### ISSUE TITLE
GetRequiredUmbracoContext() within Composer Errors

### ISSUE THREAD

**Issue by jaymarvels** [umbraco/UmbracoDocs#3995]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Routing/custom-routes.md#custom-route-with-forumbracopage***

Following the above documentation causes an error.

Umbraco v9.5

Example Code:

  
```
public class RobotsTxtComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.Services.Configure<UmbracoPipelineOptions>(options =>
            {
                options.AddFilter(new UmbracoPipelineFilter(nameof(RobotsTxtComposer))
                {
                    Endpoints = app => app.UseEndpoints(endpoints =>
                    {
                        endpoints.MapControllerRoute(
                                "Robots Txt",
                                "/robots.txt",
                                new { Controller = "RobotsTxt", Action = "Index" })
                                .ForUmbracoPage(FindContent); // Here we register our FindContent method
                    })
                });
            });
        }

        private IPublishedContent FindContent(ActionExecutingContext actionExecutingContext)
        {
            var umbracoContextAccessor = actionExecutingContext.HttpContext.RequestServices
                .GetRequiredService<IUmbracoContextAccessor>();
            var publishedValueFallback = actionExecutingContext.HttpContext.RequestServices
                .GetRequiredService<IPublishedValueFallback>();

            var umbracoContext = umbracoContextAccessor.GetRequiredUmbracoContext();
            return umbracoContext.Content.GetAtRoot().FirstOrDefault();
        }
    }
```

This line causes the error:

var umbracoContext = umbracoContextAccessor.GetRequiredUmbracoContext();

Error :  "Wasn't able to get an UmbracoContext"

**Comment by eshanrnh** [comment]
Hey @jaymarvels,

Sorry to hear that you're having this issue.

Did you take a look at the **Note** within the article? There is a [PR](https://github.com/umbraco/Umbraco-CMS/issues/12083) mentioned with a similar error which might be helpful.

Looking at the error, I'm afraid it is not something we can help you with here, as this is only for documentation-related queries.

I'd encourage you to get in touch with our support department using [contact@umbraco.com](mailto:contact@umbraco.com) or reach out to our community at the [Forum](https://our.umbraco.com/forum/).

Hope you find a solution 🤞

**Comment by jaymarvels** [comment]
@eshanrnh as a fyi this [PR](https://github.com/umbraco/Umbraco-CMS/pull/12088) saved me. Looks like additional configuration is needed when Umbraco think its a client side request, maybe need to update docs to include this:

`services.Configure<UmbracoRequestOptions>(options =>
{
    options.HandleAsServerSideRequest = httpRequest =>
    {
        return httpRequest.Path.StartsWithSegments("/sitemap.xml");
    };
});`

**Comment by eshanrnh** [comment]
That's great news, @jaymarvels 🙌 I'm glad that you could find a solution.

We appreciate your feedback and Thank you for bringing it to our attention. I'll add it to our to-do list to verify and update the article 🙂

**Comment by eshanrnh** [comment]
Hey @jaymarvels,

On second thoughts, would you be up for creating a PR and updating the article?😃 You'd even earn a shiny C-Trib badge for your contribution to our.umbraco.com account!

We have some contribution guidelines here: https://our.umbraco.com/documentation/Contribute/

**Comment by eshanrnh** [comment]
Merged the PR🙌 Closing the issue 😃
