### ISSUE TITLE
v10: Verify Key Vault docs

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#4039]
Hi @erikjanwestendorp !😄 

Was wondering if you could find some time to help us update this article for Umbraco 10? 😇 
You wrote it, so thought I'd try asking you, before we dive into it ourselves.

Let me know!

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Extending/Key-Vault/index.md***

**Comment by sofietoft** [comment]
That's just wonderful, thanks 🙌 

No worries about getting to it today - just as soon as you have some spare time! 😄

**Comment by erikjanwestendorp** [comment]
@sofietoft The Program.cs class looks slightly different in v10. I have created a PR with a v10 version of the article.
