### ISSUE TITLE
To add DB user roles

### ISSUE THREAD

**Issue by Deepti-Des** [umbraco/UmbracoDocs#4078]
## What type of issue is it? (Choose one - delete the others)
Missing documentation - Info to be added in regards to DB user 'roles'

## What article/section is this about?
Please refer to the thready below for details:
https://umbraco.slack.com/archives/C02JJQU9B/p1654609224615029 

## Describe the issue
Normally, a DB user is assigned `db_owner` role.

Other roles that can be assigned are as below:
`db_datareader` and `db_datawriter` for normal use.
`db_ddladmin` is needed for installs and upgrades (of the CMS and/or any packages that create database tables).

**Comment by eshanrnh** [comment]
Thanks for reporting this issue, @Deepti-Des 💪

We will try to update the documentation soon.
