### ISSUE TITLE
Cannot implicitly convert type 'bool' to System.Threading.Tasks.Task<bool>

### ISSUE THREAD

**Issue by bjornnorlen** [umbraco/UmbracoDocs#4111]
The method TryFindContent() under the heading "NotFoundHandlers" should return a Task<bool> but the code returns a boolean in different places which gives the error as in the heading. In Umbraco 9 it worked by making the method return a boolean (public bool TryFindContent()) but when I now tried updating to Umbraco 10  I got an error that My404ContentFinder did not implement interface member 'IContentFinder...'. When I switched to the return type for the method as specified in the documentation (Task<bool> TryFindContent) that error disappeared but, as mentioned, then the other return statements in the code gives an error.

***This is the page with issues: https://our.umbraco.com/documentation/reference/routing/request-pipeline/icontentfinder***

**Comment by eshanrnh** [comment]
Hey @bjornnorlen 👋,

Thanks for flagging this issue. Can you try this code? 

`public async Task<bool> TryFindContent(IPublishedRequestBuilder contentRequest)`

If it works, can you create a PR for the same?
