### ISSUE TITLE
Don't see the Umbraco option in VS 2022

### ISSUE THREAD

**Issue by cactusoft** [umbraco/UmbracoDocs#4136]
Have vs 2022 installed. See the standard .NET templates, but trying to install Umbraco. Docs say File > New > Project and then search for Umbraco, but there are no Umbraco product options, only vanilla .NET options. Is something else needed to be installed or enabled first?

Microsoft Visual Studio Community 2022 (64-bit) 
Version 17.0.6

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Setup/Install/visual-studio.md***

**Comment by cactusoft** [comment]
> Hey @cactusoft 👋 ,
> 
> If you scroll a little further in the article, there are steps mentioned on how to install the Umbraco's dotnet templates. To install Umbraco, you first need to install Umbraco's dotnet new templates - https://our.umbraco.com/documentation/Fundamentals/Setup/Install/visual-studio#new-project
> 

I did see that, but the abbreviated version at the top says:

> You will get the best results if you use Umbraco's **dotnet new templates**
> **In Visual Studio 2022 the dotnet new templates are enabled by default to appear.** For information on how to enable dotnet new templates to appear in Visual Studio 2019 check this [link](https://devblogs.microsoft.com/dotnet/net-cli-templates-in-visual-studio/)

I took this to mean that with Visual Studio 2022, I should see the Umbraco templates by default? If that isn't the case perhaps there should be another bullet point first in the abbreviated install guidance at the top, making clear that regardless of VS version, you need to do another process first to get the templates?

**Comment by cactusoft** [comment]
I updated to latest Visual Studio 17.2.5 but still missing. So I ran:

`dotnet new -i Umbraco.Templates::*  `

And I do see the Umbraco options now when creating a new project. 

If this is how it is supposed to be, I think maybe the docs need updating to put this as the first step in the abbreviated guidance, and make clear you still need that if using VS 2022 too, not just for 2019.

**Comment by eshanrnh** [comment]
Yes, you are right @cactusoft 🙌 Thanks for your feedback 💪

I have created a PR to clarify the text and added the point in the Abbreviated version section.
