### ISSUE TITLE
Duplicate umbracoSettings page

### ISSUE THREAD

**Issue by rasmusjp** [umbraco/UmbracoDocs#4150]
The umbracoSettings page seems to be duplicated on https://our.umbraco.com/documentation/Reference/Configuration-for-Umbraco-7-and-8/umbracoSettings/ located under `Configuration for Umbraco 7 and 8` and https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Configuration/umbracoSettings/index.md under `Configuration` which seems to be for v9+ configuration, but the page has a version range from 8-8.17 and contains XML configuration (and a small bit mentioning `appsettings.json` which isn't available in v8).

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Configuration/umbracoSettings/index.md***

**Comment by eshanrnh** [comment]
Thanks for flagging this issue, @rasmusjp 🙌

We'll look into it and revert back soon 🙂
