### ISSUE TITLE
PDF indexes and multisearchers

### ISSUE THREAD

**Issue by AndreyKarandashovUKAD** [umbraco/UmbracoDocs#4167]
## What type of issue is it? (Choose one - delete the others)
Broken link and UI issue.

## What article/section is this about?
[PDF Index](https://our.umbraco.com/documentation/reference/searching/examine/pdf-index/)

## Describe the issue
Versions section is empty and the link is broken. (It leads to 500 error page).
![image](https://user-images.githubusercontent.com/51944778/176880464-74dc716e-278a-40d9-82d1-3dee1c772289.png)

**Comment by eshanrnh** [comment]
Thanks for flagging this issue, @AndreyKarandashovUKAD 💪 We will look into it soon.

**Comment by eshanrnh** [comment]
This issue is now fixed.
