### ISSUE TITLE
Installation of NuGet package(s) not required if installed in CLI

### ISSUE THREAD

**Issue by KiltedViking** [umbraco/UmbracoDocs#4191]
Please add a comment about not having to install NuGet package(s) in Visual Studio if have installed using DotNet CLI!

(+ having to first create a package and then install NuGet packages is "backward"! :-P)

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Setup/Install/install-umbraco-with-nuget.md***

**Comment by KiltedViking** [comment]
Hello Sofie (& co. ;-)),
    
    
    A bit of background: 
    
    I decided to have a look at Umbraco
      (again! ;-)) so I started looking at installing it - both in CLI
      and Visual Studio (Community) 2022. After a bit of searching I
      found instructions for the CLI and then for VS - the former was
      easy to follow and worked, while the latter showed how to install
      an older version in VS 2017 (?) and involved having to first
      create an empty project and then install your NuGet package (which
      I find *very* backward... but I guess this has to do with the way
      VS works - I've had to do the same thing with other NuGet
      packages).
    
    
    Anyway, I couldn't find the NuGet
      package in VS, as described on your website, and I restarted VS
      (for a reason I can't remember) and suddenly I found templates for
      creating an Umbraco site (and package)! And this just after having
      installed package in CLI!
    
    
    
    And as I like your product (products?),
      I thought I should tell you that I got "confused" by instructions
      on your site and suggest that you should add a comment on page
      describing how to install NuGet package in (older versions of) VS
      that it doesn't work with latest version (10?)! ;-) (Another thing
      that "confused" me was that page on website was showing a big
      "v10", which I interpreted as page I was viewing was related to
      version 10 as I had searched your site... but this I now believe
      has to do with search field - not page being displayed. :-S)
    
    
    
    /Björn
    
    
    
    
    On 2022-07-07 10:14, sofietoft wrote:
    
    
      
      Hi @KiltedViking
        !
      Thanks for reporting this issue!
        Let me start by making sure I understand what is the case here.
      The article you're referring to, explains how to
        install Umbraco using NuGet in Visual Studio.
        This is no longer a valid option with Umbraco 9+.
      But I'm not sure I understand: Are you talking about
        Umbraco CMS as a NuGet package, or are you referring to NuGet
        packages in general? 🤔
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
      [

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/umbraco/UmbracoDocs/issues/4191#issuecomment-1177234227",

"url": "https://github.com/umbraco/UmbracoDocs/issues/4191#issuecomment-1177234227",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by KiltedViking** [comment]
Hello again Sofie,
    
    
    ... or maybe you just should ignore my
      input... :-S I just started VS 2022 and NuGet Package Manager
      again and now I find both version 8 and 10 for installation.
    
    
    (But I still feel that you should
      consider having a look at search form and consider how to avoid
      misinterpretation in regard to versions. ;-))
    
    
    
    /B
    
    
    
    On 2022-07-09 21:58, Björn G. D.
      Persson wrote:
    
    
      
      Hello Sofie (& co. ;-)),
      
      
      A bit of background: 
      
      I decided to have a look at Umbraco
        (again! ;-)) so I started looking at installing it - both in CLI
        and Visual Studio (Community) 2022. After a bit of searching I
        found instructions for the CLI and then for VS - the former was
        easy to follow and worked, while the latter showed how to
        install an older version in VS 2017 (?) and involved having to
        first create an empty project and then install your NuGet
        package (which I find *very* backward... but I guess this has to
        do with the way VS works - I've had to do the same thing with
        other NuGet packages).
      
      
      Anyway, I couldn't find the NuGet
        package in VS, as described on your website, and I restarted VS
        (for a reason I can't remember) and suddenly I found templates
        for creating an Umbraco site (and package)! And this just after
        having installed package in CLI!
      
      
      
      And as I like your product
        (products?), I thought I should tell you that I got "confused"
        by instructions on your site and suggest that you should add a
        comment on page describing how to install NuGet package in
        (older versions of) VS that it doesn't work with latest version
        (10?)! ;-) (Another thing that "confused" me was that page on
        website was showing a big "v10", which I interpreted as page I
        was viewing was related to version 10 as I had searched your
        site... but this I now believe has to do with search field - not
        page being displayed. :-S)
      
      
      
      /Björn
      
      
      
      
      On 2022-07-07 10:14, sofietoft wrote:
      
      
        
        Hi @KiltedViking !
        Thanks for reporting this issue!
          Let me start by making sure I understand what is the case
          here.
        The article you're referring to, explains how to
          install Umbraco using NuGet in Visual Studio.
          This is no longer a valid option with Umbraco 9+.
        But I'm not sure I understand: Are you talking
          about Umbraco CMS as a NuGet package, or are you referring to
          NuGet packages in general? 🤔
        —
          Reply to this email directly, view it on GitHub, or unsubscribe.
          You are receiving this because you were mentioned.Message
            ID: ***@***.***>
        [

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/umbraco/UmbracoDocs/issues/4191#issuecomment-1177234227",

"url": "https://github.com/umbraco/UmbracoDocs/issues/4191#issuecomment-1177234227",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by sofietoft** [comment]
Hi again @KiltedViking / B 👋 

Thanks a lot for your input.
Our versioning is definitely not super easy to figure out all the time - I guess that's putting it mildly 😉 

In any case, that will hopefully soon be in the past, as we are actively looking into migrating the docs to a new platform - which will open up the option to reconsider how the overall structure is built!

How to Install Umbraco is some of the most essential docs we have, so your input on this is very much valued 🙌
I'll be closing down this issue for now, as you managed to resolve the trouble you were running into - also, I've added a little note to the [article in question](https://our.umbraco.com/documentation/Fundamentals/Setup/Install/install-umbraco-with-nuget), in case Google directs other users over here 🙈
