### ISSUE TITLE
Update Examine Documentation

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#4198]
## What type of issue is it? 
The examine documentation has yet to be updated for v9 and up.

## What article/section is this about?
[Examine](https://our.umbraco.com/documentation/Reference/Searching/Examine/)

## Describe the issue
Most articles about Examine have yet to be updated. I like to help updating the articles. 😄 

- [x] [Quick start](https://our.umbraco.com/documentation/Reference/Searching/Examine/quick-start/)
- [ ] [Custom indexing](https://our.umbraco.com/documentation/Reference/Searching/Examine/indexing/)
- [ ] [PDF indexes and multisearchers](https://our.umbraco.com/documentation/Reference/Searching/Examine/pdfindex-multisearcher)
- [ ] [Examine Terminology](https://our.umbraco.com/documentation/Reference/Searching/Examine/terminology)
- [ ] [Examine Management](https://our.umbraco.com/documentation/Reference/Searching/Examine/examine-management)
- [ ] [Examine Events](https://our.umbraco.com/documentation/Reference/Searching/Examine/examine-events)
- [ ] [Examine Manager](https://our.umbraco.com/documentation/Reference/Searching/Examine/examine-manager)

**Comment by eshanrnh** [comment]
Hey Erik 👋

That's great. Thank you for taking the initiative 🙌 Please feel free to update them at your convenience 😀

**Comment by erikjanwestendorp** [comment]
Hi @sofietoft  Good to hear that it's being worked on soon! 😄  I will not pay any attention to the examine documentation.

**Comment by sofietoft** [comment]
Hi Erik-Jan 👋 
Seems we forgot to close this issue when the Dteam did their work on the Examine docs last year.
I'll do that now!

Please let us know if you still feel that something is lacking or missing 🙌 
Cheers!
