### ISSUE TITLE
Broken Links, Potentially Out of Date

### ISSUE THREAD

**Issue by deenairn** [umbraco/UmbracoDocs#4232]
The link for Pure Live models is broken, RenderMvcController and custom routing are broken. I can propose a fix for these, but Pure Live models latest reference is for v8.5, so I suspect the section should be revisited and rewritten.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Events/Troubleshooting-Slow-Startup.md***

**Comment by eshanrnh** [comment]
Hey, @deenairn 

I looked at the links on the [Troubleshooting slow startup](https://our.umbraco.com/Documentation/Reference/Events/Troubleshooting-Slow-Startup) article and none of them are broken. All the links work fine. 

Also, we have an updated page for [Builder Modes](https://our.umbraco.com/Documentation/Reference/Templating/Modelsbuilder/Builder-Modes#pure-live-models).

Unfortunately, I can't replicate this issue 🤔

**Comment by deenairn** [comment]
I'll check once I'm at home. It's definitely broken and routing to: https://our.umbraco.com/error/?aspxerrorpath=/documentation/reference/Events/_/Templating/Modelsbuilder/Builder-Modes#pure-live-models on my work laptop, but on my mobile it appears to be working which is odd.

**Comment by deenairn** [comment]
When searching via Google I am linked to https://our.umbraco.com/documentation/reference/Events/_/_/Troubleshooting-Slow-Startup. This does have the broken links, but it's not the link you've provided. Perhaps a relative linking problem?

**Comment by eshanrnh** [comment]
Ah 😃, I now get it from where you landed on that page🙈Definitely the page from Google search results has broken links. 
Thanks for flagging the issue and helping us reproduce it. We'll fix it soon.
