### ISSUE TITLE
Umbraco Forms developer documentation outdated

### ISSUE THREAD

**Issue by ruskom** [umbraco/UmbracoDocs#424]
The documentation on the "[Adding a workflow type to Umbraco Forms](https://github.com/umbraco/UmbracoDocs/blob/0e4cc817fab303f5e867aba4cfe289c943491ace/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype.md)" page is outdated and not working as it is described there.

Could you please update it.

**Comment by jamescoxhead** [comment]
Adding to this, as I think there's quite a few pages in the developer documentation that are now out of date (the [rendering scripts](https://our.umbraco.org/documentation/Add-ons/UmbracoForms/Developer/Rendering-Scripts/) page being another example).

I'm happy to submit a PR based on what I've done to get Forms working on my current project.
