### ISSUE TITLE
superfluous MyAwesomeProject folder in Project file/folder Rename Documentation page?

### ISSUE THREAD

**Issue by rudgr** [umbraco/UmbracoDocs#4240]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
https://our.umbraco.com/documentation/Umbraco-Cloud/Set-up/project-settings/#renaming-the-project-file-and-folder

## Describe the issue
`base = "src/MyAwesomeProject/MyAwesomeProject.Web"`

should be:

`base = "src/MyAwesomeProject.Web"`

**Comment by eshanrnh** [comment]
Thanks for flagging the issue and creating the PR, @rudgr 🙌
