### ISSUE TITLE
Broken link on page "BackOfficeUserManager and Events"

### ISSUE THREAD

**Issue by artykisa** [umbraco/UmbracoDocs#4248]
Hello!

There are broken links on page ["BackOfficeUserManager and Events"](https://our.umbraco.com/Documentation/Reference/Security/BackOfficeUserManager-and-Notifications/index-v8_9). The link is ["External Login Provider"](https://our.umbraco.com/Documentation/Reference/Security/BackOfficeUserManager-and-Notifications/external-login-providers).

**Comment by eshanrnh** [comment]
Thanks for flagging the issue, @artykisa 💪 The broken links are now fixed.
