### ISSUE TITLE
Need to document all of the logging types in Umbraco, how they work and configuration

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoDocs#426]
* document that we use log4net and it's config for diagnostic logging
* our `ILogger` interface
* our `ProfilingLogger` class and what it does and the timing output it creates in both logs and miniprofiler
* the audit trail, how it works, where it's stored

**Comment by marcemarc** [comment]
added some 'getting started' information here: https://github.com/umbraco/UmbracoDocs/pull/612 but this could lead into more verbose docs for the above?

**Comment by jmayntzhusen** [comment]
Hi there!

As this issue has been here for over a year without any PRs, we have decided to close it down. 
If you feel the problem is still there, then please open a new issue with as many details as you can so someone has a chance to work on it!

Thanks for reporting it in the first place! 🙂
