### ISSUE TITLE
Custom Url Provider Example Circumvents other Url Providers

### ISSUE THREAD

**Issue by eden-jh** [umbraco/UmbracoDocs#4265]
## What type of issue is it? (Choose one - delete the others)
Other (write it here)

## What article/section is this about?
[Outbound Request Pipeline - Custom Url Provider Example](https://our.umbraco.com/documentation/reference/routing/request-pipeline/outbound-pipeline#example-1)

## Describe the issue
In the example given, the custom Url Provider is written to apply only to a specific content type, but it's actually written in a way that prevents other Url Providers from being used. 

For content of different content types, it [returns the base GetUrl result](https://github.com/umbraco/UmbracoDocs/blob/70aace625e0550037d48cb594b972c68b74e70c9/Reference/Routing/Request-Pipeline/outbound-pipeline.md?plain=1#L282-L306). 

```
if (content.ContentType.Alias == "productPage")
{
   ...
}
// Otherwise return the base GetUrl result:
return base.GetUrl(content, mode, culture, current);
```

Because the [`GetUrl` method of `UrlProvider`](https://apidocs.umbraco.com/v9/csharp/api/Umbraco.Cms.Core.Routing.UrlProvider.html#Umbraco_Cms_Core_Routing_UrlProvider_GetUrl_Umbraco_Cms_Core_Models_PublishedContent_IPublishedContent_Umbraco_Cms_Core_Models_PublishedContent_UrlMode_System_String_Uri_) looks for the first non-null Url in the IEnumerable of available Url Providers, returning the base GetUrl result for other content types prevents any subsequent Url Providers from ever being called. Neither the text of the section nor the comments in the example tell the reader that it will do this.

If the example was written this way intentionally, it would be great for the content to say so, and describe what reason(s) one might have for using this approach. If not, the code example should be updated to return null for content types that this custom Url Provider should not apply to.

**Comment by sofietoft** [comment]
Hi @eden-jh !
Thanks for reporting this issue!
We agree that the example in the article here might be a little too simplistic, and doesn't consider the bigger picture where you might have multiple UrlProviders.

How about we add a note about that to the article, or make the sample return null?
What do you think would work best for explaining the concept of UrlProviders?

**Comment by eden-jh** [comment]
I think making the sample return null when that UrlProvider does not apply makes sense, because that seems like the most likely use case.

Then the description could explain how the order and the GetUrl methods of the registered UrlProviders determine which one will be used for a content item:
- GetUrl should return null if that UrlProvider should not apply to the content item
- GetUrl should return a non-null value if that UrlProvider does apply
- Only the first UrlProvider that applies to a content item will be used, so UrlProviders in the collection should be ordered from highest to lowest precedence

**Comment by sofietoft** [comment]
Sounds like you're _right on the money_ here 💪 

Would you be up for applying these changes to the article yourself? 😄 
We have some docs on contributing here: https://our.umbraco.com/documentation/Contribute/

**Comment by sofietoft** [comment]
Hi @eden-jh !

It's been a while since I've heard from you!
Wanted to check in to hear if you're up for updating the article here, with the suggestions we discussed? 🤞 
Let me know!

**Comment by simonech** [comment]
I think just returning null is good enough because even if your UrlProvider doesn't match, Umbraco will still use the default UrlProvider.

**Comment by sofietoft** [comment]
Looks like a PR related to this issue has already been merged some time ago.
With that, I'll close this issue as well.

Thanks for raising it @eden-jh !
And please do not hesitate to get back in touch, should you continue to miss something in our docs 💪
