### ISSUE TITLE
Verify Unit Testing docs for v10

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#4274]
Hi @Adolfi ,

Hope you've enjoyed your summer! ☀️ 
We have yet to get the Unit Testing docs verified against Umbraco 10, which was released a few months back.
Is there any chance you have some time to spare in the near future, to help us with the task? 🤞 😄 
As you're the original author of these docs, I thought it appropriate to loop you in here!

**Comment by Adolfi** [comment]
Hi @sofietoft.
I will have a look at verify it against v10 to see if there’s any changes needed to be made.
Thanks for the heads up.
Cheers!
