### ISSUE TITLE
redirect to setup page if database down

### ISSUE THREAD

**Issue by huwred** [umbraco/UmbracoDocs#4280]
If for any reason the databse that umbraco points at is unavailble you automatically get redirected to the umbraco setup page. Is there anyway this could be  prevented in a live environment as it seems to me that presenting the setup page to some random visitor could result in them setting up a new database instance and breaking your site.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Setup/index.md***

**Comment by sofietoft** [comment]
Hi @huwred ,
Sorry to hear that you're having some trouble with your Umbraco site.

As this GitHub repository is primarily focused on the Umbraco Documentation, I'm afraid there isn't much I can do for you in this particular case.

Sounds like you might want to have a look at your setup - perhaps someone in the [Umbraco Community](https://our.umbraco.com/forum/) would be able to help out? Might be that someone has had a similar issue before! You can find them on the forum on [Our Umbraco](https://our.umbraco.com/forum/).

Finally, if you need further support, you can always reach out to our friendly support team using [contact@umbraco.com](mailto:contact@umbraco.com).

I hope you find a solution 🙌
