### ISSUE TITLE
Cache Refreshers page needs more information or examples

### ISSUE THREAD

**Issue by TomSearle** [umbraco/UmbracoDocs#4284]
It would be great to get information about using Cache Refreshers over multiple server nodes. The document does say that it is important, and we are currently experiencing issues!

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Cache/ICacheRefresher/index.md***

**Comment by eshanrnh** [comment]
Hey @TomSearle 👋,

Sorry to hear you are experiencing issues and thanks for raising an issue 💪 We will run through this article by the D-Team and update it soon.

**Comment by kjac** [comment]
Hi @TomSearle,

That documentation is indeed a bit sparse. However, I suspect the documentation for cache refreshing might reside elsewhere. I will have a double check on that, but before I do... what specific documentation are you seeking here? Is it...

- How to use cache refreshers to invalidate cache?
- How to subscribe to cache refreshers being invoked?
- ... other?

If you could elaborate here I would appreciate it, so we can stitch together the correct documentation for cache refreshers.

**Comment by TomSearle** [comment]
I'll be honest, I was hoping the documentation would tell us whether we are even looking at the correct place for what we are trying to achieve. We have a load-balanced environment but keep finding shared resources (such as a custom Lucene index or member data) out of sync between the servers. I was hoping that we could subscribe to the cache refresher to manually update the indexes, but I'm not certain that is the correct approach.

**Comment by kjac** [comment]
Hi @TomSearle,

Thanks for elaborating. Sorry to hear you're having trouble. I understand where you're going, but I don't think it's the right approach either. These things should "just work" if you follow the documented approach for load balancing (https://our.umbraco.com/Documentation/Fundamentals/Setup/server-setup/load-balancing/).

Perhaps you can find some help on the forum? 

No matter what, @eshanrnh and I will have a talk about the article you pointed out. It does add a whole lot of value in its current state.

**Comment by eshanrnh** [comment]
Hey @TomSearle,

We hope you could find some help on the forum on [Our Umbraco](https://our.umbraco.com/forum/) 🤞

For now, we are closing this issue. We will improve/rewrite the [ICacheRefresher](https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Cache/ICacheRefresher/index.md) article in the coming months - It's added to our backlog. If you have any pointers or specific information as to how we can improve the article, please feel free to reach out to us.
