### ISSUE TITLE
Is custom settings still necessary with SQLite in v10?

### ISSUE THREAD

**Issue by skttl** [umbraco/UmbracoDocs#4290]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Umbraco-Cloud/Set-Up/Working-With-Mac/index.md***

**Comment by eshanrnh** [comment]
Hey @skttl 👋

It would be great if you could share some more details about what you are looking for. Are you just asking if you still need to configure SQLite in the `ConnectionStrings` while working with Mac? 🤔

If you are looking for `connectionstring` settings, you can refer to https://our.umbraco.com/documentation/Reference/Configuration/ConnectionStringsSettings/

**Comment by sofietoft** [comment]
Hi @skttl 👋 
It's been a while since there has been any activity on this one.

Does that mean you found an answer to your question elsewhere?
Let me know 💪

**Comment by sofietoft** [comment]
Hi @skttl !

It's been quite a while since we've seen any activity on this one.
I'll close it down for now, but please do not hesitate to get back in touch, if you have further questions!
