### ISSUE TITLE
Umbraco Forms v10 zip does not include FieldType.RichText.cshtml

### ISSUE THREAD

**Issue by Wiggee11** [umbraco/UmbracoDocs#4294]
The Umbraco Forms v10 theme download zip file does not include the new rich text field type view "FieldType.RichText.cshtml".

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Add-ons/UmbracoForms/Developer/Themes/index.md***

Details also not included in field types overview page - https://our.umbraco.com/documentation/Add-ons/umbracoforms/editor/creating-a-form/fieldtypes/

**Comment by eshanrnh** [comment]
Hi @Wiggee11 👋,

Thanks for flagging this issue. The zip file indeed does not include the rich text field type view. I will reach out to the team for it. We will also look into updating the article soon.
