### ISSUE TITLE
Add documentation on markdown descriptions for properties

### ISSUE THREAD

**Issue by jemayn** [umbraco/UmbracoDocs#4305]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## Describe the issue

With Umbraco 9.2+ it is now possible to write markdown + a few custom things (collapse) in the property descriptions. I was looking for documentation on that, but couldn't find any.

It is somewhat documented on the [PR](https://github.com/umbraco/Umbraco-CMS/pull/11628).

I'd be up for submitting a PR, but honestly not sure where to put it - maybe somewhere on [this page](https://our.umbraco.com/documentation/Fundamentals/Data/Defining-content/)?

**Comment by eshanrnh** [comment]
Hey @jemayn 👋

That page is a perfect location to add the details and a PR would be really appreciated 🙌 

Please feel free to submit a PR and add the details under https://our.umbraco.com/documentation/Fundamentals/Data/Defining-content/#adding-properties
