### ISSUE TITLE
Unclear instructions on using IFileSystem

### ISSUE THREAD

**Issue by pauldavis-dwe** [umbraco/UmbracoDocs#4312]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Extending/FileSystemProviders/index.md***

This page says to make a composer to call builder.SetMediaFileSystem(...) with a custom implementation of IFileSystem. It refers to editing startup.cs to call app.UseStaticFiles(...) but as "an extra step". Without it, when Umbraco tries to retrieve media it 404s.

The documentation should also say that we need to implement IFileProvider (and therefore also IDirectoryContents, and IFileInfo) to get media from another location e.g. Amazon S3.

**Comment by eshanrnh** [comment]
Hey @pauldavis-dwe 👋 

Thanks for raising your concerns and flagging the issue. I'll run this past the development team and hopefully we can update the article soon 🙂

**Comment by kjac** [comment]
PR in https://github.com/umbraco/UmbracoDocs/pull/4322
