### ISSUE TITLE
Most documentation pages giving "Oooops" message

### ISSUE THREAD

**Issue by jfsaliba** [umbraco/UmbracoDocs#433]
Looks like most of the Documentation pages are giving Oooops message (see image). Images are also returning 404. Example: 

https://our.umbraco.org/documentation/Reference/Querying/IPublishedContent

Something not working quite right at the moment?

![umbracodocs](https://cloud.githubusercontent.com/assets/395902/23521501/252812e8-ff34-11e6-90cd-a880fe7f321f.PNG)

**Comment by tappiorg** [comment]
Happening to me as well. All documentation pages.

**Comment by jfsaliba** [comment]
Docs are working again, dunno what was wrong but it's fixed now. :)
