### ISSUE TITLE
Inform about the need for ReservedPaths when using attribute routing

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/UmbracoDocs#4361]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Routing/Umbraco-API-Controllers/index.md***

There is a performance-issue with attribute routing if the appSetting `ReservedPaths` is not set:
https://our.umbraco.com/forum/umbraco-9/107344-api-controller-slower-than-regular-pages

The documentation should mention this and instruct to set the ReservedPaths-setting. In my case this made the call go from 50-60ms to 4-6ms. 

So, somewhere around this example there should be a text about setting this setting.

```
[Route("products/[action]")]
public class ProductsController : UmbracoApiController
{
    public IEnumerable<string> GetAllProducts()
    {
        return new[] {"Table", "Chair", "Desk", "Computer"};
    }

    public string GetProduct()
    {
        return "Monitor";
    }
}
```

**Comment by eshanrnh** [comment]
Thanks for providing us detailed feedback, @enkelmedia 💪

Would you be up for creating a PR? 😄 Let me know. We have some contribution guidelines here: https://our.umbraco.com/documentation/Contribute/

**Comment by eshanrnh** [comment]
This issue should now be fixed.
