### ISSUE TITLE
consider adding a call to IServiceCollection.ConfigureOptions

### ISSUE THREAD

**Issue by keithswright** [umbraco/UmbracoDocs#4372]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Security/External-login-providers/index.md***

Hi. This documentation works, but we were scratching our heads for a while until we remembered we had to add 

`services.ConfigureOptions<GoogleMemberExternalLoginProviderOptions>();`

to apply the configuration options. I know this is an obvious step and maybe should not be needed in the documentation, but because the sample includes the "ConfigureServices" code it might lead people to believe that the sample is a full working example.

**Comment by eshanrnh** [comment]
Hey @keithswright 👋

Thanks for your feedback. Looks like the article can definitely be updated with this step.

Would you be up for creating a PR? 😄 Let me know. We have some contribution guidelines here: https://our.umbraco.com/documentation/Contribute/
