### ISSUE TITLE
When setting up SignalR routes, you need to add the routes to `ReservedPaths`

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/UmbracoDocs#4391]
## What type of issue is it? (Choose one - delete the others)
Amending existing docs

## What article/section is this about?
[ReservedPaths](https://github.com/umbraco/UmbracoDocs/blob/main/Implementation/Custom-Routing/signalR.md)

## Describe the issue
As I've just learned from https://github.com/umbraco/Umbraco-CMS/issues/13005#issuecomment-1252282141 - when you add a SignalR route, Umbraco will try to find the page and end up in either custom 404 handlers or execute Umbraco's default `ContentFinderByConfigured404`. This is unnecessary and gives quite a bit of overhead. Instead we should add the SignalR route to the `ReservedPaths` config, like so:

```

  "Umbraco": {
    "CMS": {
      "Global": {
        "ReservedPaths": "~/app_plugins/,~/install/,~/mini-profiler-resources/,~/umbraco/,~/umbraco/testhub/"
        }
      }
    }
  }

Note that you need to provide the default reserved paths (`~/app_plugins,~/install/` etc), else you'll run into the issue described in https://github.com/umbraco/Umbraco-CMS/issues/12965

**Comment by eshanrnh** [comment]
Thanks, @nul800sebastiaan. We will add the info in the docs soon 🙂

**Comment by eshanrnh** [comment]
You can find this documentation at https://our.umbraco.com/Documentation/Implementation/Custom-Routing/signalR#add-the-route-in-appsettingsjson-file
