### ISSUE TITLE
Incorrect defaults for Global Settings

### ISSUE THREAD

**Issue by tormnator** [umbraco/UmbracoDocs#4394]
First, I believe the **"HideTopLevelNodeFromPath": false** setting, indicating that "**false**" is the default is incorrect, and that "**true**" is the actual default.

Second, the **"UmbracoScriptsPath": "\~/css"** is probably incorrect. The correct default should be **"~/js"**.
     

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Configuration/GlobalSettings/index.md***

**Comment by eshanrnh** [comment]
Thanks for flagging this issue, @tormnator 🙌 Sounds about right. However, looks like `UmbracoScriptsPath = "~/scripts";`

Would you be up for creating a PR? 😄 Let me know. We have some contribution guidelines here: https://our.umbraco.com/documentation/Contribute/

**Comment by tormnator** [comment]
Thanks @eshanrnh and @erikjanwestendorp, I see the fixes are already live. That's a pretty quick turn around! 👌
