### ISSUE TITLE
Improve readability of the docs

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#4416]
**Hacktoberfest** is upon us, and on the UmbracoDocs we have a very important task that we need **your** help with:

Improving readability!
===================================

Some time back, we implemented a style guide on the documentation - a series of "rules" to ensure consistency in the docs and articles that are easy to read.

The style guide is implemented using Vale, and every time a commit is made to the UmbracoDocs, it will be checked against all of our rules. The [rules can be found right here on the repository](https://github.com/umbraco/UmbracoDocs/tree/main/.github/styles/UmbracoDocs), and they include rules that recommends against the use of certain words, a rule that ensures that acronyms are defined and rules that ensures consistent spelling of certain terms.

How do I help out?
-----------------------------------

In order to make the task a little more edible, we've divided the docs into some sections.

**Write a comment** to this Issue, telling us which section you'd like to check, and make sure to reference this issue when you make the PR.
That way we can keep track of the progress, and other contributors will know which sections are already done or being worked on 💪 

- [x] Getting Started
- [ ] Tutorials (all!)
- [ ] Umbraco Forms
- [ ] Umbraco Deploy
- [ ] Umbraco Plumber

**Fundamentals**
- [ ] Setup
- [x] Backoffice
- [ ] Data
- [ ] Design
- [ ] Code

**Implementation**
- [x] Default and Custom routing
- [x] Controllers and Data Persistence
- [x] Composing and Services
- [ ] Integration Testing, Unit Testing and Nullable Reference Types

**Extending**
- [ ] Dashboard, Section Trees and Property Editors
- [ ] Health Checks and Language Files
- [ ] Backoffice Search, Tours and API
- [ ] Content App and Database
- [ ] Embedded Media Provider and FileSystemProviders
- [ ] Packages

**Reference**
- [ ] Configuration
- [ ] Templating
- [ ] Querying
- [ ] Routing
- [ ] Searching
- [ ] Management
- [ ] Plugins and Cache
- [ ] Debugging and Language Variation
- [ ] Notifications
- [ ] Scheduling and Using IoC

**Umbraco Cloud**
- [ ] Getting Started
- [ ] Setup
- [ ] Deployment
- [ ] Databases, Upgrades and Security
- [ ] Troubleshooting and Frequently Asked Questions

**Comment by erikjanwestendorp** [comment]
I would like to work on the Fundamentals part. 😄

**Comment by sofietoft** [comment]
Thanks for all your amazing work on making our docs more readable @erikjanwestendorp 🙌 🎉 #H5YR

I no longer have the full overview, but it sure looks like you've covered a lot!
I'll close this issue for now, as we are way past Hacktoberfest by now 😄
