### ISSUE TITLE
Add example with NPOCO and how to get data into a Content node in the BackOffice

### ISSUE THREAD

**Issue by biapar** [umbraco/UmbracoDocs#4418]
Add example with NPOCO and how to get data into a Content node in the BackOffice

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Tutorials/Creating-Tables-for-Umbraco-with-PetaPoco/index.md***

**Comment by eshanrnh** [comment]
Hey @biapar,

Can you let us know which version of Umbraco are you using?

**Comment by biapar** [comment]
10

**Comment by eshanrnh** [comment]
Ah, the article ([PetaPoco](https://our.umbraco.com/documentation/Tutorials/Creating-Tables-for-Umbraco-with-PetaPoco/#what-is-peta-poco)) you are referring to is valid only for Umbraco version 7. 

Umbraco version 8 and above uses [NPoco](https://our.umbraco.com/documentation/Extending/Database/) to query the database. You can refer to this article instead 🙂

Hope you find the solution 🤞

**Comment by biapar** [comment]
Hi. Thanks. I see it, but there isn't a documentation about how to CRUD data from external tables with standard BackOffice UI datatypes. Thais is: I create a table and I wish to manipulate data or in a custom section or in a content node.

**Comment by eshanrnh** [comment]
We have some documentation here: [Data Persistence (CRUD) in Umbraco](https://our.umbraco.com/Documentation/Implementation/Data-Persistence/) and [UmbracoHelper](https://our.umbraco.com/documentation/Reference/Querying/UmbracoHelper/)

If you are looking for specific information, you can try reaching out on the Forum on [Our Umbraco](https://our.umbraco.com/forum/). Might be that someone has had a similar issue before and you might find a resolution.

**Comment by sofietoft** [comment]
Hi @biapar !

It's been a few days since we've seen any activity on this one.
I hope that means that you managed to solve what was blocking you 💪 

I'll close this issue for now.
Please do not hesitate to get back in touch!
Have a great day!
