### ISSUE TITLE
Tutorial: Creating a new section with custom content in Umbraco

### ISSUE THREAD

**Issue by jemayn** [umbraco/UmbracoDocs#4423]
## What type of issue is it? (Choose one - delete the others)
Idea for expanding the documentation

## What article/section is this about?
New one

## Describe the issue

Hey Docs curators!

I'd like to write a new tutorial about storing custom data in a custom db table and then creating some Umbraco-looking UI to handle that data so it looks like other built in nodes.

Would be a simple example that would cover Migrations, NPoco in Umbraco and some examples of building Umbraco UI in the backoffice.

Figured I would clear it with you here before working on it, but I see several people asking about stuff like this, so it may be helpful 😊

**Comment by sofietoft** [comment]
Hi 👋 

This sounds like a great idea!
How about using the "[Samples Site](https://github.com/umbraco/Umbraco.Docs.Samples)" for the tutorial?
It's a project that the Curators team have been working on, to align the code samples in the documentation.
You can contribute to it like you would the Docs.
So, build and test with the Samples Site, and then put the docs here? 🤞

**Comment by sofietoft** [comment]
Hi @jemayn 👋 

Quick follow-up here:
You still planning on working on a tutorial for storing custom data in the custom database tables? 😁

**Comment by jemayn** [comment]
Hey @sofietoft 

Sorry I had some health issues which ruined my hackotberfest plans. Will get back to this shortly, it is still part of my plans 😊
