### ISSUE TITLE
Minimum azure app service plan tier recommendation for a MVP 

### ISSUE THREAD

**Issue by jose-lopez1** [umbraco/UmbracoDocs#4437]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Setup/Server-Setup/azure-web-apps.md***

Hi all,

It would be great to see some official recommendations when it comes to azure app service plan tier ( for both, single intances and load-balancing setups).  The current documentation currently has an official recommendation when it comes to database tier ( SQL S2) but no mentions of the App Service Plan.

**Comment by sofietoft** [comment]
Hi @jose-lopez1  👋 

Thanks for asking this question.
We might not have any official recommendation for the Azure Web Apps setup, other than what we already have in the article you're referencing.
Just in case though, I'll run it by our development team to check 💪

**Comment by sofietoft** [comment]
Hi @jose-lopez1 !
I've chatted with our developers about this, and we will not be adding any official recommendations about Azure App Service plan tiers to this article.
The reasoning behind the decision is that the tier you should choose highly depends on your project requirements. There are many factors in play here, so it would be almost impossible for HQ to make any general recommendations that would fit all.

Thanks again for raising the issue and challenging us on this 💪 
I'll close this issue for now.
Please do not hesitate to get back in touch if you have further questions.
Have a great day!
