### ISSUE TITLE
Can we add instructions to disable the NuCache file generation on Umbraco 8?

### ISSUE THREAD

**Issue by robertjf** [umbraco/UmbracoDocs#4456]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Configuration/NuCacheSettings/index.md***

The sample code to disable on Umbraco 8 is as follows:

```csharp
    public class DisableNuCacheDatabaseComposer : IComposer
    {
        public void Compose(Composition composition)
        {
            var settings = new Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotServiceOptions
            {
                IgnoreLocalDb = true
            };
            composition.Register(factory => settings, Lifetime.Singleton);
        }
    }
```

**Comment by sofietoft** [comment]
Hi @robertjf ! 👋 

Is it correct, that you're asking whether the code snippet you posted would make sense to add to the "NuCacheSettings" docs or not?
I think a better place for this would be in the "[Cache](https://our.umbraco.com/Documentation/Reference/Cache/index-v8)" section, as the section you're referring to is only for version 9+.

Let me just run it by some of our developers! I'm sure they will have some valuable input on this one for us 💪

**Comment by robertjf** [comment]
hey @sofietoft - yes, it would make more sense in an Umbraco 8 specific page, but is related to this one...

**Comment by sofietoft** [comment]
Great @robertjf ! Thanks for confirming.

I'll see if I can locate a caching expert that can help us find the perfect place for this snippet 💪

**Comment by Akimetheus** [comment]
Hello everyone, i have a problem (in log file):
"An unhandled exception was thrown by the application.","@l":"Error","@x":"System.IO.IOException: The process cannot access the file '\\\\server\\root\\hostname\\htdocs\\folder\\umbraco\\Data\\TEMP\\NuCache\\NuCache.Content.db' because it is being used by another process."
So in Umbraco doc advise to  implement:

```
"Umbraco": {
  "CMS": {
    "NuCache": {
      "BTreeBlockSize": 4096
    }
  }
}
```


```
public class DisableNuCacheDatabaseComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        var settings = new Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotServiceOptions
        {
            IgnoreLocalDb = true
        };
        builder.Services.AddSingleton(settings);
    }
}
```

How and where can i use/invoke the Compose method of DisableNuCacheDatabaseComposer ? In Startup file? In Program file?

Thanks in advance and have a nice day

**Comment by sofietoft** [comment]
Sorry to hear you're running into some trouble here @Akimetheus !

Did you manage to resolve it, or are you still experiencing issues?
