### ISSUE TITLE
Missing info : Restoring a database from cloud to a local database

### ISSUE THREAD

**Issue by CarlSargunar** [umbraco/UmbracoDocs#4484]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
Restoring a database from cloud to a local database

## Describe the issue
There are some steps required before you are able to restore a cloud bacpac file to a local DB, these were missing

**Comment by CarlSargunar** [comment]
PR Submitted : https://github.com/umbraco/UmbracoDocs/pull/4483

**Comment by sofietoft** [comment]
Thanks for submitting this issue @CarlSargunar ! 💪 
I've reviewed the referenced PR.

**Comment by jonat123** [comment]
Closing this issue as the associated PR has been merged in :)
