### ISSUE TITLE
Consistency improvements across the Fundamentals section of docs 

### ISSUE THREAD

**Issue by emma-hq** [umbraco/UmbracoDocs#4507]
## What type of issue is it? (Choose one - delete the others)
Discussion

## What article/section is this about?
(link [here)](https://our.umbraco.com/documentation/Fundamentals/)

## Describe the issue
Some of the articles here have a tagline underneath the main heading describing what is in the section. I'd like to add that to each of the articles in the Fundamentals section to improve consistency and readability. 

See below for an example 
![image](https://user-images.githubusercontent.com/78740801/197218922-8a3cdde1-1599-4268-ab54-fe310f05bee9.png)

**Comment by sofietoft** [comment]
That would be amazing @emma-hq ! 👏 

The new platform that we're moving the docs to, actually has a feature that allows us to add a description under the title for each article. That would be a perfect fit for something like this, right? 😄

**Comment by sofietoft** [comment]
Hi @emma-hq 👋 

Is this something you're still working on?
Since we migrated to a new platform, this is now the new format for adding a description/tagline to article:

```
---
description: "The description goes here"
---
```

And that should be added to the very top of the article - even before the title heading 💪

**Comment by emma-hq** [comment]
Hej Sofie, it's something I may pick up at the next hackathon but as the platform has changed and we now have a new format, feel free to close the issue
