### ISSUE TITLE
Docs to mention cache refresher notifications

### ISSUE THREAD

**Issue by bjarnef** [umbraco/UmbracoDocs#4536]
***This is the page with issues: https://our.umbraco.com/documentation/Reference/Notifications/ContentService-Notifications/

There are several notifications mentioned here, but I couldn't find anything about these cache refresher notifications:

- CacheRefresherNotification
- ContentCacheRefresherNotification
- MediaCacheRefresherNotification
- MemberCacheRefresherNotification
- UserCacheRefresherNotification

Not sure if these belong under e.g. [ContentService Notifications](https://our.umbraco.com/documentation/Reference/Notifications/ContentService-Notifications/) and [MediaService Notifications](https://our.umbraco.com/documentation/Reference/Notifications/MediaService-Notifications/) or if there should be a separate page for cache refresher notification?

Also see this old issue as reference in v8 https://github.com/umbraco/Umbraco-CMS/issues/10169 where I used these `ContentCacheRefresherUpdated` event.

**Comment by sofietoft** [comment]
Hi @bjarnef !
Thanks for reporting this. 
Looks like you've identified some missing docs here 😅 
I've tried searching our docs for each of those notifications, but as you might have guessed, I'm coming up empty.
Sounds to me like these should be documented in their own article - one for CacheRefresherNotifications, like you suggest!

I'll run it by our developers for a second opinion 💪

**Comment by sofietoft** [comment]
Hi @bjarnef !

Looks like this one can be closed: https://github.com/umbraco/UmbracoDocs/pull/4723 

Thanks again for notifying (get it?!) us about this missing doc 😄 
Cheers!
