### ISSUE TITLE
Code sample and title mismatch - IPublishedContent URL property

### ISSUE THREAD

**Issue by benbarnett02** [umbraco/UmbracoDocs#4558]
Under the title ".Url(IPublishedUrlProvider, culture = null, UrlMode mode = UrlMode.Default) - (Extension method)" the code sample says:
`@Model.Url(PublishedUrlProvider)`

The title says "**I**PublishedUrlProvider" whereas the code says `PublishedUrlProvider`

https://our.umbraco.com/Documentation/Reference/Querying/IPublishedContent/Properties/#urlipublishedurlprovider-culture--null-urlmode-mode--urlmodedefault---extension-method

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Querying/IPublishedContent/Properties/index.md***

**Comment by sofietoft** [comment]
Thanks for reporting this @benbarnett02 ! 😎 

Sure looks like a case of the code sample was updated, but not the heading 🙈 nice catch!
Would you be up for making a PR suggesting the change?
We have some docs on how to contribute here: https://our.umbraco.com/documentation/Contribute/
