### ISSUE TITLE
Create a Build and Deployment page

### ISSUE THREAD

**Issue by mattou07** [umbraco/UmbracoDocs#4644]
## What type of issue is it? (Choose one - delete the others)

Missing documentation

## What article/section is this about?
Creating a new page

## Describe the issue
It would be useful to have a page about creating a simple build pipeline either in Azure DevOps or Github actions etc. Additionally talking about deploying Umbraco would be useful too.

Happy to start this but not sure where to create the page.

**Comment by mattou07** [comment]
I will start something in: UmbracoDocs/Tutorials

**Comment by sofietoft** [comment]
Hi @mattou07 !

This is definitely a great idea 😄 and amazing to hear you're up for taking a shot at writing it 💪 

And the Tutorials section is a super place for it.
My initial thoughts were to put it in the "Fundamentals/Setup/Server-Setup" section (https://our.umbraco.com/documentation/Fundamentals/Setup/Server-Setup/).
But we can always link from the server setup section to the tutorial and vice versa! 💪

**Comment by sofietoft** [comment]
Hi @mattou07 !
You still up for making a tutorial about a simple build pipeline here? 😄 

We've changed the structure a bit, so now an article like this should be added to "11/umbraco-cms/tutorials" or "11/umbraco-cms/fundamentals/setup/server-setup" 💪

**Comment by mattou07** [comment]
> Hi @mattou07 ! You still up for making a tutorial about a simple build pipeline here? 😄
> 
> We've changed the structure a bit, so now an article like this should be added to "11/umbraco-cms/tutorials" or "11/umbraco-cms/fundamentals/setup/server-setup" 💪

Yes I am, apologies been a little busy!

**Comment by mattou07** [comment]
Got a PR ready: https://github.com/umbraco/UmbracoDocs/pull/5006

**Comment by alina-tincas** [comment]
Hi @mattou07 

I am closing this issue as you received an answer from my colleague Sofie in the [PR ](https://github.com/umbraco/UmbracoDocs/pull/5006#issuecomment-1459736323) you created. 🙏 

Thank you again for reaching out and for creating the PR and do not hesitate to contribute again to our documentation. Every help is much appreciated #h5YR 🙌
