### ISSUE TITLE
Incorrect path

### ISSUE THREAD

**Issue by C0derPr0** [umbraco/UmbracoDocs#4651]
The path to the generated models is incorrect. It should be ~/umbraco/Data/TEMP/InMemoryAuto instead of the old path ~/umbraco/Data/TEMP/PureLive.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Templating/Modelsbuilder/Builder-Modes.md***

**Comment by sofietoft** [comment]
Thanks for reporting this @C0derPr0 !
You're absolutely right - sure looks like that part was overlooked when the articles was updated 🙈 

Would you be up for making the change? 😎 
We have some Contribution guidelines to help you out: https://our.umbraco.com/documentation/Contribute/

**Comment by C0derPr0** [comment]
Hi there, @sofietoft. I updated the docs and submitted a pull request. I didn't see any other occurrences on other articles.

**Comment by sofietoft** [comment]
Looks like we can close this issue, as a related PR was merged 💪 

Thanks again for helping us keep the docs up to date!
Cheers!
