### ISSUE TITLE
Fix svg icon sizes

### ISSUE THREAD

**Issue by steve-oconnor** [umbraco/UmbracoDocs#4665]
For example the nodes icons on the [Backoffice Sections page](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/sections)

I notice the container div size is 100% as are the height and width of the icons themselves.
 
![Screenshot 2022-11-23 at 12 21 45](https://user-images.githubusercontent.com/78745153/203545723-eeb137c2-2974-4d8a-996d-5894d8209747.png)

**Comment by sofietoft** [comment]
😱 
That doesn't look super great!!

Thanks for highlighting this @steve-oconnor !
We're in the process of cleaning things like this up on the new platform - I'll make sure to flag this article 💪

**Comment by sofietoft** [comment]
Hi @steve-oconnor !

Sorry for the delay on this one.
Looks like the inline-images in the article has been scaled down: https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/sections 

Thanks again for helping us keep the docs up to date and looking good 💪 
MUCH appreciated!
