### ISSUE TITLE
[New Site] Header Search box has a strange character in it

### ISSUE THREAD

**Issue by NikRimington** [umbraco/UmbracoDocs#4669]
## What type of issue is it?
Other (write it here)

## What article/section is this about?
All (https://docs.umbraco.com/)

## Describe the issue
When visiting the new Docs site in Chrome on Windows 11 the search input has a strang `^K` in it. Not entirely sure why, I've attached a screenshot.

![image](https://user-images.githubusercontent.com/13313745/203613635-250912fb-8cf1-46a7-80a3-6af3dd5c0d61.png)

**Comment by eshanrnh** [comment]
Hey @NikRimington,

^K is GitBook's way of displaying shortcuts. Press **CMD + K** on Mac or **Ctrl + K** on Windows 🙂

**Comment by NikRimington** [comment]
That interesting to know. I have to say it looks like it's a mistake/error. I don't know if something can be done to improve the styling or help visitors know it's intentional? Might need a wider discussion but I've never noticed it on other sites (not sure if I've seen other GitBook sites).

**Comment by sofietoft** [comment]
Hi @NikRimington ! 👋 
Just adding my voice to this one.

I hadn't actually thought that the characters in the search field could be a confusing element.
I'm afraid it's not something we can remove at the moment.

Thanks a bunch for the feedback, though! Much appreciated.
I'll make sure we add it to our feedback list - might be something we can submit as a feature request to the GitBook team 🤞

**Comment by sofietoft** [comment]
Hi @NikRimington !

Thanks again for your feedback on the new docs platform 💪 Much appreciated.

The feedback has been sent through to the GitBook platform, so I'll close this issue for now!
