### ISSUE TITLE
Possible inaccuracy in 404 Content Finder example

### ISSUE THREAD

**Issue by drpeck** [umbraco/UmbracoDocs#4671]
> This example creates a new implementation of the IContentLastChanceFinder and checks whether the requested content could not be found by using the default Is404 property presented in the PublishedRequest class.
 
 I'm trying to understand how a IContentLastChanceFinder  works, but as far as I can see the example does not use "the default Is404 property presented in the PublishedRequest class".

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Routing/Request-Pipeline/IContentFinder.md***

**Comment by sofietoft** [comment]
Thanks for the report @drpeck !

Sounds like we might have made some changes to the code samples here, without updating the text 🤔 or the other way around!

I'll pass it by our developers for a check 💪

**Comment by Zeegaan** [comment]
@drpeck You are totally right. The example now will try and find the appropriate 404 node in the correct language 👍

**Comment by alina-tincas** [comment]
Hi @drpeck! The description of the example has been updated in this PR #5225 (thank you @royberris for this 🙌) therefore I am closing this issue. As a small note regarding the PR, I also made the change in the v10 docs 👍
