### ISSUE TITLE
No context for instructions

### ISSUE THREAD

**Issue by ault** [umbraco/UmbracoDocs#4699]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Extending/Key-Vault/index.md***

Line 136 is completely confusing. Which file is the user to paste the json into? Should it be at the root level? There is no context here.

Likewise, the first instruction (line 39) to edit apsetings.json does not provide a context for the code... Should it go at root? Within `"Umbraco": {` ? Noob users need more information.

**Comment by sofietoft** [comment]
Thanks for raising this issue @ault !

There is clearly some context missing here, as to where the config needs to go.
I'll make sure we take a look and get these things corrected 💪

**Comment by alina-tincas** [comment]
Hi @ault 👋 

Sorry for the delay on this one! We have reviewed the documentation and added further information to make it clear where to paste the json code here: https://docs.umbraco.com/umbraco-cms/extending/key-vault 

For line  (line 39) you can paste the json anywhere in the root level as long as you resolve it in the method `inConfigureAppConfiguration`

For line 136 you can paste the json in the azure web app -> settings -> configuration -> advanced edit- When you click "advanced edit" a new window will show up and you will see that there is where you need to paste the json code 👍 

With this I am closing this issue however, if you have any further feedback do not hesitate to create a new issue or [contribute to our documentation ](https://docs.umbraco.com/welcome/contribute/getting-started).
