### ISSUE TITLE
umbraco-cms/fundamentals/backoffice/login documentation not working

### ISSUE THREAD

**Issue by huwred** [umbraco/UmbracoDocs#4738]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
umbraco-cms/fundamentals/backoffice/login

## Describe the issue
Following the instructions to customize the greetings does not work

**Comment by sofietoft** [comment]
Thanks for the report @huwred ! Much appreciated.

This is the section you're referring to: https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/login#greeting - correct?

Which version of Umbraco did you use when you tried to follow this doc?

**Comment by huwred** [comment]
Hi,
yes that is the correct section, I was testing it in version 11

**Comment by sofietoft** [comment]
Perfect! Thanks for the details @huwred !

I'll make sure we have this tested properly 🙌

**Comment by huwred** [comment]
Many thanks, this worked perfectly

Cheers 
Huw
