### ISSUE TITLE
No example to append Block Name in Label

### ISSUE THREAD

**Issue by deanleigh** [umbraco/UmbracoDocs#4767]
Missing documentation

Configuring block editor label properties
([Configuring block editor label properties](https://github.com/umbraco/UmbracoDocs/blob/main/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration.md#configuring-block-editor-label-properties))

## Describe the issue
No example to append Block Name
 e..g. Add {{ }} in the label over-ride the default name 
 often we want to append e.g. {{ block.content.contentTypeName }} + {{ something else }}
 
But {{ $block.content.contentTypeName }} seems to return notthing

What is the correct syntax?

**Comment by eshanrnh** [comment]
Hi @deanleigh,

Thanks for reporting this issue. Looks like we can definitely add an example to improve the documentation.

I'll run it by our developers for an opinion on this one 💪

**Comment by deanleigh** [comment]
Thank you @eshanrnh - the use case arises when using the label to return some data and you wisf to retain the blocks name as a prefix but… also if the data returned is empty or null (e.g. within a ternary operator in the {{mustache}}) and you wish to diplay the blocks name instead

**Comment by nielslyngsoe** [comment]
Hi @deanleigh 

I have updated the documentation to include the 'special variable' of $contentTypeName and $layout.
https://github.com/umbraco/UmbracoDocs/blob/main/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration.md#configuring-block-editor-label-properties

And I also added a PR for a proposal on such example:
https://github.com/umbraco/UmbracoDocs/pull/4855

Let me know what you think, I will close this Issue with this :-)

**Comment by deanleigh** [comment]
Thank you @nielslyngsoe.
Many people think you can have Angular Filters 'or' the name but not both.
Perhaps that could be made clear in the example that you can append / prepend $contentTypeName to a filter.
