### ISSUE TITLE
Logging level documentation is unclear

### ISSUE THREAD

**Issue by ChrisPleasant** [umbraco/UmbracoDocs#4768]
The [documentation regarding debugging](https://docs.umbraco.com/umbraco-cms/fundamentals/code/debugging#tracing) reads _"Logging and tracing are really two names for the same technique."_  and then right after _"Do not enable trace logging in your production environment!"_

Between these two lines it appears you're instructing people to disable logging completely on production systems, which can't be right.  After discussion with a colleague, we think maybe the first line should read "Logging _at the verbose level_ and tracing are really two names for the same technique."?

Thanks

**Comment by eshanrnh** [comment]
Hi @ChrisPleasant,

Thanks for reporting this issue. I'll run it by our developers for their opinion on this one 💪

**Comment by bergmania** [comment]
I agree with @ChrisPleasant.

 "_Logging and tracing are really two names for the same technique._" is not correct.
 
Tracing is more equal to an extremely detailed logging of what code have been executed (what endpoints or methods have been called), and that is definitely not recommended to have turned on, on production environments.

**Comment by sofietoft** [comment]
Hi @ChrisPleasant !

Just wanted to let you know, that the wording in the Tracing section of the Debugging article has been updated.
Should read a little clearer now 🤞 

I'll close this issue for now!
