### ISSUE TITLE
fix .Net SDK version for Umbraco Cloud local development

### ISSUE THREAD

**Issue by idseefeld** [umbraco/UmbracoDocs#4772]
## What type of issue is it? 

Wrong documentation

## What article/section is this about?

[Working with a Local Clone](https://docs.umbraco.com/v/10.x-lts/umbraco-cloud/set-up/working-locally)

## Describe the issue
Section "Running the site Locally" references the latest .Net SDK as requirement to run the cloned Umbraco Cloud project locally. But actually you have to look into file `global.json` to figure out the correct SDK version.

**Comment by eshanrnh** [comment]
Thanks for reporting this issue and raising a PR, @idseefeld 🙌 We will review this soon.

**Comment by jonat123** [comment]
@idseefeld Some time ago the issue that was the reason for us adding the global.json file to projects has been fixed and the global.json file has been removed from all Cloud projects.

I will therefore close this issue.
