### ISSUE TITLE
Previewing rendered output locally does not work anymore

### ISSUE THREAD

**Issue by idseefeld** [umbraco/UmbracoDocs#4779]
## What type of issue is it?
Wrong documentation

## What article/section is this about?
[(Root readme)](https://github.com/umbraco/UmbracoDocs)

## Describe the issue
The mentioned preview app does not work, because `index.md` files have been renamed into `readme.md`. 
The whole project is archived and no issues can be reported.

**Comment by sofietoft** [comment]
Hi @idseefeld !
I'll close this issue, as the information about the Preview project has been removed from the Docs section.

Thanks again for making me aware of the fact 💪
