### ISSUE TITLE
Scroll needed for right hand column

### ISSUE THREAD

**Issue by craigs100** [umbraco/UmbracoDocs#4781]
Page https://apidocs.umbraco.com/v9/csharp/api/Umbraco.Cms.Core.Services.IContentService.html#methods

There are at least 25 methods unseen in the right hand menu because it's height is fixed and doesn't scroll.  Viewing at 2560x1440 on 27" screen, chrome-based browser.

Suggest the right hand column be allowed to scroll to allow proper sub-navigation.

**Comment by jonat123** [comment]
@craigs100 Hello there!

thanks for opening this issue and it is clearly a problem.

The API documentation is not something that we here at the docs team are managing.

And it is not something we can change on our end.

Instead, it is auto-generated based on the source code from the CMS.

I suggest that you create an issue on the CMS tracker instead.

I hope this makes sense :)

**Comment by craigs100** [comment]
By "CMS" do you mean Umbraco or something to do with github as I understood it was autogenerated by GH.

**Comment by sofietoft** [comment]
Hi @craigs100 !

By CMS we mean the Umbraco CMS.
The API docs you are referring to here are separate from the Umbraco Documentation.
The API Docs (apidocs.umbraco.com, https://apidocs.umbraco.com/v10/csharp/api/Umbraco.Cms.Core.html) are auto-generated based on the Umbraco CMS source code.
The Umbraco Documentation, on the other hand, is a GitHub repo managed by the documentation team here at Umbraco HQ - which is then published on docs.umbraco.com.

It's a little confusing, but I hope I manage to make it a little clearer 😅 
In any case, questions/suggestions related to the API docs, should be posted on the [Umbraco CMS issue tracker](https://github.com/umbraco/Umbraco-CMS/issues) 💪
