### ISSUE TITLE
Higlighting of found search term is erratic...

### ISSUE THREAD

**Issue by mistyn8** [umbraco/UmbracoDocs#4821]
## What type of issue is it? (Choose one - delete the others)
Searching

## What article/section is this about?
multiple

## Describe the issue
Not sure exactly what it's trying to do.. but typing in the search modal seems a bit hit and miss for it updating the highlighted search term

![image](https://user-images.githubusercontent.com/12418214/211781471-ce65b3d1-42af-4ed0-a74d-ecbfe70358d8.png)

If you cut and paste the whole term back in it highlights correctly

Other than that it seems to erratically work on not, when typing in the modal search term box, or indeed when deleting chars 

eg typing `Den` gives correct higlighting.. adding a `y` for `Deny` only highlights `den`,  then add `L` and we get highlighting of `DenyL`  but then completing `DenyLocalLogin` and we've only got `DenyL` highlighted.

deleting from right to left then only kicks back in when we get down to 3chars

It may also be related to some sort of intent implementation, as typing quicker gets different highlights to work... 🤔 

Not a deal breaker, just annoying :-)

**Comment by sofietoft** [comment]
This is indeed complicated @mistyn8 , but I think I understand!

I do believe that the highlighting in the search result is something that happens dynamically as you type, and probably stops highlighting once it stops searching - if that makes sense.
That would explain why it highlights the entire search team when you paste it in, in its full form, and why it only highlights parts of it, when the search happens once you type.

Also, it's not something we have any control over, as this part is controlled by the platform.
I can let the GitBook people know, but as it doesn't really affect the result of the search, I don't see it as a major thing - as you also mention yourself 😄

**Comment by sofietoft** [comment]
Hi @mistyn8 !

I'll be closing this issue, as the highlighting of the search results, is not something we can resolve at the moment.
I've made a query with the platform providers - they are currently working on improving the search in general, which I'm sure will mean good things are coming our way.

Thanks again for reporting your findings @mistyn8 ! Much appreciated 🙌
