### ISSUE TITLE
Suggestion for the "Going Live" page of Umbraco Cloud

### ISSUE THREAD

**Issue by readingdancer** [umbraco/UmbracoDocs#4832]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-cloud/set-up/going-live

## Describe the issue
On the above mentioned documentation page, it does not mention anything about using a root domain ( e.g. umbraco.com ) as officially you are not meant to use a CNAME record with a root domain, Cloudflare DNS does support this, but most other DNS platforms probably do not as it doesn't follow the specification and potentially breaks email services (a known issue with Exchange Servers)

I found the following Github issue that seems to say we can point an A record directly to two IP addresses, I assume it's the same addresses that the current dns.umbraco.io resolves to, but it would be good to have this officially documented on the above page.

https://github.com/umbraco/Umbraco.Cloud.Issues/issues/426

Cheers,

Chris

**Comment by sofietoft** [comment]
Thanks for suggesting this @readingdancer ! 💪 
Sure sounds like something we could add some more detailed information about.

We'll take a look and see if we can make this bit of information more clear in our docs!

**Comment by jonat123** [comment]
@readingdancer I have been looking a bit at your PR and the issue that you are linking as well.

About the IPs, we do have it documented that they can be used instead of the CNAME here: 
- https://docs.umbraco.com/umbraco-cloud/set-up/project-settings/manage-hostnames#domains 

As I understand you think it would be great to also add them to the going-live documentation as well.

Is that correct? 

- Jonathan

**Comment by jonat123** [comment]
@readingdancer It's been a while since I've heard from you, therefore I will close this issue.

You are more than welcome to open the issue again if you believe that we should look more into it.

Best regards 
Jonathan

**Comment by readingdancer** [comment]
@jonat123 - Sorry I have just been busy, you are right that I think this info would be really useful on the going live page, perhaps just a cross link to the other page that you mentioned?

**Comment by readingdancer** [comment]
@jonat123 - Sorry I have just been busy, you are right that I think this info would be really useful on the going live page, perhaps just a cross link to the other page that you mentioned?

**Comment by readingdancer** [comment]
> @readingdancer It's been a while since I've heard from you, therefore I will close this issue.
> 
> 
> 
> You are more than welcome to open the issue again if you believe that we should look more into it.
> 
> 
> 
> Best regards 
> 
> Jonathan

@jonat123 - Sorry I have just been busy, you are right that I think this info would be really useful on the going live page, perhaps just a cross link to the other page that you mentioned?
