### ISSUE TITLE
Out of date image

### ISSUE THREAD

**Issue by huwred** [umbraco/UmbracoDocs#4859]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
https://github.com/umbraco/UmbracoDocs/blob/cddaf22af266b69e6a8ddd90a5b2f05ab2776832/umbraco-cms/reference/templating/macros/README.md

## Describe the issue
This first image on the page looks like Umbraco 7 and is therfore not relevant for the new documentation and may be misleading

**Comment by sofietoft** [comment]
Good catch @huwred ! Thanks for making us aware of this.

Would you be up for updating the image?
Otherwise I'll add it to our tasks here at the HQ team, and we'll take a look as soon as we have a spare minute 💪

**Comment by huwred** [comment]
> Would you be up for updating the image?

@sofietoft I will give it a go, but never updated anything before 😄

**Comment by sofietoft** [comment]
Ah! Well we have some contribution docs here: https://docs.umbraco.com/v/10.x-lts/contribute/getting-started 
That should give you all the info you need 😄

**Comment by huwred** [comment]
Thanks @sofietoft I will give it a go 😆

**Comment by sofietoft** [comment]
Awesome! 😄 
Let me know if you need help with anything 💪

**Comment by huwred** [comment]
I think I figured it out, the correct image was already in the repository so I have updated the readme with the correct image and created my first pull-request 😄  hope it is OK.

**Comment by sofietoft** [comment]
That's excellent! 🤩 
I'll take a look right away!
