### ISSUE TITLE
Hot versus cold restarts in Umbraco show's page not found for v9+ docs

### ISSUE THREAD

**Issue by dKumarmj** [umbraco/UmbracoDocs#4895]
## What type of issue is it?

Missing documentation

## What article/section is this about?
[Hot versus cold restarts in Umbraco for v7 - v8](https://our.umbraco.com/documentation/Reference/Events/hot-vs-cold-restarts)
Missing - [Hot versus cold restarts in Umbraco for v9+](https://docs.umbraco.com/umbraco-cms/reference/events/hot-vs-cold-restarts)

## Describe the issue

The documentation for Hot versus cold restarts in Umbraco v9+ are missing, please see here [v9 +](https://docs.umbraco.com/umbraco-cms/reference/events/hot-vs-cold-restarts
)

**Comment by sofietoft** [comment]
Thanks for reporting this @dKumarmj !
It sure looks like we missed an article here - actually, it looks like several articles in that section.

I'll run it by our developers right away.
In the mean time, you might be able to find some of what you need in either of these articles:
[Creating and publishing notifications](https://docs.umbraco.com/umbraco-cms/reference/notifications/creating-and-publishing-notifications)
[Using Notifications](https://docs.umbraco.com/umbraco-cms/reference/notifications)
or perhaps this one: [Runtime Modes](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/runtime-modes).

**Comment by jonat123** [comment]
@dKumarmj this was fixed in the #4977 PR :-)

I will close down this issue.
