### ISSUE TITLE
Missing Documentation Page - Our Documentation > Add ons > UmbracoForms > Developer > Extending > Adding a Prevaluesourcetype

### ISSUE THREAD

**Issue by theotherpotter** [umbraco/UmbracoDocs#4903]
**What type of issue is it?**
Missing documentation

**What article/section is this about?**
[Umbraco Forms - Adding a Custom PreValue Source Type v8](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Prevaluesourcetype)

**Describe the issue**
The page for Adding a Custom PreValue Source Type to UmbracoForms is returning a 404.  See [Umbraco Forms - Adding a Custom PreValue Source Type v8](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Prevaluesourcetype)

**Comment by sofietoft** [comment]
Thanks for reporting this @theotherpotter ! 💪 

I've done some digging, and found that this is only something we have documented to Umbraco 9+.
You can find the article on our news docs platform: https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-prevaluesourcetype

I'll make sure to fix the link as well!

**Comment by sofietoft** [comment]
The link has now been fixed 💪 

I'll have a word with out Forms developers about whether or not there are any plans to add a v8 version of this article.

**Comment by sofietoft** [comment]
HI @theotherpotter !
Apologies for the late reply here.

Unfortunately there are no plans for adding an Umbraco 8 version of the prevalue source types at the moment.

The links have been fixed though, so I'll close this issue for now.
Please do get back in touch if you have further questions or find something else that's out of order 💪 

Cheers!
