### ISSUE TITLE
The database failed to upgrade. ERROR: The database configuration failed with the following message: Invalid column name 'preventCleanup'.

### ISSUE THREAD

**Issue by jmc18** [umbraco/UmbracoDocs#4904]
## Whan I tried to migrate the database from my old Umbraco v7 to v8 I get this error 
`The database failed to upgrade. ERROR: The database configuration failed with the following message: Invalid column name 'preventCleanup'.`

![image](https://user-images.githubusercontent.com/24300082/217668788-9e2f8693-0c9b-451c-837a-b529a779682d.png)

**Comment by sofietoft** [comment]
Hi @jmc18 !
Thanks for reporting this.
Sorry to hear you're having trouble upgrading your project.

A few questions to help me investigate:

- Are you following the "[7 to 8 migration guide](https://our.umbraco.com/documentation/Fundamentals/Setup/Upgrading/migrating-to-v8)"?
- And which version of Umbraco 8 are you upgrading to?

**Comment by jmc18** [comment]
Hi @sofietoft!

I'm following this [documentation](https://our.umbraco.com/documentation/Umbraco-Cloud/Upgrades/Migrating-from-7-to-8/) since my projects are  from Umbraco Cloud

I'm trying to migrate from v7.15.7 to v8.18.5 because that version comes from the cloud project.

Thanks!

**Comment by sofietoft** [comment]
Thanks for providing a bit more details here @jmc18 !

I'm afraid it's not possible to upgrade directly from the latest Umbraco 7 to the latest Umbraco 8.
You will need to migrate from the latest 7 to Umbraco 8.5 first.
This version includes a content migration to help you migrate all your things properly.
This migration needs to be done locally, as it's not possible to get a new Cloud project on that version.
You can follow this guide: https://our.umbraco.com/Documentation/Fundamentals/Setup/Upgrading/migrating-to-v8 - when it says 8.1, use 8.5 instead 💪 

After you've migrated to 8.5 locally, you can continue to migrate the project to the new 8 Cloud project.

I hope it makes sense.
I'd recommend that you reach out to the Cloud support team, if you need further assistance with this.

We are currently looking at updating our upgrade docs to make them more transparent and provide a better flow.
I'll make sure we add these extra steps to this article!

**Comment by sofietoft** [comment]
Hi @jmc18 !

I haven't heard back from you, and I hope that means you've managed to move forward with the migration here.

Since my last message, we've updated the Upgrade docs a bit, as we now recommend using an external package to complete the migration. This package will allow you to go directly from Umbraco 7 to the latest version of Umbraco.

You can find the updated article here: https://docs.umbraco.com/umbraco-cloud/product-upgrades/version-specific-upgrades/migrate-from-umbraco-7-to-8
