### ISSUE TITLE
'Keeping Umbraco Forms up to date' showing v7 documentation

### ISSUE THREAD

**Issue by lauraneto** [umbraco/UmbracoDocs#4928]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
[Keeping Umbraco Forms up to date](https://docs.umbraco.com/umbraco-forms/installation/upgrade)
https://github.com/umbraco/UmbracoDocs/blob/main/11/umbraco-forms/installation/upgrade.md

## Describe the issue
The `Umbraco Forms > Installation and Upgrades > Keeping Umbraco Forms up to date` page is showing documentation from v7.

**Comment by sofietoft** [comment]
Thanks for highlighting this @lauraneto !

We actually want to make sure that all upgrading paths are available on the new docs platform!
That said, it would definitely make sense to highlight that this particular article is valid only for Umbraco 7 😅 

I'll make sure we look into it as soon as possible 💪
