### ISSUE TITLE
Missing documentation for configuration options

### ISSUE THREAD

**Issue by Zeegaan** [umbraco/UmbracoDocs#4948]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-cms/reference/configuration#configuration-options

## Describe the issue
This section is missing both the `MemberPasswordConfigurationSettings` & `UserPasswordConfigurationSettings`

**Comment by sofietoft** [comment]
Thanks for reporting this @Zeegaan !

Just to make sure I understand: 
This article covers some settings that to me seem like the ones mentioned in the series of Issues/PRs here - https://docs.umbraco.com/umbraco-cms/reference/configuration/securitysettings 
But, are they something separate entirely, and not part of the "SecuritySettings" section? 🤔

**Comment by Zeegaan** [comment]
No you are totally right here, problem is both the `UserPassword` & `MemberPassword` properties no longer does anything, as they have been moved out to `MemberPasswordConfigurationSettings` & `UserPasswordConfigurationSettings` instead 🙈 
So I think this task will entail also removing mention of the old ones, from the documentation you linked 😁

**Comment by sofietoft** [comment]
Aha! I'm closer to understand, I think 😅 
So, they are now "their own" sections under Umbraco:CMS in the appSettings.json, and we need two new articles for these sections? 🤞

**Comment by Zeegaan** [comment]
Yep you got it 🙌
