### ISSUE TITLE
Missing documentation: TransformingIndexValues

### ISSUE THREAD

**Issue by drpeck** [umbraco/UmbracoDocs#4988]
Missing documentation

There is no information on how to modify values going in to an index.

[Umbraco 8 documentation has content on TransformingIndexValues](https://our.umbraco.com/Documentation/Reference/Searching/Examine/examine-events), but in 10 & 11 the [only reference to TransformingIndexValues](https://docs.umbraco.com/umbraco-cms/reference/common-pitfalls#performing-lookups-and-logic-in-examine-events) is what should _not_ be done in it.

Perhaps things have moved on, but I couldn't see any other way of extracting some values from my JSON-based property and adding it as separate fields in the index.

TY!

**Comment by sofietoft** [comment]
Thanks for raising this @drpeck !

Both Examine and Lucene are external parts that we use in Umbraco.
That is also we have decided to no longer go into detail documenting these, as it goes beyond the scope of Umbraco.

Both products have their own documentation, which we are also referring to here: https://docs.umbraco.com/umbraco-cms/reference/searching 
I'd recommend that you check them out - You might be able to find what you're looking for here 💪

**Comment by drpeck** [comment]
I entirely understand the distinction that you're making. From a developers perspective, when they are looking to update the External index they won't know that the solution is an Examine event until they have found the solution. As Umbraco created the index in the first place, I had expected that I would need to work within Umbraco's API to modify it. `TransformingIndexValues` literally only has 2 sentences on it [in the Examine docs](https://shazwazza.github.io/Examine/indexing) unfortunately.

Would it make sense to just say "Examine provides events for managing data, such has modifying the data in the external Index. See _here_"?

**Comment by sofietoft** [comment]
I think it would be a good idea to reference the examine docs in a case like this, yes! 💪 

Perhaps something like that would be good as an addition to the "[Custom indexing](https://docs.umbraco.com/umbraco-cms/reference/searching/examine/indexing)" article?
Or where do you think this would fit?

**Comment by drpeck** [comment]
That is exactly where I went to look for a solution.

**Comment by sofietoft** [comment]
Super 💪 
I'll take a closer look to see where it would fit best.

If you're up for it, please feel free to make a suggestions for the note as well 😄

**Comment by drpeck** [comment]
Please see [pull request](https://github.com/umbraco/UmbracoDocs/pull/5010)

**Comment by alina-tincas** [comment]
As the PR has been merged I am closing this one. Thank you again for bringing this up and creating a PR for this @drpeck #h5YR 🙌
