### ISSUE TITLE
Querying link broken

### ISSUE THREAD

**Issue by jamieomaguire** [umbraco/UmbracoDocs#505]
Clicking on the querying link on the documentation leads to a broken page.

https://our.umbraco.org/documentation/Reference/Templating/querying

**Comment by hemraker** [comment]
Hi Jamie, thanks for raising the issue. I'm going to need a little bit more info. Where do you find a link with the above url?

All the best
Rune

**Comment by jamieomaguire** [comment]
Hi Rune, 

My bad, I thought I had linked the page where I found the issue – here it is:

https://our.umbraco.org/documentation/Getting-Started/Design/Templates/basic-razor-syntax

At the bottom of the page there is a link to Querying. That’s the incorrect link.

All the best,
Jamie

**Comment by hemraker** [comment]
Great, it all makes sense now 😄 Fixed with 83733d226c2315cf00e440c5f441ee8bbac61707
Thanks a bunch!
