### ISSUE TITLE
Missing service in custom index builder

### ISSUE THREAD

**Issue by ewuski** [umbraco/UmbracoDocs#5067]
line in documentation https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/searching/examine/indexing#examinecomposer

Documentation for v 10

It looks like there is missing line:

`builder.Services.ConfigureOptions<ConfigureProductIndexOptions>();`

in `ExamineComposer`'s `Compose(IUmbracoBuilder builder`) method

![examinecomposer-missing-issue](https://user-images.githubusercontent.com/104149844/228944707-ee3375c3-80de-4987-b9bd-0c1bef44f8ba.gif)

**Comment by sofietoft** [comment]
Thanks for reporting this @ewuski !

Could you be a bit more specific as to which code snippet you're referring to, and where exactly this code is missing?
You can link directly to headings in the article, if that's helpful 🙌

**Comment by ewuski** [comment]
I corrected my original post - I meant `ExamineComposer `snippet.

**Comment by sofietoft** [comment]
Thanks for explaining @ewuski !
Sure looks like this is an oversight.

Would you be up for making the PR to add this missing code to the v10 docs? We have some docs on how, here: https://docs.umbraco.com/welcome/contribute/pull-request 
Then I'll be able to get a review in from our Dteam as well, just in case 😄
