### ISSUE TITLE
References to web.config should be updated or removed in the Umbraco Cloud docs

### ISSUE THREAD

**Issue by tormnator** [umbraco/UmbracoDocs#5071]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
Multiple articles in the Umbraco Cloud docs, e.g. https://docs.umbraco.com/umbraco-cloud/set-up/project-settings/manage-hostnames/rewrites-on-cloud and https://docs.umbraco.com/umbraco-cloud/security.

## Describe the issue

It is my understanding that we no longer can use web.config anymore on Umbraco Cloud web sites on "modern" installations (Umbraco 11 in my case). There are web.config files present in the Development and Live environments which would be overwritten if you place any web.config in the Local environment?? (this happened to me, but I haven't investigated thoroughly sinc the consequences were severe -> site no longer booted).

I was in contact with Cloud support today via the cloud dashboard chat regarding how to do url rewrites, and was told that you have to use the new approach for rewrites (see https://docs.umbraco.com/umbraco-cms/reference/routing/iisrewriterules).

If this is correct, then someone should review all Umbraco Cloud articles referencing web.config and update these with the recommended approach. A good start would be these search results: https://www.google.com/search?q=web.config+site%3Adocs.umbraco.com%2Fumbraco-cloud

**Comment by sofietoft** [comment]
Thanks for reporting this, @tormnator !

We were not aware that it is no longer possible to use the `web.config` file for rewrites on Cloud projects running versions 9+.
This is something we will look into as soon as possible, so we can get those article you mention updated!

**Comment by jonat123** [comment]
Hey, @tormnator just gonna jump in here 😊 

It is still possible to use the web.configs on Umbraco Cloud for projects running Umbraco 10+ since we have installed the IIS module on our Cloud servers. 

However, to make changes to the web.configs on your cloud environment you need to make a config transform as described here in our documentation: 

- docs.umbraco.com/umbraco-cloud/set-up/config-transforms 

Otherwise, as you say the changes you add will get overwritten 😊

Looking at the documentation I can see that it is not super clear that you need to use the config transform when you are on Umbraco 10 and above.

We will therefore update our documentation making it clearer that you need to use the config transform if you want to make changes to the web.config 😊

**Comment by tormnator** [comment]
Hi @jonat123 thanks for the feedback! I do indeed feel the need for very clear documentation here. Particularly, what I experienced was not that my web.config contents were overwritten, but rather the opposite that my web.config overwrote the cloud config and broke the site.

I just took at look at the transforms page (https://docs.umbraco.com/umbraco-cloud/set-up/config-transforms) and it's actually pretty good. About 2/3 down on the page I find the following warning "_Keep in mind that a misconfigured config transform may [block Data Extraction on your project](https://github.com/umbraco-cloud/troubleshooting/deployments/changes-not-being-applied)._" Maybe that's what happened to me. Maybe put this warning higher up on the page and make it stand out even more? And perhaps also include information about what will happen if you add a web.config without transforms.

Also, if you end up breaking the site due to this situation, it is not clear at all on the site, or in the Cloud dashboard, what exactly happened, and how to fix it. I think I ended up going into Kudu and manually removed my own web.config and after a forced redeploy (without the web.config) the site recovered. Not sure if this was exactly what I did though.

**Comment by jonat123** [comment]
@tormnator Thanks! That is some great feedback 😊

I'll look into updating the docs and move the warning about the transforms that might block data extractions. 

Regarding the last part, In that regard, there is not much we can do within the docs team, I know the cloud team has been working on making errors on cloud more visible in the cloud portal. However, this particular issue is not one of the things that is shown in the portal, Instead you would need to dig into the deploy logs, which should tell if an extraction is being block by a config transform.

**Comment by jonat123** [comment]
@tormnator Just want to let you know that I've moved the warning further up the page and we have changed a bit of the content of the page to make it clearer that Umbraco Cloud projects by default have a web.config file.
- https://docs.umbraco.com/umbraco-cloud/set-up/config-transforms 

Please let us know what you think 😄

**Comment by tormnator** [comment]
Looks good! The one thing I would say is to test, confirm, and document what happens if the developer adds a web.config (with and without transforms) to their Local env. Add a web.config is something that everyone coming from older Umbraco/asp.net versions is used to doing, and there's a good chance this will be done before one goes to the docs pages. If the consequences are that the cloud environment get broken and can't be loaded at all, then this really needs to be communicated to the developer in a clear way. Maybe there needs to be a separate doc page for this.

**Comment by jonat123** [comment]
@tormnator Sorry for the delayed answer.

Projects on Umbraco Cloud have always come with a Web.config file by default and we haven't really heard about it being an issue before 😊

For now, we won't be doing more in regard to this, however, if we hear that more people are having trouble with this, I will be more than happy to reopen this issue 😊
