### ISSUE TITLE
Custom UrlProviders should not return base.GetUrl

### ISSUE THREAD

**Issue by simonech** [umbraco/UmbracoDocs#5073]
## What type of issue is it? 
Wrong documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-cms/reference/routing/request-pipeline/outbound-pipeline#custom-url-provider

## Describe the issue
In the article, it is explained to return `base.GetUrl(content, mode, culture, current);` if the doctype doesn't match the one for which you want to create the custom URL.

This is fine if you have just one custom URL provider, but if you want to have multiple URL providers, returning the default URL will stop Umbraco to cycle through all the other providers, so only the first will be executed.

The code sample should return "null" if the condition is unmet.

**Comment by simonech** [comment]
I just noticed it is a duplicate of #4265 
I'll see if I can update the doc myself

**Comment by sofietoft** [comment]
Thanks for reporting the issue and creating the PR.

**Comment by alina-tincas** [comment]
Hi @simonech it seems that this PR #4265 is currently merged therefore I am closing this issue 😊
