### ISSUE TITLE
Is the default config option for scheduled deletion correct?

### ISSUE THREAD

**Issue by Rockerby** [umbraco/UmbracoDocs#5077]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
[Configuration](https://docs.umbraco.com/umbraco-forms/developer/configuration)

## Describe the issue
When installing Forms it doesn't automatically delete records, as indicated in the [Form Settings page](https://docs.umbraco.com/umbraco-forms/editor/creating-a-form/form-settings/). However the config page seems to say it is on by default. Should this say `"Enabled": false`? Extract from the current config page below:

```
  "Forms": {
    ...
    "Options": {
      ...
      "ScheduledRecordDeletion": {
        "Enabled": true,
        "FirstRunTime": "",
        "Period": "1.00:00:00"
      },
      ...
    },
    ...
  }
```

**Comment by jonat123** [comment]
Hello, @Rockerby  thanks for creating this issue 😊

That is a good question, to be honest I am not sure🤔

To me, there is some inconsistency with our documentation.

As you show from the config page it looks like it is on by default, however, when I read about it a bit longer down on the page, we state that it is set to false by [default](https://docs.umbraco.com/umbraco-forms/developer/configuration#enabled) 🤔

Let me reach out to our developers that works on forms and see what they say :)

**Comment by jonat123** [comment]
@Rockerby Just talked with our developer on Umbraco Forms and he confirms that by default the setting is set to `false` and not `true` as you have pointed out 😊

I've updated the code example so that the information is correct now 😄

**Comment by jonat123** [comment]
Hopefully, this helps 😊

I'll close down the issue for now.

Have a great easter!

**Comment by Rockerby** [comment]
Great stuff, thanks @jonat123 - you too!
