### ISSUE TITLE
Umbraco Is an Element Type description refers to Nested Content which has been deprecated in v10

### ISSUE THREAD

**Issue by pageorge** [umbraco/UmbracoDocs#5083]
Wrong documentation

I wasn't sure where to report this - here as it's kinda documentation related - or the Umbraco-CMS where it says for documentation issues report here...

In the backoffice, Settings -> Doc Type -> Permissions -> Is an Element Type -> Description:
"An Element Type is meant to be used for instance in **Nested Content**, and not in the tree."

As Nested Content has been deprecated in v10, should this be re-worded to "a list" or "block list"?

Thanks for listening!

**Comment by jonat123** [comment]
@pageorge thanks for creating this issue :D 

We are aware that it states the wrong thing, and a PR has already been created which fixes the issue 😊
- https://github.com/umbraco/Umbraco-CMS/pull/13971/files 

I'll close this issue down.

Happy easter when you get there 😊
