### ISSUE TITLE
Permissions for static files

### ISSUE THREAD

**Issue by gunnim** [umbraco/UmbracoDocs#509]
The permissions page lacks documentation for serving up media with imageprocessor or for handling static files:
https://github.com/umbraco/UmbracoDocs/blob/master/Getting-Started/Setup/Install/permissions.md

If you intend to serve css and js as static files without the ClientDependency package you need to give IUSR read and execute permissions to those folders.
For images served through imageProcessor, IUSR RX permissions are required for app _data\cache.
Images served from azure without using ImageProcessor do not need further configuration.
However images served statically from the media folder will require IUSR RX permissions.

I could add this to the documentation if that makes sense.

**Comment by gunnim** [comment]
I'm also not sure that this section is at all visible from the documentation navigation tree?
I think i found it through google.

Might also make sense to update this sentence:
The user with the permissions set are the user used by the Application Pool used by the IIS website (usually Network Service or the IIS_IUSRS group)
Since IIS by default creates a new application pool for each site, meaning the permissions should be granted to a user with a name like so
iis apppool\applicationPoolName

**Comment by nul800sebastiaan** [comment]
Wow, this is a bit of an old issue, thanks for bringing it to my attention @jmayntzhusen 

The answer here is: different people do very different things with Umbraco. It would be good to mention that if you have any specific static files / media items / etc that you should add the appropriate permissions accordingly.

The permissions documentation as it is should allow you to run a plain Umbraco install successfully, the rest.. is up to you! 👍
