### ISSUE TITLE
V11.2.2 IUmbracoBuilder no definition for AddBackOfficeExternalLogins

### ISSUE THREAD

**Issue by adamdistrictten** [umbraco/UmbracoDocs#5106]
Following the [documentation](https://docs.umbraco.com/umbraco-cms/reference/security/authenticate-with-active-directory#azure-a-d-authentication-for-users) to add AD receiving an error for IUmbracoBuilder with no definition for AddBackOfficeExternalLogins.

Is there a change in V11 that hasn't been updated in the documentation or am I missing something?

**Comment by sofietoft** [comment]
Hi there!
I hope that you clsoing down the issue means that you found what you were looking for 😄 

Please do not hesitate to get back in touch, if something doesn't look quite right!
