### ISSUE TITLE
Install Default Data Settings - Specify Potential risk/conflict

### ISSUE THREAD

**Issue by TRexStark** [umbraco/UmbracoDocs#5127]
## What type of issue is it?
Missing Documentations

## What article/section is this about?
[Install Default Data Settings](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/configuration/installdefaultdatasettings)

## Describe the issue
We may need to add a warning that some existing relations between certain DataTypes with MediaTypes and the default MemberType. as example if you set the option to NOT install any default DataType at all, but still let the MediaTypes get installed, it may potentially cause some issues, because some DataTypes are used by some MediaTypes and by the default MemberType.

Here are my findings so far:

- "Image Cropper", "Label (integer)", TextString are used by the "Image" MediaType.
- "True/False" is used by both "Image" and "Vector Graphics (SVG)" MediaTypes.
- "Label (bigint)" and "Label (string)" are used by all MediaTypes.
- "Upload Article", "Upload Audio", "Upload File", "Upload Vector Graphics" and "Upload Video" are used by their respective MediaTypes.
- "Textarea" is used for the locked "Comments" property on the default MemberType
- Another one which I'm not sure of: _Although the "List View - Media" and "List View - Members" don't show any References, aren't they used by the default views in the backoffice?_

**Comment by sofietoft** [comment]
Thanks for raising this issue @TRexStark !

I definitely see that some issues could arise here when opting to not install the default Types shipped with Umbraco CMS.

I do not necessarily think it's necessary to mention all the dependencies here.
We could add a warning letting people know to be cautious when changing this configuration, as there are some dependencies between the different Types.
And then we should add a couple of examples, like the one with the different types of labels being used and perhaps also the Text string and areas.

What do you think of that plan?

**Comment by TRexStark** [comment]
Thanks @sofietoft, thinking about it now, your solution is more viable than listing them all, otherwise it's more overhead maintaining the doc updates in the long run if something is changed/added in the CMS.

So maybe in addition to the example, we could explain that they can check the references Tab of the DataTypes to ensure they're not referenced somewhere important.

**Comment by TRexStark** [comment]
Hi @sofietoft yes no problem, I will give it a go.

**Comment by alina-tincas** [comment]
Hi @TRexStark! I was wondering if you are still up for doing those changes, or is it all right if I add this to our backlog so we can take a look into making those changes to the documentation? 😊 

If you are still up for making those changes, you can check [how to submit a PR here](https://docs.umbraco.com/welcome/contribute/pull-request) 👍

**Comment by TRexStark** [comment]
Hi @alina-tincas, sorry I didn't have enough time to get back to this. Please add it to your backlog as I'm still super busy.

**Comment by alina-tincas** [comment]
Thank you for confirming @TRexStark and no worries! 

I have just added a piece of warning information about this case, along with an example: https://docs.umbraco.com/umbraco-cms/reference/configuration/installdefaultdatasettings 

Thank you again for bringing this to our attention #h5YR 🙌
