### ISSUE TITLE
AllowEditInvariantFromNonDefault in Wrong Section

### ISSUE THREAD

**Issue by TRexStark** [umbraco/UmbracoDocs#5129]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
[Security Settings](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/configuration/securitysettings)

## Describe the issue
When installing a new Umbraco Project, by default the "AllowEditInvariantFromNonDefault" is set under the "Content" configuration section, verifying the appsettings-schema, you can see it configured under UmbracoCmsCoreConfigurationModelsContentSettings.

The docs show that this needs to be set under "Security" settings.

**Comment by sofietoft** [comment]
Hi @TRexStark !
Thanks for the report.

Sure sounds like you're on to something here.
I do believe that what is in the appSettings-schema is the correct information.

I'll run it by our developers for a quick double-check 💪

**Comment by TRexStark** [comment]
Thanks @sofietoft, that is correct, the schema has it in the correct spot (sorry I haven't mentioned that), the documentations will need to be updated and have this object moved to the content settings and removed from the security settings, unless if I'm missing something else.

**Comment by sofietoft** [comment]
Excellent @TRexStark !
Thanks for the details.
I'll make sure we get someone to look into updating those docs 💪
