### ISSUE TITLE
Deprecated/Oboslete example in EmbedProviders docs

### ISSUE THREAD

**Issue by daanbakker1995** [umbraco/UmbracoDocs#5150]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
[embedded-media-providers snippet example](https://docs.umbraco.com/umbraco-cms/extending/embedded-media-providers#register-the-provider-with-the-oembedproviderscollection)

## Describe the issue

In this snippet the `OEmbedProviders` collection builder is mentioned to compose the embed providers. When using this in umbraco 10 the obsolete attribute is present. That says use the `EmbedProviders` collection instead. 

Just wanted to  mention this so the documentation could be updated. 

Greetings,
Daan

**Comment by sofietoft** [comment]
Thanks for reporting this @daanbakker1995 ! 💪 

I can see the the OEmbedProviders are mentioned multiple places in the article - not just the sample you're referring to 🙈 
Sounds like we need to get this entire article verified against the latest version!

I'll make sure we get some developers to look into this.

**Comment by daanbakker1995** [comment]
Thank you!
