### ISSUE TITLE
A Question of Image Sizes

### ISSUE THREAD

**Issue by greystate** [umbraco/UmbracoDocs#518]
In the README for this repo it's stated that [Images can have a maximum width of **800px**.](https://github.com/umbraco/UmbracoDocs/blob/master/README.md#images) — is this still the case, or are they being "sensibly" sized?

Also, related: Should they really be retina-ready versions?

/cc @hemraker

**Comment by sofietoft** [comment]
Hi there,
Excellent questions! 😁 

I believe that the images are indeed sensibly sized.
I can see that I've added images where the width exceeds the 800px limit 🙈 
Those looks to be fitted well enough to the screen: https://our.umbraco.org/documentation/Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/

I can see that your PR was already merged, so I'm closing this issue down!
Thanks for contributing! Keep up the great work 😄 

-Sofie
