### ISSUE TITLE
how to enable tinymce features in umbraco 11

### ISSUE THREAD

**Issue by jasonc08** [umbraco/UmbracoDocs#5187]
## What type of issue is it? 
The current documentation for Umbraco lacks comprehensive guidance on how to enable all the features similar to the Tinymce demo showcased in the following link: [Tinymce Demo](https://www.tiny.cloud/docs/tinymce/6/full-featured-open-source-demo/).

## Describe the issue
To address this issue, it is suggested that the Umbraco documentation be improved by providing sample code that demonstrates how to enable all of the features in Tinymce. This sample code would serve as a practical reference for developers, guiding them through the process of configuring and utilizing the full range of features available.

Additionally, it is recommended that Umbraco offers support for configuring Tinymce using JavaScript, in addition to the existing appsettings-based configuration. Enabling JavaScript-based configuration would grant users greater flexibility and ease in customizing the editor according to their specific needs. By allowing direct manipulation of Tinymce settings through JavaScript, developers would have more control over toolbar options, plugins, and other behavior customization, resulting in a more seamless integration of Tinymce into Umbraco projects.

By addressing these documentation and configuration enhancements, Umbraco can empower its users to maximize the potential of Tinymce and ensure a more user-friendly and adaptable editing experience within their Umbraco websites.

**Comment by sofietoft** [comment]
Thanks for the very detailed report @jasonc08 !

We already have quite a few articles covering the Rich Text Editor in Umbraco, and how it can be customized and even extended.
Most of it, refers to the official TinyMCE docs, as we do not see a reason to repeat and maintain their docs on our site as well.

What we have already, can be found here:
[Rich Text Editor (general overview)](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor)
[Rich Text Editor Configuration](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/configuration)
[Rich Text Editor Settings (config files)](https://docs.umbraco.com/umbraco-cms/reference/configuration/richtexteditorsettings)

What we could do to extend these docs, is make 1 or more tutorials about how to extend the Rich Text Editor.
What do you think of that idea?

Finally, regarding adding support for configuration TinyMCE through javascript - that sounds more like a feature request to the Core Umbraco CMS product. Feel free to submit it here: https://github.com/umbraco/Umbraco-CMS/issues/new/choose

Do also keep in mind, that we are currently working on rebuilding the Umbraco CMS backoffice, changing the underlying technologies used. Learn more about this project over here: https://docs.umbraco.com/umbraco-backoffice/

**Comment by alina-tincas** [comment]
Hi @jasonc08, as we have not heard from you for some time, I am closing this issue. 

If you have any further feedback or inputs on our documentation, do not hesitate to create a new issue or [contribute to our documentation ](https://docs.umbraco.com/welcome/contribute/getting-started). 🙌
