### ISSUE TITLE
Custom error pages // 404 documentation // Integer ID

### ISSUE THREAD

**Issue by SteveAndrews** [umbraco/UmbracoDocs#5208]
https://docs.umbraco.com/umbraco-cms/tutorials/custom-error-page

For 404, the documentation says we can use GUID, XPath, or Integer ID in appsettings.

Integer ID isn't working (v11.4), but GUID still works.

Is this a bug, or should Integer ID be removed from the listed allowable values?

**Comment by sofietoft** [comment]
Thanks for reporting this @SteveAndrews !

There's no example in the article for actually using the integer ID as the value 🤔 
Which config key did you use, when you tried this out?
Did you use `ContentKey` ?

I'll add a task for this to our board, so we can get this tested and verified against the latest version 💪

**Comment by SteveAndrews** [comment]
Here is the anchor link:
https://docs.umbraco.com/umbraco-cms/tutorials/custom-error-page#set-a-custom-404-page-in-appsettings.json

The third bullet is:
`A content item's integer ID (example: 1234)
`

**Comment by sofietoft** [comment]
Thanks for explaining @SteveAndrews ! 💪 

So, just to make sure we're on the same page, what you've added to your appsettings.json file is something like this:

```
"ContentKey": "1234"
```

**Comment by jonat123** [comment]
We have added the Id example to the documentation now 😄

Thanks for making us aware of this @SteveAndrews 😁

I will close this issue.

**Comment by SteveAndrews** [comment]
Wonderful! Thank you!
