### ISSUE TITLE
Provide a HSTS C# alternative for Umbraco Cloud Security

### ISSUE THREAD

**Issue by mattou07** [umbraco/UmbracoDocs#5223]
## What type of issue is it?

Missing documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-cloud/security

## Describe the issue
The HSTS example uses the web.config to achieve the header. This can be done in C# if preferred.

**Comment by mattou07** [comment]
https://github.com/umbraco/UmbracoDocs/pull/5226

**Comment by sofietoft** [comment]
Thanks for reporting this!
I'll make sure we review the PR as soon as possible 💪

**Comment by jonat123** [comment]
Since https://github.com/umbraco/UmbracoDocs/pull/5226 has been merged in, I will close this issue down 😄

Once again thanks for the PR @mattou07 😁
