### ISSUE TITLE
Links on docs.umbraco.com are unclear

### ISSUE THREAD

**Issue by MMasey** [umbraco/UmbracoDocs#5224]
Links in the docs site only use a slight colour variation to indicate that they are in fact links. This makes them difficult if not impossible for some people to see.

![image](https://github.com/umbraco/UmbracoDocs/assets/6573613/494d0c69-da03-4aad-a445-cfc8b371cd3f)

I suggest that the link style is updated to use the something along the lines of the current hover state, or maybe just underlines at the least.

e.g.
![image](https://github.com/umbraco/UmbracoDocs/assets/6573613/547c111d-9271-4ee5-bb76-d8a2079d2ece)

**Comment by sofietoft** [comment]
Thanks for the input @MMasey!

I've raised the issue with GitBook here: https://github.com/orgs/GitbookIO/discussions/233

**Comment by MMasey** [comment]
Thanks @sofietoft, thanks awesome news!

**Comment by alina-tincas** [comment]
Hi @MMasey am happy to let you know that Gitbook has implemented this feature (underlined links to make them more visible)  along with other [improvements ](https://changelog.gitbook.com/march-2024/4-march-huge-improvements-to-your-published-documentation), so am closing this issue. 🎉 

![image](https://github.com/umbraco/UmbracoDocs/assets/83591955/3ce16c55-2e3f-4560-bc8c-ed009df06120)

Thank you again for bringing this up 💪 🙌
