### ISSUE TITLE
Update Acronyms?

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#5239]
## What type of issue is it? (Choose one - delete the others)
Suggestion/Question 

## What article/section is this about?
[Eye Dropper Color Picker - v10](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/eye-dropper-color-picker)
[Eye Dropper Color Picker - v11](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/eye-dropper-color-picker)

## Describe the issue
Is it an idea to add HEX and RGBA to the list of acronyms or do we really have to explain them?

![image](https://github.com/umbraco/UmbracoDocs/assets/7831614/41fb5d91-2a33-4214-92de-99afda4bf230)

**Comment by sofietoft** [comment]
Hi @erikjanwestendorp !

Thanks for raising this.
I think it makes sense to add these to the approved acronyms list - it seems like something most people working with website design would know what is 😄 

You up for the task? 🤞
