### ISSUE TITLE
Add docs on how to deploy bugfix on Umbraco Cloud with pending changes between environments

### ISSUE THREAD

**Issue by hemraker** [umbraco/UmbracoDocs#526]
It can in some cases be necessary to deploy a bugfix to a Live site. On projects with multiple environments this should normally be done through the portal. However there might be pending changes between environments that are not ready for deployment yet, so a step by step guide on how to do this is warranted.

**Comment by greystate** [comment]
Truth! 👍

**Comment by greystate** [comment]
I have done this horribly wrong more than once and paid for it for weeks thereafter :) Do you have any rough guides/steps? I'd be happy to test and write up the process with git commands/invocations/glögg and what have you :laughing:

**Comment by greystate** [comment]
Just needed this badly yesterday :)

I know @skttl knows a thing or two about this, so looping him in here now...

**Comment by skttl** [comment]
My approach kind of deviates from the "official" Umbraco Cloud workflow.

I add both my dev, and live environment as remotes for my local git repository.

I then find the latest common commit for both dev and live, and start a new hotfix branch from there. When done, I merge the fix into both dev and master.

I can elaborate in a hangout/skype session or similar. I have a powerpoint show, I used when introducing for my colleagues :)

**Comment by greystate** [comment]
It deviates yes - but that’s exactly what’s requested in this issue (I think?)

I was doing the same (with both environments as remotes) but missed part of using the common commit, so got stuck in “detached HEAD” ;)

I’d love to see the PowerPoint and write these docs based on that outline (and actual case of fixing a bug).

**Comment by sofietoft** [comment]
Hi guys!

Thanks for pitching in here 😁 

I'm diving into testing and writing some guides on how to apply hotfixes on Cloud environments next week.
The solution you mention, @skttl , is very technical but definitely one way of going about it!! 

What I'm going to write is gonna be a bit less technical; cloning down the Live environment and simply copying over the files from a local clone of a Development environment - so there's gonna be no _git magic_ involved 😉 

If you want and have the time ofcourse, you are very welcome to write some documentation on the way you are working with this?
