### ISSUE TITLE
 File scoped namespaces?

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#5260]
## What type of issue is it? (Choose one - delete the others)
Discussion

## Describe the issue
Is it an idea to work with file scoped namespaces in the code examples? I think this would improve the readability of the samples. Additionally, in some cases, it can prevent the occurrence of a horizontal scroll bar.

**Comment by sofietoft** [comment]
Thanks for adding this issue @erikjanwestendorp ! 💪 

I have to admit that I'm not entirely sure I understand what you mean about "file-scoped namespaces".
Perhaps you can give an example?
Unless the PR you made yesterday is actually a case of this? 😅 (https://github.com/umbraco/UmbracoDocs/pull/5266)

**Comment by erikjanwestendorp** [comment]
@sofietoft Thanks for your reply 😄! No this is not exactly the same as the PR #5266. In this PR I just added a missing namespace. 

What I mean here is change the namespace to file-scoped namespaces.  File scoped namespaces is a feature added in C# 10, the intention is to remove one level of indentation. 

Before: 

```csharp
namespace MyProject
{
    public class Umbraco
    {
    }
}
```

File scoped namespace

```
namespace MyProject;

public class Umbraco
{
}
```

Let's say we update this [article ](https://github.com/umbraco/UmbracoDocs/blob/main/12/umbraco-cms/implementation/controllers.md). By using file scoped namespaces the code easier to read (in my opinion) and also in some cases it can prevent the occurrence of a horizontal scroll bar. 


![image](https://github.com/umbraco/UmbracoDocs/assets/7831614/6720b789-997d-4426-b9c3-1cb42077e4af)
![image](https://github.com/umbraco/UmbracoDocs/assets/7831614/8d1b74ed-fd6e-40f7-9c4d-0da7e62eea7e)

**Comment by sofietoft** [comment]
Thanks for the detailed explanation here @erikjanwestendorp - and apologies for the prolonged response-time.
I've been on vacation 😇 

Sounds to me like it only makes sense to use File-scoped namespaces in the code examples - the more "noise" we can remove from them, the better 💪 
For good measure though, let me just run it by our developers in case they see any reasons why this might not be relevant!
Again, it's vacation time, so we might have to wait a little while before we get an answer 😄

**Comment by erikjanwestendorp** [comment]
@sofietoft Thanks for your reply. Hopefully you have enjoyed your vacation!😄 I understand that everything takes a little longer during the summer. There's no hurry, let me know if there's anything I can do. 😃

**Comment by sofietoft** [comment]
Hi again @erikjanwestendorp ! 👋 

A couple of the developers here at HQ have now discussed this, and they think only makes sense to change to use the file-scoped namespaces like you're suggesting in this issue.
In fact, a couple of them have been using this approach already in recent PRs 🙌 

Perhaps we could even add a few words around the recommended approach in here: https://docs.umbraco.com/welcome/contribute/code-samples 🤔 
Let me know if you're up for it - otherwise I'll get it added to our task board in the Docs team 💪

**Comment by erikjanwestendorp** [comment]
@sofietoft Thanks for your reply! It's great to hear that the dev team already used file scoped namespaces in previous PR's. I just created a PR and added a small explanation to the contribution guidelines article. Please let me know if you have any further suggestions! 😄

**Comment by alina-tincas** [comment]
as the PR has been merged, I am closing this one 💪
