### ISSUE TITLE
CharCollection is outdated

### ISSUE THREAD

**Issue by andr317c** [umbraco/UmbracoDocs#5289]
## What type of issue is it? 
Outdated documentation

## What article/section is this about?

https://docs.umbraco.com/umbraco-cms/v/11.latest/reference/configuration/requesthandlersettings

On versions 11 and 12

## Describe the issue

CharCollection has been removed from v11 and up. It has been replaced by UserDefinedCharCollection

**Comment by jonat123** [comment]
@andr317c Thanks for creating this issue!

How does UserDefinedCharCollection look?

Is it just the same with CharCollection replaced with UserDefinedCharCollection or?

**Comment by andr317c** [comment]
Yeah, the only difference is CharCollection is now called UserDefinedCharCollection.

Before it looked like this: 
```
"RequestHandler": {
        "AddTrailingSlash": true,
        "ConvertUrlsToAscii": "try",
        "EnableDefaultCharReplacements": true,
        "CharCollection": [
          {
            "Char": " ",
            "Replacement": ""
          }
        ]
      }
```
Now it looks like this instead: 
```
"RequestHandler": {
        "AddTrailingSlash": true,
        "ConvertUrlsToAscii": "try",
        "EnableDefaultCharReplacements": true,
        "UserDefinedCharCollection": [
          {
            "Char": " ",
            "Replacement": ""
          }
        ]
      }
```

**Comment by jonat123** [comment]
@andr317c I've updated the documentation.

https://docs.umbraco.com/umbraco-cms/reference/configuration/requesthandlersettings
 

I'll close this issue down :-)
