### ISSUE TITLE
Migrate local website to online VPS (linux) server

### ISSUE THREAD

**Issue by DanielOberlechner** [umbraco/UmbracoDocs#5315]
## What type of issue is it? (Choose one - delete the others)
Missing documentation - Other (write it here)

## What article/section is this about?
Migrating from locally to online server

## Describe the issue
Is there any documentation, if I develop UmbracoCMS on my local Macbook via dotnet cli how to go live with such a site.
For a example created locally a complete Website and want to put it on a linux VPS server, which steps do I have to take?
For example simply copy all files via FTP to the VPS server and run it via dotnet cli?

I'm a bit new to Umbraco and have therefore no concrete knowledge on how to deploy a site.

In the documentation I couldn't find how to migrare a local site to an online server. (In my case it would be a linux one, not windows or azure cloud or similar)

Has anyone any hints for me?

Or is it wrong to develop locally and I should put it firstly on the VPS server and develop from there?

Kind regards,
Daniel Oberlechner

**Comment by sofietoft** [comment]
Hi @DanielOberlechner , and thanks for raising these questions!

First of all, it should be entirely possible to develop locally and deploy to your remote server as you go.
As an example, this is how our Umbraco Cloud service currently works: [Umbraco Cloud Docs](https://docs.umbraco.com/umbraco-cloud/) - [Working locally with Cloud](https://docs.umbraco.com/umbraco-cloud/set-up/working-locally).

With that said, I'm coming up a bit short when it comes to answering your remaining questions, as I've not worked with Linux or Mac before.
We also currently do not have any concrete docs on how to deploy to a Linux server specifically, but I've found that Azure actually does provide an app service on Linux if that could be relevant to you?

I'll be adding a task here internally in the docs team, so we can take a closer look at whether or not we should put together some more specific docs for all of you out there not on Windows machines 💪 

In the meantime, I'd recommend that you head on over to our very helpful and friendly community on Discord: https://community.umbraco.com/get-involved/community-discord-channel/ 
I'm sure someone will be able to help you move forward from here!

**Comment by alina-tincas** [comment]
Hi @DanielOberlechner! 

I can see that you got some help from the Discord community, so am glad that you were able to figure out how to deploy to a linux VPS server with some [Microsoft documentation](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-7.0&tabs=linux-ubuntu) and [Youtube video](https://www.youtube.com/watch?v=mkBYgwfOzdc)👍 

We have also discussed with our documentation team if we should have this documented, however, this is more related to .NET rather than Umbraco so in this case it does not seem to be that relevant. 

However, you are more than welcome to [contribute to our documentation](https://docs.umbraco.com/welcome/contribute/getting-started) whereafter once you create a PR we can discuss things further from there and involve our developers if necessary. 😊

**Comment by DanielOberlechner** [comment]
@alina-tincas 
Hey, I understand that the matter. But I think some other "basics" are covered as well:
https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/install-umbraco-with-vs-code
https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/iis

Specifically the server setup iis is in my opinion the same thing I asked for in Linux except its only to click around in a graphical user interface.

I'm not to 100% done with my website, but when everything works like I except it I will definitely post a youtube video where I show other people which aren't that familiar with dotnet and Linux how to do the hosting.

It's true Microsoft has a own section to show you how to host on Linux, but it took me days to perfect it with autodeploy and similar functions. Nobody says to you how to get the files while in development to the server. I firstly used scp then tried webdav without luck yet and at the moment I use a rsync script. And in my opinion its also cluttered with information where someone gets hit with too many aspects.

For new people wanna try the "best" CMS (in my opinion) it would help to guide them a simple bit if they have no or not enough knowledge.

I worked professionally in 2017-2019 with .NET but never was really thaught how to set it up, because I wasn't ready to learn it because I had other things on my mind. Now I don't work for the company no more but have used from 2019 until now Typo3 and Wordpress.

Looking back it was the best CMS I had ever to work with but also the most complicated one.

I do understand that you don't really want to take time out to create a how to for "noobies" or beginner, but I will take the time. It removes for new people a lot of frustration and they will be happier at the end and recommend it further.

One "bad" site effect could be that people with not enough knowledge create "insecure" websites or bad looking ones or whatever but I guess this is something to live with.

In the end it will be a win-win situation as I see it.

If my video meets the required technical standard and business level for you I would be happy to create an article and link it there or a blog post which I got told on Discord.

It will probably take me at least 2-3 weeks until I can work on the video and create a simple script what to say and to edit everything in a proper manner.

It will probably not get many views but thats not the goal.

I try to be the one stackoveflow question somebody had a time ago and someone answered it in a kind way.

Hope could make more clear what and why I want to do it :)

Kind regards,
Daniel

**Comment by DanielOberlechner** [comment]
@alina-tincas 
This sounds like a great idea. :)
But one question is still left:
You recommend me Skrift.io to publish an article but your colleague Seabastian (Admin) from Discord recommended me dev.to.
Which of those to should I prefer?

Kind regards,
Daniel

**Comment by alina-tincas** [comment]
Awesome, that´s a plan then 💪 

As for where to publish this article, it is up to you which one you personally prefer 😄 For example I have not worked with dev.to before therefore I am suggesting Skrift.io. 👍
