### ISSUE TITLE
Incorrect code example 

### ISSUE THREAD

**Issue by huwred** [umbraco/UmbracoDocs#5331]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
[(link here)](https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-property-editor/part-4)

## Describe the issue
The code example below

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using Umbraco.Web.WebApi;
using Umbraco.Web.Editors;
using Umbraco.Core.Persistence;
using Umbraco.Core.Scoping;

namespace My.Controllers
{
    [Umbraco.Web.Mvc.PluginController("My")]
    public class PersonApiController : UmbracoAuthorizedJsonController
    {
        // we will add a method here later
    }
}
``` 

I believe it should be
```c#
using Umbraco.Cms.Web.BackOffice.Controllers;
using Umbraco.Cms.Web.Common.Attributes;

namespace My.Controllers
{
    [PluginController("My")]
    public class PersonApiController : UmbracoAuthorizedJsonController
    {
        // we will add a method here later
    }
}```

**Comment by alina-tincas** [comment]
Hi @huwred thank you for creating this issue! 🙌 

In order to have our developers look into this request, can you please create a[ PR](https://docs.umbraco.com/welcome/contribute/pull-request) instead? Thank you in advance #h5YR

**Comment by huwred** [comment]
PR created

**Comment by alina-tincas** [comment]
Thank you 🙌

**Comment by jonat123** [comment]
Closing this issue as the PR that fixes this issue has been merged in :-)
