### ISSUE TITLE
Two-factor-Authentification 

### ISSUE THREAD

**Issue by Dreadhorn** [umbraco/UmbracoDocs#5337]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
[(link here)](https://our.umbraco.com/documentation./Reference/Security/two-factor-authentication)

## Describe the issue
The Page is no longe availible, but i would like to use 2fa with Umbraco Members.
There is a documentation about 2fa for v12, can i use that for v8?

**Comment by alina-tincas** [comment]
Hi @Dreadhorn! 👋 

That seems interesting! I have looked further into this, and the [link ](https://our.umbraco.com/documentation./Reference/Security/two-factor-authentication)you have shared is referencing this [documentation](https://docs.umbraco.com/umbraco-cms/reference/security/two-factor-authentication#two-factor-authentication-for-members) which is for v9+. We have moved all documentation from v9 and above from https://our.umbraco.com/ to https://docs.umbraco.com/welcome/ therefore the link cannot be found anymore in our.

The 2fa for members implementation guide can be used only from v9.3.0 as per this [PR](https://github.com/umbraco/Umbraco-CMS/pull/11889)

However, I have looked further and found some other references that you can use for v8:
- https://our.umbraco.com/forum/using-umbraco-and-getting-started/104363-umbraco-8-2fa
- https://24days.in/umbraco-cms/2015/extending-membership/
- https://coderpro.net/blog/umbraco-8-member-handling-security
- https://this.isfluent.com/blog/2019/two-factor-authentication-for-umbraco-part-1

**Comment by biapar** [comment]
Is there an example for 2FA that use SMS/Email and with SPA application?
