### ISSUE TITLE
Umbraco Commerce - product variants docs need expansion/improvement

### ISSUE THREAD

**Issue by tormnator** [umbraco/UmbracoDocs#5371]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-commerce/key-concepts/product-variants

## Describe the issue

The product variants concept should be much better documented. Single-variant products are easier, but still needs better explanation and how-to guides/tutorials. Multi-variant products involve configuration in multiple places and most likely coding as well. There's an older block article from Vendr which has the best explanation that I have found: https://vendr.net/blog/vendr-1-5-0-release-candidate/.

Btw, what's the difference between "how-to guides" and "tutorials"? They are separate sections in the left-side menu.

**Comment by alina-tincas** [comment]
Hi @tormnator we have created a page for "complex-variants" here: https://docs.umbraco.com/umbraco-commerce/key-concepts/product-variants/complex-variants and added a new issue for missing documentation for "Child Variants" on #5416 👍 

Thank you again for bringing this up 💪

**Comment by tormnator** [comment]
Great job! 👍
