### ISSUE TITLE
Umbraco Cloud - More explanation of Organizations

### ISSUE THREAD

**Issue by hfloyd** [umbraco/UmbracoDocs#5396]
## What type of issue is it?
Missing documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-cloud/getting-started/the-umbraco-cloud-portal/organizations

## Describe the issue
The page in question is only a tour of the "Organizations" UI. It doesn't explain much about the purpose of an Organization, and any rules governing the associated users/projects. I think some of the following could be included, either here, or on another page which provides an overview of the structure and/or project creation process:

- Every project needs to belong to a single org right? And an org can have multiple projects, and if you add a user to the org, that user can now see/do stuff? (What stuff? If you are a member of an org, what does THAT enable you to do?)
- What happens if you invite a user directly to a project... Are they, or are they not added to the org automatically?
- If there is an org, it has multiple users and it has multiple projects... but if you have a project with an "invited" user, who is NOT in the org... what does that mean?
- If you remove a user from the org, what happens? (Do they lose access to projects?)
- If you remove a user from a project, does that affect their relationship to the org?

You might also include some guidelines for devs... Like: If you're an agency handling the Cloud payments for clients then... all client projects should be under your Agency org? Or, if you are a dev setting up a project for a new client... how do you create a new org for them to manage?
(Personally, I'm "external" to my clients' companies, but even internal devs are not necessarily the ones managing payments...)

**Comment by jonat123** [comment]
@hfloyd Thanks for opening this issue!

That is an excellent point, and just quickly glancing over the current docs, I agree that it is a bit barebones.

I will create a Task in our backlog, looking into how we can improve and add more documentation about how to use an Organization on Umbraco Cloud 😊

**Comment by jonat123** [comment]
Hey @hfloyd I talked with our cloud team in relation to your questions and what information you think is missing.

In regards to the questions that you answered, I got the following answers from the Cloud team:

- All users of an organization will be able to see some basic information about the organization and the list of members. What the user can see and do depends on the permission that the user has been assigned to the organization.
- Organization and project permissions are two separate concerns. A membership to an organization adds no project permissions.
- E.g. when a user gets access to a project, he/she does not get invited/added to the organization that owns the project.

For your last questions, the previous ones should answer those, As there is no relationship between membership of an organization and the project it owns.

 I have created the following PR: #5442 which should mitigate some of the things you believe were missing from the org documentation.

For the last part, I don't see how we would go about that, how agencies are handling payments, is up to them, and not really something that I think makes sense for us to document.

we do mention that you need to reach out to support if you need an organization, as it is not something you can create yourself. I've added it as a hint, so it is more visible as well.

I hope this makes sense 😊

**Comment by jonat123** [comment]
@hfloyd Ahhh, thanks for clarifying! 

I will see if I can fit a message like that somewhere, definitely makes sense for me to add something like that :-)

**Comment by jonat123** [comment]
@hfloyd I've added a small addition to the note at the top of the page, saying that if you need to have a project added to a org, you also need to reach out to support :-)

**Comment by hfloyd** [comment]
Always happy to help!
