### ISSUE TITLE
Missing NPM package with @umbraco-cms/backoffice@14.0.0--preview003

### ISSUE THREAD

**Issue by Rockerby** [umbraco/UmbracoDocs#5449]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-backoffice/extending/development-flow/vite-package-setup#getting-started-with-vite
The section which instructs on how to get the Umbraco backoffice NPM package as a dev dependency.

## Describe the issue
If we update the backoffice NPM package to use the latest `@umbraco-cms/backoffice@14.0.0--preview003` there are missing dependencies; specifically `@umbraco-ui/uui@1.4.0-rc.2`. This works as expected when installing `preview001`.

<img width="763" alt="image" src="https://github.com/umbraco/UmbracoDocs/assets/5808078/2c0dcfe3-b556-46c2-87fb-08538ae62f3e">

**Comment by Rockerby** [comment]
As a quick workaround, this works following the below.

Install preview001:
```npm install -D --registry https://www.myget.org/F/umbracoprereleases/npm @umbraco-cms/backoffice@14.0.0--preview001```

Then manually update the `package.json` file to use `preview003` and run `npm i`:
```
  "devDependencies": {
    "@umbraco-cms/backoffice": "^14.0.0--preview003",
    ...
  }
```

Looks like installing `preview001` installs the missing dependencies locally so can then be referenced when installing `preview003`.

**Comment by nielslyngsoe** [comment]
It could also be solved by running this line instead:

`npm install -D @umbraco-cms/backoffice@next `

I'm investigating what fits with the plans, so I will be back.

**Comment by alina-tincas** [comment]
Hi @Rockerby a PR has been created to resolve this issue: #5464, therefore, I am closing this issue 👍
