### ISSUE TITLE
Hacktoberfest 2023: Update code examples to use File-scoped namespace declaration

### ISSUE THREAD

**Issue by jonat123** [umbraco/UmbracoDocs#5465]
Once again Hacktoberfest is upon us, and on the UmbracoDocs we have a task that we need your help with:

# Update code examples to use File-scoped namespace declaration

This year, we would like your help, with updating our C# code examples to use [File-scoped namespace declaration](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#file-scoped-namespace-declaration).

## What are File scoped namespaces?

File-scoped namespace declarations were introduced in C# 10 and .NET 6.

This means that it is possible to use this on Umbraco 10 and all versions above.

_File scoped namespace declarations enable you to declare that all types in a file are in a single namespace. The following example uses a file scoped namespace declaration:_

```
using Examine.Lucene;
using Microsoft.Extensions.Options;

namespace Umbraco.Docs.Samples.Web.CustomIndexing;

    public class ConfigureExternalIndexOptions : IConfigureNamedOptions<LuceneDirectoryIndexOptions>
    {
        public void Configure(string name, LuceneDirectoryIndexOptions options)
        {
            throw new System.NotImplementedException();
        }

        public void Configure(LuceneDirectoryIndexOptions options)
        {
            throw new System.NotImplementedException();
        }
    }
```

Make sure to have a look at the [official Microsoft Documentation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/namespace) on how to properly use file-scoped namespaces.

## How can you help?

**Write a comment** on this Issue, telling us which section you'd like to check, and make sure to reference this issue when you make the PR.

That way we can keep track of the progress, and other contributors will know which sections are already done or being worked on 💪 

**Fundamentals**
- [ ] Setup
- [ ] Backoffice
- [ ] Data
- [ ] Design
- [ ] Code

**Implementation**
- [ ] routing
- [ ]  Custom routing
- [ ] Controllers 
- [ ] Data Persistence
- [ ] Composing 
- [ ] Integration Testing
- [ ] Nullable Reference types
- [ ] Services and helpers
- [ ] Integration Testing
- [ ]  Unit Testing

**Extending**
- [ ] Dashboard, Section Trees and Property Editors
- [ ] Macro parameter Editors
- [ ] Health Checks and Language Files
- [ ] Backoffice Search, Tours and API
- [ ] Content App and Creating a Custom Database table
- [ ] Embedded Media Provider and FileSystemProviders
- [ ] Configuring Azure Key Vault
- [ ] Packages

**Reference**
- [ ] Configuration
- [ ] Templating
- [ ] Querying & models
- [ ] Routing & controllers
- [ ] API versioning and OpenAPI
- [ ] Searching
- [ ] Management
- [ ] Plugins and Cache
- [ ] Debugging and Language Variation
- [ ] Notifications
- [ ] Scheduling and Using IoC
- [ ] Common pitfall & anti-pattern
- [ ] Debugging with SourceLink
- [ ] Language Variation
- [ ] UmbracoMapper
- [ ] Distributed locks

**Tutorial**
- [ ] Creating a property editor
- [ ] Add google authentication
- [ ] Add Azure Active Directory
- [ ] Creating a backoffice tour
- [ ] Creating Custom Database Tables
- [ ] Member registration and login
- [ ] Custom Views of Block list
- [ ] Connecting Umbraco forms and zapier
- [ ] Creating an XML sitemap
- [ ] Creating and distribute a package
- [ ] Custom Error pages

**Comment by royberris** [comment]
Starting on Fundamentals

**Comment by royberris** [comment]
Started and finished implementation

**Comment by royberris** [comment]
Started on extending

**Comment by royberris** [comment]
Started and finished tutorials

**Comment by royberris** [comment]
That should be all for this issue, PR: https://github.com/umbraco/UmbracoDocs/pull/5478

**Comment by alina-tincas** [comment]
UPDATE: The PR from @royberris #5478 has resolved all namespaces in the whole documentation for v12. 

What is left in this case is for the same PR/changes to be done for the whole v10 CMS docs as well💪
