### ISSUE TITLE
Add SQL snippets for creating database logins

### ISSUE THREAD

**Issue by mattou07** [umbraco/UmbracoDocs#5488]
## What type of issue is it?

Missing documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-cms/fundamentals/setup/requirements#database-account-roles

## Describe the issue

Under Database Account Roles I thought it would be useful to add some SQL code snippets for people to copy to either create a login with just db_owner or SQL to create a more restricted user.

Happy to work on this, thought I would create an issue first.

**Comment by alina-tincas** [comment]
Hi @mattou07 thank you for opening this issue 😊 
And sure thing, this could be something that we can add to our documentation! However, if the steps are all ready existing somewhere such as here: https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles?view=sql-server-ver16#a--adding-a-user-to-a-database-level-role then in this case it would be best to add an [info note ](https://docs.gitbook.com/content-creation/blocks/hint) or write a sentence where it mentions db owner etc to reference the link. Such as "for more information how to create a db user via SQL you can check the Microsoft documentation." 

You are most welcome to give it a try and create a PR for this (it will need to be on all versions of CMS as well) 🙌

**Comment by beKoool** [comment]
Hey! Can I give this a try?

**Comment by mattou07** [comment]
> Hey! Can I give this a try?

Sure! Add a link to your PR here.

**Comment by beKoool** [comment]
Added the info note and submitted a PR.

**Comment by beKoool** [comment]
Hi guys, the PR is #5497. Hope this issue is resolved. 👍

**Comment by beKoool** [comment]
Hello @alina-tincas 👋 , I have added the info note and submitted PR ( #5497 ). It is now ready for review!! 🔥🔥

**Comment by alina-tincas** [comment]
Thank you for the PR @beKoool and thank you for raising this issue @mattou07 🙌 #h5YR 

As the PR has been merged, I am closing this issue. 👍
