### ISSUE TITLE
Umbraco 7.7 AddSectionToAllUsers method in UserService removed?

### ISSUE THREAD

**Issue by gijsstegehuis** [umbraco/UmbracoDocs#549]
`AddSectionToAllUsers` seems to be removed from `UserService` since Umbraco 7.7
Whats the equivalent for this method in 7.7?

**Comment by liamlaverty** [comment]
Can't find the equivalent anymore, but you can use this to achieve the same thing

    public bool UpdateUserSections(string sectionAlias)
        {
            try
            {
                var userService = Services.UserService;

                int myTotalRecords = 0;
                //if you've got more than 100 users then you'll need to page these
                var users = userService.GetAll(0, 100, out myTotalRecords);


                //for everyone who doesn't already have this section added
                foreach (var user in users.Where(u => u.AllowedSections.InvariantContains(sectionAlias) == false))
                {
                    user.AddAllowedSection(sectionAlias);
                    userService.Save(user);
                }
                return true;
            }
            catch(Exception ex)
            {
                //do w/e with the error
                return false;
            }
        }


Source this was modified from is here: https://github.com/umbraco/Umbraco-CMS/blob/c3b1aa36b885f94cd59d3641f6f59aa3eaad08c5/src/Umbraco.Core/Services/UserService.cs#L801

**Comment by Shazwazza** [comment]
In 7.7 a User Group determines section access so you can just update the User Group that you want to add sections to
