### ISSUE TITLE
Missing documentation about creating email / export templates in Commerce

### ISSUE THREAD

**Issue by skttl** [umbraco/UmbracoDocs#5507]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## Describe the issue
Would be great, if at least the templates coming with Commerce was available for download, just like the default templates for Forms is.

Other than that, maybe some documentation about how to use them.

**Comment by alina-tincas** [comment]
Hi @skttl thank you for bringing this to our attention! 🙌 
We have added this to our backlog so this issue will be updated when we have a PR for this 👍

**Comment by sofietoft** [comment]
Closing this Issue due to duplicates.
See #5696 instead.
