### ISSUE TITLE
Wrong workflow in "Articles and Article Items" page

### ISSUE THREAD

**Issue by DORE-PD** [umbraco/UmbracoDocs#5510]
## What type of issue is it?
Wrong documentation

## What article/section is this about?
[(https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items)]

## Describe the issue
Under the heading "Updating the Document Type Permissions" there is the sentence "To update Articles Item Document Type permissions:".
Point 1 then says: "Navigate to the Articles Item Document Type and go to the Permissions tab."
You should not open Articles Item but Articles Main and set Articles Item as the allowed child node.

**Comment by alina-tincas** [comment]
Hi @DORE-PD thank you for bringing this to our attention and good catch! 🙌 

I have created a PR for this [here](https://github.com/umbraco/UmbracoDocs/pull/5514) and as it has been merged and the changes are updated in the documentation, I am closing this one 👍
