### ISSUE TITLE
Telemetry data

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/UmbracoDocs#5536]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
[(link here)](https://github.com/umbraco/UmbracoDocs/blob/main/12/umbraco-cms/fundamentals/backoffice/settings-dashboards.md)

## Describe the issue
The documentation goes into details about what "detailed telemetary data is", but not minimal or basic. We've been asked to provide more information on these from a client, and non of the blogs https://umbraco.com/blog/umbraco-92-release/ or https://umbraco.com/blog/how-umbraco-cms-is-used-telemetry-status-february-2023/ really give details about the various levels. I'm looking for the info for an Umbraco 10 site :-)

**Comment by alina-tincas** [comment]
Hi @RachBreeze 👋 

We have some documentation about telemetry data here: https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/settings-dashboards#telemetry-data Can you please confirm if this is what you were looking for and if you still believe it needs to have more information? 😊

**Comment by RachBreeze** [comment]
Hi @alina-tincas 

Thank you for getting back to me. I tried to raise the issue against that page!

It only shows what data is collected when detailed is selected, it does list what the minimal and basic levels collected which is what our client wanted to know, in order to make an informed choice. The client is on Umbraco 10.

**Comment by alina-tincas** [comment]
All right, so if I understand correctly you would want that piece of content to be more elaborated on the " Minimal and Basic" levels, similar to as how the "Detailed" are described? 💡

**Comment by RachBreeze** [comment]
That would be perfect thank you

**Comment by liamlaverty** [comment]
I've created a PR here: https://github.com/umbraco/UmbracoDocs/pull/5733, which adds the two descriptions below for versions 10, 11, 12, and 13.

>  **Basic** contains:
> 
> * Anonymized site ID, Umbraco version, and packages installed.
> 
> **Minimal** contains:
> 
> * Anonymized site ID only

**Comment by alina-tincas** [comment]
Thank you for the PR @liamlaverty #h5YR 🙌 

As the PR has been merged in, I am closing this issue 💪
