### ISSUE TITLE
Fix Issues reported by Vale

### ISSUE THREAD

**Issue by syedzubeen** [umbraco/UmbracoDocs#5547]
## What type of issue is it? (Choose one - delete the others)

Other: Fixes some issues reported by Vale

## What article/section is this about?
(link here)

## Describe the issue

- Issue Number 1
![image](https://github.com/umbraco/UmbracoDocs/assets/14253061/c4337276-9931-4796-9e42-f9119bb06bf0)

- Issue Number 2
 ![image](https://github.com/umbraco/UmbracoDocs/assets/14253061/5e61e75f-545a-40e7-b320-ff6c46464937)

- Issue Number 3
![image](https://github.com/umbraco/UmbracoDocs/assets/14253061/1f090652-7535-4f88-be19-f358e7301465)

- Issue Number 4
![image](https://github.com/umbraco/UmbracoDocs/assets/14253061/0d4d0fe7-d872-4cf2-938e-350643a1c260)

- Issue Number 5
![image](https://github.com/umbraco/UmbracoDocs/assets/14253061/12bf583a-5dfa-4058-9874-1700d3de7171)

- Issue Number 6
![image](https://github.com/umbraco/UmbracoDocs/assets/14253061/127f7117-4252-4c22-8f64-fae414b9746e)

- Issue Number 7
![image](https://github.com/umbraco/UmbracoDocs/assets/14253061/94d7c725-e6f3-4112-965a-aafdd13b1535)

- Issue Number 8
![image](https://github.com/umbraco/UmbracoDocs/assets/14253061/abef8c86-7529-4997-b100-89f77fc1ca92)

- Issue Number 9
![image](https://github.com/umbraco/UmbracoDocs/assets/14253061/fb005351-9749-4a79-a34b-64a9c107abb3)

- Issue Number 10
![image](https://github.com/umbraco/UmbracoDocs/assets/14253061/5b4faeba-7888-439c-b370-5eac878d409c)

**Comment by syedzubeen** [comment]
Tried addressing some vale issues against the documentation. Left out what seemed to me as false positives.

Looking forward to your feedback as this is the first time I tried using Vale and this is my first contribution to this project as well. 😃

**Comment by alina-tincas** [comment]
Hi @syedzubeen 👋 

We are currently aware there are many issues that we have with vale errors and in this case, we appreciate any contribution like your PR. This issue will be closed once your PR is merged.

I have left some feedback on your PR, can you please take a look into them? Thank you again for opening a PR #h5YR 🙌

**Comment by syedzubeen** [comment]
Thank you @alina-tincas for reviewing the MR. 
I have resolved the review comments and added new PRs for updating guides for versions 10 and 11 too.

**Comment by alina-tincas** [comment]
Hi @syedzubeen thank you for making all the requested changes #h5YR

In the future, instead of creating one PR for each, it is possible to fork this Docs Repository, then you can clone down your fork, make changes for all versions, push the changes up to your repository, head to your repository and create a PR which will then show in the Docs Repository. You can read more about this here: https://docs.umbraco.com/welcome/contribute/pull-request#options-2-creating-a-pr-through-a-fork 🙌

As the PRs have been merged, I am closing this issue 💪
