### ISSUE TITLE
Duplicated steps in "Articles and Article Items"

### ISSUE THREAD

**Issue by DORE-PD** [umbraco/UmbracoDocs#5553]
## What type of issue is it?
Duplicated steps

## What article/section is this about?
(https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items#updating-the-document-type-permissions)

## Describe the issue
There are 2 items in "Updating the Document Type Permissions". The first is about "Articles Main" and the other is about "Articles Item". However, items 6-8 of "Articles Main" are the same as the 3 items of "Articles Item".
I think points 6-8 can be removed.

**Comment by alina-tincas** [comment]
Hi @DORE-PD thank you for bringing this to our attention! It makes sense indeed to remove point 6-8. 
Setting this issue as up for grabs 💪 

Note: when creating a PR, this issue will need to be resolved for all versions of CMS: v12, v11 and v10.

**Comment by Abdjulaziz** [comment]
On it 😄

**Comment by alina-tincas** [comment]
Thank you @Abdjulaziz 🙌 

As the PR #5560 has been merged, I am closing this issue 💪
