### ISSUE TITLE
Markup issue in "Articles and Article Items"

### ISSUE THREAD

**Issue by DORE-PD** [umbraco/UmbracoDocs#5554]
## What type of issue is it?
Markup

## What article/section is this about?
(https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items#creating-the-content-node)

## Describe the issue
The 5th point of "Creating the Content Node" has several "*" in the text. I guess the text in between should be written in bold.

**Comment by alina-tincas** [comment]
Hi @DORE-PD thank you for bringing this to our attention! Setting this issue as up for grabs 💪 

Note: when creating a PR, this issue will need to be resolved for all versions of CMS: v12, v11 and v10.

**Comment by jannikanker** [comment]
Argh, I got beaten to it! I've created https://github.com/umbraco/UmbracoDocs/pull/5557 - which fixes the formatting in v10, 11 and 12 Markdown files. I think the PR @Abdjulaziz only fixes v12?

**Comment by Abdjulaziz** [comment]
For now yes @jannikanker 😢

**Comment by jannikanker** [comment]
Dang it. Sorry, I forgot to write here before I got started :-(

**Comment by alina-tincas** [comment]
As a [PR](https://github.com/umbraco/UmbracoDocs/pull/5557) for this has already been merged in, I am closing this issue 🙌 

I have also talked with @Abdjulaziz and he will create a PR for #5553 instead 💪
