### ISSUE TITLE
UI Builder license page needs updating

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/UmbracoDocs#5586]
## What type of issue is it?
Wrong documentation

## What article/section is this about?
[(UI Builder Licensing)](https://docs.umbraco.com/umbraco-ui-builder/getting-started/licensing-model)

## Describe the issue
I don't know how much of this page is correct considering the licensing that I've been reading about this week, but this part is definitely wrong!

![image](https://github.com/umbraco/UmbracoDocs/assets/4716542/86f6b630-2fd0-49e0-8844-b4f138502f61)

**Comment by jonat123** [comment]
@LottePitcher Thanks for raising this issue!

That does indeed look wrong and like some commerce documentation has sneaked itself into the UI-builder docs 🙈

I will make sure it gets removed! 

Thanks again for creating this issue 😄

**Comment by alina-tincas** [comment]
Hi @LottePitcher! 😊 

This has been resolved in this PR: #5649 therefore I am closing this issue. 

Thank you again for bringing this to our attention 🙌
