### ISSUE TITLE
Document Db provider changes for v12

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/UmbracoDocs#5598]
Hi!

The upgraded DB-driver in Umbraco v12 will cause an error that is very hard to track down to the source.

Similar to this:
```
"Umbraco.Cms.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.\r\n   at Umbraco.Cms.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException)\r\n   at 
Umbraco.Cms.Web.Common.Middleware.BootFailedMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at
 Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
\r\n--- End of stack trace from previous location ---\r\n   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)\r\n   a
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

Not that there are no details at all about why this is happening. 

Found this https://our.umbraco.com/forum/using-umbraco-and-getting-started/112407-umbraco-v12-exception-at-startup-when-run-in-docker

https://our.umbraco.com/forum/using-umbraco-and-getting-started/112173-error-while-upgrade-from-1141-to-12

Adding this to the connection-string will solve the problem:

```
<connectionstring>;TrustServerCertificate=True
```

It would be nice if this was documented

**Comment by jonat123** [comment]
@enkelmedia Thanks for creating this issue 😊

We already mention it in the upgrading documentation her: https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading#upgrade-to-a-new-major 

Is there any other places you think it should be added?

**Comment by jonat123** [comment]
@enkelmedia As this is something that has already been documented, I will close this issue for now.

If you believe that it should be added, you are more than welcome to open up this issue again 😊

**Comment by enkelmedia** [comment]
Thanks @jonat123 =D Looks great in the article! I think that most people will search for something in the error message - but it's very generic so I guess it does not make sense to include in the docs.

Let keep this closed - cheers!
