### ISSUE TITLE
Clicking Edit on Github should open a new tab

### ISSUE THREAD

**Issue by mattou07** [umbraco/UmbracoDocs#5604]
## What type of issue is it? (Choose one - delete the others)
Discussion

## What article/section is this about?
This applies to all pages: https://docs.umbraco.com/

## Describe the issue
When clicking the three dot menu and then clicking Edit on Github, it should open in a new tab. 

This makes it easy to compare my changes against the live page.  Currently I have to duplicate the tab and then go back in the duplicated tab to get the page back to compare my proposed changes against what is currently published.

**Comment by jonat123** [comment]
@mattou07 Thanks for opening this issue 😄

That makes sense to me, however as it is a Gitbook feature, I am not sure if it is currently possible.

I will make sure to look into it and see if it might be possible and let you know!

Otherwise I might need to reach out to Gitbook :-)

**Comment by jonat123** [comment]
@mattou07 Sorry for the delay on this one. 

Unfortunately, it is not something we can change, however, I have created an issue on the Gitbook tracker here:
- https://github.com/orgs/GitbookIO/discussions/460

**Comment by alina-tincas** [comment]
Hi @mattou07 am happy to share that there is an [update ](https://changelog.gitbook.com/march-2024/4-march-huge-improvements-to-your-published-documentation) from Gitbook where now it is possible to right click on the "Edit on Github" and open on new tab, which was not possible before. It might not be what you are looking for, but just sharing this here as it is an improvement 💪 

![image](https://github.com/umbraco/UmbracoDocs/assets/83591955/bf5478b2-0a82-4892-9830-35b9d0d7a759)
