### ISSUE TITLE
Delete code examples that update Program.cs or Startup.cs

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#5709]
## What type of issue is it? (Choose one - delete the others)
Discussion/Wrong documentation

## What article/section is this about?
Several articles like: 
https://docs.umbraco.com/umbraco-cms/extending/section-trees/sections 
https://docs.umbraco.com/umbraco-cms/extending/content-apps 
etc.

## Describe the issue
In a discussion about [extension methods](https://github.com/umbraco/Umbraco-CMS/pull/15432#issuecomment-1852091417), the advice is given to make no changes to the `Startup.cs` or `Program.cs` files. I believe it is a good idea to remove the code examples from the docs that make changes to the `Startup.cs` or `Program.cs`. Instead, examples using an `IComposer` can be added.

**Comment by alina-tincas** [comment]
Hi @erikjanwestendorp thank you for opening this issue! We are currently aware of it and have this is a task in our backlog 🙏

**Comment by erikjanwestendorp** [comment]
@alina-tincas Thanks for your reply! 😄  As far as I know the advice in general is: Do not touch the 'Program.cs/Startup.cs' files and use an `ICompser` instead. My PRs aren't so much about changing `Startup.cs` to `Program.cs` or updating to the minimal hosting model. My PRs removes code samples that update `Startup.cs` or `Program.cs` in general, since that is the advice (These articles also provide examples with an `IComposer` already). I think it is good to remove these examples, otherwise the documentation goes against this advice 😄.

**Comment by alina-tincas** [comment]
I understand! We will discuss this with our CMS developers on what is the best approach in this case, if those examples should indeed be removed. I will get back to you on this 👍

**Comment by jonat123** [comment]
Hey Erik and happy new year 🎉

I want to let you know, that I have talked with the Lead developer for the CMS team, and he is fine with removing the examples that updates make changes to the `startup.cs` and `program.cs` files and replacing them with examples using composers instead(If they don't already have composer examples) 😄

There is only one thing to be aware of and that is examples that are using middleware. For Middleware it can also be done in a Composer, using the pipeline filter 😊

**Comment by erikjanwestendorp** [comment]
@jonat123 Happy new year! Thanks for the update 😄! Good to hear that the examples can indeed be removed/replaced

**Comment by sofietoft** [comment]
Hi @erikjanwestendorp ! 👋 
Long time to see! Hope you're doing well, and congratz on getting your MVP status renewed last week 😎 

I've been looking at this one, and I like the idea of keeping the docs streamlined in terms of what we recommend - eg. do we recommend using composers versus making changes to the `Program.cs` file?

Were you working on this based on a list of articles referencing the `Program.cs` file? 
I'll be making one, but don't want to, if one already exists! 😁

**Comment by erikjanwestendorp** [comment]
Mucho gracias @sofietoft! 😄  Indeed, it's been a long time! Are you back at the Umbraco office after your leave (I assume you were on leave)? Sorry for my late response, I was on leave myself last month (👶🍼 ). 

To be honest, I haven't made a list yet and I started going through the articles, but it is indeed a good idea to make a list to have a clear overview.

**Comment by sofietoft** [comment]
I have indeed been on leave for the past 10 months, yes (👶🏻👶🏻🍼) , but it's very good to be back at work again! Kids are great and all, but I'm really not the "stay at home mom" type 😁 
Congratz on the little one! Hope you had a great leave!

Fair enough about the list. I just wanted to make sure I didn't start making a list, if one had already been made.
Work smart, not hard, right? 😉

I'll get to work on a list of articles where code samples make changes to the Program.cs file 💪

**Comment by sofietoft** [comment]
Hi @erikjanwestendorp 👋 

I've just made a PR related to this issue: #6243 

With this, I've breaking this issue down a bit, to only revolve around using the Program.cs for registering dependencies.
We'll take a look at the rest of the scenarios after that fact, if necessary!

After talking with our CMS PO, Lasse, about this, we agreed that we want to try to keep opinions and personal preference out of our documentation - if it all possible! 🤞 

That's why I've now rewritten the IoC article a bit, so that it presents a couple of strategies while leaving it up to the individual user to chose the one best fitting their scenario.

You're welcome to take a look and see if it makes sense.
The next step is to reference this article in other articles where dependencies are registered, and make sure that we're not too opinionated in those articles either 😅 

I hope it all makes sense! Let me know if you have comments, thoughts, questions...

**Comment by sofietoft** [comment]
Hi @erikjanwestendorp ! 👋 

I think we should consider this Issue resolved.
Looking at the initial messages, it seems that you've been wanting to remove the examples that register dependencies directly in the Startup.cs/Program.cs files - and this is to some degree what my two related PRs do.

If you still feel we should look into the other places where changes are made to the Program.cs (or Startup.cs) files, you're most than welcome to open a new issue, and we'll take a closer look into it 💪 

As always, THANK YOU for helping us keep the docs up to speed! 🙌 #H5YR
