### ISSUE TITLE
Umbraco 13 RC Documentation

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#5763]
I see that the Umbraco 13-rc folder is still there. Can't this be removed since there is a final Umbraco 13 version?

![image](https://github.com/umbraco/UmbracoDocs/assets/7831614/2dd88bcb-c28e-4b7f-a4a4-2e8ec81e6fdf)

**Comment by alina-tincas** [comment]
HI @erikjanwestendorp v13-rc folder and v11 have just been removed from the repository 💪
