### ISSUE TITLE
Wrong link on release note documentation for Umbraco UI Builder

### ISSUE THREAD

**Issue by jemayn** [umbraco/UmbracoDocs#5771]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
[(link here)](https://github.com/umbraco/UmbracoDocs/blob/main/13/umbraco-ui-builder/release-notes.md)

## Describe the issue
At the bottom it says you can read additional release notes in another document, and then it links to a Vendr document. 

I'd be happy to submit a PR for this, but I don't know if that section should just be deleted, or whether a similar document exists for old Konstrukt releases somewhere that it should link to?

**Comment by alina-tincas** [comment]
Hi @jemayn thank you for bringing this to our attention! 

The correct link for konstrukt older releases is this: https://github.com/umbraco/UmbracoDocs/blob/main/13/umbraco-ui-builder/changelog-archive/changelog.md 

So if you are up for it you can make a PR to change the reference link to the above for all versions: v13, 12 and 10 😊

**Comment by jemayn** [comment]
Thanks for pointing me in the right direction @alina-tincas - I've submitted a PR with a fix now 🙂
