### ISSUE TITLE
npm create vite in docs is wrong

### ISSUE THREAD

**Issue by jemomi-twoday-co3** [umbraco/UmbracoDocs#5774]
In the docs there is this command displayed for using recommended setup for building extensions: ([here](https://github.com/umbraco/UmbracoDocs/blame/50ec14dbce94542f9164d53f3972372e6d16ab8a/new-backoffice/tutorials/creating-your-first-extension.md#L130))
```bash
npm create vite@latest --template lit-ts my-extension
```
however this is how vite docs define the command: ([reference link](https://vitejs.dev/guide/#scaffolding-your-first-vite-project))
```bash
# npm 7+, extra double-dash is needed:
npm create vite@latest my-vue-app -- --template vue
```
So the docs should be changed to:
```bash
npm create vite@latest my-extension -- --template lit-ts
```
Please note that in vite docs it says: _npm 7+, extra double-dash is needed_

Also, just a heads up.
`npm create vite@latest` will currently use vite5, not vite4. But i dont know if this is an issue

**Comment by jemomi-twoday-co3** [comment]
After running `npm install -D @umbraco-cms/backoffice`, i can see that npm fails because, `@umbraco-cms/backoffice` is dependant on lit@2 and it seems that vite5 uses lit@3.
So the dics, should probably be changed to: 
```bash
npm create vite@4^ my-extension -- --template lit-ts
```

**Comment by jemomi-twoday-co3** [comment]
After digging a bit in `@umbraco-cms/backoffice` source code, i can see that it uses, vite5, so maybe the previous comment, about using vite4, can be ignored. Unless my feature request on upgrading from Lit2 to Lit3 can come through.
Or alternatively, maybe a custom template for `create-vite` can be made, so we can have vite5 with Lit2.8

**Comment by alina-tincas** [comment]
Hi @jemomi-twoday-co3 👋 

When you mention that npm installation in docs is not correct, are you referring to this docs: https://docs.umbraco.com/umbraco-backoffice/extending/development-flow/vite-package-setup#getting-started-with-vite or this [docs](https://github.com/umbraco/UmbracoDocs/blame/50ec14dbce94542f9164d53f3972372e6d16ab8a/new-backoffice/tutorials/creating-your-first-extension.md#L130)? 

If it is the 2nd one, then it is the New Backoffice team that is taking care of it so you should open an issue about this on their github repository. As you have opened a Backoffice feature request: https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1118 the New Backoffice team will take a look at it 👍

**Comment by jemomi-twoday-co3** [comment]
@alina-tincas To some extend i think both in case the user after setup, decides to use Lit, but mainly the 2nd :)
Thought i should create the issue here, since the document is part of this repo, but i'll add the issue on new.backoffice :)

Thanks, for your response

**Comment by alina-tincas** [comment]
@jemomi-twoday-co3 oh, just noticed the first link you shared is part of docs repository: https://docs.umbraco.com/umbraco-backoffice/tutorials/creating-your-first-extension#getting-started-with-vite 🙈 My bad, it is still start of a Monday morning! 

Feel free to close this issue: https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1120 and we can continue with this here 👍 

I have asked one of our new backoffice developers for assistance on this one so when we have some updates we will get back to you here!

**Comment by jemomi-twoday-co3** [comment]
@alina-tincas okay i has been closed :)
That sounds great! thanks :D
