### ISSUE TITLE
Configuring Azure Key Vault | Docs no longer correct for v13

### ISSUE THREAD

**Issue by Matthew-Wise** [umbraco/UmbracoDocs#5787]
## What type of issue is it? 
Wrong documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-cms/extending/key-vault#configuration

## Describe the issue
Program.cs configuration shows using
``` 
Host.CreateDefaultBuilder(args)
    .ConfigureUmbracoDefaults()
   .ConfigureAppConfiguration((context, config) =>
```

However v13 now ships using 

```
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);
```
Which doesn't have the same configuration options.

**Comment by Matthew-Wise** [comment]
Currently working on getting this working if I manage I'll try get a PR done as well

**Comment by alina-tincas** [comment]
Hi @Matthew-Wise, there is a merged PR that updated the KeyVault config to work for v13 in https://github.com/umbraco/UmbracoDocs/pull/5862, so am closing this one.

Thank you again for bringing this to our attention 😊
