### ISSUE TITLE
Duplicated class declaration

### ISSUE THREAD

**Issue by DORE-PD** [umbraco/UmbracoDocs#5789]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
(https://docs.umbraco.com/umbraco-cms/reference/routing/custom-routes#custom-route-with-ivirtualpagecontroller)

## Describe the issue
In the first code snippet of the "Custom route with IVirtualPageController" section, the ShopController was declared twice:

![image](https://github.com/umbraco/UmbracoDocs/assets/141619760/7e8d4fb5-9fae-442f-b271-1648806b519f)

**Comment by alina-tincas** [comment]
Hi @DORE-PD, as @LiliM4 has created a PR to resolve this issue which has been merged in as well, I am closing this one 😊 

Thank you again for bringing this to our attention and thank you Lili for the PR 🙌
