### ISSUE TITLE
Oooops, something broke..

### ISSUE THREAD

**Issue by khoatruongquocanh** [umbraco/UmbracoDocs#579]
Hi
When I go to the link below or all link on our.umbraco.org.
https://our.umbraco.org/documentation/getting-started

Oooops, something broke..
Looks like you ran into a broken link. We really want to fix it but we need to know about it first. You can let us know by creating an issue on Github.

The Umbraco documentation is open source so you can also help us make the documentation better by creating a pull request. You can find information on how to get involved in the guidelines.

Regards,
Truong Quoc Anh Khoa
email: m_living@hotmail.com

**Comment by sofietoft** [comment]
Hi there,
Thank you so much for reporting this!

It seems that you might have tried to access Our at a time where it was down 😞 
Fear not! It's all up a running again!

-Sofie
