### ISSUE TITLE
Links not generated correctly on docs page

### ISSUE THREAD

**Issue by peterrydetorp** [umbraco/UmbracoDocs#5793]
## What type of issue is it? 
Wrong documentation

## What article/section is this about?
https://docs.umbraco.com/welcome/getting-started/developing-websites-with-umbraco/extending-the-umbraco-backoffice#what-can-be-extended

https://docs.umbraco.com/welcome/getting-started/hosting-an-umbraco-infrastructure

Almost all internal links in the main window are generated wrong.

## Describe the issue
Links are not generated correctly

**Comment by alina-tincas** [comment]
Hi @peterrydetorp thank you for bringing this to our attention 🙌 

The links have been fixed, therefore I will close this issue 😊
