### ISSUE TITLE
Documentation Start-Item should inform user that Start-Item must be a root content node.

### ISSUE THREAD

**Issue by jlfolland** [umbraco/UmbracoDocs#5827]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
[(link here)](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#start-item)

## Describe the issue
Under section start-item, it should inform the reader that the start-item must be a root node in the content tree. Thus, a developer could not use a structure such as /site-group/site/home and then select the home item as the start-item. This could impact on content structure decisions.

This can be verified by reviewing the current code:

`_requestedStartContent = Guid.TryParse(headerValue, out Guid key)
    ? rootContent.FirstOrDefault(c => c.Key == key)
    : rootContent.FirstOrDefault(c => c.UrlSegment(_variationContextAccessor).InvariantEquals(headerValue));`

**Comment by alina-tincas** [comment]
Hi @jlfolland thank you for bringing this to our attention! 🙌 

We will take a look at this as soon as we can 🙏

**Comment by eshanrnh** [comment]
Hello @jlfolland,
 
I haven't received any updates from you, so I assume the issue has been resolved. 

If you still need any assistance, please don't hesitate to reach out to us 🙌
