### ISSUE TITLE
Umbraco 13: Integration testing with existing database

### ISSUE THREAD

**Issue by Domitnator** [umbraco/UmbracoDocs#5834]
## What type of issue is it? 
Missing documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-cms/implementation/integration-testing

## Describe the issue
Hi Guys,

The last several days i'm having a hard time to figure out how i can run a simple integration test against an existing umbraco database. 

We often have to import data from another system and create pages within umbraco based on that imported data. For instance, a PIM system contains 1000 products and we need to display that products on the umbraco website.  You can solve this in 1000 ways but on a global level we mostly do:

1. We create a seperate class library
2. Write code that will fetch the data from the external system
3. Write code that will create the data in umbraco
4. Use hangfire to register this as a recurring job

But how do you test this code? I see a lot of developers creating a temporary umbraco API endpoint and then use postman (or the browser) to trigger the endpoint and then they start debugging. Stop the browser, make some changes, start the project, open postman, trigger the endpoint again, start debugging..and this goes on and on.

The solution to this anoying workflow is creating a integration test in my opinion so i started to look at some documentation and resources to get started:

- https://docs.umbraco.com/umbraco-cms/implementation/integration-testing
- https://www.youtube.com/watch?v=02mxZRIX2es ( i think this video was input for the documentation page)
- https://www.youtube.com/watch?v=EECWJOTrKEM

I then started coding but i was quickly struggeling. My first goal was to just retrieve some data from a existing umbraco installation (with SQL server database). So i wrote a simple test to get the root node:

![image](https://github.com/umbraco/UmbracoDocs/assets/13468638/d3c41e78-d455-4fbc-99c7-128f05d722af)

![image](https://github.com/umbraco/UmbracoDocs/assets/13468638/cf457170-2140-46a1-ab79-fea8a7870234)

My questions:

1. Any idea why the test fails? Why does the contentservice does not return content?
2. Is it even possible to test against an existing database without creating a package and use that as an embedded resource?
3. What is the difference between the UmbracoIntegrationTest and the UmbracoTestServerTestBase?

I find this global information on testing usefull:

![image](https://github.com/umbraco/UmbracoDocs/assets/13468638/79ae8865-ba40-445c-b88f-7143be328642)

I feel that Umbraco has great support for Unit Test + Isolated Integration Tests but is lacking support for simple integration tests. I wonder how other feel about this? I am willing to update or restructure the docs if needed! If integration testing against an existing database is not supported then this should be pointed out more clear in the documentation in my opinion. But if it is supported then also is should be pointed out more clear how to setup such a integration test.

**Comment by Domitnator** [comment]
To add up...I see other people struggle with this too. This is a printscreen from the Umbraco Discord channel:

![image](https://github.com/umbraco/UmbracoDocs/assets/13468638/97ae020d-50f4-44ad-bcbb-214ae03fa212)

**Comment by alina-tincas** [comment]
Hi @Domitnator thank you for bringing this to our attention! 🙌 

We will take a look at this as soon as we can 🙏

**Comment by lars-erik** [comment]
Hi @Domitnator.

The integration tests package has some hardcoded stuff to create a new test database.  
So I don't think it's possible to point to an existing database with it today.  
That means you'll have to create your content for each test.  
The [Testing Notification](https://docs.umbraco.com/umbraco-cms/implementation/integration-testing#testing-a-notification) example in the docs shows how to set up a content type and some content using the builders that come with the integration test project.  
If you use the `NewSchemaPerFixture` option for the database, you should be able to do the setup once per fixture and then have faster individual tests.

**Comment by Domitnator** [comment]
@lars-erik 

Hi lars, thanks for you reply! I deep dived into the package this weekend and indeed it is not possible to point to an existing database. But I do managed to create my own package which support integration testing with an existing database!. Testing against a existing database is actually really fast! For me personally, it really speeds up my workflow so i am happy with the result!

 I'll try to see if my solution would fit into the existing integration test package so others could benefit from it too!

**Comment by eshanrnh** [comment]
Hey @Domitnator,

Sorry to hear you are having difficulties with integration testing in Umbraco. It sounds like you're dealing with quite a challenging workflow.

Since this GitHub repository is primarily focused on Umbraco Documentation, I'm afraid I can't assist you in this particular case.

Your feedback on the documentation and the need for clearer instructions is valuable. If you feel that the documentation lacks clarity on certain aspects, please feel free to [raise a PR](https://docs.umbraco.com/welcome/contribute/pull-request) to update or restructure it. It will greatly benefit the community.

Regarding your concerns about Umbraco's support for integration testing, I suggest reaching out to [Umbraco Discord](https://discord.com/channels/) or [Umbraco Community Forum](https://our.umbraco.com/forum/) can be quite beneficial. You might find others who have faced similar challenges and could offer insights or solutions.

Hang in there and don't hesitate to ask for help if needed.

I hope you find a solution 🤞
