### ISSUE TITLE
 Docs for Azure AD Authentication are missing for Umbraco 12, 13

### ISSUE THREAD

**Issue by kristofferwebmind** [umbraco/UmbracoDocs#5835]
## What type of issue is it?
Missing documentation

## What article/section is this about?
[https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/security/authenticate-with-active-directory](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/security/authenticate-with-active-directory)

## Describe the issue
The article above is missing for version 12 and 13

**Comment by alina-tincas** [comment]
Hi @kristofferwebmind this documentation for v12 and v13 exists here: https://docs.umbraco.com/umbraco-cms/v/12.latest/tutorials/add-azure-active-directory-authentication 😊 

Can you please confirm if the above is what you were looking for?

**Comment by kristofferwebmind** [comment]
Hi @alina-tincas ! I see, thanks for that! I think the confusion is due to the fact that if I'm on this page: https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/security/authenticate-with-active-directory and then switch from version 10 to version 12 or 13 using the version dropdown menu, then I am redirected to https://docs.umbraco.com/umbraco-cms/

![image](https://github.com/umbraco/UmbracoDocs/assets/143802330/e503b35a-bec4-408c-a4fe-7b45ab0665ed)

Same issue accutually occurs if I'm on the link you provided and then switch to version 10.

**Comment by kristofferwebmind** [comment]
Hi @alina-tincas ! Not entirely, we were looking for the documentation regarding Azure AD authentication for Users rather than Members. (The v10 page has both).

**Comment by alina-tincas** [comment]
Hi @kristofferwebmind! 

I dug a bit more to find out why this article was moved and why it is not the same on all versions. Then I saw one of my colleagues has moved this guide to the tutorials section and also removed the users examples with the explanation that Azure Active Directory authentication showcases an example for members while Google Authentication showcases an example for users:
https://github.com/umbraco/UmbracoDocs/pull/5120#pullrequestreview-1418510890

What we can do in this case is we can move the article to the tutorials page to fit with the rest of the versions. 

As for the conflicting information between the Azure Active Directory authentication docs and Google Authentication with the warning, it is as mentioned. [Umbraco Cloud hosting](https://umbraco.com/products/umbraco-cloud/) comes with a default login provider called Umbraco ID. If you are trying to setup Azure Active Directory authentication on an Umbraco Cloud project it will conflict with the Umbraco ID and will not work as intended, therefore the warning. If you are hosting umbraco yourself then this will be no issue 👍

**Comment by kristofferwebmind** [comment]
Thank you! 👌Do you know whether this recommendation is specific from version 10 and upwards? The site we are goin to rebuild is hosted on Umbraco Cloud and has Azure AD login, so that's why I was suprised to read this info. That site is an 8 though.

**Comment by alina-tincas** [comment]
Hi @kristofferwebmind no worries! I have asked around and there is no clear recommendation if it should or should not be used on Umbraco Cloud. Normally it should work with Umbraco Cloud as well, however, if it is not implemented correctly it might not work as intended and could be a factor of a security perspective. By using Azure AD then Umbraco ID (which is our primary security model for users login in the portal) is disregarded. So in short, you are more than welcome to give it a try if you would prefer it to. But from a security perspective, this approach might be less secure than a UmbracoID-only approach. These were the answers I got from colleague from Cloud team. 

I also got a suggestion from another colleague where you can also check out one of Umbraco's MVP full OpenID connect example implementations https://github.com/jbreuer/Umbraco-OpenIdConnect-Example however this is not confirmed if it works on Umbraco Cloud. 

For now I have moved over the article for v10 to tutorials to fit the ones from v11+: https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/tutorials/add-azure-active-directory-authentication 

Considering that you have mentioned you have this implementation on v8 I see no reason why it should not work for v10+. If you are giving it a try for v10+ you are more than welcome to get back to me or [contribute to our docs](https://docs.umbraco.com/welcome/contribute/pull-request) to remove that warning if all is good 💪 If the article is not working as intended you are more than welcome to open another issue and then we can take it from there. Let me know if this sounds like a plan?

Before closing this issue, I was wondering if you have any further questions? 😊

**Comment by kristofferwebmind** [comment]
Hi @alina-tincas , that sounds great 🙌 Thanks so much for diggin into this. Sounds like we should dare to give it a go. Thanks for your help, no further questions!

**Comment by alina-tincas** [comment]
Hi @kristofferwebmind 👋 

Just wanted to let you know that we currently have a PR to add a community example for v10+ using Azure AD for users: https://github.com/umbraco/UmbracoDocs/pull/5868/files which could help you on the way to setup the Azure AD from v10+(https://github.com/Gibe/Umbraco.Community.AzureSSO) - the only thing am not sure in this case is if it works with Cloud (which in this case it could be an idea to reach out to them on their github example about this 💪 ) 😊
