### ISSUE TITLE
Docs for Google Authentication mentions visual studio

### ISSUE THREAD

**Issue by Zeegaan** [umbraco/UmbracoDocs#5843]
## What type of issue is it?
Wrong documentation

## What article/section is this about?

https://docs.umbraco.com/umbraco-cms/tutorials/add-google-authentication#id-2.-integrating-google-auth-in-visual-studio
## Describe the issue

Docs mentions setting it up in Visual Studio, but this should not be Visual Studio specific.

It's "just" installing a Nuget package, so changing this to use console would be great so everyone can use it 😁

**Comment by alina-tincas** [comment]
Hi @Zeegaan thank you for bringing this to our attention 🙌 

We will take a look at it as soon as we can 😊

**Comment by alina-tincas** [comment]
Hi @Zeegaan a PR to "fix" this issue has been merged in https://github.com/umbraco/UmbracoDocs/pull/5983 so am closing this one! Thank you again for bringing this up 😊 💪 🙌
