### ISSUE TITLE
Update needed for the Configuring Azure Key Vault article

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#5861]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-cms/extending/key-vault 

## Describe the issue
It seems that the article uses the old `Program.cs` structure. I thinks it's a good idea to update the article. Something like this: 

Extension method:
```csharp
public static WebApplicationBuilder ConfigureKeyVault(this WebApplicationBuilder builder)
{
var keyVaultEndpoint = builder.Configuration["AzureKeyVaultEndpoint"];
if (!string.IsNullOrWhiteSpace(keyVaultEndpoint) && Uri.TryCreate(keyVaultEndpoint, UriKind.Absolute, out var validUri))
{
	builder.Configuration.AddAzureKeyVault(validUri, new DefaultAzureCredential());
}

return builder;
}
```

Pogram.cs:

```csharp
using Microsoft.AspNetCore.Builder;
using Project.Web.UI;
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Extensions;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.ConfigureKeyVault();

builder.CreateUmbracoBuilder()
    .AddBackOffice()
    .AddWebsite()
    .AddDeliveryApi()
    .AddComposers()
    .Build();

WebApplication app = builder.Build();

await app.BootUmbracoAsync();

...
```

**Comment by alina-tincas** [comment]
Hi @erikjanwestendorp thank you for bringing this to our attention! We currently have an issue open about this article here: https://github.com/umbraco/UmbracoDocs/issues/5787 so I was wondering if you can comment on that issue to keep it in one place until it is looked into? 😊

**Comment by erikjanwestendorp** [comment]
@alina-tincas Sorry, I should have checked first to see if there was already an issue. 🙈 Just created a PR:

https://github.com/umbraco/UmbracoDocs/pull/5862
