### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by lumimario** [umbraco/UmbracoDocs#5874]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
[(How to resolve collision errors)](https://docs.umbraco.com/umbraco-cloud/troubleshooting/deployments/structure-error)

## Describe the issue
This page has two broken links.
- One on: To do this, follow the steps described in the [schema deployment guide](https://github.com/umbraco/UmbracoDocs/blob/main/umbraco-cloud/deployment/deploy-operations/deploy-schema.md).

- and the other one on: 'You can find a full playlist about Collision errors on our [YouTube Channel](https://www.youtube.com/playlist?list=PLgX62vUaGZsHAKusJRjVyquIV47eJgjDq).'

**Comment by alina-tincas** [comment]
Hi @lumimario thank you for bringing this to our attention! 🙌 

Let´s take them one by one:
- One on: To do this, follow the steps described in the [schema deployment guide](https://github.com/umbraco/UmbracoDocs/blob/main/umbraco-cloud/deployment/deploy-operations/deploy-schema.md).

Here, the link that needs to be updated is https://docs.umbraco.com/umbraco-cloud/deployments/deploy-dashboard 

- and the other one on: 'You can find a full playlist about Collision errors on our [YouTube Channel](https://www.youtube.com/playlist?list=PLgX62vUaGZsHAKusJRjVyquIV47eJgjDq).'

This playlist does not exist anymore as it has been replaced with the video above this text, so this paragraph should be removed. 

With these said, I have made the necessary changes as described above. Thank you again for bringing this to our attention #h5YR 😊
