### ISSUE TITLE
Delivery API deprecated v1 routes

### ISSUE THREAD

**Issue by ak2426** [umbraco/UmbracoDocs#5877]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
<https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api>

## Describe the issue
Hi, some parts of this document have `/umbraco/delivery/api/v1` which is marked as deprecated in Swagger. Would also be nice to document the breaking changes on `v1` vs `v2`, if any. Thanks!

**Comment by alina-tincas** [comment]
Hi @ak2426, as you mention swagger, I believe in this case you are testing v14 where you have seen that v1 is deprecated?

**Comment by alina-tincas** [comment]
Hi @ak2426 👋 

Thank you for confirming! After further investigation it seems that this PR has been lost somehow and changes have not gone through on our documentation: https://github.com/umbraco/UmbracoDocs/pull/5626. This PR includes changes for content delivery API from v1 to v2 and other changes. I have re-added those changes in a new PR #5945 which is merged in, with confirmation that those changes are now on docs 👍 

I have asked one of our developers what are the breaking changes from v1 to v2 and got an answer that the significant change from v1 to v2 is how output expansion works. (this is also documented/changed in the docs)

For further information on other breaking changes for a new major version such as v13.0.0 they are documented here: https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading/version-specific#umbraco-13 

Additionally you can also visit the release notes for each version on https://our.umbraco.com/download/releases/1300.

As the issue has been resolved, I am closing this one. If you have any further questions, please let me know 😊 

Thank you again for brining this to our attention 🙌
