### ISSUE TITLE
Confusing Content Delivery API stats in 2024 telemetry document

### ISSUE THREAD

**Issue by liamlaverty** [umbraco/UmbracoDocs#5889]
## What type of issue is it?
Discussion / Clarification

## What article/section is this about?

https://docs.umbraco.com/sustainability-best-practices/telemetry/2024-02-telemetry

## Describe the issue

The page describes the _Content Delivery API_ being explicitly disabled on 27% of all reporting sites. The chart of _Active Versions_, further down the page shows that only ~22% of sites run on v12 or v13 - when the feature was introduced. As written, te article states that there are more Umbraco applications with Content Delivery API explicitly disabled than there are Umbraco applications running both v12 and v13 combined. 

**Snippet**:

> Another new feature is the [Content Delivery API](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api). We see this enabled on 6% of all projects. However, **we also see that 27% have disabled public access**. This number shouldn't be higher than the number of elements, as the Content Delivery API is disabled by default. A takeaway from this is that it is important to know that the Content Delivery API is disabled by default.

**Chart**:

![spaces_ZOU4fHcVxqYnC8V1dry6_uploads_git-blob-34ab6b2c6d63d0c17607924fc3b66c990dce2ffe_active-versions-2024](https://github.com/umbraco/UmbracoDocs/assets/7046713/1f3c0147-d3ff-45a8-9956-7c93cece39ef)

**Comment by lassefredslund** [comment]
@liamlaverty, I can understand the confusion, but there is a good explanation. The top part of the article is based on detailed telemetry, which we've collected from 9.5 and onwards whereas the bottom part with the active installations is based on basic telemetry, that has been collected since 8.10. So you can't link these two results.

**Comment by liamlaverty** [comment]
Thanks for the clarification @lassefredslund
