### ISSUE TITLE
Outdated information for ContentService Notifications

### ISSUE THREAD

**Issue by MMasey** [umbraco/UmbracoDocs#5947]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
[docs.umbraco.com/umbraco-cms/reference/notifications/contentservice-notifications](https://docs.umbraco.com/umbraco-cms/reference/notifications/contentservice-notifications)

## Describe the issue
The description documentation for some of the notification events refers to using the `raiseEvents` parameter if you need to suppress a specific notification. The Content Service not longer appears to have this parameter, for example doing something like `_contentService.Save(contentNode)`, doesn't have a `raiseEvents` parameter.

I'm not actually sure how you are meant to do this any more so can't update this documentation myself.

**Comment by MMasey** [comment]
I've just found an old post on our that suggest something like the following which works.

```
... // Some prior code to update the current content;

using var scope = _scopeProvider.CreateScope(autoComplete: true);
using var _ = scope.Notifications.Suppress();
_contentService.Save(content);
```

**Comment by alina-tincas** [comment]
Hi @MMasey thank you for bringing this to our attention! We will look into this as soon as we can 🙏 

Meanwhile, for reference, can you please share the link from OUR forum that you have found about this? 😊

**Comment by MMasey** [comment]
Hey @alina-tincas, this is the forum post. It's referring to the media service, but works the same when I tested it - https://our.umbraco.com/forum/using-umbraco-and-getting-started/110466-mediaservicesave-without-raising-events-umbraco-10#comment-342071

**Comment by alina-tincas** [comment]
Hi @MMasey I have created a PR #6022 to add the information about raiseEvents to the 3 services documentations as mentioned in my last comment. As the PR is merged, am closing this issue as well. Thank you again for bringing this to our attention 🙌
