### ISSUE TITLE
Oooops, something broke.. appears within documentation search results

### ISSUE THREAD

**Issue by rolorogan** [umbraco/UmbracoDocs#598]
The broken link page appears in the documentation search results (https://our.umbraco.org/documentation/). e.g. search for "link" 

This appears in the resultss - https://our.umbraco.org/Documentation/broken-link

**Comment by sofietoft** [comment]
Hi there, 
You have a really good point there!
The 'broken link' site shouldn't show up in the search results 🙈 

@nul800sebastiaan, could this be a task for you perhaps?

-Sofie

**Comment by sofietoft** [comment]
The _broken link_ page no longer appears in the search result! 👏
