### ISSUE TITLE
Info on article abort two factor authentication

### ISSUE THREAD

**Issue by estsan** [umbraco/UmbracoDocs#5986]
## What type of issue is it? (Choose one - delete the others)
Adding info on article

## What article/section is this about?
[Two Factor Authentication](https://docs.umbraco.com/umbraco-cms/reference/security/two-factor-authentication)

## Describe the issue
On Umbraco Cloud there is no login option with credentials, only to sign in with Umbraco ID. The 2FA build in the example above is not applicable on signing in with Umbraco ID and is thus redundant on Cloud. It is also only useful for users with access to the "Users" tab, since you can only enable your own 2FA and not anyone else, and this is done under the "Users" tab.

I suggest an info text on top of the article outlining this, and possible a link to the documentation outlining how to enable multi factor authentication for logging in to Backoffice via Umbraco ID. [MFA](https://docs.umbraco.com/umbraco-cloud/set-up/multi-factor-authentication-on-cloud)

**Comment by alina-tincas** [comment]
Hi @estsan, thank you for bringing this to our attention 🙌 

I have added an info text at the top of the page in this PR #5989 therefore am closing this issue 💪
