### ISSUE TITLE
Creating a Property Editor—Value Types Should Be Discussed

### ISSUE THREAD

**Issue by markadrake** [umbraco/UmbracoDocs#5998]
## What type of issue is it? (Choose one - delete the others)

Missing documentation

## What article/section is this about?

https://github.com/umbraco/UmbracoDocs/blob/main/13/umbraco-cms/tutorials/creating-a-property-editor/part-2.md

## Describe the issue

The walkthrough and code samples ignore the ValueTypes (String/Text/JSON/and more). It's not provided for the manifest nor the C# methods.

**Comment by alina-tincas** [comment]
Hi @markadrake thank you for bringing this to our attention! 🙏 

We will take a look into it as soon as we can.

**Comment by sofietoft** [comment]
Hi @markadrake !

I'm currently looking into this.
Are you experiencing any issues with the guide/tutorial based on the missing ValueTypes in the package.manifest / C# file?

When the ValueType is left out - like it is in the references tutorial here, it will default to a String.
See more about it here: https://docs.umbraco.com/umbraco-cms/v/13.latest-lts/extending/property-editors/package-manifest#editor 

Could it be, that that is the intention in this tutorial? 🤔 

Let me know what you think!

**Comment by sofietoft** [comment]
Hi @markadrake !

I haven't heart back from you in a while, so I'm taking the liberty to close this issue for now.
If you still believe this is an issue, please do not hesitate to reopen it and let me know how we can move forward!

I hope you understand.
Cheers!
