### ISSUE TITLE
Document Umbraco Forms options

### ISSUE THREAD

**Issue by sussexrick** [umbraco/UmbracoDocs#600]
On this page: https://our.umbraco.org/documentation/Add-ons/UmbracoForms/Developer/Configuration/

1. The configuration values need to be documented. 
2. The documentation for `EnableAntiForgeryToken` says it's not there by default but, in Forms 6.0.5, it is. I can't update the doc as I don't know at what point that changed.

**Comment by sofietoft** [comment]
Closing this issue, as Warren has added a bunch of configuration options to the article: https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Configuration/
