### ISSUE TITLE
Update needed for the field types article (Umbraco Forms)

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#6000]
## What type of issue is it?
Wrong documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-forms/developer/field-types 

## Describe the issue
The article still refers to the umbracoforms.config file. I think this is now possible with the help of an app settings. See also the example below:

```json
    "Forms": {
      "FieldTypes": {
        "DatePicker": {
          "DatePickerYearRange": 12
        }
      }
    }
```

**Comment by alina-tincas** [comment]
Hi @erikjanwestendorp thank you for bringing this to our attention! 🙌 

We will look into it as soon as we can 😊

**Comment by jonat123** [comment]
@erikjanwestendorp Thanks for bringing this to our attention!

You are indeed correct that this is done in the appsettings.json file and not in the umbracoforms.config as it does not exist in v10+ as described in the [Configuration](https://docs.umbraco.com/umbraco-forms/developer/configuration) docs 😄

I will updated the documentation accordingly 😊

**Comment by jonat123** [comment]
@erikjanwestendorp The PR #6015 will fix this issue 😄

**Comment by erikjanwestendorp** [comment]
@jonat123 Awesome thanks! 😄
