### ISSUE TITLE
Broken link - Content Delivery API - property expansion

### ISSUE THREAD

**Issue by kristofferwebmind** [umbraco/UmbracoDocs#6001]
## What type of issue is it?
Missing documentation

## What article/section is this about?
Link 1: https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#property-expansion-and-limiting
Link 2: https://github.com/umbraco/UmbracoDocs/blob/main/13/umbraco-cms/reference/content-delivery-api/property-expansion-and-limiting/README.md

## Describe the issue
Link 1 above refers to Link 2 for an in-depth explanation of the feature. Link 2 links to a github readme.md that doesn't exist on that path

![image](https://github.com/umbraco/UmbracoDocs/assets/143802330/bc77b7bf-063c-4aa0-9886-120a960babfe)
![image](https://github.com/umbraco/UmbracoDocs/assets/143802330/9f099010-fd7b-4ce5-9327-5fea97d79748)

**Comment by alina-tincas** [comment]
Hi @kristofferwebmind thank you for bringing this to our attention 🙌 

I have created a PR to resolve this issue in #6002 and as it has been merged in, I am closing this one😊
