### ISSUE TITLE
LTS 13, docs dont reflect the correct template

### ISSUE THREAD

**Issue by fasteddys** [umbraco/UmbracoDocs#6009]
help Umbraco does not show up per the documentation on the LTS 13 site

![image](https://github.com/umbraco/UmbracoDocs/assets/96149622/8c3106d3-27b1-4542-8572-be4dcc7b129a)

https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/visual-studio

**Comment by alina-tincas** [comment]
Hi @fasteddys! 👋 

That seems quite interesting! Can you please confirm if you have followed the Prerequisites: https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/visual-studio#prerequisites and installed the Umbraco dotnet templates? 

By installing the templates you will then have the option to create an Umbraco project via Visual Studio:
![image](https://github.com/umbraco/UmbracoDocs/assets/83591955/1cf32465-63ab-4b96-8ad3-8aa2f24205a8)

There is also a good video showcasing how to get started, I was wondering if you have had a chance to look into it as well? https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/visual-studio#video-tutorial 

Looking forward to hearing back from you soon! 😊

**Comment by alina-tincas** [comment]
Am glad to hear you have been able to find the issue and resolve it #h5YR 😊
