### ISSUE TITLE
Backoffice Tour Step Object Missing Property

### ISSUE THREAD

**Issue by nobledm** [umbraco/UmbracoDocs#6038]
## What type of issue is it?
Missing documentation

## What article/section is this about?
[(Backoffice Tours)](https://docs.umbraco.com/umbraco-cms/extending/backoffice-tours#tour-file-locations)

## Describe the issue
The Step Object is missing the **skipStepIfVisible** property.

Not sure all the versions it is relevant to, but I started a branch with updates for v13 where I can confirm this is an undocumented functioning property. I'm happy to make the updates on any other doc versions and put in a PR if anyone can let me know which it all applies to <3

Or if preferred I can supply the couple of line additions here for Umbraco to edit to their liking :3

**Comment by alina-tincas** [comment]
Hi @nobledm thank you for bringing this to our attention 🙌 

You are more than welcome to create a PR and then we can take it from there 👍 😊
