### ISSUE TITLE
Wrong documentation - Color Picker - Add values programmatically

### ISSUE THREAD

**Issue by jcrittenden** [umbraco/UmbracoDocs#6088]
Wrong documentation

Color Picker - Add values programmatically
https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/color-picker#add-values-programmatically

Although the documentation's version partially works, values are not store correctly.
Documentation example:
content.SetValue("color", "38761d");

Real world example of what it should be, that actually sets the PickedColor properly:
node.SetValue("color", "{ \"value\": \"000000\",\"label\": \"Black\",\"sortOrder\": 1,\"id\": \"1\"}");

**Comment by jonat123** [comment]
@jcrittenden Thanks for creating this issue 😊

Thanks for including an example of how it should look like the code.

Would you be up for updating the page yourself with the working example? 😄

Otherwise, I will add it to our backlog to have a look at updating it 😊

**Comment by jcrittenden** [comment]
@jonat123 I see my confusion now. The example is based on the "Include labels?" toggle being off on the Umbraco.ColorPicker. So, the current example is in-fact valid. 

Perhaps, we add a secondary example when "Include labels?" is on. When the toggle is on, values are then store as JSON, like my example.

**Comment by jonat123** [comment]
@jcrittenden You are more than welcome to send a PR our way, adding a secondary example, and then we will take a look at it 😄
