### ISSUE TITLE
Wrong documentation in Integrating services with a property editor - missing button click action

### ISSUE THREAD

**Issue by Ahmed-Adel3** [umbraco/UmbracoDocs#6098]
## What type of issue is it? (Choose one - delete the others)

**Type :**  Missing documentation

## What article/section is this about?
[(link here)](https://github.com/umbraco/UmbracoDocs/blob/main/13/umbraco-cms/tutorials/creating-a-property-editor/part-3.md)

## Describe the issue
As mentioned in the last section of the documentation, the alert should be triggered by field change or button click, but button click trigger was missing in the code.

On applying the documentation, we found out that the `getNotification` is not triggered on `getSuggestions`.

![image](https://github.com/umbraco/UmbracoDocs/assets/30068146/e4c4c5bb-d6d0-4d44-8e31-499423a64714)

**Comment by eshanrnh** [comment]
Thanks, @Ahmed-Adel3 for raising this issue and creating a PR. We appreciate your efforts. 🙌

We will take a look at the PR as soon as possible. 🙂
