### ISSUE TITLE
Umbraco CMS Build Documentation has an issue with the command related to "git submodule update" command

### ISSUE THREAD

**Issue by BuddhiEash** [umbraco/UmbracoDocs#6142]
## What type of issue is it? 
Other (the existing command should be updated)

## What article/section is this about?
[https://github.com/umbraco/Umbraco-CMS/blob/41dddee620bc7a7c5c26d15550ee5f11111bf45c/.github/BUILD.md#getting-started](url)

## Describe the issue
It asks to "Execute `git submodule init` and then `git submodule update` to get the files into Umbraco.Web.UI.Client project"

`git submodule update` command doesn't clone the submodule properly if an older version of git is installed.

Tried with git version 2.32.0.windows.2

![Screenshot 2024-05-31 115849](https://github.com/umbraco/UmbracoDocs/assets/3594697/0650e3d6-5e97-473d-a698-a67c1435179e)

`git submodule update --init` works with any of the git versions whether it's older or the latest version.

Suggesting to update the line as below:

"Execute `git submodule init` and then `git submodule update --init` to get the files into Umbraco.Web.UI.Client project"

If this verified as an issue, I can contribute the change to the documentation.

**Comment by alina-tincas** [comment]
Hi @BuddhiEash thank you for raising this issue! As far as I can see this is related to the CMS repository rather than the Umbraco Documentation repository. Can you please raise this issue in the CMS repository https://github.com/umbraco/Umbraco-CMS/issues so the right department can help out with this issue in this case? 🙏

**Comment by BuddhiEash** [comment]
Hi @alina-tincas thanks for replying, and thanks for directing me to the correct space to post the issue.
Sorry for posting the issue in the wrong space.
I just now created the issue in the CMS repository - [https://github.com/umbraco/Umbraco-CMS/issues/16526](url)

**Comment by alina-tincas** [comment]
No worries @BuddhiEash 😊 As you have created the issue in the right place, then am closing this one 👍 

Have a nice weekend!
