### ISSUE TITLE
UseInstallerEndpoints() does not exist in v14, yet is referenced in the documentation

### ISSUE THREAD

**Issue by jakob-bagterp** [umbraco/UmbracoDocs#6151]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-cms/reference/security/ssl-https

## Describe the issue
The endpoint configuration `UseInstallerEndpoints()` that was used in earlier versions of Umbraco is mentioned in the documentation...

<img width="720" alt="Screenshot 2024-06-04 at 11 28 15" src="https://github.com/umbraco/UmbracoDocs/assets/25110864/d06ae2c7-5928-4d91-9f00-f965f335d1ba">

... yet when trying to run Umbraco with a similar implementation and executing `dotnet run`, it throws an error:

> error CS1061: 'IUmbracoEndpointBuilderContext' does not contain a definition for 'UseInstallerEndpoints' and no accessible extension method 'UseInstallerEndpoints' accepting a first argument of type 'IUmbracoEndpointBuilderContext' could be found (are you missing a using directive or an assembly reference?)

What should you use instead? Or maybe simply delete `UseInstallerEndpoints()` from the startup?

**Comment by jonat123** [comment]
@jakob-bagterp Thanks for creating this issue 😊

That is a good catch!

`u.UseInstallerEndpoints();` has indeed been removed in Umbraco 14.

You should just remove it from your `program.cs `file, then you should be able to run your project 😄

I will create a PR to remove it from the v14 documentation 😄

**Comment by jonat123** [comment]
#6155 Fixes this 😄
