### ISSUE TITLE
Remove instructions to 'right click' nodes in the tree to open menus and perform actions in V14

### ISSUE THREAD

**Issue by marcemarc** [umbraco/UmbracoDocs#6156]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?

Most articles that refer to using the action menus available from content/media/member trees.
The best way to find them is to search for the term 'right click' in the V14 docs

![image](https://github.com/umbraco/UmbracoDocs/assets/260802/97bfbf1b-8b7f-41f5-91fe-78fb63df7dcc)

eg here we've updated the document screenshots:

https://docs.umbraco.com/umbraco-cms/fundamentals/data/members#creating-a-member

but kept the V13 instruction in the text to be 'Go to the Settings section, right-click Member Types and select Create.' 

## Describe the issue

With Umbraco 14 - we've removed the ability for editors and implementers to right click items listed in the current tree (quite rightly! - https://github.com/umbraco/Umbraco-CMS/issues/16233)  to perform actions or open context menus, but in the documentation for V14, when explaining how Umbraco works, we still use language which instructs people to right click, and we need to tell people about using the ... and + icons instead.

**Comment by jonat123** [comment]
@marcemarc Thanks for opening this issue! 😄

That is right and seems to be an oversight from our side, not to remove that you can't right-click anymore 🙈

I will create a task in our backlog to remove the mention of using right-click to access menus in our documentation 😊

**Comment by sofietoft** [comment]
Hi @marcemarc !
Long time to see 😄 Hope you're doing good!

I wanted to let you know that we've just merged a PR this morning, which removes the mention of right-clicking: https://github.com/umbraco/UmbracoDocs/pull/6184 

Hopefully we caught them all 🤞 

With that, I'll close this issue!
Cheers 🎉
