### ISSUE TITLE
Missing Doctype in new template

### ISSUE THREAD

**Issue by deanleigh** [umbraco/UmbracoDocs#6157]
## What article/section is this about?
[Creating a Master Template](https://github.com/umbraco/UmbracoDocs/blob/main/14/umbraco-cms/tutorials/creating-a-basic-website/creating-master-template-part-1.md)

## Describe the issue
Points 4 and 6 incorrectly leave the doctype in the homepage template where it should be moved to the master template

**Comment by jonat123** [comment]
Hello @deanleigh thanks for creating this issue 😄

I can also see that you have created a few more issues related to this tutorial.

Would you be up for updating the tutorial? 

Otherwise, we will add a task in our backlog to have a look at updating it 😊

**Comment by deanleigh** [comment]
I would but some of it is in the screenshots and I am not sure if you would be happy with those being updated?
If so it would most likely be after CodeGarden.

**Comment by jonat123** [comment]
@deanleigh If the screenshots do not look correct, you are more than welcome to update them 😄
