### ISSUE TITLE
Typo in instructions

### ISSUE THREAD

**Issue by deanleigh** [umbraco/UmbracoDocs#6158]
## What article/section is this about?
[Setting the Navigation Menu](https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-basic-website/setting-the-navigation-menu)

## Describe the issue
The `<ul>` tag needs to be wrapped inside the `<class>` and `<nav>` tags,
should say
The `<ul>` tag needs to be wrapped inside the `<div class="container">` and `<nav>` tags,

**Comment by eshanrnh** [comment]
Thanks for bringing this issue to our attention, @deanleigh 💪

If you have some time and would like to contribute further, we encourage you to create a Pull Request (PR) with the necessary changes. If not, no worries at all 🙂 

We will prioritize this issue and address it as soon as we have some time.
