### ISSUE TITLE
Install instructions for v13 (and older versions) will install v14 instead

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/UmbracoDocs#6160]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-cms/v/13.latest-lts/fundamentals/setup/install

## Describe the issue
The fix is easy enough: instead of `dotnet new install Umbraco.Templates` you can change it to `dotnet new install Umbraco.Templates::13.*` which installs the latest available v13.

Would love to see that updated for the other older version as well please! Thanks in advance!

**Comment by jonat123** [comment]
@nul800sebastiaan Thanks for opening this issue!

That makes sense, that it should be changed for all older versions 🙈

I will create a task in our backlog to update this to be correct 😄

**Comment by nul800sebastiaan** [comment]
Thanks @jonat123! 🎉
