### ISSUE TITLE
Clearer and best practice instructions 

### ISSUE THREAD

**Issue by deanleigh** [umbraco/UmbracoDocs#6162]
## Wrong documentation
In Articles and Article Items item 21 swapping the code from the example.
Needs to be clearer to remove the `<ul>` as well as the `<li>` code.

Also the example using Read More is considered poor UX and Accessibility.
We should not be encouraging this bad practice pattern.

## What article/section is this about?
[Articles and Article Items](https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items#updating-the-template)

**Comment by eshanrnh** [comment]
Hi @deanleigh,

Thank you for pointing out the issues with the article. We'll make the necessary changes to clarify the removal of both <ul> and <li> tags and update the example to promote better UX and Accessibility standards.

Thank you again for your valuable feedback. If you have any further suggestions or would like to contribute directly, we welcome your input or a Pull Request (PR).
