### ISSUE TITLE
"umbracoInternalRedirectId" property adding a trailing slash before rendering it in the breadcrumb. 

### ISSUE THREAD

**Issue by The-algar** [umbraco/UmbracoDocs#6167]
## What type of issue is it? (Choose one - delete the others)

Bug ? trailing slash from each URL with "umbracoInternalRedirectId" property

## What article/section is this about?
[(link here)](https://github.com/umbraco/UmbracoDocs/blob/main/14/umbraco-cms/reference/routing/routing-properties.md)

## Describe the issue
Why the "umbracoInternalRedirectId" property is adding a trailing slash at the end of the target link? This is breaking the target page design when this property is called from the Umbraco Breadcrumb
Is there any way to avoid this?

FYI I used trimEnd in the breadcrumb (a href="@item.Url().TrimEnd('/')") but I shouldn't have to do this

the back office screen
![image](https://github.com/umbraco/UmbracoDocs/assets/33525561/d1f7aa1b-79e5-40b8-ad73-7afa7184999b)

The result with the /
![image](https://github.com/umbraco/UmbracoDocs/assets/33525561/1b58285b-b53d-4474-a543-483bf021425d)

The result without the /
![image](https://github.com/umbraco/UmbracoDocs/assets/33525561/a586fd5b-51fe-49d1-ad6b-90f0dcbb09ec)

**Comment by sofietoft** [comment]
Hi there @The-algar !

Thanks for reporting this.
I'm afraid this falls a bit outside the docs category, and lands more in the support department..
I'd suggest that you reach out in the [Umbraco Forums](https://our.umbraco.com/forum/), where you'll meet a bunch of great people that'll be able to help you out!

If there is indeed something wrong in the documentation, please let us know, and we'll of course be taking a look at it! 💪
