### ISSUE TITLE
crosssitescriptingprotection is still using startup file

### ISSUE THREAD

**Issue by SSmale** [umbraco/UmbracoDocs#6204]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
13/umbraco-cms/extending/health-check/guides/crosssitescriptingprotection.md

## Describe the issue
This is still using the the startup.cs file which is not present in v13 or 14

**Comment by sofietoft** [comment]
Thanks for reporting this @SSmale ! 💪 

I'll make sure we have someone look at it as soon as possible!
