### ISSUE TITLE
YouTube video for Member Property Types inaccessible

### ISSUE THREAD

**Issue by chrisrandledev** [umbraco/UmbracoDocs#6263]
## What type of issue is it? (Choose one - delete the others)
Discussion
Missing documentation
**Wrong documentation**
Other (write it here)

## What article/section is this about?
([link here](https://docs.umbraco.com/umbraco-cms/fundamentals/data/members#references))

## Describe the issue
There are links to various other videos, hosted on YouTube.  One of them is non-public so it cannot be viewed, making the link effectively dead.  

![image](https://github.com/user-attachments/assets/d1bb208a-69b9-4681-81fe-66369315cf34)

The link says **Video: Member types properties** and links to https://www.youtube.com/watch?v=_aMZJWxdNHg but clicking it results in the following screens.  

![image](https://github.com/user-attachments/assets/b8cc00e0-92b5-4998-96ae-76efdd4e7630)

This above is shown is the visitor is logged in to YouTube - using Chrome 126.0.6478.127 (Official Build) (64-bit). The following page is shown when the visitor is not logged in to YouTube - using Firefox 127.0.2 (64-bit).

![image](https://github.com/user-attachments/assets/e1ac16fb-519d-4186-b67c-8935a297b81e)

## Proposed Fix
* Fix 1 - the owner needs to login to the YouTube dashboard, and change the permissions for that video.
* Fix 2 - paste a link to a visible video
* Fix 3 - prevent this happening again by using a Link Checker / Analyzer framework to follow all links in the docs - such as (headless) Selenium - and check the resultant page for "This is a private video. Please sign in to verify that you may see it." (for unauthenticated / anonymous, unauthorised viewers) and/or "This video is private" (for authenticated, unauthorised viewers).

**Comment by eshanrnh** [comment]
Thanks for bringing the broken link to our attention, @chrisrandledev. I've fixed it, and you should now be able to view the video. 💪
