### ISSUE TITLE
Add CSP to health checks article 

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/UmbracoDocs#6336]
## What type of issue is it?
Missing documentation

## What article/section is this about?
(https://docs.umbraco.com/umbraco-cms/extending/health-check/guides)

## Describe the issue
It would be nice to add an article about the CSP health check (When https://github.com/umbraco/Umbraco-CMS/pull/16830 is merged). See comment: https://github.com/umbraco/Umbraco-CMS/pull/16830#discussion_r1711382372

**Comment by sofietoft** [comment]
Thanks for adding this issue, so we wont forget that this indeed needs to be documented when it's released 🤩 💪
