### ISSUE TITLE
Update "Setup Your Site to use Azure Storage for Media" 

### ISSUE THREAD

**Issue by Jeavon** [umbraco/UmbracoDocs#634]
The security.config example is outdated and needs to be updated to use the container setting

**Comment by ed-parry** [comment]
@Jeavon Happy to PR for this one if you're not looking at it? From what I can see from recently implementing this process, the `Container` is missing from `security.config` as you said, and `CachedCDNTimeout` and `UseCachedContainerInUrl` from `cache.config`?

**Comment by Jeavon** [comment]
@ed-parry yes, that's exactly it. If you want to send in a PR I would love to see it :)

**Comment by ed-parry** [comment]
There you go, @Jeavon! Added in the missing items and updated Azure-based URLs to recommend HTTPS by default (though made an assumption sites on the umbraco.io domain pick up HTTPS by default?)

Also set `UseCachedContainerInUrl` to `false` by default, as the latest [ImageProcessing docs](http://imageprocessor.org/imageprocessor-web/plugins/azure-blob-cache/) suggest newer Azure formats require that. Though we're using a couple of implementation currently with that set to `true` without issue, so you're probably in the best place to confirm it either way.
