### ISSUE TITLE
Creating a Custom UFM Block Label - missing import statements

### ISSUE THREAD

**Issue by nackler** [umbraco/UmbracoDocs#6374]
## What type of issue is it? 
Missing documentation

## What article/section is this about?
[(https://docs.umbraco.com/umbraco-cms/reference/umbraco-flavored-markdown)](https://docs.umbraco.com/umbraco-cms/reference/umbraco-flavored-markdown)

## Describe the issue
When following along with the doc mentioned above, the .ts file example is missing the 'import' section. This results in two compilation errors -- one for "Tokens" and the other for "UmbUfmComponentBase"

I believe the "Tokens" class uses the following import
import { Tokens } from '@umbraco-cms/backoffice/external/marked';

However the other unfound class, "UmbUfmComponentBase," might not be exported as part of any modules in @umbraco-cms/backoffice, in which case perhaps we need to open a feature request in that project if the intent was for this example to be possible. Please help confirm.

**Comment by sofietoft** [comment]
Thanks for raising this issue, @sofietoft ! 💪 

I'll make sure we take a look at it as soon as possible.

**Comment by leekelleher** [comment]
@nackler You're correct, the `UmbUfmComponentBase` type wasn't being exported, that's an oversight, apologies for this.
We'll fix this for the next release, (PR https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2243).

@sofietoft I'll update the documentation accordingly. This will be scheduled for v14.3.0-RC release.

**Comment by sofietoft** [comment]
A PR fixing this has been merged with the release of Umbraco 14.3 RC 🎉 

I'll consider this issue closed.
