### ISSUE TITLE
Document the appSetting: umbracoDisableElectionForSingleServer and it's role in flexible load balancing

### ISSUE THREAD

**Issue by marcemarc** [umbraco/UmbracoDocs#639]
We should document this setting and how it affects flexible load balancing:

               //by default we'll use the db server registrar unless the developer has the legacy
            // dist calls enabled, in which case we'll use the config server registrar
            if (UmbracoConfig.For.UmbracoSettings().DistributedCall.Enabled)
            {
                ServerRegistrarResolver.Current = new ServerRegistrarResolver(new ConfigServerRegistrar());
            }
            else if ("true".InvariantEquals(ConfigurationManager.AppSettings["umbracoDisableElectionForSingleServer"]))
            {
                ServerRegistrarResolver.Current = new ServerRegistrarResolver(new SingleServerRegistrar());
            }
            else
            {
                ServerRegistrarResolver.Current = new ServerRegistrarResolver(
                    new DatabaseServerRegistrar(
                        new Lazy<IServerRegistrationService>(() => ApplicationContext.Services.ServerRegistrationService),
                        new DatabaseServerRegistrarOptions()));
            }

So essentially if the setting is set to true, the server won't register itself in the pool of Servers for flexible load balancing, but it's a bit obscure because people won't see 'Election' to be something related to Server Role assignment...

Perhaps too if we have a Troubleshooting Flexible Load Balancing section just confirming

1) Distributed Calls Off
2) umbracoDisableElectionForSingleServer - false
3) umbracoApplicationUrl set and resolvable by all servers... 
etc

**Comment by Shazwazza** [comment]
There's a whole topic in the docs about election here: https://our.umbraco.org/documentation/Getting-Started/Setup/Server-Setup/load-balancing/flexible#scheduling-and-master-election

Enabling this setting simply means that any election will be disabled. We use this on Umbraco Cloud since we are certain there is no load balancing taking place. This can slightly improve startup performance since no DB calls are needed.

**Comment by marcemarc** [comment]
@Shazwazza Yes, that is the page I was going to add it on, helped a client today, who couldn't get flexible load balancing to work, they had that setting, set to true in the web.config, in fact, the site 'used' to be hosted on Umbraco Cloud, which probably explains why it was there. So I think important to mention the setting, somewhere in the docs, and within the context of this page,  and I was thinking it will usually be within the context of troubleshooting... the text on this page is very informative but very dense to read through, if you are trying to work out what you have done wrong... so a quick troubleshooting checklist may help here!

**Comment by Shazwazza** [comment]
Ah i see what you are saying. Yup it's dense reading but i guess there's a lot to know :) 

A troublshooting guide could be pretty good, we could potentially combine that with the FAQ list that was started too (which isn't to discoverable either) https://our.umbraco.org/documentation/Getting-Started/Setup/Server-Setup/load-balancing/#faqs

**Comment by marcemarc** [comment]
Yes, I'd like to tie it in with this too: http://issues.umbraco.org/issue/U4-10955 there are lots of small subtle variations in the different configuration scenarios, so having something to keep your sanity, "I did actually change that setting..." etc - and get people used to the language of  master/slave/single etc to reflect the info here.
