### ISSUE TITLE
Forms docs for v14 still contains macro-examples

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/UmbracoDocs#6443]
## What type of issue is it? (Choose one - delete the others)
This article still contains code samples using macros:

https://github.com/umbraco/UmbracoDocs/blob/main/14/umbraco-forms/developer/themes.md

**Comment by sofietoft** [comment]
Thanks for reporting this @enkelmedia ! 🙌 

I'll make sure we look into getting this resolved.

**Comment by sofietoft** [comment]
We have removed the mentions of macros from the Forms article 💪
