### ISSUE TITLE
Version number has disappeared from the Documentation Dropdown.

### ISSUE THREAD

**Issue by marcloveUSN** [umbraco/UmbracoDocs#6453]
Version number has disappeared from the Documentation Dropdown.

![docs](https://github.com/user-attachments/assets/a205865a-f9a5-4108-8fa2-125008b28543)

**Comment by sofietoft** [comment]
Thanks for letting us know @marcloveUSN ! 🙌 

I'll look into this right away.

**Comment by sofietoft** [comment]
This has now been resolved.
I'll close the issue.
