### ISSUE TITLE
Add article descriptions

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#6465]
# Hacktoberfest 2024

**The tasks in this issue in intended for [Hacktoberfest contributions](https://hacktoberfest.com/).
Hacktoberfest starts on October 1st.**

## All articles need to have a proper description

A description is a one-liner that will be displayed directly below the titles of the article.
This description also acts as the _meta description_ used for SEO.

A good description will

- Describe what the article covers
- Be no longer than 156 characters (1 - max 2 - short sentences)
- Include keywords relevant to the content of the article

### How to add a description

Adding a description requires adding some YAML to the top of the article.
Use the example below as a reference:

```
---
description: Health Checks are used to determine the state of your Umbraco project. Learn more about each of them in this section.
---
```

### Where to start

Many articles in the Umbraco Documentation are missing a description, but here's a list to help you get started.

* [x] [Health Check: ClickJacking Protection](https://docs.umbraco.com/umbraco-cms/extending/health-check/guides/clickjackingprotection)
* [x] [Health check: CSP](https://docs.umbraco.com/umbraco-cms/extending/health-check/guides/contentsecuritypolicy)
* [x] [Health Check: Content/MIME sniffing protection](https://docs.umbraco.com/umbraco-cms/extending/health-check/guides/contentsniffingprotection)
* [x] [Health Check: Debug Compilation Mode](https://docs.umbraco.com/umbraco-cms/extending/health-check/guides/debugcompilationmode)
* [x] [Cookies](https://docs.umbraco.com/umbraco-cms/reference/security/cookies)
* [x] [Replacing the basic username/password check](https://docs.umbraco.com/umbraco-cms/reference/security/custom-password-check)
* [x] [Locking of Users and password reset](https://docs.umbraco.com/umbraco-cms/reference/security/password-reset)
* [x] [Umbraco Security Hardening](https://docs.umbraco.com/umbraco-cms/reference/security/security-hardening)
* [x] [Language Variation](https://docs.umbraco.com/umbraco-cms/reference/language-variation)

Other places to look for missing descriptions:

* [Umbraco Cloud Project Settings docs](https://docs.umbraco.com/umbraco-cloud/set-up/project-settings)
* [Umbraco Forms Developer docs](https://docs.umbraco.com/umbraco-forms/developer)
* [Umbraco Forms Editor docs](https://docs.umbraco.com/umbraco-forms/editor)

**Comment by SamTimalsina-ST** [comment]
@sofietoft  Has this been done? I would love to contribute

**Comment by sofietoft** [comment]
> @sofietoft Has this been done? I would love to contribute

Hi! How wonderful to hear that you want to contribute!! 🙌 
Only a couple, I think 4, from the list, have already been fixed, so there is still lots more to do 😁 

If you could wait juuuuust a few more days, I'd suggest you join [Hacktoberfest](https://hacktoberfest.com/), which starts on October 1st.
It's this month-long celebration of open source, where you can get recognized and also (I believe) get a Tshirt for submitting a number of PR to open source products 😎 

I'll add a little note to the Issue, to let people know this is intended for Hacktoberfest contributions!

I look forward to reviewing your contributions 😄

**Comment by SamTimalsina-ST** [comment]
Hi! Thanks for the suggestion!😊, I have joined Hacktoberfest and im excited 🎉 I’ll definitely wait and get involved when it starts

**Comment by sofietoft** [comment]
That's great to hear @Iqmaa ! 😄 
Please let me know in a comment if you're picking up some of the articles in the list, otherwise, feel free to make the PRs and I'll make sure we get them reviewed.

You can find contribution docs here: https://docs.umbraco.com/contributing/documentation/getting-started 

Let me know if something isn't clear!
Happy writing 💪

**Comment by Iqmaa** [comment]
Thanks @sofietoft !
I'll like to take the article 'Locking of users and password reset', 'Umbraco Security Hardening' and 'Cookies'

**Comment by Iqmaa** [comment]
Hi @sofietoft , I've sent in a pull request.
Please review it when you can.

**Comment by ovindu-a** [comment]
Hi @sofietoft, can I work on this as well?

**Comment by sofietoft** [comment]
> Hi @sofietoft, can I work on this as well?

For sure @ovindu-a ! 💪 
Let me know which articles from the list (not many left though 😅 ), or identify missing descriptions in one of the sections I've mentioned.

**Comment by ovindu-a** [comment]
@sofietoft I must add the descriptions for the documentation on v14 right?

**Comment by sofietoft** [comment]
Yes, please do that @ovindu-a !
You're welcome to add the description to 10 and 13 as well - but not a requirement!

**Comment by ovindu-a** [comment]
I have made a PR @sofietoft. Will add them for 10 and 13 once it gets approved.

**Comment by Iqmaa** [comment]
Hi @sofietoft I've found missing descriptions in [Umbraco Forms Developer Docs](https://docs.umbraco.com/umbraco-forms/developer) on the pages _prepping-frontend_ and _rendering-scripts_.

Please assign them to me

**Comment by sofietoft** [comment]
> Hi @sofietoft I've found missing descriptions in [Umbraco Forms Developer Docs](https://docs.umbraco.com/umbraco-forms/developer) on the pages _prepping-frontend_ and _rendering-scripts_.
> 
> Please assign them to me

Go right ahead @ovindu-a ! 💪

**Comment by Iqmaa** [comment]
> > Hi @sofietoft I've found missing descriptions in [Umbraco Forms Developer Docs](https://docs.umbraco.com/umbraco-forms/developer) on the pages _prepping-frontend_ and _rendering-scripts_.
> > Please assign them to me
> 
> Go right ahead @ovindu-a ! 💪

Thanks !
I'm Iqma though
