### ISSUE TITLE
Migrate from Vendr to Umbraco Commerce minimum version required

### ISSUE THREAD

**Issue by Lantzify** [umbraco/UmbracoDocs#6478]
## What type of issue is it? (Choose one - delete the others)
Discussion

## What article/section is this about?
[(Migrate from Vendr to Umbraco Commerce)](https://docs.umbraco.com/umbraco-commerce/upgrading/migrate-from-vendr-to-umbraco-commerce)

## Describe the issue
I recently tried to migrate Vendr 1.8.6 to Umbraco Commerce. But that didn't work to well. It wasn't until I upgraded to Vendr 3.0.0 that I got the migration guide to work.

Could we add some sort of "minimum Vendr version required".

**Comment by sofietoft** [comment]
Thanks for flagging this @Lantzify ! 🙌 

I'll bring it to our Commerce experts, to confirm our recommendations on this!
