### ISSUE TITLE
Collection (formerly ListView) Article for v14+ needs updated terminology

### ISSUE THREAD

**Issue by loranallensmith** [umbraco/UmbracoDocs#6553]
## What type of issue is it?
Wrong documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/listview

## Describe the issue
While I was working on umbraco/Umbraco-CMS#17230 for Hacktoberfest, I discovered that the documentation for the Collection property type needs updating to make sure it uses the terminology for current versions of Umbraco.  If I understand correctly, the mentions of ListView should be changed to Collection and references to Content App should be changed to Workspace View.

If it's helpful as a point of reference, I've updated the Backoffice elements in umbraco/Umbraco.CMS.Backoffice#2452.  I'm not too committed to any specific verbiage, so I'm happy to update my PR there with different text if it helps ensure all of these bits and pieces are consistent.  😄 

I _think_ the change from List View to Collection happened as of v14, but I'm not 100-percent certain.  🤔 

I would love to submit a PR for this as part of my work on the issue above, but I don't know if I will have an opportunity.  With that in mind, I thought I would create this issue in case anyone participating in Hacktoberfest had a chance to snag it.  😄

**Comment by sofietoft** [comment]
Thanks for reporting this @loranallensmith !

The change to these new names indeed happened in Umbraco 14, and you are correct that this has not been updated consistently throughout the docs.

I'll put some labels on it 🙌

**Comment by caronvincent** [comment]
I would like to work on this issue if it's still up for grabs.

**Comment by sofietoft** [comment]
It is still up for grabs @caronvincent 👏 😄
