### ISSUE TITLE
Clarification of CI/CD limitations needed

### ISSUE THREAD

**Issue by kristofferwebmind** [umbraco/UmbracoDocs#6663]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
[(link here)](https://github.com/umbraco/UmbracoDocs/blob/main/umbraco-cloud/set-up/project-settings/umbraco-cicd/KnownLimitationsAndConsiderations.md)

"Back Office Limitations

To ensure smooth execution of the Umbraco CI/CD Flow, it is highly recommended to adhere to a specific principle: refrain from making any alterations to the schema, except in the leftmost environment within the Umbraco Cloud back offices. The intention behind this principle is to prevent conflicts that could potentially arise due to simultaneous modifications made in different environments."

## Describe the issue

The above text can be read as if the principle is to make schema changes directly in the backoffice of the cloud environment. The sentence "in the leftmost environment _within the Umbraco Cloud back offices_" is wrongfully stating that the environment in question is an environment on Umbraco Cloud when the leftmost environment in question where the schema changes should be made actually equates to the developer's local environment.

**Comment by sofietoft** [comment]
Hmmmm! VERY good point @kristofferwebmind !

Let me talk to those who wrote this guide. They should be able to provide us some more insight on this - hopefully 😁 
I'll get back to you!

**Comment by sofietoft** [comment]
Alright, I've had a chat with Alina who wrote parts of these CI/CD docs, and we came up with a new rewrite:

> Workflow considerations
> 
> To ensure smooth execution of the CI/CD Flow, it is recommended to make schema changes in the [leftmost environment](link to deployment workflow article). Ideally, this means the local development environment. Schema changes include changes made to Document Types, Data Types, Templates, and the like. The intention behind this principle is to prevent conflicts that could potentially arise due to simultaneous modifications made in different environments.

To add some more context to it:
The section was added because not many people are actually aware of the "left to right" deployment approach on Cloud 🙈 the support team often need to help people out of messes because of this, so that is why this "limitation" was mentioned in this context as well 😅

**Comment by kristofferwebmind** [comment]
Nice! :) Well done! #H5YR

**Comment by sofietoft** [comment]
I've made a PR with the changes.
Thanks again for highlighting this and helping us making sure the Docs are as clear as possible 💪 MUCH appreciated!!
