### ISSUE TITLE
Oooops, something broke.. on getting started documentation

### ISSUE THREAD

**Issue by mirhat** [umbraco/UmbracoDocs#668]
I am getting Oooops, something broke.. text on on getting started documentation

**Comment by sofietoft** [comment]
Hi!
Thanks for bringing this to our attention.
It has been fixed now, and you should be able to view the Getting Started section once again.

Unfortunately the connection between Github and Our breaks occasionally when we merge in new PRs. We are working on resolving it!

-Sofie 😸
