### ISSUE TITLE
Update .Net framework version

### ISSUE THREAD

**Issue by dampee** [umbraco/UmbracoDocs#674]
This page (Getting-Started/Setup/Install/install-umbraco-with-nuget.md) still mentions the .net framework.

@nul800sebastiaan [suggested to drop it completely](https://github.com/umbraco/UmbracoDocs/pull/638#issuecomment-364096540)

**Comment by ed-parry** [comment]
Submitted PR #709.

**Comment by marcemarc** [comment]
Merged!
