### ISSUE TITLE
Umbraco Documentation - 404 Errors for section Getting Started

### ISSUE THREAD

**Issue by mzmati** [umbraco/UmbracoDocs#675]
As in title, whole section "Getting Started" returns 404 and message "Oooops, something broke.."

**Comment by dampee** [comment]
I don't have any issues.  Can you verify this is still the case?  Or can you specify where you encounter this issue exactly?  On which page are you before you got a 404?

**Comment by mzmati** [comment]
Ok, section is back again ! :)

**Comment by dampee** [comment]
Apparently we had an issue earlier with GH not pushing correctly to Our but this has been resolved indeed.

Thanks for reporting this!
