### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rajwar** [umbraco/UmbracoDocs#676]
https://our.umbraco.org/documentation/getting-started/backoffice/property-editors/built-in-property-editors/multinode-treepicker

**Comment by dampee** [comment]
Hi @rajwar 
How did you got to this page?
Kind regards
Damiaan

**Comment by dampee** [comment]
This is the correct page: https://our.umbraco.org/documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Multinode-Treepicker2

@nul800sebastiaan can we create a redirect?

**Comment by Jeavon** [comment]
They are not the same, the first one is non UDI picker the second is the new UDI picker.

I don't think it's a broken link, we had an issue earlier with GH not pushing correctly to Out but this has been resolved.

**Comment by dampee** [comment]
Indeed.  It's working again.  Let's close this.
