### ISSUE TITLE
Adding a workflow type docs are out of date

### ISSUE THREAD

**Issue by jameskraus** [umbraco/UmbracoDocs#703]
https://github.com/umbraco/UmbracoDocs/blob/master/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype.md

The doc says to use RecordService from Umbraco.Forms.Core.Services. RecordService doesn't seem to exist under that namespace.

Also, "Both the RecordService and RecordStorage is described in detail in the reference chapter.". Neither seem to be described in a reference chapter. Let me know if I'm just missing it.

**Comment by jmayntzhusen** [comment]
This is on a list of things we need to update, for now I can tell you that the correct namespace is Umbraco.Forms.Web.Services.RecordService 🙂

**Comment by sofietoft** [comment]
Duplicate: #424

**Comment by jameskraus** [comment]
Closing, no longer use Umbraco
