### ISSUE TITLE
Umbraco.Media vs Umbraco.TypedMedia

### ISSUE THREAD

**Issue by NikRimington** [umbraco/UmbracoDocs#712]
Hi Curators of the Umbraco Docs.

As I understand it Dynamics is being phased out as the best approach for accessing content. I was under the impression that this was also true for accessing media. Does the following page need updating to show the TypedMedia way of accessing media? 

https://github.com/umbraco/UmbracoDocs/blob/master/Getting-Started/Design/Rendering-Media/index.md

(If it does I'm happy to look at creating a pull request for it :-)  )

Thanks.

**Comment by Jeavon** [comment]
:thumbsup: Absolutely! Look forward to seeing a PR from you.

**Comment by marcemarc** [comment]
Was about to say exactly the same thing! we should be looking I think to show the TypedMedia approach but also how you'd work with media if using modelsbuilder - also looking very forward to seeing a PR :-P

**Comment by dampee** [comment]
My eyes hurt when I see all these "dynamics" in examples. :-)

**Comment by ed-parry** [comment]
Looks like this one can be closed now?

**Comment by dampee** [comment]
We could indeed close this one.  There are certainly other examples, but we could just create a new issue at that moment!
