### ISSUE TITLE
Document Cloud organizations

### ISSUE THREAD

**Issue by hemraker** [umbraco/UmbracoDocs#718]
Would be helpful with an explanation of what an organization actually is and what is currently possible with organizations on Cloud.

* What is an organization
* What are the benefits organizations
* What are the features of organizations

There is a tiny bit documented atm https://our.umbraco.org/Documentation/Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/Organizations/ but you need some context in order to be able get anything out of it ;)

**Comment by sofietoft** [comment]
Hi! Closing this one for now.
There is already some information about the Cloud Organizations, and not much has changed since it was created.
Feel free to reopen it, if you feel something's still missing! 😄 

/Sofie
