### ISSUE TITLE
Document What Application Context is

### ISSUE THREAD

**Issue by marcemarc** [umbraco/UmbracoDocs#762]
Document what ApplicationContext is
and UmbracoContext

we never really explain what they are anywhere, so it would be good to have one place to emphasise the good practice to link to from other places in the docs, eg no using .Current - but injecting in instances of ApplicationContext etc - See Anti Patterns common pitfalls docs

**Comment by sofietoft** [comment]
Hi! 
As we haven't seen any new activity on this issue in while, I'll close it for now.

If you feel it's still relevant, you're welcome to reopen it! 😁 
Thanks.

/Sofie
