### ISSUE TITLE
Contour mentioned in the docs

### ISSUE THREAD

**Issue by jamescoxhead** [umbraco/UmbracoDocs#764]
I found Contour was mentioned in the Forms documentation earlier today (see [here](https://our.umbraco.org/Documentation/Add-ons/UmbracoForms/Installation/license#can-i-add-additional-domains-to-the-license)). A wider search of the docs also revealed a mention of it [here](https://our.umbraco.org/Documentation/Getting-Started/Setup/Upgrading/general#merge-uixml-and-language-files).

**Comment by mateoholman** [comment]
I can take this one on if no one else is currently working on it?

**Comment by sofietoft** [comment]
Hi @mateoholman 

Looks like there's already an open PR for this: #765 
But thanks anyways 😄 
Perhaps there's something else you can grab instead?

-Sofie

**Comment by jmayntzhusen** [comment]
Seems this has been fixed and merged, will close this 🙂
