### ISSUE TITLE
Scheduling Parent/ Child Pages

### ISSUE THREAD

**Issue by jonroberts24** [umbraco/UmbracoDocs#781]
I have realised that if you schedule publishing for a Parent and its Child pages there is a good chace that the Parent page is scheduled milliseconds after the child pages. This will prevent the child pages from publishing as the Parent page hasn't been published yet.
Apart from the obvious of staggering the schedule times is there a fix for this to check Parent/Child relationships?

**Comment by dampee** [comment]
Not that I know of by heart.  As this is the documentation repo, you might be asking this on the forum or raise an issue on http://issues.umbraco.org

Is it ok to close this issue here?
You can add a link here to the other places if you want to.
