### ISSUE TITLE
Link to the old wiki is now dead

### ISSUE THREAD

**Issue by abjerner** [umbraco/UmbracoDocs#815]
At the bottom of this page:

https://github.com/umbraco/UmbracoDocs/blob/master/Reference/Templating/Macros/Xslt/45-XML-Schema.md

is a link referring to the old wiki, which now is dead:

`/wiki/reference/xslt/45-xml-schema/switching-between-old-and-new-schema`

I haven't been able to find a replacement in the new documentation - hence this issue.

![image](https://user-images.githubusercontent.com/3634580/40589753-894637be-61f3-11e8-88c7-523d5ec14064.png)

**Comment by marcemarc** [comment]
I think we may need to remove this link, I can't find the content anyway :-( and I've tried
