### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by abjerner** [umbraco/UmbracoDocs#819]
Links for Tekpub are now dead:

https://github.com/umbraco/UmbracoDocs/blob/master/Tutorials/Creating-a-Property-Editor/index.md
https://github.com/umbraco/UmbracoDocs/blob/master/Tutorials/Creating-a-Custom-Dashboard/index.md

![image](https://user-images.githubusercontent.com/3634580/40590565-128cb8ec-6201-11e8-99d5-934f00f22c84.png)

Most likely the links can just be removed, but wanted to create the issue here first ;)

**Comment by ed-parry** [comment]
Going through these, I've updated them to point to the AngularJS path on Pluralsight, as Tekpub eventually became that so the closest thing in terms of content. I'll link to the PR including these here shortly if we need/want to review.
