### ISSUE TITLE
Increasing security of a site

### ISSUE THREAD

**Issue by AndyFelton** [umbraco/UmbracoDocs#823]
May be worth referencing some of the modifications @JeffreyPerplex mentioned in his talk at Codegarden.

EG. if you use Visual Studio rather than the Back Office to change templates, style sheets, etc make the appropriate directories read only.

I'm happy to make changes  (probably a new section Setup/Security) if it makes sense?

**Comment by JeffreyPerplex** [comment]
Hi Andy, I've posted my slides over here; https://www.perplex.nl/en/blog/2018/security-umbraco-codegarden-2018/. If we agree on the tips I've mentioned, I'm more than willing to contribute to the documentation, but I think the first important step is to agree on the points.

**Comment by marcemarc** [comment]
@JeffreyPerplex @AndyFelton I'm thinking there should be a page called 'Hardening Access to the Umbraco Backoffice' linked from this page: https://our.umbraco.org/documentation/Reference/Security/  which could talk about the pros and cons of hiding the different aspects of Umbraco and the techniques for making the backoffice available to only your editors, etc ?

**Comment by marcemarc** [comment]
@AndyFelton I'm closing this issue as @JeffreyPerplex 's sterling work in #897 has been pulled in!
