### ISSUE TITLE
Make the Umbraco UI documentation easier to find by adding a link in the docs navigation.

### ISSUE THREAD

**Issue by readingdancer** [umbraco/UmbracoDocs#845]
Currently it doesn't seem like the Umbraco UI API docs are linked to from the main documentation section, so unless you have Googled it and come across the link, it's almost impossible to find.

I think there should be a clear link in the main documentation navigation tree on the left across to the API docs:

https://our.umbraco.org/apidocs/ui/#/api

**Comment by marcemarc** [comment]
Would you have it on the top level, or in the reference section? think we just need @nul800sebastiaan to setup a redirect

**Comment by readingdancer** [comment]
My gut feeling is it should be within one of the sections so that we can describe what it is used for. If people see it on the top level they might just click in and be confused as to its usage?

As you said perhaps in the reference section or in a second that talks about back office development. ( I am not at my PC currently so not 100% sure )

**Comment by marcemarc** [comment]
@readingdancer have added a couple of 'landing pages' in reference and extending, that might be a start, should at least make  them appear in the navigation... https://github.com/umbraco/UmbracoDocs/pull/850

what do you think?

**Comment by dampee** [comment]
I think we should at least make them appear in the search  :-)

**Comment by marcemarc** [comment]
@readingdancer ok that's merged in! Have a look see if that's a step in the right direction; thanks for pointing it out... Be interesting to see in the analytics if more people discover them in this way

**Comment by marcemarc** [comment]
@readingdancer forgot to close the issue!
