### ISSUE TITLE
Package.manifest JSON documentation page is broken

### ISSUE THREAD

**Issue by SwastikMS** [umbraco/UmbracoDocs#846]
Link:- https://our.umbraco.org/documentation/tutorials/Extending/Property-Editors/package-manifest

Access Point :- https://our.umbraco.org/documentation/tutorials/Creating-a-Property-Editor/_/

**Comment by dampee** [comment]
Hi @SwastikMS 
Who do you got on the first page?  You should not have a url ending in /_/ .
If that part is gone, the link works just fine.

**Comment by SwastikMS** [comment]
Hi @dampee 
No you took it wrong. 
Please visit the url  https://our.umbraco.org/documentation/tutorials/Creating-a-Property-Editor/_/
There you can see a link "For full package.manifest JSON documentation see here" which redirects to "https://our.umbraco.org/documentation/tutorials/Extending/Property-Editors/package-manifest" link. This link doesn't load. It shows "something broke".

**Comment by marcemarc** [comment]
Hi @SwastikMS 

If you visit this page:

[https://our.umbraco.org/documentation/Tutorials/Creating-a-Property-Editor/](https://our.umbraco.org/documentation/Tutorials/Creating-a-Property-Editor/)

Then you'll find the link isn't broken.

The link is being made by traversing up two folders to the extending section, and then across to the Json documentation...

but the url of the page you are reporting the broken link on, isn't the correct url for that content!

you can see when compared to the link above, it has an extra /_/ on the end

and that's confusing the relative link, causing it to be broken

I don't think you are  visiting the correct url of the page and then manually adding the /_/ on the end of the url :-) 

So there must be somewhere else in the docs, or possibly outside of the docs, a link you have followed that has brought you to the docs with this rogue /_/ on the end...

it would be super useful if we could track down where that was!

**Comment by dampee** [comment]
Yes indeed.  It would be super helpfull if you know where we can find the page linking to the page ending on /_/ 

Hope you can help us @SwastikMS

**Comment by SwastikMS** [comment]
@dampee Why everyone is after /_/ . It's not creating any problem.

Please follow my 2nd comment. 

visit the url https://our.umbraco.org/documentation/tutorials/Creating-a-Property-Editor/_/

There in "Setting up a plugin" section,  you will find a link with text "For full package.manifest JSON documentation see here". Click on that link, you will come to know the issue.

Thanks

**Comment by abjerner** [comment]
@SwastikMS It is your original link itself that is the culprit. Do you remember where you got this from?

The URL for *Creating a Property Editor* should really be:

https://our.umbraco.org/documentation/tutorials/Creating-a-Property-Editor/

rather than:

https://our.umbraco.org/documentation/tutorials/Creating-a-Property-Editor/_/

If you found that link somewhere else in the documentation, then that's where we need to fix it.

**Comment by jmayntzhusen** [comment]
I stumpled upon this old issue, I found a while ago some links that ended in `/_/`, and they should be fixed, either way this issue is no longer an issue and if any other broken links occur we should get a new issue.
