### ISSUE TITLE
Missing documentation for services

### ISSUE THREAD

**Issue by abjerner** [umbraco/UmbracoDocs#847]
About half of the services are not documented - at least when looking here:

https://our.umbraco.org/documentation/Reference/Management/Services/

- [x] ApplicationTreeService
- [x] AuditService
- [x] ConsentService
- [x] ContentService
- [x] ContentTypeService
- [x] DataTypeService
- [x] DomainService
- [x] FileService
- [x] EntityService
- [x] ExternalLoginService
- [x] FileService
- [x] LocalizationService
- [x] MacroService
- [x] MediaService
- [x] MemberGroupService
- [x] MemberService
- [x] MemberTypeService
- [ ] MigrationEntryService
- [x] NotificationService
- [x] PackagingService
- [x] PublicAccessService
- [x] RedirectUrlService
- [x] RelationService
- [x] SectionService
- [x] ServerRegistrationService
- [x] TagService
- [ ] TaskService
- [x] TextService
- [x] UserService (work in progress : #604)

Just posting this for reference here. The ones in the list with a checkmark already have their own page(s) - the ones without the checkmark are missing. Should I create an issue for each missing service instead?

**Comment by marcemarc** [comment]
@abjerner I think it's fine for this to be a single issue, we have been in two minds when discussing the services, in that I think they should all be listed, their existence acknowledged! - and a short description of what they are and where they might be used, and any quirks, example of common usage if appropriate - but we sort of also feel we want to steer clear of duplicating the content generated in the API docs - eg https://our.umbraco.org/apidocs/csharp/api/Umbraco.Core.Services.ContentTypeService.html (but each service should have a clear signpost to the relevant api doc too) - just having each service, listed with it's own page would be a great start, so the checkbox list above is super useful

**Comment by Soundug** [comment]
@marcemarc Can I take this one? 
I could add some services documentation.

**Comment by marcemarc** [comment]
@Soundug Yes, absolutely, we're trying to follow the pattern that @abjerner has established for the services - take a look at the domain service for example: https://our.umbraco.com/Documentation/Reference/Management/Services/

Essentially we are not trying to duplicate the auto generated api documentation eg https://our.umbraco.com/apidocs/csharp/api/Umbraco.Core.Services.DomainService.html

but kind of create a 'landing page' for each service, which links to the api documentation, and gives an overview of what the service does / is commonly used for, with samples on how to 'get a reference to it' etc

or at least first step is to get something existing for each service!

**Comment by abjerner** [comment]
@Soundug Feel free to write here if you started adding documentation for some of the services. I planned on doing that for a least some of the missing services this weekend. I'll write here as well so we don't end up working on the same services ;)

**Comment by aredshaw** [comment]
Are you using REST APIs? If so, I might be able to help.
What are the following?
* The base path
* Endpoints
* All possible methods and parameters
* An API Key (If required)

**Comment by erikjanwestendorp** [comment]
@sofietoft It seems that the TaskService and the MigrationEntryService not available in v8. Is it necessary to add a v7 version only to the documentation?

**Comment by sofietoft** [comment]
That's a great question @erikjanwestendorp 🤔 

I would say no. If it doesn't exist in the current major, it most likely will not be part of the next major either!
So, no need to spend your time writing about those, if you ask me!

**Comment by sofietoft** [comment]
As all services in this list have been updated for Umbraco 8, I'll close the issue.

There are some remaining services that are not yet added, but as they are not present in the latest major, they are not a priority.
Feel free to open a new issue with the remaining two services - TaskService and the MigrationEntryService.

Thanks for the help all 🙌 Much appreciated!
