### ISSUE TITLE
Let's encrypt

### ISSUE THREAD

**Issue by jomehmet** [umbraco/UmbracoDocs#851]
It should be clear that Let's encrypt is enabled on Umbraco as a Service. I didn't know this and bought a certificate, but suddenly my domain was "Secure" without doing anything. When I inspected the certificate I could see it was Let's encrypt.

**Comment by dampee** [comment]
Hi @jomehmet 
I understand it should be mentioned somewhere.  What you encountered is the new product called [Latch](https://umbraco.com/products/umbraco-latch/).
I'll ask @sofietoft to look into this!

Kind regards
Damiaan

**Comment by sofietoft** [comment]
Hi @jomehmet 

You are completely right, and I agree!
We need to make LATCH more visible.
I've already talked with our communication people, and they are putting some info on our website.

I have a plan to write / rewrite the documentation we have about domains and certificates for Cloud already.

-Sofie

**Comment by sofietoft** [comment]
Umbraco Latch Documentation is now Live: https://our.umbraco.org/documentation/Umbraco-Cloud/Set-Up/Manage-Domains/Umbraco-Latch

**Comment by jomehmet** [comment]
Great that you created documentation for this. For people using google to find the documentation, I think it would be nice in this article: https://our.umbraco.org/Documentation/Umbraco-Cloud/Set-Up/Manage-Domains/Security-Certificates/ To write on the top of the article: "In case you don't want to use automated certificate (LATCH), you can add it manually, for instans if you want a green bar certificate." I see there is a link at the bottom, but in many cases people don't know what LATCH is and they don't scroll to the bottom.
