### ISSUE TITLE
Editors manual missing

### ISSUE THREAD

**Issue by GertyEngrie** [umbraco/UmbracoDocs#877]
It would be nice to have a link to the editors manual on the documentation overview page. 
But, the available versions of the manual(s) at this moment are not really ideal:
- static pdf version ( [https://our.umbraco.org/projects/website-utilities/umbraco-7-editors-manual/](https://our.umbraco.org/projects/website-utilities/umbraco-7-editors-manual/) )
- markdown version to use with bookshelf package ( [https://github.com/okhenry/V7-Editors-Manual](https://github.com/okhenry/V7-Editors-Manual) )

Would it be an option to merge in the markdown version and provide an option to generate a pdf from the current documentation? This way it would be straightforward to keep the manual up to date & userfriendly for editors to grasp the basic functionality of Umbraco.

**Comment by dampee** [comment]
Hi @GertyEngrie 

I think that's a great idea!  Because the mentioned repo's are already 3 years old, I don't think someone will object to move this to the documentation repo.

Creating a PDF would involve submitting a PR to OUR.  Don't know what the best step for that would be.
Also, I don't know if the bookshelf package from Kevin supports partial repo's.

Maybe another approach: if Umbraco forks the repo and we can maintain it in a separate (or sub-) repo, that might work too.

**Comment by GertyEngrie** [comment]
Hi @dampee!

yes, true, a fork might be a better idea! 
A pdf version might not be necessairy at first. Let's get it consultable & maintainable first. If there's a way to display the manual in 1 page then you can always use the browser's 'print to pdf' functionality i guess :)

**Comment by marcemarc** [comment]
This is a great idea!, if everyone who put work into the original V7 manual would be happy to have the work maintained in this location. The manual sort of stops at early seven, doesn't mention grid etc, also I have bits and pieces on the Editor Training Course I run that I could bring across into it.

That said, yesterday, Umbraco announced, a new Content Editor Course, so it is a fair assumption that materials will have been generated for this too, which could tie into any documentation for editors here...

@ilhambo @hemraker

**Comment by hemraker** [comment]
I think it would be great to get the Editors Manual in the docs. It obviously needs an update but other then that I say go for it 😃  There is a bit of overlap with the content management course but I think they will be good companions.

**Comment by samus-aran** [comment]
Hey peeps. Hope I didn't step on anyone's toes and added the already existing v7 Editor Manual as separate sections. The did contemplate if there should be a single file that contains everything but felt that would be unmaintainable - so still none the closer on how to generate a pdf doc using live and dynamic pages without being a coder. :woman_shrugging: 
My only suggestion is that part of the generation of the static webpages run a simple script to generate that section and store in the assets and reference it via link.

**Comment by dampee** [comment]
Thanks for starting something.  It's helpful for sure!
