### ISSUE TITLE
Add a specific page about AngularJS usage

### ISSUE THREAD

**Issue by BatJan** [umbraco/UmbracoDocs#885]
I just submitted to very minor PR's about a link to egghead.io, which was pointing at just the frontpage and not explicitly at the AngularJS courses they provide - I asked on one of the PR's if perhaps it would make sense to add a specific page about AngularJS usage in Umbraco in general like we have a "common pitfalls" page and @dampee asked me to raise the question/issue here. So here I go :)

Don't know if it will make sense but perhaps it would be good to write specifically that AngularJS is being used the road ahead and links to the good AngularJS tutorials from the web and the AngularJS cookbook from CG14 for instance - Just to have a central place to refer too and avoid any newcomers getting confused about AngularJS and Angular for instance.

Does my idea make sense? Thoughts? :)

**Comment by marcemarc** [comment]
Yes; I agree, a page that explains where it's used; the specific version and resources to learn it... Although not really docs - I'd squeeze in a statement on why the version is not super recent ... Just because that is a FAQ

**Comment by BatJan** [comment]
Yup it would be nice to have something to refer to. And especially with explaining the version choices and why it's not latest version in 7 yet etc.

I'll see if I can give it a go during the week - But otherwise I have some time in the weekend. Thanks for the input @marcemarc

**Comment by sofietoft** [comment]
Hi! 
As we haven't seen any new activity on this issue in while, I'll close it for now.

If you feel it's still relevant, you're welcome to reopen it! 😁 
Thanks.

/Sofie
