### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by Myster** [umbraco/UmbracoDocs#889]
Hi,
I am looking at this documentation about formsupdate file.
https://github.com/umbraco/UmbracoDocs/blob/master/Add-ons/UmbracoForms/Installation/ManualUpgrade.md

The file seems to put a version number in it (that does not match the nuget package version number)
the documentation says it should dissappear, it doesn't.

Note: I upgraded via nuget rather than manually.

**Comment by sofietoft** [comment]
Hi @Myster 

Thanks for reporting this.
Maybe what's needed here, is more documentation on the different options you have for upgrading Forms?
Like, there is already documentation for how to do it manually, how to do it from the Backoffice, but documentation on how to do it using NuGet is missing.
What do you think?

-Sofie

**Comment by sofietoft** [comment]
Hi @Myster 

I've done some testing, and it seems that you are right.
No matter how I update Forms, the `formsupdate` marker isn't automatically removed as the documentation states 🤔 

Could you create an issue on this on the [Forms issue tracker](https://github.com/umbraco/Umbraco.Forms.Issues/issues)?
In the meantime, I've updated the documentation to mention that sometimes you might need to remove the file manually.

-Sofie

**Comment by Myster** [comment]
I don't seem to be able to do that today, git-hub keeps signing me out.
I'll try and remember to do it later.

**Comment by jmayntzhusen** [comment]
Hey @Myster 

As this seems to be a bug in Forms rather than a fault in the documentation I will close this for now as the issue should be on the Forms issue tracker instead 🙂
