### ISSUE TITLE
Creating a custom dashboard tutorial needs an update

### ISSUE THREAD

**Issue by dawoe** [umbraco/UmbracoDocs#894]
The tutorial [here](https://our.umbraco.org/documentation/Tutorials/Creating-a-Custom-Dashboard/) can not be completed at the moment because of some bugs in Umbraco.

More details can be found in this [forum topic](https://our.umbraco.org/forum/extending-umbraco-and-using-the-api/92396-custom-dashboard-and-sqlce) and this [issue](http://issues.umbraco.org/issue/U4-11458) on the tracker

I already created a [PR](https://github.com/umbraco/Umbraco-CMS/pull/2719) for fixing the issues.

But the tutorial uses the getUserLog method which calls a API method that is marked as obsolete. So maybe it's better to update the tutorial to use the getPagedUserLog method

Looking at the screenshots in the tutorial I have a strong suspicion that @marcemarc created the tutorial.

Dave

**Comment by marcemarc** [comment]
:-) yep, it wasn't obsolete when the tutorial was created :-P (though it didn't work!, and needed a PR) 
 which confused people trying to complete the tutorial on an older version of Umbraco - probably the paging got added now that we have the history displayed on the info tab of a node... so yes, we can switch the tutorial to use the new method, thanks @dawoe !!

**Comment by marcemarc** [comment]
Needs this PR to be merged into core: https://github.com/umbraco/Umbraco-CMS/pull/2719/files
then update tutorial

**Comment by marcemarc** [comment]
Now dependant on this PR: https://github.com/umbraco/Umbraco-CMS/pull/3759
as the entities aren't present in the log resource!
