### ISSUE TITLE
Update screendumps in documentation?

### ISSUE THREAD

**Issue by BatJan** [umbraco/UmbracoDocs#895]
I'm wondering what the correct approach to updating the screendumps in the documentation in general would be? Because some places it's not just enough to update the screendumps but also the writing to reflect the changed process of doing things in the backoffice - An example of this can be found here https://our.umbraco.org/documentation/Getting-Started/Design/Rendering-Content/ - The "Insert" options UI has changed with the release of Umbraco 7.6 and the process of inserting stuff has changed a bit.

But if this page is updated with new screendumps and text, which assumes 7.6+ then what about older installations? It would be confusing for someone new to Umbraco who happens to have to work on a 7.3 install for instance to make sense of what's documented for instance. I think in general terms here not just the example page that I have referenced.

I remember seeing Niels posting an image from the retreat this year where it seemed there was something version specific added to the markdown files for v8 - Is this something that could also be made use of for this scenario? So it's possible to keep what's relevant before 7.6 and then tag up new guidelines for 7.6+ ?

I hope my question makes sense - Would love to update the documentation here and there but feel like there are some things that should still be kept available rather than just deleting the old stuff and replacing it with the new stuff.

So I guess my question really is - Can we tag stuff in the documentation for path releases or will it be / is it a major releases thing?

**Comment by dampee** [comment]
Hi Jan
What you saw is umbraco/OurUmbraco#236. It is not completely ready, so it's not merged in.  We planned on working on this, later this week.
I would suggest to wait a few more days until this has been delivered because our PR will introduce a few new concepts:

* tagging of documents (using YAML)
* version agnostic documentation

Your question makes a lot of sense.  And there are solutions (in the very near future).  :-)

**Comment by BatJan** [comment]
Hi Damiaan

Ah cool! Was hoping that this was the case but could not recall it being mentioned at CG18 or at Twitter etc. - Just remembered that screendump :)

I also have some documentation for the tags property editor in the works, which I will hold back untill this feature is available since it will need to be written differently for v7.6+ and for version before this.

Will you let me know in here when it's possible? Then I'll go update frenzy :D

Good work folks!

**Comment by dampee** [comment]
If you create already a PR and reference #170 and/or #230 then no-one else will start on this.

You should write for the current version.  If you have specific information about (older) versions you should move that to a different file with the same name adding a postfix in the filename (eg xxx.v-6.2.md).

**Comment by BatJan** [comment]
Thanks @dampee - I have opened a PR here https://github.com/umbraco/UmbracoDocs/pull/900

**Comment by jmayntzhusen** [comment]
As the update has been rolled out I will close this issue, all documentation can now be versioned so any screen shot updates can be made 🙂

Read more about setting up versioned documentation here: https://our.umbraco.com/documentation/Contribute/#multi-version-documentation
