### ISSUE TITLE
Invalid URL's for Courier Nightly URL's

### ISSUE THREAD

**Issue by readingdancer** [umbraco/UmbracoDocs#912]
I think this one needs someone from HQ, so maybe @sofietoft can help?

On this page:

https://github.com/umbraco/UmbracoDocs/blob/master/Add-ons/UmbracoCourier/CommonIssues.md

All the links are invalid, they look like they should be re-directs that then point to the current location of these files, but we don't have access to fix these re-directs, I assume this is something the HQ can do. I could update these to point directly to the files, but I assume the re-directs are used to create statistics / make it possible to change the location of the stored files.

Also, I am pretty sure the links are pointing to quite old versions and should be updated to point to more recent nightly versions of these files.

All the nightly builds can be found here:

http://nightly.umbraco.org/?container=umbraco-courier

**Comment by sofietoft** [comment]
Hi Chris,

You sure are right! That article is out-of-date. 
I'll add it to my list, and hopefully get to it soon! 👌 

-Sofie
