### ISSUE TITLE
Add details of the UmbracoDefaultOwinStartup_MiddlewareConfigured event

### ISSUE THREAD

**Issue by marcemarc** [umbraco/UmbracoDocs#913]
Document the existence of the UmbracoDefaultOwinStartup_MiddlewareConfigured

on the Events page under a heading of OWIN

and also possibly in link to it from the security page? OWIN Stuff...

if we can come up with a good example of using it other than wiring up SignalR in Umbraco < 7.6

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
