### ISSUE TITLE
Document existence of SignalR in the core, and how to work with it.

### ISSUE THREAD

**Issue by marcemarc** [umbraco/UmbracoDocs#914]
SignalR now ships with the core 7.6 there are a couple of tricks to use it in your own packages,  or on the frontend of your site, we could add some info perhaps in /extending area of the docs to let people know where this is.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
