### ISSUE TITLE
Incorrect documentation for creating Courier data resolvers

### ISSUE THREAD

**Issue by hemraker** [umbraco/UmbracoDocs#929]
This documentation is outdated and needs to be updated to work with the latest version of Courier.

https://our.umbraco.com/documentation/Add-ons/UmbracoCourier/Developer/DataResolvers

**Comment by hemraker** [comment]
There are some good examples on how to create these here https://github.com/umbraco/Umbraco.Courier.Contrib/tree/dev/src/Umbraco.Courier.Contrib.Resolvers/PropertyDataResolvers

**Comment by jmayntzhusen** [comment]
Closing as the Courier section recently had an overhaul, and for now referring to examples from the Contrib project is good enough.
