### ISSUE TITLE
Update documentation on users

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/UmbracoDocs#932]
The member section and member groups have pretty good documentation: https://our.umbraco.com/documentation/Getting-Started/Data/Members/

It seems the users are missing out, all I could find was https://our.umbraco.com/documentation/Getting-Started/Backoffice/#user 
Would be great with more careful documentation on the difference between members and users aswell as user groups, granular permissions, etc.

**Comment by michizhou** [comment]
I could write up some documentation for this. I would appreciate it if you could provide some more info and docs that could help fill in the gaps about the differences between users and members as well as users themselves represent. Thanks!

**Comment by gorlapraveen** [comment]
hi @jmayntzhusen , I tried to added some documentation,  #1047

**Comment by jmayntzhusen** [comment]
Hey @michizhou ,

Thanks for offering to write something, what I was thinking is to make something similar to https://our.umbraco.com/documentation/Getting-Started/Data/Members/ but for users, it could also be in the same path /Getting-Started/Data/Users for example. The topics that could be covered is:
* What is a user
* How do you make users and user groups
* How do you set permissions on user groups
* How do granular permissions work

There is some info to be found in this playlist: https://umbraco.tv/videos/umbraco-v7/content-editor/administrative-content/users/ otherwise you can start up an Umbraco site and dig around yourself a bit.


As for @gorlapraveen , I think other than having a specific users / user group section it is also very nice to have a quick overview of the differences between users and members, so good job I will review the PR you made shortly 😉

**Comment by michizhou** [comment]
@jmayntzhusen I added some new documentation that should address the issue (#1058)
