### ISSUE TITLE
Nested content is not a package anymore

### ISSUE THREAD

**Issue by dampee** [umbraco/UmbracoDocs#943]
The document about [Migrating to the cloud](https://github.com/umbraco/UmbracoDocs/edit/master/Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md) mentions Nested Content as "_a package with no Data Resolver_".  As nested content is a core feature, I can only hope there is a default data resolver.

**Comment by sofietoft** [comment]
Updated: https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/
