### ISSUE TITLE
Example Code is incorrect for Forms v7

### ISSUE THREAD

**Issue by paulsterling** [umbraco/UmbracoDocs#953]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype.md***

The current example code is not correct and will not work as-is with Forms v7. It is a bit mis-leading in that the namespaces are not correct and the approach has changed as well - at least if what I've done to have it work as expected is correct ;-) .

If I can find a spot of time I'll update the example code and underlying explanatory text, but in the meantime I believe the code should be similar to:

```
        public override WorkflowExecutionStatus Execute(Record record, RecordEventArgs e)
        {
            // this example calculates a score based on the number of fields with a value of 'Yes'
            // we then use the calculated score to update the 'score' field for the record
            // in this case the score field is a hidden form field with a default value of '0'

            // the unique id for the 'score' field on the Form
            Guid scoreFieldId = Guid.Parse("c2fde6ac-ba58-460b-9fd4-c1acc1721e43");

            // our local calculated value
            int score = 0;

            foreach (RecordField rf in record.RecordFields.Values)
            {
				// make sure we skip the score field
				if(!rf.Key.Equals(scoreFieldId))
                {
                
					if (rf.ValuesAsString() == "Yes")
                    {
                        // add 1 for each 'Yes'
                        score++;
                    }
                }
            }
            // update the score field
            record.GetRecordField(scoreFieldId).Values.Clear();
            record.GetRecordField(scoreFieldId).Values = new List<object> { score };

            // invoke the RecordService to update the record and set the record state to 'Approved'
            RecordService.Instance.Approve(record, e.Form);

            return WorkflowExecutionStatus.Completed;
        }
```

**Comment by sofietoft** [comment]
Hi @paulsterling 

Thanks for this!
Perhaps @warrenbuckley , have a minute or two to look at this?

If everything looks good, would you prefer to make a PR yourself, or should I update the article? 😁 

-Sofie

**Comment by paulsterling** [comment]
@sofietoft No need to wait for me on the update if it's good as-is. I'd update if I can find the time, but if this is actually the right approach, better to update sooner.

-Paul
