### ISSUE TITLE
Missing (or deprecated/obsolete?) info about context-aware help?

### ISSUE THREAD

**Issue by greystate** [umbraco/UmbracoDocs#967]
In [this article](https://24days.in/umbraco-cms/2012/superhero/) on **24 Days In Umbraco** (albeit about v6), there's a `<help>` element mentioned that enables the **Help** link to be context-aware.

Is that still possible? I've noticed that the Help drawer seems to have been prepared for something like this (but I don't know where to look for how it would be populated).

So is this a "missing documentation" or "no longer relevant" issue?

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Config/umbracoSettings/index.md***

**Comment by sofietoft** [comment]
Hi @greystate 

That's a great question!
I bit outside my scope of Umbraco knowledge though.
Perhaps one of my fellow curators can help us out; @dampee , @marcemarc , @Jeavon ?

I'm also not 100% sure about the link to the repo you've sent.
It's this article: https://our.umbraco.com/Documentation/Reference/Config/umbracoSettings/, right? Is there any specific section in this article you are referring to?

-Sofie

**Comment by greystate** [comment]
Ah, right... 

Douglas' article refers to a `<help>` section in the **umbracoSettings.config** file, so I'm just asking if there needs to be a description of it (i.e. _missing documentation_) or if it's been deprecated/obsoleted?

**Comment by jmayntzhusen** [comment]
Hey @greystate 

Seems like it was marked obsolete Jun 30, 2017.. So I guess we can close this issue - thanks for considering the docs when you saw this feature though! 😄👍
