### ISSUE TITLE
Error in sample code

### ISSUE THREAD

**Issue by telljimmy** [umbraco/UmbracoDocs#971]
The last part of this page shows sample for showing first 100 characters of an article (Fig 42). This is throwing an error saying @item.ArticleContents is not found. 

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Tutorials/Creating-Basic-Site/Articles-Parent-and-Article-Items.md***

**Comment by dampee** [comment]
Hi @telljimmy 
Are you sure you have created the Article Content property as mentioned in this image:
![afbeelding](https://user-images.githubusercontent.com/1857460/44960979-63478c80-af09-11e8-856d-d0fa15ed7063.png)

**Comment by telljimmy** [comment]
Sorry for the late reply. I used Article Content instead of Article Contents. But its the same in both document type and in the Macro Partial. So hope it should have worked. images below. Thanks
![articleitemdoctype](https://user-images.githubusercontent.com/36344598/45152343-1408a100-b214-11e8-8f99-ac11d101fe3c.PNG)
![macropartial](https://user-images.githubusercontent.com/36344598/45152351-19fe8200-b214-11e8-87b7-d75859fa8c6a.PNG)

**Comment by telljimmy** [comment]
the error is 
\Views\\MacroPartials\\listArticles.cshtml(23): error CS1061: 'Umbraco.Core.Models.IPublishedContent' does not contain a definition for 'ArticleContent' and no extension method 'ArticleContent' accepting a first argument of type 'Umbraco.Core.Models.IPublishedContent' could be found (are you missing a using directive or an assembly reference?)"	string

**Comment by dampee** [comment]
To the team:
It has to do with the modelsbuilder.  We should take some time to validate whether that this tutorials has issues with the new modelsbuilder features.

Hi @telljimmy 
I am sure that if you do `@(Umbraco.Truncate(item.GetPropertyValue<string>("articleContent"), 100)` 
... it will work.

**Comment by andrewmumblebee** [comment]
I also hit this issue when following the tutorial and using the sample code, using GetPropertyValue and casting to a string resolves this. I'm running v7.12.3

**Comment by castlino** [comment]
Also getting same error here.

**Comment by castlino** [comment]
@Jeavon yeah i think you are right, For anyone who's getting the same problem, try below

`@Umbraco.Truncate(@Umbraco.Field(item, "articleContents"), 100)`

**Comment by jmayntzhusen** [comment]
I have updated the sample to 
`@(Umbraco.Truncate(item.GetPropertyValue<string>("articleContent"), 100)`

Thanks for reporting the issue, will close it now 🙂
