### ISSUE TITLE
Error while running sample code

### ISSUE THREAD

**Issue by telljimmy** [umbraco/UmbracoDocs#973]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Tutorials/Creating-a-Custom-Dashboard/index.md***

![image](https://user-images.githubusercontent.com/36344598/45217896-1d177200-b2e9-11e8-95e2-083e8b4fb3e2.png)

Code in Controller
================
angular.module("umbraco").controller("CustomWelcomeDashboardController", function ($scope, userService, logResource) {
	var vm = this;
	//alert('hello world');

	var user = userService.getCurrentUser().then(function (user) {
		//console.log(user);
		vm.UserName = user.name;
	})

	vm.LogEntries = [];

    logResource.getUserLog("save", new Date())
   .then(function (response) {
   	console.log(response)
   	vm.LogEntries = response;
   });
});

The error happens from the call to getUserLog. If I comment this call, it works. getLog not giving error.

**Comment by andrewmumblebee** [comment]
I'm having the same issue when running this code sample 😢 , @telljimmy did you have any luck resolving this?

**Comment by andrewmumblebee** [comment]
Upon further investigation looks like this issue is fixed with https://github.com/umbraco/Umbraco-CMS/pull/2719 , not within a release version yet though.

**Comment by telljimmy** [comment]
@andrewmumblebee . thanks for finding this. glad to know that its getting fixed.

**Comment by nul800sebastiaan** [comment]
I'll close this as the fix will be released when 7.13 is released 👍
