### ISSUE TITLE
Hard-to-follow example in config-transforms documentation

### ISSUE THREAD

**Issue by greystate** [umbraco/UmbracoDocs#977]
***This is the page (and section) in question: https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Config-Transforms/#including-transforms-in-umbraco-packages***

Though there's some very clever stuff going on in this section, I find it a little confusing and hard to follow - I've turned to this section more than a few times, and I always have to really slow down when trying to decipher it, mainly because of two things:

## 1. Naming

It's does not explain how I should name the file(s) other than _"it can be any word, for example `RollingStones` or `uPaintItBlack`"_ — so which is it? Where do they come from? If you can literally  name them anything, how do you prevent a name clash with another package? Probably much better to state that you should try to use your package's name or alias to prevent clashing with any other transform file(s)? (Only when reading it the second or third time and then picturing to myself what I'd do, did it occur to me that they _can_ be named literally anything because they're just executed.)

## 2. Sample values

While describing the three different values for the example, it's kinda confusing to say that in one place it should be _a red **door**_ so the setting should be `red`, and then suddenly talk about _a green **sea**_ for the second value? Then immediately state that this could just as easily be _a deeper `blue`_ instead? Only if you _really_ know the lyrics to that song will this make an inch of meaning, and I'm guessing that's not the majority of the developers looking this up 😬 

I would prefer a simpler example that just sets a different value (e.g. "Setting the `environmentColor`") for each environment - will probably cover what more than 80% of people looking this up is looking for, right?

I know I could be the only one having trouble with this, but I will (of course) take a stab at rephrasing this section myself, and propose a PR for further discussion.

**Comment by sofietoft** [comment]
Hi Chriztian,

As much as I do appreciate the clever play on the lyrics from the Rolling Stones - Paint it Black song, I understand how this can be very confusing 🙈 

Regarding the file-naming, it can indeed be anything you like. 
I do agree, however, that we should write in the documentation that the name of the file should be the name of the package as well - just to make it more consistent, and - of course - easier to understand!

You are very welcome to take a stab at rephrasing it, if you have time? 😁 

-Sofie

**Comment by greystate** [comment]
Thanks @sofietoft – I'll give it a whirl :)
