### ISSUE TITLE
Add new section to getting started page - Community

### ISSUE THREAD

**Issue by ravimotha** [umbraco/UmbracoDocs#979]
## What type of issue is it?
Discussion

## What article/section is this about? 
https://our.umbraco.com/documentation/Getting-Started/

## Describe the issue:
https://www.owain.codes/blog/posts/2018/august/jamie-townsend/ I was reading the following article and noticed that the community memeber did not know about #h5yr as a hashtag : I made me think we need at the very least a glossary of common in jokes and terms so people who are new can at least get a handle on certain things: 

looking at the getting started page a 
community section
glossary
meetups 
Code of Conduct
other features that are part of the community but not technical

Note this may well be related to https://github.com/umbraco/UmbracoDocs/issues/657

**Comment by OwainWilliams** [comment]
That was a surprise, one of my blogs starting this discussion. I think a community 'getting started' is a great idea. It's not always easy getting in to an established community, even when it's as friendly as Umbraco. 

The Umbraco t-shirt day needs to be on the list too 😊

**Comment by BatJan** [comment]
Great idea @ravimotha - I'm thinking that it should perhaps also contain information about some or all of the following
- The Umbraco slack channel (As an oldtimer I even forget that there's a lot of activity in there and have not really been active in there)
- Twitter hashtags as you mention, apart from #h5yr I also think that #h5is deserves an explanation - Other hastags are of course umbteesday as Owain mentioned above, #umbraco obviously. Might be good to mention if people ask specific questions on Twitter for instance
- The difference between the Gitter channel and the forum / Where to get help and where to discuss PR's and core stuff
- Community initiatives like umbracoCoffe, UmbracoBBQ, Meetups, Community corner, skrift.io, 24days.in/umbraco-cms, and I have probably forgotten something here. Sooo much to keep track of these days :-)

Hope it's useful!

**Comment by nul800sebastiaan** [comment]
1½ years later.. :-o 
I love this idea! And indeed, I don't think it fits the documentation section, but would make an excellent fit for the https://our.umbraco.com/community/ section instead.

If anyone reading along is still motivated to pick this up then I think this is what needs to happen:
- Add a new markdown file to the [Our source](https://github.com/umbraco/OurUmbraco)
- Add doctype to Our for dealing with this markdown file, and allow it  under doctypes of type `communityHub`
- Hijack the new doctype and make it read the markdown file and output HTML
- Send the HTML to the template

Now, there may in the future be multiple page that will read from a markdown, so it could good to make it configurable. In the new doctype, have a textstring where we can enter a path (`~/markdown/community-glossary.md`, etc) so we can potentially create more pages that use an MD file as input.

The MD file will be in the Our Source code, so it's open for contributions and will periodically update when we release Our.

I'll close this issue, as it doesn't fit in the documentation section but if someone wants to pick it up then I very much look forward to seeing a PR for Our!
