### ISSUE TITLE
Extend the markdown generation classes

### ISSUE THREAD

**Issue by dampee** [umbraco/UmbracoDocs#980]
## What type of issue is it?
Discussion

## What article/section is this about? 
All :-)

## Describe the issue:
Sometimes you want to warn the user, or make a side node. We currently have no possibility to include this kind of extra information in the documentation. And because Microsoft Docs has been doing awesome things, I've been looking at them.  :-)

While I know the solution will need to be a PR on the https://github.com/umbraco/OurUmbraco, my best take is to create the issue in the docs issues because it only affects the documentation.  :-)

Microsoft docs has a neat way of rendering this with simple markdown:
```
> [!NOTE]
> In dit artikel gaat u een app implementeren in App Service onder Windows. Zie [Een PHP- en MySQL-web-app bouwen in Azure App Service onder Linux ](./containers/tutorial-php-mysql-app.md) om een app te implementeren in App Service onder _Linux_.
>
```
Generates this: 
![afbeelding](https://user-images.githubusercontent.com/1857460/45644306-bdc21a80-babd-11e8-9efe-94e1cadb22e1.png)

_Oh, have you seen that NOTE is translated into the uses language. _

## And there is more!
I think we don't only need a "note", but also other things

* Note
* Tip
* warning
* ...  (please comment below)

### a checklist
```
> [!div class="checklist"]
> * Een MySQL-database in Azure maken
> * Een PHP-app verbinden met MySQL
> * De app implementeren in Azure
```
becomes:
![afbeelding](https://user-images.githubusercontent.com/1857460/45645177-fa8f1100-babf-11e8-8508-2d3833b6e3e8.png)

### embedding other md files
While I don't agree wheter we need this, it's an easy way to insert a commercial plug to e.g. umbraco cloud trial.... in a controllable way
```
[!INCLUDE [quickstarts-free-trial-note](../../includes/quickstarts-free-trial-note.md)]
```

### Code examles
```
` ` `sql 
CREATE DATABASE sampledb;
` ` ` 
```

makes me just jealous if you see this:
![afbeelding](https://user-images.githubusercontent.com/1857460/45645363-75f0c280-bac0-11e8-9263-4fc4463232f9.png)

### next section button
Look at this code
```
> [!div class="nextstepaction"]
> [Een bestaande aangepaste DNS-naam toewijzen aan Azure Web Apps](app-service-web-tutorial-custom-domain.md)
```
![afbeelding](https://user-images.githubusercontent.com/1857460/45645509-ef88b080-bac0-11e8-8383-5419b48527f3.png)

__ SORRY FOR A THE DUTCH examples.  I hope you guys get the picture.  :-) __

**Comment by jmayntzhusen** [comment]
This looks great, not sure we need all of these, but there are definitely a couple of them that would be amazing - and would tie in well with a possible contribution guideline update as well once implemented!

Now all we need is to figure out how to extend Markdig to make this work 😄

**Comment by dampee** [comment]
Apparently, Markdig already supports something like this already: 
https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/CustomContainerSpecs.md

**Comment by jmayntzhusen** [comment]
So apparently this is already implemented:
https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Documentation/Busineslogic/MarkdownLogic.cs#L49 

I just tried locally to add this to a markdown file:
```
:::test
This is test content
:::
```

And it made this:

```html
<div class="test">
  <p>This is test content</p>
</div>
```

So I guess all we need is to add some css and agree on conventions for doing things? 😃

**Comment by dampee** [comment]
Indeed. The only thing is that I would like to have a type.  E.g. "Note", "Tip", "Warning".
Something like this: ![afbeelding](https://user-images.githubusercontent.com/1857460/45685359-69fd1300-bb49-11e8-942c-1183021a20e4.png)

**Comment by jmayntzhusen** [comment]
We can do something like that with pure css though, we just need to agree how it will look - here is an example I quickly threw together: https://codepen.io/anon/pen/VGVeVY 😉

**Comment by jmayntzhusen** [comment]
I'll be having a look at implementing this next week, will update here what I make so people can pitch in ideas / feedback 😄

**Comment by jmayntzhusen** [comment]
So my first try ended up looking like this:
![udklip](https://user-images.githubusercontent.com/36075913/46013531-df7a5d80-c0cc-11e8-9953-536b863033f1.PNG)

The only markdown is below, the rest is made with pure css 😁


```
:::note
This is a note, it contains useful information and also a link: https://thisisalink.com/useful/resource, please make sure it looks nice on Our!
:::

:::warning
This is a warning, it contains useful information and also a link: https://thisisalink.com/useful/resource, please make sure it looks nice on Our!
:::

:::tip
This is a tip, it contains useful information and also a link: https://thisisalink.com/useful/resource, please make sure it looks nice on Our!
:::
```

Will take a look at something like checklists and maybe small menues next - we are using sitewide menues a few places like here: https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/ 

Let me know what you think!

**Comment by dampee** [comment]
Looks fine IMHO.  Is this on your PC only?  Or is it merged stuff?

**Comment by jmayntzhusen** [comment]
For now it is only on my pc, didn't have time to check if it needed some scalability for tablets / screens yet, but the css was actually rather simply and only takes up 45 lines, if you want to play around with it I have uploaded the css here: https://gist.github.com/jmayntzhusen/5bf0cf917f07684a309a8cbff355ac2a 

If there is nothing else needed for now I will test out how it scales and then create a PR with it 🙂

**Comment by jmayntzhusen** [comment]
Closing this as it has been merged 🎉
