### ISSUE TITLE
Should documentation on site structure be added?

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/UmbracoDocs#988]
## What type of issue is it? 
Discussion

## Describe the issue:
I find myself sometimes recommending the "ultimate site structure" described in Sebastiaans old blogpost: https://cultiv.nl/blog/tip-of-the-week-the-ultimate-site-structure-setup/ 

As someone who is admittedly a bit out of touch with the recommendations on this sort of things I figured maybe some people could pitch in on what they feel is a good structure and if there is a consensus on one or two being the best we could add them to the documentation somewhere? 🙂

**Comment by dampee** [comment]
As discussed by the curators:
* It would be very opinionated
* is it already in the getting started section
* there are many very good ways
* Do we need to take things to take into account like multi lingual, multi site, ...
* training course teaching group properties by composition

Creating a basic site tutorial can (and should) be extended with a "how to architect a site".

Different approaches: 
* starter kit approach
* training approach
* marc & lee's atomic approach
* jonathan richards manifesto

Adding different examples of real websites could help too. Like a gallery of examples.

**Comment by jmayntzhusen** [comment]
As this discussion has stalled it will be closed for now.
