### ISSUE TITLE
No Documentation for Content Templates (Blueprints)

### ISSUE THREAD

**Issue by KevinJump** [umbraco/UmbracoDocs#989]
There appears to be no documentation for Content Templates (the ones in the settings/content templates - introduced in v7.7)

At least nothing relevant comes up when you search for Content Templates, and i couldn't see anything around in the content docs.

**Comment by jmayntzhusen** [comment]
Hey @KevinJump ,

I think you are absolutely correct, thanks for reporting it 🙂 Is this something you would like to also submit a PR for or should I throw an up-for-grabs label on this issue?

**Comment by marcemarc** [comment]
Perhaps added to the 'backoffice' section: https://our.umbraco.com/documentation/Getting-Started/Backoffice/ in a new section called 'Content Templates' ?

**Comment by michizhou** [comment]
Hi @jmayntzhusen I could write up documentation for this. Let me know if there's any useful reference docs you would recommend I look over.

**Comment by mateoholman** [comment]
@marcemarc @jmayntzhusen I'll tackle this issue and start a new section in the 'backoffice' area!

**Comment by dampee** [comment]
Great to hear @mateoholman 
Looking forward to your PR!

**Comment by dampee** [comment]
Closing this issue with the PR merge
